import type { ProductDefinition } from '../types'

export const changhuaProducts: ProductDefinition[] = [
  {
    slug: 'lukang-mazu-temple',
    title: '鹿港天后宮參拜導覽',
    description: '走訪400年歷史的國定古蹟媽祖廟，聽廟宇建築與信仰故事。',
    content:
      '<p>鹿港天后宮創建於明末，主祀天上聖母媽祖，是台灣最古老的媽祖廟之一。廟宇雕樑畫棟、交趾陶工藝精美絕倫，導覽將深入解說建築細節與鹿港信仰文化。</p>',
    price: 500,
    originPrice: 650,
    address: '彰化縣鹿港鎮中山路430號',
    category: 'package',
    coordinates: { lat: 24.0565, lng: 120.434 },
    imagePool: 'temple',
    features: '國定古蹟,媽祖信仰,廟宇建築,交趾陶,專人導覽',
    transport: '搭乘彰化客運至鹿港站下車步行約5分鐘，或台鐵彰化站轉乘公車。',
    evaluate: 4.6,
    evaluateNum: 580,
  },
  {
    slug: 'baguashan-buddha',
    title: '八卦山大佛風景區門票',
    description: '登上彰化地標大佛像，俯瞰彰化平原與遠方海岸線。',
    content:
      '<p>八卦山大佛高22公尺，是彰化最具代表性的地標。佛像內部可入內參觀，沿階梯登頂眺望彰化市區全景。風景區內設有天空步道、生態園區與軍事碉堡遺跡，適合半日遊。</p>',
    price: 100,
    originPrice: 130,
    address: '彰化縣彰化市溫泉路31號',
    category: 'tickets',
    coordinates: { lat: 24.078, lng: 120.558 },
    imagePool: 'temple',
    features: '大佛地標,天空步道,市區全景,生態園區,免費入園',
    transport: '台鐵彰化站步行約20分鐘上山，或搭乘彰化市公車6933至八卦山站。',
    evaluate: 4.3,
    evaluateNum: 450,
  },
  {
    slug: 'lukang-old-street',
    title: '鹿港老街文化深度遊',
    description: '穿梭紅磚古厝與百年老店，品嚐蝦猴、鳳眼糕等鹿港名產。',
    content:
      '<p>鹿港老街由埔頭街與瑤林街組成，兩旁紅磚老屋保存完好，百年糕餅鋪、手工藝品店林立。漫步其中可體驗傳統童玩、品嚐在地小吃，感受清代鹿港「一府二鹿三艋舺」的繁華。</p>',
    price: 900,
    originPrice: 1100,
    address: '彰化縣鹿港鎮埔頭街',
    category: 'package',
    coordinates: { lat: 24.055, lng: 120.4355 },
    imagePool: 'oldStreet',
    features: '紅磚古厝,百年老店,鹿港名產,傳統童玩,文化導覽,含試吃',
    transport: '搭乘彰化客運至鹿港站下車即達老街區。',
    evaluate: 4.7,
    evaluateNum: 650,
  },
  {
    slug: 'wanggong-oyster-art',
    title: '王功漁港蚵藝體驗',
    description: '搭採蚵車出海，體驗蚵農日常並動手製作蚵殼藝品。',
    content:
      '<p>王功漁港是彰化最重要的蚵仔養殖基地，搭乘採蚵車沿潮間帶出海，親眼見證蚵農如何養殖牡蠣。回港後可動手製作蚵殼藝品，品嚐最新鮮的炸蚵嗲與蚵仔煎。</p>',
    price: 800,
    originPrice: 1000,
    address: '彰化縣芳苑鄉王功村漁港路',
    category: 'package',
    coordinates: { lat: 23.963, lng: 120.326 },
    imagePool: 'beach',
    features: '採蚵車體驗,蚵藝DIY,潮間帶,新鮮蚵仔,漁村文化',
    transport: '自員林火車站搭彰化客運至王功站，車程約40分鐘。',
    evaluate: 4.5,
    evaluateNum: 380,
  },
  {
    slug: 'fan-shaped-depot',
    title: '彰化扇形車庫門票',
    description: '全台唯一保存的扇形火車庫，鐵道迷必訪的活古蹟。',
    content:
      '<p>彰化扇形車庫建於1922年，是台灣唯一保留的扇形機關車庫。12股軌道呈放射狀展開，中央轉車台仍可運作，庫內停放多輛蒸汽機車與柴電機車，是活的鐵道博物館。</p>',
    price: 80,
    originPrice: 100,
    address: '彰化縣彰化市彰美路一段1號',
    category: 'tickets',
    coordinates: { lat: 24.081, lng: 120.537 },
    imagePool: 'museum',
    features: '扇形車庫,蒸汽機車,鐵道古蹟,轉車台,免費參觀',
    transport: '台鐵彰化站後站步行約5分鐘即達。',
    evaluate: 4.4,
    evaluateNum: 520,
  },
  {
    slug: 'taiwan-glass-gallery',
    title: '台灣玻璃館門票',
    description: '走進璀璨的玻璃藝術世界，黃金隧道與玻璃媽祖廟令人驚豔。',
    content:
      '<p>台灣玻璃館位於彰濱工業區，展示台灣精湛的玻璃工藝技術。館內有全台唯一的玻璃媽祖廟、夢幻黃金隧道、玻璃迷宮等特色展區，還可體驗玻璃DIY手作。</p>',
    price: 150,
    originPrice: 200,
    address: '彰化縣鹿港鎮鹿工南四路30號',
    category: 'tickets',
    coordinates: { lat: 24.083, lng: 120.406 },
    imagePool: 'museum',
    features: '玻璃藝術,黃金隧道,DIY體驗,玻璃廟,室內景點',
    transport: '搭乘彰化客運至彰濱工業區站，或自鹿港市區搭計程車約10分鐘。',
    evaluate: 4.2,
    evaluateNum: 340,
  },
  {
    slug: 'xizhou-park',
    title: '溪州公園花卉巡禮',
    description: '漫步繽紛花海與綠蔭大道，彰化最大的平地公園。',
    content:
      '<p>溪州公園占地約123公頃，是彰化最大的平地公園。園區分為苗木區與花博區，四季花卉輪番綻放，設有自行車道、野餐區與生態池，是假日休閒踏青的好去處。</p>',
    price: 500,
    originPrice: 600,
    address: '彰化縣溪州鄉中央路三段138號',
    category: 'package',
    coordinates: { lat: 23.855, lng: 120.506 },
    imagePool: 'park',
    features: '花卉花海,自行車道,野餐區,生態池,親子友善',
    transport: '自田中火車站搭計程車約15分鐘。',
    evaluate: 4.1,
    evaluateNum: 200,
  },
  {
    slug: 'tianzhong-kiln',
    title: '田中窯陶藝體驗',
    description: '親手拉坯製陶，在百年窯場感受泥土的溫度與藝術。',
    content:
      '<p>田中窯是彰化知名的陶藝工作室，提供手拉坯、手捏陶與彩繪等多種體驗課程。在專業老師指導下，從一團泥巴到完成自己的陶器作品，享受手作的療癒時光。</p>',
    price: 600,
    originPrice: 750,
    address: '彰化縣田中鎮斗中路二段230巷36號',
    category: 'package',
    coordinates: { lat: 23.862, lng: 120.581 },
    imagePool: 'oldStreet',
    features: '手拉坯,陶藝體驗,手作療癒,含材料費,作品可帶回',
    transport: '自田中火車站步行約15分鐘。',
    evaluate: 4.4,
    evaluateNum: 270,
  },
  {
    slug: 'baiguoshan-adventure',
    title: '百果山探索樂園門票',
    description: '全台最大恐龍主題樂園，等比例恐龍模型與刺激遊樂設施。',
    content:
      '<p>百果山探索樂園以恐龍為主題，園區內超過40隻等比例恐龍模型，會動會叫栩栩如生。設有VR虛擬實境、考古沙坑及多種遊樂設施，是親子家庭的恐龍冒險天堂。</p>',
    price: 350,
    originPrice: 450,
    address: '彰化縣員林市出水巷15-30號',
    category: 'tickets',
    coordinates: { lat: 23.957, lng: 120.606 },
    imagePool: 'park',
    features: '恐龍樂園,等比模型,VR體驗,考古沙坑,親子友善',
    transport: '自員林火車站搭計程車約10分鐘。',
    evaluate: 4.0,
    evaluateNum: 410,
  },
  {
    slug: 'lukang-longshan-temple',
    title: '鹿港龍山寺建築賞析',
    description: '國定一級古蹟，台灣保存最完整的清代寺廟建築典範。',
    content:
      '<p>鹿港龍山寺建於清乾隆年間，被譽為台灣最美的寺廟之一。八卦藻井、石雕龍柱、木雕門神等工藝登峰造極，戲台與正殿的空間布局堪稱清代建築教科書。</p>',
    price: 600,
    originPrice: 780,
    address: '彰化縣鹿港鎮龍山街100號',
    category: 'package',
    coordinates: { lat: 24.053, lng: 120.431 },
    imagePool: 'temple',
    features: '一級古蹟,八卦藻井,石雕龍柱,清代建築,專業導覽',
    transport: '搭乘彰化客運至鹿港站，步行約10分鐘。',
    evaluate: 4.7,
    evaluateNum: 430,
  },
  {
    slug: 'changbin-factory-tour',
    title: '彰濱工業區觀光工廠一日遊',
    description: '走訪白蘭氏、緞帶王等觀光工廠，體驗DIY手作與試吃。',
    content:
      '<p>彰濱工業區聚集多家觀光工廠，包括白蘭氏健康博物館、緞帶王織帶文化園區、台灣優格餅乾學院等。一日遊串聯3-4個工廠，每站皆有導覽、DIY體驗與免費試吃試喝。</p>',
    price: 1500,
    originPrice: 1800,
    address: '彰化縣鹿港鎮彰濱工業區',
    category: 'package',
    coordinates: { lat: 24.08, lng: 120.398 },
    imagePool: 'city',
    features: '觀光工廠,DIY手作,免費試吃,多站串聯,含交通接送',
    transport: '鹿港市區集合，由專車接駁至各觀光工廠。',
    evaluate: 4.3,
    evaluateNum: 350,
  },
  {
    slug: 'fenyuan-flower-center',
    title: '芬園花卉生產中心賞花',
    description: '季節花海免費賞，櫻花、落羽松、向日葵輪番綻放。',
    content:
      '<p>芬園花卉生產休憩園區四季皆有不同花卉盛開，春天櫻花、秋天落羽松、夏天向日葵。園區免費入場，設有步道、涼亭與拍照造景，是彰化在地人的賞花秘境。</p>',
    price: 80,
    originPrice: 100,
    address: '彰化縣芬園鄉溪尾村庄仔巷140號',
    category: 'tickets',
    coordinates: { lat: 24.023, lng: 120.585 },
    imagePool: 'nature',
    features: '四季花海,免費入場,櫻花,落羽松,拍照景點',
    transport: '自彰化火車站搭計程車約20分鐘。',
    evaluate: 4.0,
    evaluateNum: 180,
  },
  {
    slug: 'qingshuiyan-temple',
    title: '清水岩寺古蹟巡禮',
    description: '三百年古寺與森林步道，感受山林間的禪意與清幽。',
    content:
      '<p>清水岩寺創建於清雍正年間，是彰化縣定古蹟。寺廟背倚八卦山脈，周邊有十八彎古道、中央嶺步道等健行路線，森林茂密、蟲鳥豐富，是結合宗教文化與自然生態的景點。</p>',
    price: 500,
    originPrice: 650,
    address: '彰化縣社頭鄉清水村清水岩路1號',
    category: 'package',
    coordinates: { lat: 23.908, lng: 120.592 },
    imagePool: 'temple',
    features: '三百年古寺,森林步道,古蹟巡禮,自然生態,禪意氛圍',
    transport: '自社頭火車站搭計程車約10分鐘。',
    evaluate: 4.2,
    evaluateNum: 160,
  },
  {
    slug: 'tianwei-garden-highway',
    title: '田尾公路花園自行車遊',
    description: '騎車穿梭花田與園藝店，台灣最大的花卉集散地。',
    content:
      '<p>田尾公路花園沿省道一號兩側綿延數公里，聚集數百家園藝業者，四季花卉爭奇鬥豔。租輛自行車悠遊花間小路，選購多肉植物、蘭花、季節盆栽，是花卉愛好者的天堂。</p>',
    price: 700,
    originPrice: 900,
    address: '彰化縣田尾鄉民生路一段',
    category: 'package',
    coordinates: { lat: 23.893, lng: 120.526 },
    imagePool: 'nature',
    features: '花卉集散地,自行車遊,園藝選購,花田美景,含自行車租借',
    transport: '自田中火車站搭彰化客運至田尾站，車程約15分鐘。',
    evaluate: 4.4,
    evaluateNum: 360,
  },
  {
    slug: 'erlin-winery',
    title: '二林酒莊品酒之旅',
    description: '品嚐彰化在地葡萄酒與荔枝蜂蜜酒，認識台灣農村釀酒文化。',
    content:
      '<p>二林是台灣重要的釀酒葡萄產地，當地酒莊以金香葡萄與黑后葡萄釀製獨特風味的台灣酒。品酒之旅包含葡萄園參觀、釀酒流程解說與多款酒品試飲，感受農村的微醺魅力。</p>',
    price: 1000,
    originPrice: 1200,
    address: '彰化縣二林鎮斗苑路二段',
    category: 'package',
    coordinates: { lat: 23.896, lng: 120.374 },
    imagePool: 'nature',
    features: '葡萄酒莊,品酒體驗,釀酒導覽,葡萄園,含試飲',
    transport: '自員林火車站搭彰化客運至二林站，車程約30分鐘。',
    evaluate: 4.3,
    evaluateNum: 190,
  },
  {
    slug: 'beidou-meatball-tour',
    title: '北斗肉圓美食之旅',
    description: '探訪肉圓發源地，品嚐各家老店的經典北斗肉圓。',
    content:
      '<p>北斗鎮是台灣肉圓的發源地，鎮上多家百年肉圓老店各有獨門配方。美食之旅將帶您走訪3-4家名店，品嚐炸肉圓與蒸肉圓的不同風味，搭配在地小吃與甜品。</p>',
    price: 600,
    originPrice: 750,
    address: '彰化縣北斗鎮中華路',
    category: 'package',
    coordinates: { lat: 23.871, lng: 120.519 },
    imagePool: 'nightMarket',
    features: '肉圓發源地,百年老店,美食品嚐,文化導覽,含試吃',
    transport: '自田中火車站搭彰化客運至北斗站，車程約20分鐘。',
    evaluate: 4.5,
    evaluateNum: 300,
  },
  {
    slug: 'shetou-trail',
    title: '社頭清水岩步道健行',
    description: '八卦山脈最美森林步道，綠蔭蔽日的天然冷氣房。',
    content:
      '<p>清水岩步道位於八卦山脈社頭段，全長約4.5公里，步道平緩好走，沿途老樹成蔭、溪水潺潺。春季可觀賞螢火蟲，四季皆有豐富的蝴蝶與鳥類生態，是健行踏青的絕佳路線。</p>',
    price: 500,
    originPrice: 600,
    address: '彰化縣社頭鄉清水岩路',
    category: 'package',
    coordinates: { lat: 23.906, lng: 120.594 },
    imagePool: 'mountain',
    features: '森林步道,綠蔭步道,螢火蟲,生態豐富,輕鬆健行',
    transport: '自社頭火車站搭計程車約10分鐘至步道入口。',
    evaluate: 4.3,
    evaluateNum: 220,
  },
  {
    slug: 'changhua-confucius-temple',
    title: '彰化孔廟文化巡禮',
    description: '參訪全台保存最完整的縣級孔廟，感受儒學傳統之美。',
    content:
      '<p>彰化孔廟建於清雍正四年，是全台保存最完整的縣級孔廟。建築格局依循傳統規制，大成殿、泮池、櫺星門等一應俱全，每年秋季舉辦祭孔大典，是認識儒學文化的重要場所。</p>',
    price: 80,
    originPrice: 100,
    address: '彰化縣彰化市孔門路30號',
    category: 'tickets',
    coordinates: { lat: 24.075, lng: 120.542 },
    imagePool: 'temple',
    features: '縣定古蹟,儒學文化,傳統建築,祭孔大典,免費參觀',
    transport: '台鐵彰化站步行約10分鐘。',
    evaluate: 4.0,
    evaluateNum: 130,
  },
  {
    slug: 'huatan-octagonal-kiln',
    title: '花壇八卦窯文化園區',
    description: '探訪全台僅存的八卦窯磚窯遺址，認識百年磚瓦產業。',
    content:
      '<p>花壇八卦窯是日治時期興建的環形磚窯，全台僅存。巨大的圓形窯體內部空間壯觀，園區內展示傳統磚瓦燒製過程，設有磚雕DIY體驗，是認識台灣建材產業歷史的獨特景點。</p>',
    price: 150,
    originPrice: 200,
    address: '彰化縣花壇鄉橋頭村中正路',
    category: 'tickets',
    coordinates: { lat: 24.042, lng: 120.547 },
    imagePool: 'oldStreet',
    features: '八卦窯遺址,磚瓦文化,DIY體驗,產業歷史,獨特景點',
    transport: '自花壇火車站步行約15分鐘。',
    evaluate: 3.9,
    evaluateNum: 110,
  },
  {
    slug: 'lukang-glass-temple',
    title: '鹿港玻璃廟門票',
    description: '全球唯一用玻璃建造的媽祖廟，夜間點燈璀璨奪目。',
    content:
      '<p>鹿港玻璃廟（護聖宮）以七萬片玻璃打造，耗時六年建成，是全球唯一的玻璃廟宇。白天陽光穿透玻璃折射出繽紛光彩，夜間LED燈光秀更是璀璨耀眼，是彰化最獨特的宗教藝術建築。</p>',
    price: 100,
    originPrice: 130,
    address: '彰化縣鹿港鎮鹿工路12號',
    category: 'tickets',
    coordinates: { lat: 24.084, lng: 120.405 },
    imagePool: 'temple',
    features: '玻璃建築,夜間燈光秀,媽祖廟,全球唯一,拍照打卡',
    transport: '搭乘彰化客運至彰濱工業區站，步行約5分鐘。',
    evaluate: 4.1,
    evaluateNum: 290,
  },
]
