import type { ProductDefinition } from '../types'

export const chiayiProducts: ProductDefinition[] = [
  {
    slug: 'hinoki-village',
    title: '檜意森活村導覽體驗',
    description: '全台最大日式建築群，漫步檜木香氣中感受和風歲月。',
    content:
      '<p>檜意森活村前身為日治時期的林業官舍群，經整修後成為全台保存最完整、規模最大的日式建築聚落。28棟檜木建築散發淡淡木香，園區內進駐各式文創商店、手作工坊與特色餐廳。穿上浴衣漫步其中，彷彿穿越時空回到昭和年代。</p>',
    price: 500,
    originPrice: 650,
    address: '嘉義市東區林森東路1號',
    category: 'package',
    coordinates: { lat: 23.4801, lng: 120.441 },
    imagePool: 'oldStreet',
    features: '日式建築,檜木香氣,浴衣體驗,文創商店,手作工坊,歷史導覽',
    transport: '嘉義火車站步行約10分鐘，或搭乘BRT至檜意森活村站',
    evaluate: 4.4,
    evaluateNum: 620,
  },
  {
    slug: 'wenhua-road-night-market',
    title: '嘉義文化路夜市美食巡禮',
    description: '嘉義最熱鬧的觀光夜市，匯集火雞肉飯、方塊酥等在地美食精華。',
    content:
      '<p>文化路夜市是嘉義市最具代表性的美食街區，從中山路到民族路綿延約500公尺。白天是一般商店街，入夜後攤販齊聚，火雞肉飯、涼麵、涼圓、豆花、方塊酥等道地美食令人垂涎。這趟美食巡禮由在地美食家帶路，一次品嚐八道經典小吃。</p>',
    price: 600,
    originPrice: 780,
    address: '嘉義市東區文化路',
    category: 'package',
    coordinates: { lat: 23.48, lng: 120.449 },
    imagePool: 'nightMarket',
    features: '火雞肉飯,在地小吃,美食導覽,夜市文化,八道品嚐,步行美食',
    transport: '嘉義火車站步行約5分鐘即達文化路夜市入口',
    evaluate: 4.5,
    evaluateNum: 710,
  },
  {
    slug: 'forest-song',
    title: '森林之歌裝置藝術參觀',
    description: '藝術大師王文志以阿里山木材打造的巨型裝置藝術，夜間燈光更添夢幻。',
    content:
      '<p>森林之歌是藝術家王文志以阿里山漂流木、鐵軌及黃藤等素材創作的大型公共藝術作品。高約14公尺的蛋型結構象徵生命的起源，白天陽光透過藤編縫隙灑落形成光影之美，夜晚LED燈光點亮整座作品，營造出如夢似幻的浪漫氛圍，是嘉義市的地標景點。</p>',
    price: 80,
    originPrice: 100,
    address: '嘉義市東區文化路與忠孝路交叉口旁',
    category: 'tickets',
    coordinates: { lat: 23.4778, lng: 120.4378 },
    imagePool: 'park',
    features: '裝置藝術,夜間燈光,公共藝術,拍照景點,免費參觀,地標建築',
    transport: '嘉義火車站步行約15分鐘，或搭乘市區公車至文化公園站',
    evaluate: 4.2,
    evaluateNum: 380,
  },
  {
    slug: 'chiayi-park',
    title: '嘉義公園歷史散步',
    description: '百年歷史的市民公園，日治遺跡與自然生態交織的綠色秘境。',
    content:
      '<p>嘉義公園創建於1910年，佔地26.8公頃，是嘉義市歷史最悠久的公園。園區內保存射日塔、忠烈祠、孔廟、史蹟館等多處古蹟，參天的老樹與蜿蜒的步道構成一片都市綠洲。這趟歷史散步包含專業導覽，帶您走讀百年公園的故事。</p>',
    price: 300,
    originPrice: 380,
    address: '嘉義市東區公園街46號',
    category: 'package',
    coordinates: { lat: 23.4756, lng: 120.4567 },
    imagePool: 'park',
    features: '百年公園,歷史古蹟,自然步道,導覽解說,古樹群,都市綠洲',
    transport: '嘉義火車站搭乘市區公車至嘉義公園站，車程約10分鐘',
    evaluate: 4.1,
    evaluateNum: 290,
  },
  {
    slug: 'shooting-sun-tower',
    title: '射日塔觀景門票',
    description: '嘉義市地標建築，登高12樓可360度俯瞰嘉義市區與遠眺玉山群峰。',
    content:
      '<p>射日塔位於嘉義公園內，高62公尺，外觀以鋁合金打造的原住民射日神話圖騰包覆，極具藝術感。搭乘電梯直上12樓觀景台，360度環景視野令人驚嘆，晴朗時可遠眺玉山主峰與阿里山山脈。塔內設有空中花園、咖啡廳及藝文展覽空間。</p>',
    price: 150,
    originPrice: 200,
    address: '嘉義市東區公園街46號（嘉義公園內）',
    category: 'tickets',
    coordinates: { lat: 23.475, lng: 120.4575 },
    imagePool: 'city',
    features: '360度展望,玉山遠眺,空中花園,咖啡廳,射日神話,地標建築',
    transport: '嘉義火車站搭乘市區公車至嘉義公園站，步行約5分鐘',
    evaluate: 4.0,
    evaluateNum: 340,
  },
  {
    slug: 'chiayi-museum',
    title: '嘉義市立博物館門票',
    description: '認識嘉義的自然地質與人文歷史，互動式展覽老少咸宜。',
    content:
      '<p>嘉義市立博物館以嘉義的地質、化石、歷史文物及藝術創作為展示主題。常設展「嘉義的故事」以多媒體互動方式呈現這座城市從諸羅城到現代的發展歷程。頂樓的交趾陶特展則展出嘉義引以為傲的傳統工藝精品，館內定期舉辦特展與教育活動。</p>',
    price: 100,
    originPrice: 130,
    address: '嘉義市東區忠孝路275-1號',
    category: 'tickets',
    coordinates: { lat: 23.4789, lng: 120.4533 },
    imagePool: 'museum',
    features: '地質化石,歷史文物,交趾陶,互動展覽,教育活動,多媒體',
    transport: '嘉義火車站步行約12分鐘，或搭乘市區公車至博物館站',
    evaluate: 3.9,
    evaluateNum: 210,
  },
  {
    slug: 'lantan',
    title: '蘭潭環潭步道散策',
    description: '嘉義市後花園，環潭步道搭配月影潭心藝術作品，日夜皆美。',
    content:
      '<p>蘭潭水庫是嘉義市最重要的水源地，也是市民休閒的好去處。全長約3.6公里的環潭步道平坦好走，沿途綠樹成蔭。湖畔的「月影潭心」裝置藝術以鋁片編織出雲、月、水草意象，夜間燈光映照水面極為夢幻。清晨可見許多市民在此慢跑、打太極。</p>',
    price: 200,
    originPrice: 260,
    address: '嘉義市東區小雅路25號',
    category: 'tickets',
    coordinates: { lat: 23.4639, lng: 120.4733 },
    imagePool: 'nature',
    features: '環潭步道,月影潭心,夜間燈光,晨運聖地,湖畔美景,輕鬆散步',
    transport: '嘉義火車站搭乘市區公車66路至蘭潭站，車程約20分鐘',
    evaluate: 4.3,
    evaluateNum: 350,
  },
  {
    slug: 'beimen-station',
    title: '北門驛阿里山鐵道文化體驗',
    description: '阿里山森林鐵路的起點站，日式木造車站保留完整鐵道風華。',
    content:
      '<p>北門驛建於1912年，是阿里山森林鐵路的起點站，也是台灣僅存的日式木造火車站之一。檜木構建的站房散發著歲月的香氣，站旁的阿里山林業鐵路車庫園區展示多輛退役蒸汽火車頭。這趟體驗包含導覽解說、鐵道文物參觀及紀念品。</p>',
    price: 350,
    originPrice: 450,
    address: '嘉義市東區共和路428號',
    category: 'package',
    coordinates: { lat: 23.4817, lng: 120.44 },
    imagePool: 'oldStreet',
    features: '日式車站,檜木建築,蒸汽火車,鐵道文化,歷史導覽,攝影景點',
    transport: '嘉義火車站步行約5分鐘即達北門驛',
    evaluate: 4.2,
    evaluateNum: 280,
  },
  {
    slug: 'prison-museum',
    title: '獄政博物館導覽',
    description: '全台唯一開放參觀的監獄古蹟，揭開獄政文化的神秘面紗。',
    content:
      '<p>嘉義舊監獄建於1922年，是台灣唯一完整保存的日治時期監獄建築，現為國定古蹟。館內保留了放射狀的牢房走廊、獨居房、工場及刑具展示區，導覽人員生動講述監獄的歷史故事與受刑人生活。獨特的建築空間與歷史氛圍，讓人印象深刻。</p>',
    price: 100,
    originPrice: 120,
    address: '嘉義市東區維新路140號',
    category: 'tickets',
    coordinates: { lat: 23.4822, lng: 120.4522 },
    imagePool: 'museum',
    features: '國定古蹟,日治建築,獄政文化,導覽解說,放射狀牢房,歷史教育',
    transport: '嘉義火車站步行約15分鐘，或搭乘市區公車至維新路站',
    evaluate: 4.3,
    evaluateNum: 310,
  },
  {
    slug: 'railway-art-village',
    title: '嘉義鐵道藝術村文創巡禮',
    description: '廢棄鐵道倉庫華麗轉身為藝術村，匯集在地藝術家的創作能量。',
    content:
      '<p>嘉義鐵道藝術村利用嘉義火車站旁的舊鐵路倉庫群改建而成，是嘉義市重要的藝文展演空間。多間倉庫分別規劃為展覽廳、工作室與表演場地，不定期舉辦當代藝術展覽、音樂表演及市集活動。這趟巡禮包含藝術家工作室參訪及手作體驗課程。</p>',
    price: 400,
    originPrice: 520,
    address: '嘉義市西區北興街37-10號',
    category: 'package',
    coordinates: { lat: 23.4811, lng: 120.4383 },
    imagePool: 'city',
    features: '鐵道倉庫,當代藝術,手作體驗,藝術家工作室,市集活動,文創空間',
    transport: '嘉義火車站後站步行約3分鐘即達',
    evaluate: 4.0,
    evaluateNum: 190,
  },
  {
    slug: 'historical-relics-hall',
    title: '嘉義市史蹟館參觀',
    description: '日治時期神社附屬建築改建，展示嘉義市百年發展史。',
    content:
      '<p>嘉義市史蹟館原為日治時期嘉義神社的齋館與社務所，木造建築典雅精緻。館內展示嘉義從諸羅縣到現代的歷史變遷，包含嘉義大地震、KANO棒球隊、林業發展等重要歷史事件。和式建築搭配庭園造景，本身就是一座值得細細品味的歷史建築。</p>',
    price: 80,
    originPrice: 100,
    address: '嘉義市東區公園街42號',
    category: 'tickets',
    coordinates: { lat: 23.4758, lng: 120.4561 },
    imagePool: 'museum',
    features: '日式建築,城市歷史,KANO文化,林業史,免費參觀,庭園景觀',
    transport: '嘉義火車站搭乘市區公車至嘉義公園站，步行約3分鐘',
    evaluate: 3.8,
    evaluateNum: 150,
  },
  {
    slug: 'alishan-railway-garage',
    title: '阿里山森林鐵路車庫園區門票',
    description: '鐵道迷朝聖地，近距離觀賞阿里山森林鐵路的珍貴老火車頭。',
    content:
      '<p>車庫園區是阿里山森林鐵路列車的維修基地，開放部分區域供民眾參觀。園區內展示多輛不同年代的蒸汽機車、柴油機車及客貨車廂，還有全台唯一的扇形車庫。透過解說牌了解每輛車的歷史故事，鐵道迷可以在此待上大半天也不膩。</p>',
    price: 100,
    originPrice: 130,
    address: '嘉義市東區林森西路2號',
    category: 'tickets',
    coordinates: { lat: 23.4822, lng: 120.4389 },
    imagePool: 'oldStreet',
    features: '蒸汽機車,扇形車庫,鐵道文物,歷史車輛,親子景點,攝影天堂',
    transport: '嘉義火車站步行約8分鐘，沿林森西路方向前行',
    evaluate: 4.1,
    evaluateNum: 260,
  },
  {
    slug: 'koji-pottery-museum',
    title: '交趾陶館導覽體驗',
    description: '欣賞嘉義獨特的交趾陶工藝，親手體驗捏陶樂趣。',
    content:
      '<p>交趾陶是嘉義最具代表性的傳統工藝，色彩鮮豔、造型生動，多見於廟宇裝飾。交趾陶館展示從清代至現代的精美作品，並介紹製作工藝流程。導覽體驗包含館藏賞析、工匠技藝解說及親手捏陶DIY，完成的作品經燒製後可寄回作為獨一無二的紀念品。</p>',
    price: 450,
    originPrice: 580,
    address: '嘉義市東區忠孝路275-1號3樓',
    category: 'package',
    coordinates: { lat: 23.4789, lng: 120.4535 },
    imagePool: 'museum',
    features: '交趾陶藝,捏陶DIY,傳統工藝,廟宇文化,作品帶回,專業導覽',
    transport: '嘉義火車站步行約12分鐘，或搭乘市區公車至博物館站',
    evaluate: 4.4,
    evaluateNum: 200,
  },
  {
    slug: 'chenghuang-temple-food',
    title: '嘉義城隍廟美食巡禮',
    description: '以城隍廟為中心的傳統美食圈，品嚐最道地的嘉義小吃。',
    content:
      '<p>嘉義城隍廟已有三百多年歷史，廟宇周邊自然形成熱鬧的美食聚落。這趟美食巡禮由在地老饕帶路，走訪廟口排骨酥、碗粿、米糕、春捲等老字號攤位，每一口都是嘉義人從小吃到大的好味道。同時認識城隍廟的歷史典故與建築之美。</p>',
    price: 550,
    originPrice: 700,
    address: '嘉義市東區吳鳳北路168號',
    category: 'package',
    coordinates: { lat: 23.4822, lng: 120.4489 },
    imagePool: 'nightMarket',
    features: '廟口美食,傳統小吃,老饕帶路,城隍廟,歷史典故,六道品嚐',
    transport: '嘉義火車站步行約8分鐘，沿中山路直行右轉吳鳳北路',
    evaluate: 4.5,
    evaluateNum: 430,
  },
  {
    slug: 'chiayi-sawmill',
    title: '嘉義製材所歷史園區導覽',
    description: '日治時期東洋最大製材廠遺址，見證嘉義木都的輝煌歲月。',
    content:
      '<p>嘉義製材所建於1914年，曾是日治時期東洋規模最大的木材加工廠，處理阿里山運下的珍貴檜木。經修復後開放參觀，園區保留了動力室、乾燥室、製材機具等工業遺跡。導覽將帶您認識嘉義如何因林業而興盛，成為「木都」的歷史脈絡。</p>',
    price: 300,
    originPrice: 380,
    address: '嘉義市西區林森西路4號',
    category: 'package',
    coordinates: { lat: 23.4819, lng: 120.4392 },
    imagePool: 'oldStreet',
    features: '工業遺跡,林業歷史,檜木文化,木都故事,古蹟修復,專業導覽',
    transport: '嘉義火車站步行約7分鐘，沿林森西路方向前行',
    evaluate: 4.2,
    evaluateNum: 180,
  },
  {
    slug: 'moon-shadow-lake-heart',
    title: '月影潭心夜間光影體驗',
    description: '蘭潭畔的浪漫光影藝術，夜間限定的水上聲光饗宴。',
    content:
      '<p>月影潭心是嘉義市蘭潭湖畔的大型裝置藝術，由鋁片編織而成的鏤空造型在夜間搭配LED燈光投射，映照在湖面上形成如夢似幻的光影效果。夜間限定的體驗包含環潭步道導覽、光影藝術賞析及湖畔茶席，在星空下享受一個浪漫的夜晚。</p>',
    price: 500,
    originPrice: 650,
    address: '嘉義市東區小雅路（蘭潭風景區）',
    category: 'package',
    coordinates: { lat: 23.4639, lng: 120.4733 },
    imagePool: 'nature',
    features: '光影藝術,夜間限定,湖畔茶席,浪漫體驗,裝置藝術,環潭步道',
    transport: '嘉義火車站搭乘市區公車66路至蘭潭站，車程約20分鐘',
    evaluate: 4.3,
    evaluateNum: 220,
  },
  {
    slug: 'chiayi-old-street-walk',
    title: '嘉義老街慢步散策',
    description: '穿梭嘉義舊城巷弄，發現隱藏版老屋咖啡與街頭藝術。',
    content:
      '<p>嘉義舊城區保留了許多日治時期的街屋與巴洛克風格建築，近年來老屋活化運動讓這些建築重獲新生。散策路線從中正路出發，經過成仁街、光彩街等巷弄，探訪老屋改建的咖啡廳、獨立書店及藝術空間。每個轉角都可能遇見精彩的街頭塗鴉與裝置藝術。</p>',
    price: 350,
    originPrice: 450,
    address: '嘉義市西區中正路',
    category: 'package',
    coordinates: { lat: 23.4811, lng: 120.4456 },
    imagePool: 'oldStreet',
    features: '老屋巡禮,巷弄探索,街頭藝術,咖啡廳,獨立書店,舊城散步',
    transport: '嘉義火車站步行約5分鐘即達散策路線起點',
    evaluate: 4.1,
    evaluateNum: 270,
  },
  {
    slug: 'chiayi-art-museum',
    title: '嘉義美術館門票',
    description: '菸酒公賣局舊建築改建的美術館，古典外觀內藏當代藝術能量。',
    content:
      '<p>嘉義美術館由日治時期的菸酒公賣局嘉義分局改建而成，融合古蹟建築與現代展演空間。一樓保留原始建築結構與歷史展示，二、三樓為當代藝術展覽空間，不定期舉辦國內外藝術家特展。館內的咖啡廳也是一大亮點，在歷史空間中享用咖啡別有風味。</p>',
    price: 100,
    originPrice: 130,
    address: '嘉義市西區廣寧街101號',
    category: 'tickets',
    coordinates: { lat: 23.48, lng: 120.4444 },
    imagePool: 'museum',
    features: '古蹟建築,當代藝術,特展活動,歷史空間,館內咖啡,建築之美',
    transport: '嘉義火車站步行約8分鐘，沿中山路方向前行',
    evaluate: 4.2,
    evaluateNum: 230,
  },
  {
    slug: 'kano-memorial-park',
    title: 'KANO紀念園區導覽',
    description: '紀念嘉農棒球隊的光榮歷史，重溫1931年甲子園傳奇。',
    content:
      '<p>KANO紀念園區位於嘉義市棒球場旁，紀念1931年嘉義農林棒球隊打進日本甲子園決賽的傳奇故事。園區設有KANO銅像群、歷史圖文展、棒球文物展示及影音體驗區。導覽將帶您回顧這支由漢人、日本人、原住民組成的球隊如何創造歷史奇蹟。</p>',
    price: 250,
    originPrice: 320,
    address: '嘉義市東區山仔頂249-1號',
    category: 'package',
    coordinates: { lat: 23.475, lng: 120.46 },
    imagePool: 'park',
    features: 'KANO歷史,棒球文化,銅像群,影音體驗,甲子園傳奇,運動精神',
    transport: '嘉義火車站搭乘市區公車至棒球場站，車程約15分鐘',
    evaluate: 4.3,
    evaluateNum: 310,
  },
  {
    slug: 'dongshi-fisherman-wharf',
    title: '東石漁人碼頭半日遊',
    description: '嘉義海線的休閒漁港，品嚐最新鮮的蚵仔料理與海風吹拂。',
    content:
      '<p>東石漁人碼頭位於嘉義縣東石鄉，是嘉義最具代表性的漁港景點。碼頭設有親水沙灘、彩色蚵殼裝置藝術及海景餐廳。這裡是台灣最大的蚵仔產地，鮮蚵料理種類繁多，蚵仔煎、蚵仔包、蚵捲、蚵仔麵線應有盡有。半日遊包含漁港導覽與蚵仔風味餐。</p>',
    price: 700,
    originPrice: 900,
    address: '嘉義縣東石鄉彩霞大道420號',
    category: 'package',
    coordinates: { lat: 23.4511, lng: 120.1533 },
    imagePool: 'beach',
    features: '漁港風情,鮮蚵料理,親水沙灘,裝置藝術,海景餐廳,漁村文化',
    transport: '嘉義火車站搭乘嘉義客運往東石方向，於東石站下車步行約10分鐘',
    evaluate: 4.2,
    evaluateNum: 350,
  },
]
