import type { ProductDefinition } from '../types'

export const chiayiCountyProducts: ProductDefinition[] = [
  {
    slug: 'alishan-forest-recreation-area',
    title: '阿里山國家森林遊樂區門票',
    description: '台灣最知名的森林遊樂區，日出、雲海、晚霞、森林與鐵道五大奇景。',
    content:
      '<p>阿里山國家森林遊樂區海拔約2200公尺，是台灣最具國際知名度的觀光景點之一。園區內擁有千年紅檜巨木群、姊妹潭、受鎮宮等景點，搭乘森林小火車穿梭於參天古木間更是必體驗的行程。春季櫻花盛開時整座山頭染上粉紅，美不勝收。</p>',
    price: 300,
    originPrice: 400,
    address: '嘉義縣阿里山鄉中正村59號',
    category: 'tickets',
    coordinates: { lat: 23.5111, lng: 120.8028 },
    imagePool: 'mountain',
    features: '五大奇景,千年神木,森林步道,櫻花季,森林鐵路,雲海日出',
    transport: '嘉義火車站搭乘台灣好行阿里山線，車程約2.5小時',
    evaluate: 4.7,
    evaluateNum: 800,
  },
  {
    slug: 'fenqihu-old-street',
    title: '奮起湖老街鐵道便當之旅',
    description: '海拔1400公尺的山城老街，品嚐全台最知名的鐵路便當。',
    content:
      '<p>奮起湖位於阿里山森林鐵路中途，因地形三面環山形似畚箕而得名。老街上最有名的就是鐵路便當，滷排骨配上古早味醃蘿蔔，簡單卻令人回味無窮。街上還有百年老店、手工愛玉及山葵料理等特色美食。漫步在雲霧繚繞的老街中，感受高山小鎮的獨特魅力。</p>',
    price: 600,
    originPrice: 780,
    address: '嘉義縣竹崎鄉中和村奮起湖',
    category: 'package',
    coordinates: { lat: 23.5042, lng: 120.6961 },
    imagePool: 'oldStreet',
    features: '鐵路便當,山城老街,雲霧美景,手工愛玉,百年老店,小火車',
    transport: '嘉義火車站搭乘阿里山森林鐵路至奮起湖站，車程約2小時',
    evaluate: 4.4,
    evaluateNum: 560,
  },
  {
    slug: 'danayigu',
    title: '達娜伊谷自然生態公園門票',
    description: '鄒族守護的忘憂谷，清澈溪水中鯝魚成群悠游的生態天堂。',
    content:
      '<p>達娜伊谷是鄒族語「忘憂谷」之意，位於嘉義縣阿里山鄉山美村。經過族人多年的封溪護魚，溪中鯝魚數量驚人，清澈見底的溪水中銀色魚群翻騰的畫面令人讚嘆。園區提供鄒族歌舞表演、原住民風味餐及溪谷步道健行，是一趟兼具生態與文化的深度之旅。</p>',
    price: 250,
    originPrice: 320,
    address: '嘉義縣阿里山鄉山美村3鄰51號',
    category: 'tickets',
    coordinates: { lat: 23.4367, lng: 120.6783 },
    imagePool: 'nature',
    features: '鯝魚生態,鄒族文化,封溪護魚,原住民歌舞,溪谷步道,忘憂谷',
    transport: '嘉義火車站搭乘嘉義客運往達邦方向，於山美站下車步行約15分鐘',
    evaluate: 4.3,
    evaluateNum: 310,
  },
  {
    slug: 'taiping-cloud-bridge',
    title: '太平雲梯門票',
    description: '全台最長景觀吊橋，漫步海拔1000公尺雲端俯瞰嘉南平原。',
    content:
      '<p>太平雲梯全長281公尺，海拔約1000公尺，是全台最長的單跨景觀吊橋。站在橋上可遠眺嘉南平原直至台灣海峽，天氣晴朗時甚至能看到澎湖。雲霧繚繞時彷彿漫步雲端，夢幻感十足。橋頭設有雲之南道步道系統，可延伸健行至太平老街品嚐在地美食。</p>',
    price: 100,
    originPrice: 130,
    address: '嘉義縣梅山鄉太平村下坑仔5號',
    category: 'tickets',
    coordinates: { lat: 23.5711, lng: 120.6328 },
    imagePool: 'mountain',
    features: '景觀吊橋,雲海美景,嘉南平原,步道健行,太平老街,攝影景點',
    transport: '嘉義火車站搭乘嘉義客運太平線，於太平站下車步行約10分鐘',
    evaluate: 4.5,
    evaluateNum: 650,
  },
  {
    slug: 'southern-branch-npm',
    title: '故宮南院門票',
    description: '故宮博物院南部院區，以亞洲藝術文化為主題的國際級博物館。',
    content:
      '<p>國立故宮博物院南部院區佔地70公頃，建築由姚仁喜建築師設計，以流線型外觀象徵中華、印度及波斯三股文化交流。常設展覽涵蓋亞洲佛教藝術、陶瓷、織品及茶文化，館藏豐富且展示方式新穎。戶外的人工湖與景觀橋也是拍照的好去處。</p>',
    price: 150,
    originPrice: 200,
    address: '嘉義縣太保市故宮大道888號',
    category: 'tickets',
    coordinates: { lat: 23.4711, lng: 120.2961 },
    imagePool: 'museum',
    features: '亞洲藝術,國際博物館,建築美學,常設特展,人工湖,親子適合',
    transport: '高鐵嘉義站搭乘BRT至故宮南院站，車程約10分鐘',
    evaluate: 4.4,
    evaluateNum: 580,
  },
  {
    slug: 'xingang-fengtian-temple',
    title: '新港奉天宮媽祖文化之旅',
    description: '開台媽祖廟的歷史巡禮，體驗台灣最虔誠的民間信仰文化。',
    content:
      '<p>新港奉天宮建於1811年，供奉來自湄洲的開台媽祖，是台灣最重要的媽祖信仰中心之一。每年大甲媽祖遶境的終點就在此。這趟文化之旅包含廟宇建築導覽、交趾陶與剪黏藝術賞析、媽祖文物館參觀，以及新港老街上的鴨肉羹、粉圓等傳統美食品嚐。</p>',
    price: 500,
    originPrice: 650,
    address: '嘉義縣新港鄉新民路53號',
    category: 'package',
    coordinates: { lat: 23.5536, lng: 120.3472 },
    imagePool: 'temple',
    features: '媽祖信仰,廟宇建築,交趾陶,遶境文化,老街美食,文物館',
    transport: '嘉義火車站搭乘嘉義客運往新港方向，於新港站下車步行約3分鐘',
    evaluate: 4.3,
    evaluateNum: 380,
  },
  {
    slug: 'budai-fish-market',
    title: '布袋觀光漁市海鮮體驗',
    description: '嘉義海線最熱鬧的漁港，現撈海鮮直送餐桌的鮮味饗宴。',
    content:
      '<p>布袋漁港是嘉義縣最大的漁港，觀光漁市內匯集各式新鮮海產，從活蝦、生蠔到各種鮮魚應有盡有。市場二樓設有代客料理區，現買現煮最新鮮。漁港旁還有高跟鞋教堂等景點可順遊。這趟體驗包含漁市導覽、海鮮挑選教學及豐盛的海鮮風味餐。</p>',
    price: 800,
    originPrice: 1000,
    address: '嘉義縣布袋鎮中山路3號',
    category: 'package',
    coordinates: { lat: 23.3778, lng: 120.1667 },
    imagePool: 'beach',
    features: '現撈海鮮,漁市導覽,代客料理,海鮮風味餐,漁港風情,伴手禮',
    transport: '嘉義火車站搭乘嘉義客運往布袋方向，於布袋站下車步行約5分鐘',
    evaluate: 4.3,
    evaluateNum: 420,
  },
  {
    slug: 'alishan-sunrise',
    title: '阿里山日出觀賞專車',
    description: '凌晨搭乘祝山小火車，迎接台灣最壯麗的高山日出。',
    content:
      '<p>阿里山日出是台灣最具代表性的自然景觀之一。凌晨搭乘祝山線小火車前往祝山觀日平台，在海拔2488公尺的高度等待太陽從玉山群峰間緩緩升起。日出前的漫天彩霞、金色光芒照耀雲海的那一刻，壯麗到讓人屏息。包含小火車來回車票及專業攝影指導。</p>',
    price: 350,
    originPrice: 450,
    address: '嘉義縣阿里山鄉祝山觀日平台',
    category: 'package',
    coordinates: { lat: 23.5078, lng: 120.7572 },
    imagePool: 'mountain',
    features: '高山日出,祝山小火車,雲海奇景,玉山展望,攝影指導,凌晨體驗',
    transport: '阿里山森林遊樂區內搭乘祝山線小火車，車程約25分鐘',
    evaluate: 4.8,
    evaluateNum: 720,
  },
  {
    slug: 'tefuye-old-trail',
    title: '特富野古道一日健行',
    description: '阿里山最美的森林古道，穿越柳杉林與鐵道遺跡的夢幻路線。',
    content:
      '<p>特富野古道全長6.32公里，前段為日治時期伐木鐵道改建的平緩步道，枕木鐵軌隱沒在茂密的柳杉林中，充滿歲月痕跡。後段為原始山徑，穿越雜木林與竹林。沿途雲霧繚繞、苔蘚密布，被譽為阿里山最美的步道。一日健行含在地嚮導與風味便當。</p>',
    price: 1200,
    originPrice: 1500,
    address: '嘉義縣阿里山鄉特富野古道入口',
    category: 'package',
    coordinates: { lat: 23.5167, lng: 120.7167 },
    imagePool: 'mountain',
    features: '森林古道,鐵道遺跡,柳杉林,雲霧繚繞,專業嚮導,風味便當',
    transport: '嘉義搭乘台灣好行阿里山線至自忠站下車即達登山口',
    evaluate: 4.6,
    evaluateNum: 290,
  },
  {
    slug: 'ruili-wisteria-season',
    title: '瑞里紫藤花季賞花之旅',
    description: '春季限定的紫色浪漫，瑞里山區紫藤花隧道美如仙境。',
    content:
      '<p>每年三月至四月是瑞里紫藤花盛開的季節，綿延的紫藤花架形成夢幻的紫色隧道，陽光透過花串灑落的光影令人陶醉。瑞里地區還有綠色隧道、蝙蝠洞、燕子崖等自然景觀可順道遊覽。這趟賞花之旅包含專車接送、花季導覽及山區風味餐。</p>',
    price: 1500,
    originPrice: 1900,
    address: '嘉義縣梅山鄉瑞里村',
    category: 'package',
    coordinates: { lat: 23.5583, lng: 120.6667 },
    imagePool: 'nature',
    features: '紫藤花季,花隧道,春季限定,專車接送,燕子崖,風味餐',
    transport: '嘉義火車站搭乘專車前往，車程約1.5小時',
    evaluate: 4.5,
    evaluateNum: 340,
  },
  {
    slug: 'minxiong-haunted-house',
    title: '民雄鬼屋探險導覽',
    description: '全台最知名的鬼屋傳說，日式洋樓廢墟的神秘探索之旅。',
    content:
      '<p>民雄鬼屋原為日治時期劉家古厝，三層樓的巴洛克式洋樓因長年無人居住而荒廢，加上各種靈異傳說使其成為全台最知名的鬼屋。導覽將帶您了解古厝的真實歷史、建築特色及流傳的故事。附近的民雄鬼屋咖啡提供各式「靈異」創意飲品，氣氛十足。</p>',
    price: 250,
    originPrice: 320,
    address: '嘉義縣民雄鄉興中村義橋12號',
    category: 'tickets',
    coordinates: { lat: 23.5456, lng: 120.4283 },
    imagePool: 'oldStreet',
    features: '靈異傳說,日式洋樓,歷史導覽,鬼屋咖啡,探險體驗,攝影景點',
    transport: '民雄火車站步行約15分鐘，或搭乘計程車約5分鐘',
    evaluate: 3.9,
    evaluateNum: 480,
  },
  {
    slug: 'alishan-train',
    title: '阿里山小火車體驗券',
    description: '搭乘世界僅存的高山森林鐵路，體驗獨特的之字形登山路線。',
    content:
      '<p>阿里山森林鐵路是世界僅存的三條高山鐵路之一，全長71.4公里，從海拔30公尺的嘉義一路攀升至2216公尺的阿里山。獨特的之字形（Switchback）與螺旋形路線是工程上的偉大成就。沿途穿越熱帶、暖帶、溫帶三個林相帶，車窗外的景觀變化萬千。</p>',
    price: 600,
    originPrice: 780,
    address: '嘉義縣竹崎鄉竹崎車站',
    category: 'tickets',
    coordinates: { lat: 23.5239, lng: 120.5511 },
    imagePool: 'mountain',
    features: '高山鐵路,之字形路線,三帶林相,歷史鐵道,車窗景觀,世界遺產',
    transport: '嘉義火車站搭乘阿里山森林鐵路本線，全程約3.5小時',
    evaluate: 4.6,
    evaluateNum: 670,
  },
  {
    slug: 'aogu-wetland',
    title: '鰲鼓濕地賞鳥生態之旅',
    description: '嘉義海岸的國際級濕地，冬季候鳥群聚的生態觀察天堂。',
    content:
      '<p>鰲鼓濕地佔地約1470公頃，是台灣西南沿海最大的濕地生態園區。每年冬季有超過兩百種候鳥在此棲息過冬，包含黑面琵鷺、環頸雉等珍稀鳥類。園區設有多處賞鳥亭與步道，搭配專業生態導覽，讓您近距離觀賞壯觀的候鳥群飛景象。</p>',
    price: 800,
    originPrice: 1000,
    address: '嘉義縣東石鄉鰲鼓村',
    category: 'package',
    coordinates: { lat: 23.4917, lng: 120.15 },
    imagePool: 'nature',
    features: '候鳥賞鳥,濕地生態,黑面琵鷺,生態導覽,冬季推薦,攝影天堂',
    transport: '嘉義火車站搭乘嘉義客運往東石方向，於鰲鼓站下車',
    evaluate: 4.4,
    evaluateNum: 230,
  },
  {
    slug: 'meishan-taixing-waterfall',
    title: '梅山太興飛瀑步道健行',
    description: '隱藏在梅山山區的秘境飛瀑，壯觀水簾與幽靜竹林的完美結合。',
    content:
      '<p>太興飛瀑位於梅山鄉太興村，又稱阿葉溪瀑布，落差約30公尺的瀑布在雨季時氣勢磅礴。步道全程約1.5公里，沿途穿越茂密的孟宗竹林，涼爽宜人。抵達瀑布底部時，水霧飛濺帶來沁涼感受，是炎夏最佳的消暑秘境。含在地嚮導與竹筒飯午餐。</p>',
    price: 900,
    originPrice: 1150,
    address: '嘉義縣梅山鄉太興村',
    category: 'package',
    coordinates: { lat: 23.575, lng: 120.65 },
    imagePool: 'waterfall',
    features: '秘境飛瀑,竹林步道,消暑秘境,在地嚮導,竹筒飯,生態豐富',
    transport: '嘉義火車站搭乘嘉義客運往梅山方向，於太興站下車步行約20分鐘',
    evaluate: 4.4,
    evaluateNum: 180,
  },
  {
    slug: 'zhuqi-water-park',
    title: '竹崎親水公園門票',
    description: '阿里山腳下的親水樂園，花仙子步道與天空走廊老少咸宜。',
    content:
      '<p>竹崎親水公園佔地約12公頃，位於朴子溪畔，是竹崎鄉最受歡迎的休閒景點。園區最大亮點是全長185公尺的天空走廊，離地最高約19公尺，穿梭於樹冠層間視野遼闊。花仙子步道四季花卉盛開，夏季的戲水區更是孩子們的天堂。</p>',
    price: 80,
    originPrice: 100,
    address: '嘉義縣竹崎鄉竹崎村中華路',
    category: 'tickets',
    coordinates: { lat: 23.5244, lng: 120.5522 },
    imagePool: 'park',
    features: '天空走廊,親水戲水,花仙子步道,樹冠層,親子景點,免費入園',
    transport: '嘉義火車站搭乘嘉義客運往竹崎方向，於竹崎站下車步行約10分鐘',
    evaluate: 4.1,
    evaluateNum: 350,
  },
  {
    slug: 'chukou-visitor-center',
    title: '觸口遊客中心生態體驗',
    description: '阿里山入口處的生態教育中心，認識阿里山的自然與人文。',
    content:
      '<p>觸口遊客中心是進入阿里山風景區的第一站，中心以綠建築概念打造，展示阿里山的地質、動植物生態及鄒族文化。戶外設有觸口牛埔仔大草原、逐鹿傳說梅花鹿園及樹木銀行，適合在上山前先全面認識阿里山。生態體驗包含導覽、餵鹿及手作DIY。</p>',
    price: 350,
    originPrice: 450,
    address: '嘉義縣番路鄉觸口村車埕51號',
    category: 'package',
    coordinates: { lat: 23.4567, lng: 120.5917 },
    imagePool: 'nature',
    features: '生態教育,梅花鹿,鄒族文化,綠建築,手作DIY,親子適合',
    transport: '嘉義火車站搭乘台灣好行阿里山線至觸口站下車即達',
    evaluate: 4.0,
    evaluateNum: 270,
  },
  {
    slug: 'high-heel-church',
    title: '高跟鞋教堂拍照巡禮',
    description: '全球唯一高跟鞋造型建築，獲金氏世界紀錄認證的浪漫地標。',
    content:
      '<p>高跟鞋教堂位於布袋海景公園內，以320片藍色玻璃打造，高約17公尺，獲金氏世界紀錄認證為「以鞋子為造型的最大建築物」。建築靈感來自對早期烏腳病患者無法穿上高跟鞋出嫁的遺憾，浪漫中帶著溫暖的故事。夜間燈光投射下更顯夢幻。</p>',
    price: 100,
    originPrice: 130,
    address: '嘉義縣布袋鎮海興街6號',
    category: 'tickets',
    coordinates: { lat: 23.3794, lng: 120.1628 },
    imagePool: 'beach',
    features: '金氏紀錄,藍色玻璃,浪漫地標,夜間燈光,拍照景點,免費參觀',
    transport: '嘉義火車站搭乘嘉義客運往布袋方向，於布袋站下車步行約15分鐘',
    evaluate: 3.7,
    evaluateNum: 520,
  },
  {
    slug: 'dongshi-ecology-tour',
    title: '東石生態之旅',
    description: '探訪嘉義沿海的蚵田風光與紅樹林生態，體驗蚵農的日常。',
    content:
      '<p>東石鄉是台灣最重要的蚵仔產地，沿海的蚵棚景觀壯闘有致。這趟生態之旅帶您搭乘膠筏深入蚵田，了解蚵仔的養殖過程，親手體驗剖蚵。接著前往紅樹林生態區觀察招潮蟹、彈塗魚等潮間帶生物，最後享用一頓豐盛的鮮蚵大餐。</p>',
    price: 900,
    originPrice: 1150,
    address: '嘉義縣東石鄉東石村',
    category: 'package',
    coordinates: { lat: 23.45, lng: 120.1583 },
    imagePool: 'beach',
    features: '蚵田體驗,膠筏遊覽,紅樹林,潮間帶,剖蚵體驗,鮮蚵大餐',
    transport: '嘉義火車站搭乘嘉義客運往東石方向，於東石站下車',
    evaluate: 4.3,
    evaluateNum: 260,
  },
  {
    slug: 'guanghua-firefly-trail',
    title: '光華賞螢步道夜間導覽',
    description: '春季限定的螢火蟲大爆發，光華村的夜間魔幻森林體驗。',
    content:
      '<p>光華村位於阿里山風景區內，每年四月至六月是螢火蟲大量出現的季節。入夜後步道兩旁數以萬計的螢火蟲同時閃爍，宛如置身銀河之中。專業生態導覽員帶領觀賞螢火蟲的同時，也會介紹夜間生態，有機會遇見貓頭鷹、飛鼠等夜行性動物。</p>',
    price: 500,
    originPrice: 650,
    address: '嘉義縣竹崎鄉光華村',
    category: 'package',
    coordinates: { lat: 23.5333, lng: 120.6667 },
    imagePool: 'nature',
    features: '螢火蟲,夜間生態,春季限定,專業導覽,夜行動物,魔幻森林',
    transport: '嘉義火車站搭乘台灣好行阿里山線至石棹站，轉搭接駁車約15分鐘',
    evaluate: 4.6,
    evaluateNum: 280,
  },
  {
    slug: 'eryanping-trail-cloud',
    title: '二延平步道雲瀑體驗',
    description: '阿里山公路旁的秘境步道，冬季限定的壯觀雲瀑傾瀉而下。',
    content:
      '<p>二延平步道位於阿里山公路53.5K處，全長約1公里，是欣賞雲瀑最佳的觀景點。冬季東北季風將雲海推過山稜，形成如瀑布般傾瀉的雲瀑奇景，搭配夕陽染紅的天際，美到令人感動。步道沿途茶園翠綠、竹林搖曳，四季各有不同風貌。</p>',
    price: 300,
    originPrice: 380,
    address: '嘉義縣番路鄉阿里山公路53.5K',
    category: 'tickets',
    coordinates: { lat: 23.4833, lng: 120.65 },
    imagePool: 'mountain',
    features: '雲瀑奇景,夕陽美景,茶園風光,冬季限定,攝影秘境,輕鬆步道',
    transport: '嘉義火車站搭乘台灣好行阿里山線至二延平步道口站下車',
    evaluate: 4.7,
    evaluateNum: 390,
  },
]
