import type { ProductDefinition } from '../types'

export const hsinchuProducts: ProductDefinition[] = [
  {
    slug: 'chenghuang-temple',
    title: '新竹城隍廟文化巡禮',
    description: '超過兩百年歷史的城隍廟，北台灣香火最鼎盛的廟宇之一。',
    content:
      '<p>新竹城隍廟建於1748年，是全台官位最高的城隍爺，廟內雕樑畫棟保存完整。廟口周圍匯集了數十攤經典小吃——貢丸湯、米粉、潤餅等新竹名產一應俱全，是認識新竹信仰文化與飲食的最佳起點。</p>',
    price: 400,
    originPrice: 500,
    address: '新竹市北區中山路75號',
    category: 'package',
    coordinates: { lat: 24.8058, lng: 120.9678 },
    imagePool: 'temple',
    features: '百年古蹟,廟口小吃,文化導覽,傳統工藝,貢丸湯',
    transport: '搭乘火車至新竹站步行約10分鐘',
    evaluate: 4.5,
    evaluateNum: 620,
  },
  {
    slug: 'nanliao-fishing-port',
    title: '南寮漁港自行車半日遊',
    description: '地中海風情漁港搭配十七公里海岸線，風城最美濱海之旅。',
    content:
      '<p>南寮漁港經過改造後充滿地中海異國風情，白色建築與藍天大海相映成趣。從漁港出發沿十七公里海岸線自行車道騎行，途經看海公園、港南運河與香山濕地，全程平坦舒適，是新竹最受歡迎的休閒路線。</p>',
    price: 600,
    originPrice: 750,
    address: '新竹市北區南寮街261號',
    category: 'package',
    coordinates: { lat: 24.8297, lng: 120.9292 },
    imagePool: 'beach',
    features: '自行車道,地中海風情,海岸風光,落日美景,親子適合',
    transport: '搭乘新竹市公車藍15路至南寮漁港站下車',
    evaluate: 4.6,
    evaluateNum: 580,
  },
  {
    slug: 'hsinchu-zoo',
    title: '新竹動物園門票',
    description: '全台最古老動物園華麗重生，沒有籠子的友善動物園。',
    content:
      '<p>新竹市立動物園創立於1936年，是台灣現存最古老的動物園。經過「新竹動物園再生計畫」大幅翻新後，以無籠舍開放式設計重新開園，讓遊客能更近距離觀察動物自然行為，園區緊鄰新竹公園，適合安排一日遊。</p>',
    price: 100,
    originPrice: 120,
    address: '新竹市東區食品路66號',
    category: 'tickets',
    coordinates: { lat: 24.7997, lng: 120.9794 },
    imagePool: 'park',
    features: '開放式園區,動物互動,親子景點,歷史園區,無障礙設施',
    transport: '搭乘火車至新竹站轉乘市公車至動物園站',
    evaluate: 4.4,
    evaluateNum: 720,
  },
  {
    slug: 'moat-park',
    title: '護城河親水公園漫步',
    description: '貫穿新竹市中心的綠帶廊道，城市中的悠閒水岸。',
    content:
      '<p>護城河親水公園沿著舊護城河道整治而成，兩岸種植垂柳與花卉，步道串聯東門城、新竹市政府與火車站商圈。夜間河道燈光璀璨，假日常有街頭藝人表演，是散步約會的浪漫去處。</p>',
    price: 350,
    originPrice: 450,
    address: '新竹市東區東門街',
    category: 'package',
    coordinates: { lat: 24.8019, lng: 120.9711 },
    imagePool: 'city',
    features: '水岸步道,夜間燈光,街頭藝人,城市綠帶,輕鬆散步',
    transport: '搭乘火車至新竹站步行約5分鐘',
    evaluate: 4.2,
    evaluateNum: 340,
  },
  {
    slug: 'eighteen-peaks',
    title: '十八尖山健行步道',
    description: '新竹市區最高點，春季花季繽紛絕美的都會山丘。',
    content:
      '<p>十八尖山是新竹市區最大的都會森林公園，步道全長約3.5公里，沿途林蔭茂密、花木扶疏。每年三月花季期間種植數萬株杜鵑與茶花，繽紛花海是新竹春天的代表景觀。山頂可遠眺市區與海岸線全景。</p>',
    price: 400,
    originPrice: 500,
    address: '新竹市東區寶山路145巷',
    category: 'package',
    coordinates: { lat: 24.7903, lng: 120.9856 },
    imagePool: 'mountain',
    features: '都會森林,花季步道,全景觀景,健行運動,自然生態',
    transport: '搭乘新竹市公車至十八尖山站下車',
    evaluate: 4.5,
    evaluateNum: 400,
  },
  {
    slug: 'chenghuang-temple-food',
    title: '新竹都城隍廟美食通票',
    description: '一票吃遍城隍廟口經典小吃，貢丸米粉潤餅全包。',
    content:
      '<p>城隍廟口美食區是新竹最密集的傳統小吃聚落，數十年老店林立。本通票精選五家人氣攤位——阿城號米粉、鄭家貢丸、郭家潤餅、北門炸粿與廟口鴨香飯，一票在手即可逐攤品嚐新竹最道地的風味。</p>',
    price: 450,
    originPrice: 580,
    address: '新竹市北區中山路75號周邊',
    category: 'package',
    coordinates: { lat: 24.8062, lng: 120.9681 },
    imagePool: 'nightMarket',
    features: '貢丸湯,米粉,潤餅,炸粿,鴨香飯,老店巡禮',
    transport: '搭乘火車至新竹站步行約10分鐘',
    evaluate: 4.6,
    evaluateNum: 510,
  },
  {
    slug: 'glass-museum',
    title: '玻璃工藝博物館參觀門票',
    description: '風城獨有的玻璃藝術殿堂，感受光影與工藝之美。',
    content:
      '<p>新竹玻璃工藝博物館設於日治時期自治會館建築內，展示新竹玻璃產業的發展歷程與當代玻璃藝術創作。館內常設展與特展輪替展出，並提供玻璃DIY體驗課程，讓訪客親手感受這項在地傳統工藝的魅力。</p>',
    price: 100,
    originPrice: 130,
    address: '新竹市東區東大路一段2號',
    category: 'tickets',
    coordinates: { lat: 24.8003, lng: 120.9786 },
    imagePool: 'museum',
    features: '玻璃藝術,DIY體驗,日式建築,特展活動,文創商品',
    transport: '搭乘火車至新竹站步行約15分鐘至新竹公園內',
    evaluate: 4.3,
    evaluateNum: 290,
  },
  {
    slug: 'image-museum',
    title: '影像博物館門票',
    description: '全台首座影像主題博物館，百年戲院風華再現。',
    content:
      '<p>新竹影像博物館前身為1933年落成的「新竹有樂館」，是當時最先進的歐化劇場。修復後作為影像藝術展演空間，定期放映經典與獨立電影、舉辦影像藝術展覽，建築本身就是一部活的電影史。</p>',
    price: 80,
    originPrice: 100,
    address: '新竹市東區中正路65號',
    category: 'tickets',
    coordinates: { lat: 24.8033, lng: 120.9686 },
    imagePool: 'museum',
    features: '百年戲院,電影放映,影像藝術,歷史建築,藝文展覽',
    transport: '搭乘火車至新竹站步行約8分鐘',
    evaluate: 4.1,
    evaluateNum: 180,
  },
  {
    slug: 'xinzhiping-house',
    title: '辛志平校長故居參觀',
    description: '日式木造宿舍群靜謐之美，走進昭和時代的生活。',
    content:
      '<p>辛志平校長故居為日治時期新竹中學校長宿舍，是典型的日式木造住宅建築。修復後保留了雨淋板外牆、和室格局與日式庭園，內部展示辛校長生平事蹟與新竹中學歷史，是感受日式生活美學的隱藏景點。</p>',
    price: 100,
    originPrice: 130,
    address: '新竹市東區東門街32號',
    category: 'tickets',
    coordinates: { lat: 24.8022, lng: 120.9714 },
    imagePool: 'temple',
    features: '日式宿舍,歷史建築,和室空間,庭園造景,文化導覽',
    transport: '搭乘火車至新竹站步行約6分鐘',
    evaluate: 4.2,
    evaluateNum: 150,
  },
  {
    slug: 'hsinchu-zoo-v2',
    title: '新竹市立動物園親子套票',
    description: '含動物園門票與公園野餐組合，親子一日遊最佳選擇。',
    content:
      '<p>本套票結合新竹市立動物園門票與新竹公園野餐體驗，含野餐墊、輕食餐盒與飲品。在無籠舍的友善環境中觀賞河馬樂樂、孟加拉虎等明星動物後，移步至公園草坪享用野餐，是最療癒的親子時光。</p>',
    price: 650,
    originPrice: 800,
    address: '新竹市東區食品路66號',
    category: 'package',
    coordinates: { lat: 24.7997, lng: 120.9794 },
    imagePool: 'park',
    features: '動物園門票,野餐體驗,輕食餐盒,親子活動,公園綠地',
    transport: '搭乘新竹市公車至動物園站下車',
    evaluate: 4.5,
    evaluateNum: 430,
  },
  {
    slug: 'east-gate',
    title: '東門城歷史散步',
    description: '新竹僅存的古城門，見證竹塹城兩百年歲月。',
    content:
      '<p>東門城（迎曦門）建於1829年，是新竹竹塹城唯一留存的城門古蹟。城門採雙層樓閣式設計，周圍的東門城廣場是市民活動的中心，夜間打上燈光格外莊嚴。搭配護城河步道散步，可完整感受舊城區氛圍。</p>',
    price: 200,
    originPrice: 260,
    address: '新竹市東區中央路與東門街交叉口',
    category: 'package',
    coordinates: { lat: 24.8025, lng: 120.9708 },
    imagePool: 'city',
    features: '古城門,歷史古蹟,夜間燈光,城市散步,護城河',
    transport: '搭乘火車至新竹站步行約5分鐘',
    evaluate: 4.3,
    evaluateNum: 270,
  },
  {
    slug: 'hsinchu-park',
    title: '新竹公園全園區套票',
    description: '動物園、玻工館、氣象站一票暢遊新竹最大公園。',
    content:
      '<p>新竹公園佔地約18公頃，園區內涵蓋動物園、玻璃工藝博物館、昆蟲館、氣象站與大片綠地。本套票含園區內所有收費設施門票，可一次暢遊所有場館，春天櫻花與杜鵑盛開時更是絕美的賞花勝地。</p>',
    price: 350,
    originPrice: 450,
    address: '新竹市東區東大路一段',
    category: 'tickets',
    coordinates: { lat: 24.8, lng: 120.979 },
    imagePool: 'park',
    features: '動物園,玻工館,櫻花季,昆蟲館,都會公園',
    transport: '搭乘新竹市公車至公園站下車',
    evaluate: 4.4,
    evaluateNum: 350,
  },
  {
    slug: 'xiangshan-wetland',
    title: '香山濕地賞蟹步道',
    description: '北台灣最大的潮間帶濕地，招潮蟹大軍的壯觀秘境。',
    content:
      '<p>香山濕地面積約1600公頃，是國家級重要濕地，擁有全台種類最豐富的招潮蟹族群。賞蟹步道以高架木棧道深入潮間帶，退潮時可近距離觀察弧邊招潮蟹、彈塗魚等濕地生物，夕陽時分更是攝影天堂。</p>',
    price: 500,
    originPrice: 650,
    address: '新竹市香山區中華路五段320巷',
    category: 'package',
    coordinates: { lat: 24.7631, lng: 120.9208 },
    imagePool: 'beach',
    features: '賞蟹步道,潮間帶生態,夕陽美景,生態導覽,攝影景點',
    transport: '搭乘新竹市公車藍1路至海山漁港站下車步行約10分鐘',
    evaluate: 4.6,
    evaluateNum: 380,
  },
  {
    slug: 'qingcaohu',
    title: '青草湖遊船體驗',
    description: '新竹八景之一的青草湖，泛舟湖上賞古寺山色。',
    content:
      '<p>青草湖位於新竹市東南方，曾是台灣知名的風景區，近年整治後重現往日風采。湖畔有靈隱寺與環湖步道，租借小船泛舟湖面，兩岸綠意盎然、古寺鐘聲迴盪，是遠離城市喧囂的清幽之地。</p>',
    price: 400,
    originPrice: 500,
    address: '新竹市東區明湖路',
    category: 'tickets',
    coordinates: { lat: 24.7878, lng: 120.9911 },
    imagePool: 'nature',
    features: '遊船體驗,環湖步道,古寺巡禮,湖光山色,攝影景點',
    transport: '搭乘新竹市公車至青草湖站下車',
    evaluate: 4.2,
    evaluateNum: 240,
  },
  {
    slug: 'hsinchu-art-museum',
    title: '新竹美術館特展門票',
    description: '市定古蹟活化的藝術空間，在百年建築中欣賞當代創作。',
    content:
      '<p>新竹市美術館前身為1925年落成的新竹市役所，是巴洛克風格的歷史建築。活化後作為當代藝術展覽空間，定期更換特展主題，結合在地藝術家與國際創作者作品，建築與藝術的對話令人驚艷。</p>',
    price: 120,
    originPrice: 150,
    address: '新竹市北區中央路116號',
    category: 'tickets',
    coordinates: { lat: 24.8047, lng: 120.9669 },
    imagePool: 'museum',
    features: '歷史建築,當代藝術,特展活動,巴洛克建築,文創商品',
    transport: '搭乘火車至新竹站步行約8分鐘',
    evaluate: 4.3,
    evaluateNum: 200,
  },
  {
    slug: 'military-village-museum',
    title: '眷村博物館導覽體驗',
    description: '走進新竹眷村的時光記憶，感受大時代下的小日子。',
    content:
      '<p>新竹眷村博物館是全台第一座以眷村為主題的博物館，透過實物展示、影音紀錄與模擬場景，重現1950至1980年代眷村居民的日常生活。從竹籬笆圍牆到大同電鍋，每個物件都承載著一段遷移與落地生根的故事。</p>',
    price: 250,
    originPrice: 320,
    address: '新竹市東區東大路二段105號',
    category: 'package',
    coordinates: { lat: 24.7978, lng: 120.9825 },
    imagePool: 'museum',
    features: '眷村文化,歷史展覽,互動體驗,導覽解說,時代記憶',
    transport: '搭乘新竹市公車至眷村博物館站下車',
    evaluate: 4.4,
    evaluateNum: 190,
  },
  {
    slug: 'hsinchu-prefecture',
    title: '新竹州廳建築巡禮',
    description: '百年歐風官署建築，新竹最優雅的歷史地標。',
    content:
      '<p>新竹州廳建於1925年，為磚造二層樓的西洋歷史主義建築，是日治時期新竹州的行政中心。立面的紅磚搭配洗石子裝飾、圓拱窗與山牆極為典雅，現為新竹市政府所在地，開放時段可入內參觀廳堂與迴廊。</p>',
    price: 300,
    originPrice: 380,
    address: '新竹市北區中正路120號',
    category: 'package',
    coordinates: { lat: 24.805, lng: 120.9664 },
    imagePool: 'city',
    features: '歷史建築,歐式風格,導覽解說,建築巡禮,攝影景點',
    transport: '搭乘火車至新竹站步行約7分鐘',
    evaluate: 4.3,
    evaluateNum: 160,
  },
  {
    slug: 'wind-city-shopping',
    title: '風城購物體驗套票',
    description: '新竹巨城與遠百優惠通票，科技城也能盡情血拼。',
    content:
      '<p>新竹是台灣科技重鎮，消費力旺盛。本套票結合巨城購物中心與遠東百貨的購物優惠券、美食街折扣與電影票，讓您在逛完古蹟景點後，也能享受現代都會的購物樂趣，體驗新竹新舊交融的城市魅力。</p>',
    price: 1200,
    originPrice: 1500,
    address: '新竹市東區中央路229號',
    category: 'package',
    coordinates: { lat: 24.8006, lng: 120.9739 },
    imagePool: 'city',
    features: '購物優惠,美食街,電影票,百貨公司,都會體驗',
    transport: '搭乘火車至新竹站步行約10分鐘',
    evaluate: 4.1,
    evaluateNum: 310,
  },
  {
    slug: 'hukou-old-street',
    title: '湖口老街一日遊',
    description: '紅磚拱廊的客家老街，品味古早味與慢活時光。',
    content:
      '<p>湖口老街保留了日治時期的紅磚拱廊建築，全長約三百公尺，兩側店家販售客家米食、擂茶與手工藝品。街尾的三元宮是客家信仰中心，假日還有文創市集。搭配導覽深入了解客家移民史，是新竹近郊最有味道的老街。</p>',
    price: 800,
    originPrice: 1000,
    address: '新竹縣湖口鄉湖口老街',
    category: 'package',
    coordinates: { lat: 24.8931, lng: 121.0417 },
    imagePool: 'oldStreet',
    features: '客家文化,紅磚拱廊,擂茶體驗,文創市集,三元宮',
    transport: '搭乘火車至湖口站步行約15分鐘',
    evaluate: 4.4,
    evaluateNum: 350,
  },
  {
    slug: 'nanliao-fisherman-wharf',
    title: '新竹漁人碼頭夕陽之旅',
    description: '南寮漁港旁的觀景碼頭，欣賞台灣海峽最美日落。',
    content:
      '<p>新竹漁人碼頭位於南寮漁港旁，設有觀景平台與親水設施。每日傍晚時分，夕陽緩緩沒入台灣海峽，天空染成橘紅色彩，是新竹最浪漫的賞夕陽景點。周邊有海鮮餐廳與咖啡廳，可邊享用美食邊等待日落。</p>',
    price: 500,
    originPrice: 600,
    address: '新竹市北區南寮街',
    category: 'package',
    coordinates: { lat: 24.8289, lng: 120.9278 },
    imagePool: 'beach',
    features: '夕陽美景,觀景平台,海鮮餐廳,親水設施,浪漫約會',
    transport: '搭乘新竹市公車藍15路至南寮站下車',
    evaluate: 4.5,
    evaluateNum: 420,
  },
]
