import type { ProductDefinition } from '../types'

export const hsinchuCountyProducts: ProductDefinition[] = [
  {
    slug: 'neiwan-old-street',
    title: '內灣老街散策體驗',
    description: '漫步內灣老街，品嚐客家美食與懷舊風情，感受山城小鎮的悠閒氛圍。',
    content:
      '<p>內灣老街位於新竹縣橫山鄉，是一條充滿客家文化特色的懷舊老街。街上保留了日治時期的建築風貌，兩旁林立著各式客家美食攤位，野薑花粽、擂茶、粄條等道地小吃讓人目不暇給。老街盡頭的內灣戲院更是拍照打卡的熱門景點，帶您穿越時空回到舊時光。</p>',
    price: 350,
    originPrice: 450,
    address: '新竹縣橫山鄉內灣村中正路',
    category: 'package',
    coordinates: { lat: 24.7042, lng: 121.1742 },
    imagePool: 'oldStreet',
    features: '客家美食,懷舊老街,內灣戲院,野薑花粽,手作體驗,山城風情',
    transport: '搭乘台鐵內灣線至內灣站，步行約3分鐘即達老街入口',
    evaluate: 4.3,
    evaluateNum: 520,
  },
  {
    slug: 'leofoo-village-theme-park',
    title: '六福村主題遊樂園門票',
    description: '台灣最大主題遊樂園，集合刺激遊樂設施與野生動物園，適合全家大小同樂。',
    content:
      '<p>六福村主題遊樂園位於新竹縣關西鎮，園區分為美國大西部、南太平洋、阿拉伯皇宮及非洲部落四大主題區。擁有全台最刺激的笑傲飛鷹、急流泛舟等遊樂設施，非洲部落區更可近距離觀賞獅子、長頸鹿等野生動物，是老少咸宜的歡樂天堂。</p>',
    price: 799,
    originPrice: 999,
    address: '新竹縣關西鎮仁安里拱子溝60號',
    category: 'tickets',
    coordinates: { lat: 24.8308, lng: 121.2072 },
    imagePool: 'park',
    features: '遊樂設施,野生動物園,四大主題區,笑傲飛鷹,親子同樂,水上樂園',
    transport: '於中壢或竹北車站搭乘新竹客運直達六福村',
    evaluate: 4.5,
    evaluateNum: 780,
  },
  {
    slug: 'smangus',
    title: '司馬庫斯神木群二日遊',
    description: '深入泰雅族聖地司馬庫斯，探訪千年巨木群與上帝的部落之美。',
    content:
      '<p>司馬庫斯位於新竹縣尖石鄉海拔1500公尺的深山中，被譽為「上帝的部落」。這裡擁有全台最大的紅檜巨木群，樹齡超過兩千年的神木令人嘆為觀止。沿途可欣賞壯麗的山谷雲海與豐富的自然生態，體驗泰雅族傳統文化與部落生活，是一趟身心靈的深度之旅。</p>',
    price: 4500,
    originPrice: 5500,
    address: '新竹縣尖石鄉玉峰村司馬庫斯部落',
    category: 'package',
    coordinates: { lat: 24.5938, lng: 121.2358 },
    imagePool: 'mountain',
    features: '千年巨木,泰雅部落,雲海美景,生態導覽,部落美食,深度旅遊',
    transport: '自行開車由竹東經尖石、秀巒至司馬庫斯，全程約3.5小時',
    evaluate: 4.8,
    evaluateNum: 350,
  },
  {
    slug: 'lavender-cottage',
    title: '薰衣草森林門票',
    description: '隱身山林中的紫色浪漫莊園，享受花草香氛與悠閒的森林午後。',
    content:
      '<p>薰衣草森林新竹尖石店坐落於海拔700公尺的山林中，園區種植了大片薰衣草與各式香草植物，空氣中瀰漫著淡雅花香。漫步森林步道、在樹屋咖啡廳享用下午茶、體驗手作香草課程，每個角落都充滿浪漫與驚喜，是遠離塵囂的療癒聖地。</p>',
    price: 150,
    originPrice: 200,
    address: '新竹縣尖石鄉嘉樂村嘉樂129號',
    category: 'tickets',
    coordinates: { lat: 24.6697, lng: 121.1839 },
    imagePool: 'nature',
    features: '薰衣草花田,森林步道,手作體驗,下午茶,浪漫拍照,香草植物',
    transport: '自竹東搭乘新竹客運往尖石方向，於嘉樂站下車步行約15分鐘',
    evaluate: 4.4,
    evaluateNum: 430,
  },
  {
    slug: 'beipu-old-street',
    title: '北埔老街客家文化之旅',
    description: '探訪北埔古蹟群與客家擂茶文化，品味百年歷史的人文風情。',
    content:
      '<p>北埔老街是新竹縣最具歷史底蘊的客家聚落之一，街上保存了金廣福公館、天水堂、姜阿新洋樓等國定古蹟。這趟文化之旅將帶您深入了解客家擂茶的製作過程，品嚐柿餅、粄條等傳統美食，並參觀百年古蹟建築，感受北埔深厚的人文歷史。</p>',
    price: 500,
    originPrice: 650,
    address: '新竹縣北埔鄉北埔街',
    category: 'package',
    coordinates: { lat: 24.6971, lng: 121.0533 },
    imagePool: 'oldStreet',
    features: '客家擂茶,古蹟導覽,柿餅品嚐,金廣福公館,天水堂,手作體驗',
    transport: '於竹東搭乘新竹客運往北埔方向，於北埔站下車即達',
    evaluate: 4.2,
    evaluateNum: 380,
  },
  {
    slug: 'xinpu-persimmon',
    title: '新埔柿餅手作體驗',
    description: '秋季限定的柿餅曬製體驗，親手參與客家傳統食品的製作過程。',
    content:
      '<p>新埔鎮是台灣柿餅的故鄉，每年九月至翌年一月是柿餅產季。在百年老字號的柿餅加工廠中，您可以親眼見證從選果、削皮、日曬到炭烤的完整製程，還能親手體驗削柿皮與捏柿餅的樂趣。金黃色的柿餅在九降風中緩緩風乾的壯觀畫面，更是攝影愛好者的天堂。</p>',
    price: 350,
    originPrice: 450,
    address: '新竹縣新埔鎮旱坑里旱坑路一段283巷53號',
    category: 'package',
    coordinates: { lat: 24.8278, lng: 121.0756 },
    imagePool: 'oldStreet',
    features: '柿餅製作,手作體驗,攝影景點,客家文化,伴手禮,季節限定',
    transport: '於新竹搭乘新竹客運往新埔方向，於新埔站下車轉搭計程車約10分鐘',
    evaluate: 4.5,
    evaluateNum: 290,
  },
  {
    slug: 'green-world',
    title: '綠世界生態農場門票',
    description: '北埔山間的生態教育農場，近距離接觸草泥馬、鵜鶘等可愛動物。',
    content:
      '<p>綠世界生態農場佔地75公頃，園區規劃為天鵝湖、大探奇區、鳥類生態公園、蝴蝶生態公園及水生植物公園五大主題區。這裡最受歡迎的明星動物是草泥馬（羊駝），您可以近距離餵食互動。園區內生態豐富，適合親子共遊與生態學習。</p>',
    price: 380,
    originPrice: 480,
    address: '新竹縣北埔鄉大湖村7鄰20號',
    category: 'tickets',
    coordinates: { lat: 24.6674, lng: 121.0536 },
    imagePool: 'nature',
    features: '草泥馬互動,生態導覽,天鵝湖,蝴蝶園,親子景點,鳥類觀察',
    transport: '於竹東搭乘新竹客運往北埔方向，於綠世界站下車即達',
    evaluate: 4.3,
    evaluateNum: 510,
  },
  {
    slug: 'jianshi-hot-spring',
    title: '尖石溫泉湯屋體驗',
    description: '隱身山谷的美人湯溫泉，享受碳酸氫鈉泉質的潤滑觸感。',
    content:
      '<p>尖石溫泉位於新竹縣尖石鄉油羅溪畔，泉質為碳酸氫鈉泉，俗稱美人湯，泡後肌膚滑嫩細緻。在群山環繞的溪谷中享受露天溫泉，聆聽潺潺溪流聲，是遠離都市喧囂的絕佳放鬆方式。冬季泡湯搭配周邊部落美食，更是一大享受。</p>',
    price: 600,
    originPrice: 780,
    address: '新竹縣尖石鄉嘉樂村8鄰1號',
    category: 'package',
    coordinates: { lat: 24.7083, lng: 121.1975 },
    imagePool: 'hotSpring',
    features: '碳酸氫鈉泉,美人湯,露天湯屋,溪谷景觀,放鬆療癒,冬季推薦',
    transport: '自竹東搭乘新竹客運往尖石方向，於尖石站下車步行約10分鐘',
    evaluate: 4.4,
    evaluateNum: 320,
  },
  {
    slug: 'guanxi-xiancao-museum',
    title: '關西仙草博物館門票',
    description: '全台唯一仙草主題博物館，認識仙草文化並品嚐各式仙草料理。',
    content:
      '<p>關西鎮是台灣仙草的主要產地，仙草博物館以互動展示介紹仙草的種植、加工與應用歷史。館內設有仙草生態園區、DIY體驗區及仙草美食區，可以品嚐仙草凍、仙草雞湯、仙草茶等特色料理。寓教於樂的內容讓大人小孩都能收穫滿滿。</p>',
    price: 100,
    originPrice: 130,
    address: '新竹縣關西鎮中豐路二段326號',
    category: 'tickets',
    coordinates: { lat: 24.7889, lng: 121.1772 },
    imagePool: 'museum',
    features: '仙草文化,DIY體驗,特色美食,生態園區,親子適合,伴手禮',
    transport: '於中壢或新竹搭乘新竹客運往關西方向，於關西站下車步行約10分鐘',
    evaluate: 3.9,
    evaluateNum: 210,
  },
  {
    slug: 'emei-lake',
    title: '峨眉湖環湖自行車一日遊',
    description: '騎乘自行車環繞峨眉湖畔，欣賞巨型彌勒佛與湖光山色。',
    content:
      '<p>峨眉湖又名大埔水庫，湖畔矗立著全球最高的青銅彌勒佛像，高達72公尺的巨像倒映湖面蔚為壯觀。環湖自行車道全長約7公里，沿途經過十二寮休閒農業區、峨眉天主堂等景點，騎行在湖光山色間，微風拂面，是最愜意的休閒方式。</p>',
    price: 450,
    originPrice: 580,
    address: '新竹縣峨眉鄉湖光村',
    category: 'package',
    coordinates: { lat: 24.6758, lng: 121.0156 },
    imagePool: 'nature',
    features: '環湖自行車,彌勒佛像,湖光山色,十二寮,休閒農業,攝影景點',
    transport: '自竹東搭乘新竹客運往峨眉方向，於峨眉站下車轉搭計程車約5分鐘',
    evaluate: 4.3,
    evaluateNum: 260,
  },
  {
    slug: 'zhudong-anime-park',
    title: '竹東動漫園區門票',
    description: '結合動漫文創與在地客家文化的特色園區，體驗動漫彩繪世界。',
    content:
      '<p>竹東動漫園區利用閒置空間打造充滿動漫元素的文創基地，園區內有大型3D彩繪牆、動漫角色造景、文創市集及DIY工作坊。結合客家文化元素的動漫創作別具特色，不定期舉辦cosplay活動與動漫展覽，是動漫迷與文青族群的必訪景點。</p>',
    price: 100,
    originPrice: 130,
    address: '新竹縣竹東鎮東林路196號',
    category: 'tickets',
    coordinates: { lat: 24.7333, lng: 121.0933 },
    imagePool: 'city',
    features: '動漫彩繪,3D壁畫,文創市集,DIY工坊,客家元素,拍照打卡',
    transport: '搭乘台鐵內灣線至竹東站，步行約10分鐘',
    evaluate: 3.8,
    evaluateNum: 180,
  },
  {
    slug: 'hengshan-hexing-station',
    title: '橫山合興車站浪漫之旅',
    description: '全台唯一的愛情火車站，充滿浪漫元素的鐵道文化景點。',
    content:
      '<p>合興車站原為內灣線上的招呼站，因一段追火車的愛情故事而被保留，被譽為「愛情火車站」。站內設有愛情候車亭、許願鐘、心鎖牆等浪漫裝置藝術，舊式火車車廂改裝為文創商店。這趟浪漫之旅包含導覽解說、手作明信片及在地下午茶。</p>',
    price: 380,
    originPrice: 480,
    address: '新竹縣橫山鄉中山街一段17號',
    category: 'package',
    coordinates: { lat: 24.7217, lng: 121.1283 },
    imagePool: 'oldStreet',
    features: '愛情車站,鐵道文化,浪漫裝置,手作體驗,下午茶,拍照景點',
    transport: '搭乘台鐵內灣線至合興站即達',
    evaluate: 4.1,
    evaluateNum: 340,
  },
  {
    slug: 'zhenxibao-giant-trees',
    title: '鎮西堡巨木群登山之旅',
    description: '探訪全台最大檜木原始林，穿梭於千年巨木間感受大自然的磅礴。',
    content:
      '<p>鎮西堡位於新竹縣尖石鄉，擁有全台面積最大的檜木原始林。巨木群步道全程約12公里，沿途可見數十棵樹齡超過千年的紅檜與扁柏巨木，最大的巨木胸圍超過20公尺。行走在霧氣繚繞的原始林中，感受千年巨木的莊嚴與大自然的鬼斧神工。</p>',
    price: 3800,
    originPrice: 4800,
    address: '新竹縣尖石鄉秀巒村鎮西堡',
    category: 'package',
    coordinates: { lat: 24.5583, lng: 121.2583 },
    imagePool: 'mountain',
    features: '千年檜木,原始林,登山健行,雲霧繚繞,生態豐富,高山體驗',
    transport: '自竹東經尖石、秀巒至鎮西堡部落，需自行開車約3小時',
    evaluate: 4.7,
    evaluateNum: 190,
  },
  {
    slug: 'wuzhi-mountain',
    title: '五指山健行步道體驗',
    description: '新竹縣著名的宗教聖山，五座山峰形如五指，登頂可俯瞰竹東平原。',
    content:
      '<p>五指山海拔1062公尺，因五座山峰排列如手指而得名，是新竹地區著名的登山勝地。步道沿途設有多座廟宇，其中觀音寺與玉皇宮最為知名。攀登至最高峰「中指峰」，可飽覽竹東平原至海岸線的遼闊景色。步道難度適中，適合一般體能的登山者。</p>',
    price: 200,
    originPrice: 260,
    address: '新竹縣五峰鄉大隘村',
    category: 'tickets',
    coordinates: { lat: 24.6367, lng: 121.0867 },
    imagePool: 'mountain',
    features: '登山步道,宗教文化,山頂展望,廟宇巡禮,中級難度,自然生態',
    transport: '自竹東搭計程車至五指山登山口，車程約30分鐘',
    evaluate: 4.2,
    evaluateNum: 250,
  },
  {
    slug: 'yuanyang-valley-waterfall',
    title: '鴛鴦谷瀑布溯溪體驗',
    description: '夏日消暑首選，在鴛鴦谷瀑布享受清涼溯溪與戲水樂趣。',
    content:
      '<p>鴛鴦谷瀑布位於尖石鄉玉峰溪上游，瀑布高約30公尺，水量豐沛時氣勢磅礴。溯溪體驗由專業教練帶領，沿溪谷攀岩、跳水、滑瀑，刺激又安全。清澈見底的溪水與翠綠的峽谷景觀，讓人彷彿置身世外桃源，是夏季最受歡迎的戶外活動。</p>',
    price: 1200,
    originPrice: 1500,
    address: '新竹縣尖石鄉玉峰村',
    category: 'package',
    coordinates: { lat: 24.6417, lng: 121.2333 },
    imagePool: 'waterfall',
    features: '溯溪體驗,瀑布跳水,清涼消暑,專業教練,峽谷美景,夏季限定',
    transport: '自竹東經尖石至玉峰村，需自行開車約1.5小時',
    evaluate: 4.6,
    evaluateNum: 200,
  },
  {
    slug: 'hakka-cultural-park',
    title: '新竹縣客家文化園區門票',
    description: '深入認識客家歷史與文化，互動展覽與傳統技藝體驗。',
    content:
      '<p>新竹縣客家文化園區是北台灣規模最大的客家文化展示中心，館內以互動多媒體方式呈現客家族群的遷徙史、建築藝術、飲食文化與民俗信仰。定期舉辦客家戲曲表演、藍染體驗、擂茶DIY等活動，讓遊客在玩樂中深度認識客家文化。</p>',
    price: 80,
    originPrice: 100,
    address: '新竹縣竹東鎮中山路2號',
    category: 'tickets',
    coordinates: { lat: 24.7328, lng: 121.0867 },
    imagePool: 'museum',
    features: '客家文化,互動展覽,藍染體驗,擂茶DIY,戲曲表演,歷史導覽',
    transport: '搭乘台鐵內灣線至竹東站，步行約8分鐘',
    evaluate: 4.0,
    evaluateNum: 170,
  },
  {
    slug: 'daba-jianshan-trail',
    title: '大霸尖山步道二日登山團',
    description: '挑戰台灣百岳之一的大霸尖山，欣賞「世紀奇峰」的壯麗岩壁。',
    content:
      '<p>大霸尖山海拔3492公尺，因頂部平坦如桶狀而被譽為「世紀奇峰」，是台灣百岳中最具辨識度的山峰之一。兩天一夜的登山行程從大鹿林道出發，經九九山莊過夜後攻頂。沿途可見壯闊的雪山山脈稜線、高山杜鵑花海，以及豐富的高山動植物生態。</p>',
    price: 5000,
    originPrice: 6000,
    address: '新竹縣尖石鄉大霸尖山登山口',
    category: 'package',
    coordinates: { lat: 24.4611, lng: 121.2297 },
    imagePool: 'mountain',
    features: '百岳登山,世紀奇峰,高山生態,雲海日出,九九山莊,專業嚮導',
    transport: '自竹東經觀霧至大鹿林道登山口，需自行開車約2.5小時',
    evaluate: 4.9,
    evaluateNum: 120,
  },
  {
    slug: 'qingquan-hot-spring',
    title: '清泉溫泉半日遊',
    description: '日治時期即聞名的清泉溫泉，泡湯之餘可造訪三毛故居。',
    content:
      '<p>清泉溫泉位於五峰鄉上坪溪畔，泉質為無色無味的弱鹼性碳酸泉，日治時期即是知名的溫泉療養地。周邊景點包含已故作家三毛曾居住的紅磚小屋、清泉吊橋及張學良故居。泡完溫泉後漫步溪畔步道，感受山林間的靜謐與歷史人文交織的獨特氛圍。</p>',
    price: 800,
    originPrice: 1000,
    address: '新竹縣五峰鄉桃山村清泉256-8號',
    category: 'package',
    coordinates: { lat: 24.5983, lng: 121.1117 },
    imagePool: 'hotSpring',
    features: '溫泉泡湯,三毛故居,張學良故居,溪畔步道,弱鹼性泉,歷史人文',
    transport: '自竹東搭乘新竹客運往清泉方向，於清泉站下車步行約5分鐘',
    evaluate: 4.3,
    evaluateNum: 280,
  },
  {
    slug: 'sheipa-leisure-farm',
    title: '雪霸休閒農場一日遊',
    description: '海拔1923公尺的高山農場，四季花卉與壯闊雲海盡收眼底。',
    content:
      '<p>雪霸休閒農場位於新竹縣五峰鄉，海拔約1923公尺，緊鄰雪霸國家公園。農場內種植各式溫帶花卉與水果，春櫻、夏繡球、秋楓、冬梅四季皆美。清晨可欣賞壯闊的雲海與日出，夜晚在無光害的環境中觀星。一日遊包含農場導覽、DIY體驗及在地風味餐。</p>',
    price: 1500,
    originPrice: 1900,
    address: '新竹縣五峰鄉桃山村民石380號',
    category: 'package',
    coordinates: { lat: 24.5167, lng: 121.1 },
    imagePool: 'nature',
    features: '高山農場,雲海日出,四季花卉,觀星體驗,DIY活動,風味餐',
    transport: '自竹東經五峰至農場，需自行開車約2小時',
    evaluate: 4.6,
    evaluateNum: 310,
  },
  {
    slug: 'qionglin-feifengshan',
    title: '芎林飛鳳山步道健行',
    description: '新竹近郊的熱門健行路線，登頂可遠眺新竹平原與台灣海峽。',
    content:
      '<p>飛鳳山步道位於芎林鄉，海拔約423公尺，是新竹地區最受歡迎的郊山步道之一。主步道全長約2.5公里，沿途林蔭茂密、涼爽宜人。登頂後的觀日亭可遠眺新竹平原、頭前溪及台灣海峽，天氣晴朗時甚至能看到桃園機場的飛機起降。步道設施完善，適合闔家健行。</p>',
    price: 150,
    originPrice: 200,
    address: '新竹縣芎林鄉飛鳳山登山步道入口',
    category: 'tickets',
    coordinates: { lat: 24.775, lng: 121.0833 },
    imagePool: 'mountain',
    features: '郊山步道,觀景平台,林蔭步道,親子健行,日落美景,輕鬆路線',
    transport: '於竹東搭乘新竹客運往芎林方向，於飛鳳山站下車步行約5分鐘',
    evaluate: 4.1,
    evaluateNum: 400,
  },
]
