import type { ProductDefinition } from "../types";

export const hualienProducts: ProductDefinition[] = [
  {
    slug: "taroko-national-park",
    title: "太魯閣國家公園",
    description: "世界級峽谷地質奇觀，大理石絕壁與湛藍溪流交織的壯闘景致。",
    content:
      "<p>太魯閣國家公園是台灣最具國際知名度的自然景觀，立霧溪切割大理石岩層形成深達千公尺的峽谷。園區內步道眾多，從輕鬆的砂卡礑步道到挑戰級的錐麓古道皆有。套票含園區接駁、專業地質導覽及午餐便當，帶您深度領略峽谷之美。</p>",
    price: 1800,
    originPrice: 2200,
    address: "花蓮縣秀林鄉富世村富世291號",
    category: "package",
    coordinates: { lat: 24.1587, lng: 121.495 },
    imagePool: "mountain",
    features: "峽谷奇觀,大理石地質,步道健行,生態導覽,國家公園,午餐包含",
    transport: "於花蓮火車站搭乘太魯閣客運1133A至太魯閣遊客中心，車程約40分鐘",
    evaluate: 4.9,
    evaluateNum: 800,
  },
  {
    slug: "qingshui-cliff",
    title: "清水斷崖",
    description: "蘇花公路上最壯觀的海崖絕景，碧海藍天與千仞峭壁的震撼。",
    content:
      "<p>清水斷崖是台灣十景之一，綿延約21公里的大理石與片麻岩崖壁近乎垂直沒入太平洋，落差超過800公尺。本套票包含SUP立槳或獨木舟海上體驗，從海面仰望斷崖更顯壯觀，含專業教練指導、裝備及防水相機拍照服務。</p>",
    price: 2500,
    originPrice: 3000,
    address: "花蓮縣秀林鄉蘇花公路清水段",
    category: "package",
    coordinates: { lat: 24.2285, lng: 121.6619 },
    imagePool: "beach",
    features: "SUP體驗,海崖絕景,獨木舟,專業教練,防水攝影,太平洋風光",
    transport: "含花蓮市區至崇德海灘接駁服務，於指定地點集合上車",
    evaluate: 4.8,
    evaluateNum: 650,
  },
  {
    slug: "qixingtan",
    title: "七星潭風景區",
    description: "花蓮最美的月牙灣礫石海灘，背倚中央山脈面朝太平洋。",
    content:
      "<p>七星潭是花蓮最具代表性的海灣，弧形的礫石海灘綿延數公里，海水呈現層次分明的漸層藍。沿海自行車道連接四八高地與柴魚博物館，可遠眺清水斷崖。門票含自行車租借與柴魚博物館參觀，是悠閒半日遊的理想選擇。</p>",
    price: 350,
    originPrice: 420,
    address: "花蓮縣新城鄉海岸路",
    category: "tickets",
    coordinates: { lat: 24.0282, lng: 121.631 },
    imagePool: "beach",
    features: "礫石海灘,自行車道,太平洋景觀,柴魚博物館,單車租借",
    transport: "於花蓮火車站搭乘花蓮客運105至七星潭站，車程約20分鐘",
    evaluate: 4.6,
    evaluateNum: 720,
  },
  {
    slug: "ruisui-hot-spring",
    title: "瑞穗溫泉體驗",
    description: "全台唯一的碳酸鹽泉，富含鐵質的黃金湯泉滋養身心。",
    content:
      "<p>瑞穗溫泉是花蓮縱谷的知名溫泉區，泉質為全台稀有的碳酸鹽泉，含豐富鐵質，泉水呈金黃色。本套票包含露天湯池泡湯、溫泉魚足浴體驗及下午茶點心，在群山環繞的自然環境中享受身心靈的放鬆與療癒。</p>",
    price: 1200,
    originPrice: 1500,
    address: "花蓮縣瑞穗鄉溫泉路一段58號",
    category: "package",
    coordinates: { lat: 23.4977, lng: 121.3637 },
    imagePool: "hotSpring",
    features: "碳酸鹽泉,黃金湯泉,露天泡湯,溫泉魚體驗,下午茶,山林環繞",
    transport: "搭乘台鐵至瑞穗站，轉乘花蓮客運或計程車約10分鐘",
    evaluate: 4.5,
    evaluateNum: 430,
  },
  {
    slug: "farglory-ocean-park",
    title: "遠雄海洋公園",
    description: "東台灣唯一的海洋主題樂園，結合海豚表演與刺激遊樂設施。",
    content:
      "<p>遠雄海洋公園依山面海，擁有海豚互動體驗、海獅表演、水族館及多項遊樂設施。園區分為八大主題區，從海洋村到歡樂大街，適合全家大小同樂。套票含全日暢遊通行證與海豚互動區優先入場，是花蓮親子旅遊的首選。</p>",
    price: 1500,
    originPrice: 1800,
    address: "花蓮縣壽豐鄉鹽寮村福德189號",
    category: "package",
    coordinates: { lat: 23.8893, lng: 121.5521 },
    imagePool: "park",
    features: "海洋主題,海豚表演,遊樂設施,水族館,親子同樂,全日暢遊",
    transport: "於花蓮火車站搭乘花蓮客運1140至海洋公園站，車程約30分鐘",
    evaluate: 4.4,
    evaluateNum: 580,
  },
  {
    slug: "keishuin-temple",
    title: "慶修院",
    description: "日治時期保存最完整的日式寺院，三級古蹟充滿東洋禪意。",
    content:
      "<p>慶修院建於1917年，原為日本真言宗高野派的「吉野布教所」，是台灣現存最完整的日式寺院建築。院內保存88尊石佛、不動明王石刻及手水舍，庭園幽靜典雅。門票含導覽解說與抹茶體驗，在百年古蹟中感受靜謐的東洋氛圍。</p>",
    price: 150,
    originPrice: 180,
    address: "花蓮縣吉安鄉吉安村中興路345-1號",
    category: "tickets",
    coordinates: { lat: 23.962, lng: 121.568 },
    imagePool: "temple",
    features: "日式寺院,三級古蹟,石佛雕刻,抹茶體驗,禪意庭園",
    transport: "於花蓮火車站搭乘花蓮客運至吉安站，步行約5分鐘",
    evaluate: 4.3,
    evaluateNum: 380,
  },
  {
    slug: "taroko-gorge-trail",
    title: "太魯閣峽谷步道健行",
    description: "專業嚮導帶領走訪燕子口與九曲洞，深入峽谷最精華路段。",
    content:
      "<p>太魯閣峽谷步道健行行程涵蓋燕子口、九曲洞與長春祠三大經典路段，由認證高山嚮導帶領解說地質成因、動植物生態與原住民文化。全程約4小時，含安全頭盔、保險及礦泉水，適合一般體能的遊客參加。</p>",
    price: 1500,
    originPrice: 1900,
    address: "花蓮縣秀林鄉太魯閣口",
    category: "package",
    coordinates: { lat: 24.1573, lng: 121.5078 },
    imagePool: "mountain",
    features: "峽谷健行,專業嚮導,地質解說,燕子口,九曲洞,安全裝備",
    transport: "含花蓮市區至太魯閣口接駁服務，於指定飯店集合上車",
    evaluate: 4.7,
    evaluateNum: 520,
  },
  {
    slug: "dongdamen-night-market",
    title: "花蓮東大門夜市",
    description: "花蓮最大的觀光夜市，原住民風味美食與在地小吃齊聚。",
    content:
      "<p>東大門夜市位於花蓮市區，分為福町、原住民一條街、各省一條街與自強夜市四大區域。原住民烤肉、石板烤豬肉、官財板等特色美食是必嚐亮點。本套票包含美食護照可兌換8道精選小吃，讓您一次吃遍花蓮好味道。</p>",
    price: 699,
    originPrice: 880,
    address: "花蓮縣花蓮市中山路與重慶路口",
    category: "package",
    coordinates: { lat: 23.9749, lng: 121.6063 },
    imagePool: "nightMarket",
    features: "原住民美食,在地小吃,美食護照,夜市文化,石板烤肉,假日限定",
    transport: "於花蓮火車站步行約15分鐘，或搭乘市區公車至東大門夜市站",
    evaluate: 4.5,
    evaluateNum: 610,
  },
  {
    slug: "liyu-lake",
    title: "鯉魚潭",
    description: "花蓮最大的內陸湖泊，群山倒映湖面如詩如畫。",
    content:
      "<p>鯉魚潭位於壽豐鄉，四面環山，湖水碧綠如翠。遊客可選擇環湖步道健行、踩天鵝船遊湖或在湖畔野餐。每年四至五月的螢火蟲季更是不容錯過的生態盛事。門票含天鵝船租借30分鐘與湖畔咖啡一杯，是悠閒午後的完美去處。</p>",
    price: 300,
    originPrice: 380,
    address: "花蓮縣壽豐鄉池南村環潭北路100號",
    category: "tickets",
    coordinates: { lat: 23.9298, lng: 121.5102 },
    imagePool: "nature",
    features: "湖泊風光,天鵝船,環湖步道,螢火蟲季,湖畔咖啡",
    transport: "於花蓮火車站搭乘花蓮客運1139至鯉魚潭站，車程約25分鐘",
    evaluate: 4.4,
    evaluateNum: 450,
  },
  {
    slug: "shitiping",
    title: "石梯坪",
    description: "壯觀的海蝕階梯地形，太平洋浪花拍打火山岩的自然劇場。",
    content:
      "<p>石梯坪位於豐濱鄉海岸線上，因海蝕作用形成如階梯般的岩石平台，地質景觀極為特殊。園區設有步道沿海岸蜿蜒，可近距離觀察壺穴、海蝕溝等地形。門票含地質解說導覽與潮間帶生態觀察，是認識東海岸地質的最佳教室。</p>",
    price: 200,
    originPrice: 250,
    address: "花蓮縣豐濱鄉石梯坪52號",
    category: "tickets",
    coordinates: { lat: 23.4885, lng: 121.51 },
    imagePool: "beach",
    features: "海蝕地形,潮間帶,地質導覽,太平洋海景,岩石步道",
    transport: "於花蓮火車站搭乘花蓮客運1145至石梯坪站，車程約90分鐘",
    evaluate: 4.3,
    evaluateNum: 280,
  },
  {
    slug: "liushishi-mountain",
    title: "六十石山金針花季",
    description: "每年八至九月金針花盛開，滿山遍野的金黃花海如同仙境。",
    content:
      "<p>六十石山位於富里鄉海拔約800公尺處，是花蓮三大金針花產區之一。花季期間漫山遍野的橙黃金針花搭配藍天白雲，美不勝收。套票含花蓮市區至六十石山來回接駁、專業攝影導覽及金針花風味午餐，讓您盡情沉浸在花海之中。</p>",
    price: 2200,
    originPrice: 2800,
    address: "花蓮縣富里鄉竹田村雲閩路",
    category: "package",
    coordinates: { lat: 23.2183, lng: 121.289 },
    imagePool: "nature",
    features: "金針花海,攝影導覽,季節限定,山景風光,風味午餐,來回接駁",
    transport: "含花蓮市區至六十石山來回接駁車，於花蓮火車站前集合",
    evaluate: 4.7,
    evaluateNum: 350,
  },
  {
    slug: "xiuguluan-rafting",
    title: "秀姑巒溪泛舟",
    description: "東台灣最刺激的泛舟體驗，穿越壯麗的秀姑巒溪峽谷。",
    content:
      "<p>秀姑巒溪泛舟全程約24公里，從瑞穗大橋至長虹橋出海口，途經23處急流激灘，全程約3至4小時。本套票包含專業教練指導、全套安全裝備、保險及終點站至起點站的接駁巴士，是挑戰自我、享受大自然的極致水上冒險。</p>",
    price: 1800,
    originPrice: 2200,
    address: "花蓮縣瑞穗鄉中正北路一段泛舟遊客中心",
    category: "package",
    coordinates: { lat: 23.4962, lng: 121.3768 },
    imagePool: "nature",
    features: "泛舟體驗,急流冒險,專業教練,安全裝備,峽谷風光,接駁服務",
    transport: "搭乘台鐵至瑞穗站，套票含瑞穗站至泛舟中心免費接駁",
    evaluate: 4.6,
    evaluateNum: 490,
  },
  {
    slug: "xincheng-old-street",
    title: "新城老街",
    description: "隱藏版文青小鎮，日式神社改建教堂與懷舊商店街的奇遇。",
    content:
      "<p>新城老街保留了日治時期的街屋風貌，最特別的是新城天主堂由原日本神社改建而成，鳥居與十字架並存的畫面令人驚奇。街上有佳興冰果室的招牌檸檬汁、練習曲書店等文青據點。門票含老街散步地圖與一杯佳興檸檬汁兌換券。</p>",
    price: 180,
    originPrice: 220,
    address: "花蓮縣新城鄉新城村博愛路",
    category: "tickets",
    coordinates: { lat: 24.1271, lng: 121.6477 },
    imagePool: "oldStreet",
    features: "日式神社,文青小鎮,懷舊街巷,檸檬汁名店,教堂建築",
    transport: "搭乘台鐵至新城站，步行約10分鐘至老街入口",
    evaluate: 4.2,
    evaluateNum: 260,
  },
  {
    slug: "emerald-valley",
    title: "翡翠谷",
    description: "秘境級的碧綠深潭，溪水清澈見底如翡翠般璀璨。",
    content:
      "<p>翡翠谷位於秀林鄉木瓜溪上游，須穿越一段隧道後方能抵達。谷內溪水呈現夢幻的翡翠綠色，深潭周圍巨石環繞，是夏日戲水的天堂。套票含專業溯溪嚮導、安全裝備（救生衣、頭盔、溯溪鞋）及接駁服務，安全暢玩秘境。</p>",
    price: 1600,
    originPrice: 2000,
    address: "花蓮縣秀林鄉銅門村",
    category: "package",
    coordinates: { lat: 24.0385, lng: 121.4825 },
    imagePool: "waterfall",
    features: "秘境深潭,溯溪體驗,翡翠綠水,安全裝備,專業嚮導,夏日戲水",
    transport: "含花蓮市區至翡翠谷入口接駁服務，於指定地點集合上車",
    evaluate: 4.7,
    evaluateNum: 370,
  },
  {
    slug: "baiyang-waterfall",
    title: "白楊步道水簾洞",
    description: "太魯閣內最夢幻的步道，穿越隧道後驚見地下水簾瀑布。",
    content:
      "<p>白楊步道全長約2.1公里，途經七座隧道，終點的水簾洞由地下湧泉從隧道頂部傾瀉而下，形成天然水幕，宛如仙境。步道平緩好走，沿途可欣賞立霧溪支流的峽谷風光。門票含頭燈租借與防水袋，確保您安全盡興體驗水簾洞。</p>",
    price: 250,
    originPrice: 300,
    address: "花蓮縣秀林鄉天祥白楊步道入口",
    category: "tickets",
    coordinates: { lat: 24.1822, lng: 121.4876 },
    imagePool: "waterfall",
    features: "水簾洞奇觀,隧道探險,峽谷步道,地下湧泉,頭燈租借",
    transport: "搭乘太魯閣客運至天祥站，步行約15分鐘至步道入口",
    evaluate: 4.6,
    evaluateNum: 540,
  },
  {
    slug: "shakadang-trail",
    title: "砂卡礑步道",
    description: "太魯閣最親民的步道，碧藍溪水與大理石河床如夢似幻。",
    content:
      "<p>砂卡礑步道沿砂卡礑溪而建，全長約4.1公里，步道平緩適合各年齡層。溪水因含礦物質呈現獨特的碧藍色，與白色大理石河床交映成趣。沿途可觀察太魯閣族部落遺址與豐富的蕨類植物。門票含導覽解說及太魯閣族文化體驗。</p>",
    price: 300,
    originPrice: 380,
    address: "花蓮縣秀林鄉砂卡礑隧道旁",
    category: "tickets",
    coordinates: { lat: 24.163, lng: 121.5015 },
    imagePool: "mountain",
    features: "碧藍溪水,大理石河床,親民步道,原住民文化,蕨類生態",
    transport: "搭乘太魯閣客運至砂卡礑站，步道入口即在砂卡礑隧道西口",
    evaluate: 4.5,
    evaluateNum: 580,
  },
  {
    slug: "chinan-forest",
    title: "池南國家森林遊樂區",
    description: "鯉魚潭畔的原始森林園區，林業文化與自然生態的寶庫。",
    content:
      "<p>池南國家森林遊樂區位於鯉魚潭南側，保存完整的低海拔闊葉林與林業歷史設施。園區內有蒸汽集材機、索道等珍貴林業遺跡，以及多條森林浴步道。門票含全區參觀與林業文物導覽，適合想遠離塵囂享受森林芬多精的旅人。</p>",
    price: 100,
    originPrice: 120,
    address: "花蓮縣壽豐鄉池南村林園路65號",
    category: "tickets",
    coordinates: { lat: 23.9168, lng: 121.5077 },
    imagePool: "nature",
    features: "森林浴,林業遺跡,闊葉林,生態步道,芬多精",
    transport: "於花蓮火車站搭乘花蓮客運1139至池南站，車程約30分鐘",
    evaluate: 4.1,
    evaluateNum: 190,
  },
  {
    slug: "hualien-cultural-park",
    title: "花蓮文創園區",
    description: "日治酒廠變身文創基地，在百年建築中遇見花蓮的藝術能量。",
    content:
      "<p>花蓮文創園區前身為日治時期的花蓮酒廠，佔地3.3公頃，保留了26棟歷史建築。如今轉型為東台灣最大的文化創意園區，進駐藝術家工作室、手作工坊、獨立書店與特色餐廳。門票含DIY手作體驗（手工皂或藍染擇一）。</p>",
    price: 350,
    originPrice: 420,
    address: "花蓮縣花蓮市中華路144號",
    category: "tickets",
    coordinates: { lat: 23.9764, lng: 121.6015 },
    imagePool: "city",
    features: "文創園區,日式建築,手作體驗,藝術工坊,獨立書店",
    transport: "於花蓮火車站步行約10分鐘",
    evaluate: 4.3,
    evaluateNum: 340,
  },
  {
    slug: "pine-garden",
    title: "松園別館",
    description: "百年松林環繞的日式軍官宿舍，俯瞰花蓮港與太平洋。",
    content:
      "<p>松園別館建於1943年，為日治時期軍事指揮中心，園區內老松蒼鬱，建築保留完整的日式木構造。站在二樓陽台可遠眺花蓮港與美崙溪出海口，景色開闊。門票含園區導覽與一杯松園特調飲品，在歷史與自然交融中享受午後時光。</p>",
    price: 200,
    originPrice: 250,
    address: "花蓮縣花蓮市松園街65號",
    category: "tickets",
    coordinates: { lat: 23.9842, lng: 121.6139 },
    imagePool: "park",
    features: "日式建築,百年松林,港口景觀,歷史導覽,特調飲品",
    transport: "於花蓮火車站搭乘計程車約5分鐘，或步行約20分鐘",
    evaluate: 4.4,
    evaluateNum: 310,
  },
  {
    slug: "mukumugi",
    title: "慕谷慕魚生態廊道",
    description: "太魯閣族的秘境溪谷，翡翠色溪水與原始森林的生態天堂。",
    content:
      "<p>慕谷慕魚位於木瓜溪上游，是太魯閣族世居之地。溪谷中清澈見底的翡翠色溪水、巨石與瀑布構成絕美景觀。本套票含申請入山許可、專業嚮導帶領溯溪、原住民文化解說及部落風味午餐，深度體驗花蓮最美的秘境。</p>",
    price: 2800,
    originPrice: 3500,
    address: "花蓮縣秀林鄉銅門村榕樹部落",
    category: "package",
    coordinates: { lat: 24.042, lng: 121.453 },
    imagePool: "waterfall",
    features: "秘境溯溪,原住民文化,翡翠溪谷,部落風味餐,入山許可,專業嚮導",
    transport: "含花蓮市區至銅門部落接駁服務，於花蓮火車站前集合",
    evaluate: 4.8,
    evaluateNum: 290,
  },
  {
    slug: "lichuan-fishery",
    title: "立川漁場",
    description: "花蓮黃金蜆的故鄉，體驗下水摸蜆仔的純樸農村樂趣。",
    content:
      "<p>立川漁場以養殖黃金蜆聞名，是花蓮壽豐鄉的觀光漁場。遊客可捲起褲管下水體驗「摸蜆仔兼洗褲」的古早味農村生活，摸到的蜆仔還能帶回家。套票含摸蜆體驗、蜆精品嚐及蜆料理午餐，是寓教於樂的親子活動。</p>",
    price: 680,
    originPrice: 850,
    address: "花蓮縣壽豐鄉魚池45號",
    category: "package",
    coordinates: { lat: 23.87, lng: 121.5153 },
    imagePool: "nature",
    features: "摸蜆體驗,農村生活,黃金蜆料理,親子活動,蜆精品嚐,寓教於樂",
    transport: "搭乘台鐵至壽豐站，轉乘計程車約5分鐘",
    evaluate: 4.3,
    evaluateNum: 380,
  },
  {
    slug: "lintianshan",
    title: "林田山林業文化園區",
    description: "台灣保存最完整的伐木聚落，彷彿走入時光隧道的山林小鎮。",
    content:
      "<p>林田山曾是台灣四大林場之一，如今保留了日式木造宿舍、中山堂、森林鐵道與伐木器具。漫步於檜木香氣瀰漫的聚落中，感受昔日林業榮景。門票含園區導覽與林田山咖啡一杯，在百年檜木建築中品味山林歲月。</p>",
    price: 150,
    originPrice: 180,
    address: "花蓮縣鳳林鎮森榮里林森路99巷99號",
    category: "tickets",
    coordinates: { lat: 23.7464, lng: 121.4001 },
    imagePool: "nature",
    features: "林業文化,日式宿舍,檜木建築,森林鐵道,山林咖啡",
    transport: "搭乘台鐵至萬榮站，步行約15分鐘；或搭花蓮客運至林田山站",
    evaluate: 4.5,
    evaluateNum: 320,
  },
  {
    slug: "fengbin-sky-trail",
    title: "豐濱天空步道",
    description: "花蓮海岸線上的透明步道，腳下是驚濤拍岸的壯闊海景。",
    content:
      "<p>豐濱天空步道（親不知子斷崖）建於垂直的海崖峭壁上，部分路段採用透明強化玻璃，腳下便是湛藍的太平洋與白浪滔天的礁岩。步道全長約150公尺，驚險刺激度滿分。門票含步道通行與附近新社梯田觀景台參觀。</p>",
    price: 120,
    originPrice: 150,
    address: "花蓮縣豐濱鄉花東海岸公路旁",
    category: "tickets",
    coordinates: { lat: 23.6435, lng: 121.5297 },
    imagePool: "beach",
    features: "天空步道,透明玻璃,海崖絕景,親不知子斷崖,梯田景觀",
    transport: "於花蓮火車站搭乘花蓮客運1145至豐濱站，車程約70分鐘",
    evaluate: 4.2,
    evaluateNum: 410,
  },
  {
    slug: "hualien-sugar-factory",
    title: "花蓮觀光糖廠",
    description: "日治時期糖業遺產，品嚐全台最好吃的手工冰淇淋。",
    content:
      "<p>花蓮觀光糖廠（光復糖廠）建於1920年代，是花蓮重要的產業文化資產。廠區保留了日式木屋宿舍群，現改建為特色民宿與文創空間。糖廠冰品以香濃綿密聞名全台，每年吸引數十萬遊客。門票含園區導覽與兩球手工冰淇淋兌換。</p>",
    price: 180,
    originPrice: 220,
    address: "花蓮縣光復鄉糖廠街19號",
    category: "tickets",
    coordinates: { lat: 23.6694, lng: 121.4218 },
    imagePool: "oldStreet",
    features: "糖業文化,手工冰淇淋,日式宿舍,產業遺產,文創空間",
    transport: "搭乘台鐵至光復站，步行約10分鐘",
    evaluate: 4.4,
    evaluateNum: 520,
  },
  {
    slug: "jian-cycling-tour",
    title: "吉安慶修院單車文化巡禮",
    description: "騎單車穿梭吉安鄉間，串聯慶修院、菸樓與日式移民村遺跡。",
    content:
      "<p>吉安鄉是日治時期日本移民村「吉野村」所在地，至今保留慶修院、菸樓、圳道等歷史遺跡。本套票以單車代步，由在地文史導覽員帶領騎行約12公里，串聯慶修院、吉安菸樓、楓林步道與在地農場。含單車租借、導覽及農場鮮採水果體驗。</p>",
    price: 980,
    originPrice: 1200,
    address: "花蓮縣吉安鄉中興路345號",
    category: "package",
    coordinates: { lat: 23.9615, lng: 121.569 },
    imagePool: "oldStreet",
    features: "單車巡禮,日式移民村,文史導覽,菸樓遺跡,農場體驗,鄉間風光",
    transport: "於花蓮火車站搭乘花蓮客運至吉安站，或套票含花蓮市區集合接駁",
    evaluate: 4.5,
    evaluateNum: 220,
  },
];
