import type { ProductDefinition } from '../types'

export const kaohsiungProducts: ProductDefinition[] = [
  {
    slug: 'pier2-art-center',
    title: '駁二藝術特區',
    description: '高雄最具代表性的文創藝術園區，結合倉庫群與當代藝術展覽。',
    content:
      '<p>駁二藝術特區位於高雄港旁，由舊倉庫群改建而成，匯集藝術展覽、文創商店、街頭裝置藝術與特色餐飲。園區內常態性舉辦國際級當代藝術展，並設有鐵道草地供遊客休憩，是感受高雄港都文化魅力的絕佳去處。</p>',
    price: 250,
    originPrice: 300,
    address: '高雄市鹽埕區大勇路1號',
    category: 'tickets',
    coordinates: { lat: 22.6196, lng: 120.2815 },
    imagePool: 'city',
    features: '文創藝術,展覽空間,裝置藝術,港口風情,攝影熱點',
    transport: '搭乘高雄捷運橘線至鹽埕埔站1號出口，步行約5分鐘',
    evaluate: 4.6,
    evaluateNum: 720,
  },
  {
    slug: 'lotus-pond',
    title: '蓮池潭風景區',
    description: '左營著名景點，龍虎塔與春秋閣矗立湖畔，是高雄經典地標。',
    content:
      '<p>蓮池潭佔地約75公頃，湖畔環繞多座寺廟與古蹟，其中龍虎塔、春秋閣最為知名。遊客可入龍口出虎口祈福消災，沿湖步道散步欣賞廟宇倒影，傍晚時分的夕照更是絕美。周邊還有孔廟與舊城門遺址可一併參觀。</p>',
    price: 150,
    originPrice: 180,
    address: '高雄市左營區蓮潭路36號',
    category: 'tickets',
    coordinates: { lat: 22.6813, lng: 120.2942 },
    imagePool: 'temple',
    features: '龍虎塔,春秋閣,湖畔散步,古蹟巡禮,夕陽美景',
    transport: '搭乘高雄捷運紅線至左營站2號出口，轉乘公車紅51至蓮池潭站',
    evaluate: 4.4,
    evaluateNum: 580,
  },
  {
    slug: 'cijin-fort',
    title: '旗津旗後砲台',
    description: '清代軍事古蹟，居高臨下俯瞰旗津海峽與高雄港全景。',
    content:
      '<p>旗後砲台建於清光緒年間，為二級古蹟，位於旗後山頂。砲台保留完整的營門、兵房與砲座遺跡，站在砲台上可飽覽高雄港進出船隻與旗津海岸線。結合旗後燈塔一同遊覽，是認識高雄海防歷史的最佳路線。</p>',
    price: 100,
    originPrice: 120,
    address: '高雄市旗津區旗後山頂',
    category: 'tickets',
    coordinates: { lat: 22.6118, lng: 120.2654 },
    imagePool: 'mountain',
    features: '歷史古蹟,海港全景,旗後燈塔,砲台遺址,攝影聖地',
    transport: '搭乘捷運橘線至西子灣站，步行至鼓山渡輪站搭船至旗津，再步行約15分鐘上山',
    evaluate: 4.3,
    evaluateNum: 420,
  },
  {
    slug: 'liuhe-night-market',
    title: '六合夜市美食巡禮',
    description: '高雄最知名的觀光夜市，匯集在地小吃與國際美食體驗。',
    content:
      '<p>六合夜市是高雄歷史最悠久的夜市之一，全長約380公尺，聚集超過百攤美食。從海產粥、木瓜牛奶到烤肉之家，每一攤都有獨特風味。本套票包含專業導覽員帶路品嚐精選6道美食，深入了解每道料理的故事與文化背景。</p>',
    price: 899,
    originPrice: 1100,
    address: '高雄市新興區六合二路',
    category: 'package',
    coordinates: { lat: 22.6317, lng: 120.2993 },
    imagePool: 'nightMarket',
    features: '美食導覽,在地小吃,海鮮料理,木瓜牛奶,文化體驗,夜間活動',
    transport: '搭乘高雄捷運橘線至美麗島站11號出口，步行約2分鐘',
    evaluate: 4.5,
    evaluateNum: 650,
  },
  {
    slug: 'fo-guang-shan',
    title: '佛光山佛陀紀念館',
    description: '世界級佛教藝術殿堂，壯觀的建築群與豐富的文化展覽。',
    content:
      '<p>佛光山佛陀紀念館由星雲大師創建，佔地百餘公頃，主體建築大佛與八塔氣勢磅礡。館內收藏佛教文物、常態展覽及多媒體互動體驗，戶外園區綠意盎然。本套票含專業導覽與素食午餐，適合全家大小深度體驗佛教藝術之美。</p>',
    price: 1200,
    originPrice: 1500,
    address: '高雄市大樹區統嶺里統嶺路1號',
    category: 'package',
    coordinates: { lat: 22.7521, lng: 120.4435 },
    imagePool: 'temple',
    features: '佛教藝術,文化導覽,建築之美,素食體驗,冥想空間,親子友善',
    transport: '搭乘高鐵至左營站，轉乘義大客運至佛陀紀念館站，車程約40分鐘',
    evaluate: 4.8,
    evaluateNum: 780,
  },
  {
    slug: 'shoushan-zoo',
    title: '壽山動物園',
    description: '全新改造的山林動物園，結合生態教育與親子遊憩空間。',
    content:
      '<p>壽山動物園經大規模翻新後重新開園，以「新動物園運動」理念打造友善動物的開放式展區。園區依山而建，擁有空中廊道可近距離觀察動物，並設有兒童遊戲區與生態解說站。門票含空中廊道體驗，是親子出遊的熱門選擇。</p>',
    price: 350,
    originPrice: 420,
    address: '高雄市鼓山區萬壽路350號',
    category: 'tickets',
    coordinates: { lat: 22.6349, lng: 120.2726 },
    imagePool: 'nature',
    features: '親子遊樂,空中廊道,生態教育,動物觀察,山林步道',
    transport: '搭乘捷運橘線至西子灣站，轉乘56號公車至壽山動物園站',
    evaluate: 4.5,
    evaluateNum: 530,
  },
  {
    slug: 'dome-of-light',
    title: '美麗島站光之穹頂',
    description: '全球最美地鐵站之一，巨幅玻璃藝術穹頂令人屏息。',
    content:
      '<p>美麗島站的光之穹頂由義大利藝術家水仙大師耗時四年創作，直徑30公尺的玻璃鑲嵌藝術品是全球最大的單一玻璃藝術作品。本導覽套票包含專業藝術解說員帶領深度賞析穹頂四大主題：水、土、光、火，並延伸至周邊藝術裝置。</p>',
    price: 600,
    originPrice: 750,
    address: '高雄市新興區中山一路115號B1',
    category: 'package',
    coordinates: { lat: 22.6316, lng: 120.3017 },
    imagePool: 'city',
    features: '公共藝術,玻璃藝術,捷運站導覽,攝影景點,文化體驗,藝術解說',
    transport: '搭乘高雄捷運紅線或橘線至美麗島站，穹頂位於地下一樓穿堂層',
    evaluate: 4.7,
    evaluateNum: 690,
  },
  {
    slug: 'love-river-cruise',
    title: '愛河遊船體驗',
    description: '搭乘遊船悠遊愛河，欣賞兩岸燈光夜景與城市天際線。',
    content:
      '<p>愛河貫穿高雄市中心，夜晚兩岸霓虹燈飾與咖啡座構成浪漫的港都風情。遊船從國賓站出發，沿途經過高雄流行音樂中心、愛河之心等地標，全程約25分鐘。套票包含船票及一杯特調飲品，適合情侶與家庭同享河畔夜色。</p>',
    price: 500,
    originPrice: 600,
    address: '高雄市前金區河東路189號',
    category: 'package',
    coordinates: { lat: 22.6267, lng: 120.2934 },
    imagePool: 'city',
    features: '河畔夜景,遊船體驗,浪漫約會,城市天際線,飲品附贈,攝影熱點',
    transport: '搭乘捷運橘線至鹽埕埔站4號出口，步行約3分鐘至國賓碼頭',
    evaluate: 4.4,
    evaluateNum: 480,
  },
  {
    slug: 'cijin-beach',
    title: '旗津海水浴場',
    description: '高雄最受歡迎的海灘，黑沙海岸搭配完善的戲水設施。',
    content:
      '<p>旗津海水浴場是高雄市民夏日消暑的首選，綿延數百公尺的黑沙灘面向台灣海峽，海水清澈適合戲水。浴場設有更衣室、沖洗設施及救生員駐守。本套票包含沙灘躺椅租借、陽傘及一份旗津海鮮小點心，讓您盡情享受海灘時光。</p>',
    price: 450,
    originPrice: 550,
    address: '高雄市旗津區廟前路1號',
    category: 'package',
    coordinates: { lat: 22.6078, lng: 120.2637 },
    imagePool: 'beach',
    features: '海灘戲水,黑沙海岸,躺椅租借,海鮮點心,夕陽觀賞,親子友善',
    transport: '搭乘捷運橘線至西子灣站，步行至鼓山渡輪站搭船至旗津，步行約5分鐘',
    evaluate: 4.2,
    evaluateNum: 390,
  },
  {
    slug: 'zuoying-village',
    title: '左營眷村文化導覽',
    description: '深入探訪左營眷村聚落，品味戰後移民的生活記憶與美食。',
    content:
      '<p>左營眷村是台灣規模最大的眷村群之一，保留了完整的低矮紅磚房與巷弄文化。本套票由在地眷村二代帶路，走訪明德新村、建業新村等聚落，聽老故事、嚐眷村味，包含導覽解說及經典眷村菜午餐，深刻感受時代記憶。</p>',
    price: 1500,
    originPrice: 1800,
    address: '高雄市左營區明德新村1號',
    category: 'package',
    coordinates: { lat: 22.6756, lng: 120.2938 },
    imagePool: 'oldStreet',
    features: '眷村文化,歷史導覽,眷村美食,在地故事,文化體驗,建築巡禮',
    transport: '搭乘捷運紅線至左營站1號出口，步行約10分鐘至明德新村',
    evaluate: 4.6,
    evaluateNum: 310,
  },
  {
    slug: 'kaohsiung-museum-of-fine-arts',
    title: '高雄市立美術館',
    description: '南台灣首座現代美術館，典藏豐富的台灣當代藝術作品。',
    content:
      '<p>高雄市立美術館座落於內惟埤文化園區，以推廣台灣現當代藝術為主軸，定期舉辦國際級特展。館內建築本身即為藝術品，周圍環繞生態湖與雕塑公園。門票含當期特展與常設展參觀權，是藝術愛好者不可錯過的殿堂。</p>',
    price: 200,
    originPrice: 250,
    address: '高雄市鼓山區美術館路80號',
    category: 'tickets',
    coordinates: { lat: 22.6498, lng: 120.2862 },
    imagePool: 'museum',
    features: '當代藝術,特展體驗,雕塑公園,生態湖畔,藝文空間',
    transport: '搭乘捷運橘線至鹽埕埔站，轉乘紅32公車至美術館站',
    evaluate: 4.5,
    evaluateNum: 420,
  },
  {
    slug: 'chengcing-lake',
    title: '澄清湖風景區',
    description: '高雄最大的人工湖泊，九曲橋與中興塔交織出優雅的湖光山色。',
    content:
      '<p>澄清湖位於鳥松區，是高雄市的水源地，也是著名的風景區。園區內有九曲橋、中興塔、富國島等景點，湖光山色幽靜秀麗。沿湖步道全長約4公里，適合慢跑與騎自行車。門票含全區參觀，是市民假日休憩的好去處。</p>',
    price: 100,
    originPrice: 120,
    address: '高雄市鳥松區大埤路32號',
    category: 'tickets',
    coordinates: { lat: 22.6575, lng: 120.3642 },
    imagePool: 'park',
    features: '湖畔風光,九曲橋,自行車道,慢跑步道,自然生態',
    transport: '搭乘高雄客運8008至澄清湖站，或捷運紅線至鳳山西站轉乘公車',
    evaluate: 4.1,
    evaluateNum: 350,
  },
  {
    slug: 'british-consulate',
    title: '打狗英國領事館',
    description: '百年歷史的英式建築，居高臨下飽覽西子灣夕照與高雄港。',
    content:
      '<p>打狗英國領事館建於1879年，是台灣現存最完整的西洋近代建築之一，已列為國定古蹟。上山官邸與山下辦公室以古道相連，展示清末至日治時期的歷史文物。黃昏時分在山上官邸露台品茶賞日落，是高雄最浪漫的體驗之一。</p>',
    price: 120,
    originPrice: 150,
    address: '高雄市鼓山區蓮海路20號',
    category: 'tickets',
    coordinates: { lat: 22.6243, lng: 120.2665 },
    imagePool: 'museum',
    features: '英式古蹟,西子灣夕照,歷史展覽,下午茶,港口景觀',
    transport: '搭乘捷運橘線至西子灣站2號出口，步行約10分鐘',
    evaluate: 4.5,
    evaluateNum: 620,
  },
  {
    slug: 'ruifeng-night-market',
    title: '瑞豐夜市美食體驗',
    description: '在地人最愛的超大型夜市，上千攤位匯聚高雄平民美味。',
    content:
      '<p>瑞豐夜市位於左營區，是高雄最大的在地型夜市，每逢營業日聚集超過千個攤位。從萬國牛排、蒙古烤肉到日式章魚燒，選擇琳瑯滿目。本套票包含美食導覽及精選5道人氣小吃品嚐，帶您像在地人一樣逛夜市。</p>',
    price: 799,
    originPrice: 999,
    address: '高雄市左營區裕誠路與南屏路口',
    category: 'package',
    coordinates: { lat: 22.6669, lng: 120.3061 },
    imagePool: 'nightMarket',
    features: '在地夜市,平民美食,美食導覽,小吃品嚐,遊戲攤位,熱鬧氛圍',
    transport: '搭乘捷運紅線至巨蛋站1號出口，步行約3分鐘',
    evaluate: 4.3,
    evaluateNum: 550,
  },
  {
    slug: 'e-da-world',
    title: '義大世界主題樂園',
    description: '南台灣最大的主題樂園，結合購物、遊樂設施與飯店度假。',
    content:
      '<p>義大世界位於高雄大樹區，擁有47項遊樂設施，從刺激的雲霄飛車到親子旋轉木馬一應俱全。園區分為衛城、聖托里尼與特洛伊三大主題區，彷彿置身希臘。套票含全日暢遊通行證與義大購物中心折價券，適合全家同樂。</p>',
    price: 1800,
    originPrice: 2200,
    address: '高雄市大樹區學城路一段12號',
    category: 'package',
    coordinates: { lat: 22.7317, lng: 120.4204 },
    imagePool: 'park',
    features: '主題樂園,遊樂設施,購物中心,親子同樂,希臘風情,全日通行',
    transport: '搭乘高鐵至左營站，轉乘義大客運直達義大世界，車程約30分鐘',
    evaluate: 4.4,
    evaluateNum: 710,
  },
  {
    slug: 'weiwuying',
    title: '衛武營國家藝術文化中心',
    description: '全球最大單一屋頂綜合劇院，建築本身即為藝術傑作。',
    content:
      '<p>衛武營由普立茲克建築獎得主法乃迪克設計，流線型的白色屋頂如同巨型貝殼。中心內含歌劇院、音樂廳、戲劇院與表演廳四座專業劇場。本套票含建築導覽與當月演出優先購票權，帶您深入認識這座世界級藝文殿堂。</p>',
    price: 800,
    originPrice: 1000,
    address: '高雄市鳳山區三多一路1號',
    category: 'package',
    coordinates: { lat: 22.6228, lng: 120.3465 },
    imagePool: 'city',
    features: '建築導覽,劇場體驗,國際級表演,公共藝術,文化殿堂,設計美學',
    transport: '搭乘捷運橘線至衛武營站6號出口，步行約1分鐘',
    evaluate: 4.8,
    evaluateNum: 560,
  },
  {
    slug: 'harbor-cruise',
    title: '高雄港遊港體驗',
    description: '搭乘遊艇巡遊高雄港，近距離觀賞貨櫃碼頭與港區建設。',
    content:
      '<p>高雄港是台灣最大的國際商港，遊港行程從光榮碼頭出發，途經高雄流行音樂中心、新光碼頭、貨櫃中心等港區設施，全程約60分鐘。船上提供專業港口導覽解說，讓您了解高雄從漁港蛻變為國際大港的發展歷程。</p>',
    price: 650,
    originPrice: 800,
    address: '高雄市苓雅區海邊路2號光榮碼頭',
    category: 'package',
    coordinates: { lat: 22.6189, lng: 120.2878 },
    imagePool: 'city',
    features: '遊港體驗,港口導覽,海上風光,貨櫃碼頭,城市地標,船上解說',
    transport: '搭乘輕軌至光榮碼頭站，步行約2分鐘',
    evaluate: 4.3,
    evaluateNum: 380,
  },
  {
    slug: 'fengshan-city-god',
    title: '鳳山城隍廟',
    description: '鳳山歷史最悠久的廟宇之一，感受傳統民間信仰文化。',
    content:
      '<p>鳳山城隍廟始建於清乾隆年間，是鳳山地區重要的信仰中心。廟內保存精美的交趾陶、石雕與木雕藝術，每逢農曆七月的城隍出巡更是地方盛事。門票含導覽解說與祈福體驗，帶您深入了解台灣民間信仰與廟宇建築之美。</p>',
    price: 150,
    originPrice: 180,
    address: '高雄市鳳山區鳳明街66號',
    category: 'tickets',
    coordinates: { lat: 22.6268, lng: 120.3567 },
    imagePool: 'temple',
    features: '民間信仰,廟宇建築,交趾陶藝術,祈福體驗,歷史文化',
    transport: '搭乘捷運橘線至鳳山站2號出口，步行約8分鐘',
    evaluate: 4.1,
    evaluateNum: 210,
  },
  {
    slug: 'yanchengpu-old-street',
    title: '鹽埕埔老街散策',
    description: '高雄最早的商業中心，懷舊街巷中品味老港都風華。',
    content:
      '<p>鹽埕埔曾是高雄最繁華的商業區，如今巷弄間仍保留日治時期的洋樓與老店鋪。本套票由在地文史工作者帶領，走訪堀江商場、大溝頂、新樂街等歷史街區，品嚐老字號美食如阿婆冰、大ㄎ咖肉粽，重新發現老高雄的魅力。</p>',
    price: 980,
    originPrice: 1200,
    address: '高雄市鹽埕區新樂街',
    category: 'package',
    coordinates: { lat: 22.6232, lng: 120.2852 },
    imagePool: 'oldStreet',
    features: '懷舊老街,文史導覽,在地美食,日式建築,商場文化,港都記憶',
    transport: '搭乘捷運橘線至鹽埕埔站1號出口，步行約1分鐘',
    evaluate: 4.4,
    evaluateNum: 280,
  },
  {
    slug: 'moon-world',
    title: '月世界地景公園',
    description: '獨特的惡地地形景觀，荒涼月球表面般的奇幻風景。',
    content:
      '<p>月世界位於田寮區，因雨水與河水沖蝕泥岩而形成獨特的禿山惡地地形，景觀如同月球表面般荒涼壯觀。園區設有環湖步道、天空步道與觀景台，夕陽時分的光影變化尤為迷人。門票含全區步道通行及地質解說導覽。</p>',
    price: 200,
    originPrice: 250,
    address: '高雄市田寮區崇德里月球路36號',
    category: 'tickets',
    coordinates: { lat: 22.8724, lng: 120.3868 },
    imagePool: 'mountain',
    features: '惡地地形,地質奇觀,天空步道,夕陽觀賞,生態導覽',
    transport: '自高雄市區開車走國道3號田寮交流道下，約50分鐘車程；或搭客運至田寮站轉計程車',
    evaluate: 4.2,
    evaluateNum: 340,
  },
  {
    slug: 'dadong-arts-center',
    title: '大東文化藝術中心',
    description: '鳳山區地標性藝文空間，獨特的熱氣球造型屋頂引人注目。',
    content:
      '<p>大東文化藝術中心以11顆半透明的熱氣球造型薄膜屋頂為特色，白天可透入自然光，夜間則化身夢幻燈飾。中心設有演藝廳、展覽館與圖書館，定期舉辦藝文展演。套票含建築導覽與當期展覽門票，是認識高雄當代建築的好去處。</p>',
    price: 350,
    originPrice: 420,
    address: '高雄市鳳山區光遠路161號',
    category: 'package',
    coordinates: { lat: 22.628, lng: 120.3603 },
    imagePool: 'city',
    features: '當代建築,藝文展演,熱氣球屋頂,夜間燈飾,圖書館,文化空間',
    transport: '搭乘捷運橘線至大東站1號出口，步行約1分鐘',
    evaluate: 4.3,
    evaluateNum: 290,
  },
  {
    slug: 'gangshan-eye',
    title: '岡山之眼天空廊道',
    description: '小崗山上的天空步道，360度俯瞰高雄平原與海岸線。',
    content:
      '<p>岡山之眼是一座以小提琴意象設計的天空廊道，位於小崗山頂，全長88公尺，最高處離地約40公尺。站在透明玻璃步道上可360度環視高雄平原、阿公店水庫與台灣海峽。門票含接駁車與天空廊道通行，適合喜歡刺激體驗的遊客。</p>',
    price: 300,
    originPrice: 380,
    address: '高雄市岡山區大莊路80巷',
    category: 'tickets',
    coordinates: { lat: 22.7906, lng: 120.3134 },
    imagePool: 'mountain',
    features: '天空步道,玻璃廊道,全景視野,小提琴造型,接駁車服務',
    transport: '搭乘高雄客運至岡山站，轉乘接駁車至岡山之眼園區',
    evaluate: 4.1,
    evaluateNum: 410,
  },
  {
    slug: 'maolin-scenic-area',
    title: '茂林國家風景區',
    description: '紫斑蝶越冬棲地，壯闊的峽谷地形與原住民文化交織。',
    content:
      '<p>茂林國家風景區橫跨桃源、六龜、茂林三區，擁有多納神祕谷、情人谷瀑布與龍頭山等壯麗景觀。每年冬季數百萬紫斑蝶在此棲息，形成蝶瀑奇觀。套票含生態導覽、原住民文化體驗與風味午餐，適合深度自然之旅。</p>',
    price: 2200,
    originPrice: 2800,
    address: '高雄市茂林區茂林里1-6號',
    category: 'package',
    coordinates: { lat: 22.8861, lng: 120.6633 },
    imagePool: 'nature',
    features: '紫斑蝶生態,峽谷地形,原住民文化,風味餐,瀑布景觀,自然導覽',
    transport: '自高雄市區開車走台27線至茂林區，約90分鐘；或搭高雄客運至茂林站',
    evaluate: 4.6,
    evaluateNum: 250,
  },
  {
    slug: 'tianliao-moon-world',
    title: '田寮月世界深度導覽',
    description: '地質學家帶路，深入解讀百萬年泥岩地形的形成奧秘。',
    content:
      '<p>田寮月世界是台灣最大的惡地地形區，本套票特別邀請地質專家帶領深度導覽，從泥火山、惡地溝谷到化石層逐一解說。行程包含日落觀賞、泥岩地質標本體驗及在地農特產品嚐，是一趟結合知識與美景的難忘之旅。</p>',
    price: 1600,
    originPrice: 2000,
    address: '高雄市田寮區崇德里月球路36號',
    category: 'package',
    coordinates: { lat: 22.873, lng: 120.3875 },
    imagePool: 'mountain',
    features: '地質導覽,泥火山,惡地奇觀,日落觀賞,專家解說,農特產品嚐',
    transport: '含高雄市區至田寮接駁服務，於指定地點集合上車',
    evaluate: 4.5,
    evaluateNum: 180,
  },
  {
    slug: 'cishan-old-street',
    title: '旗山老街',
    description: '巴洛克式洋樓老街，品嚐香蕉名產與古早味美食。',
    content:
      '<p>旗山老街保留了日治時期的巴洛克式建築立面與石拱迴廊，是高雄最美的歷史老街之一。街上以香蕉為主題的伴手禮琳瑯滿目，還有傳統的枝仔冰城、旗山肉圓等古早味小吃。門票含老街導覽解說及一份香蕉特色甜品兌換券。</p>',
    price: 350,
    originPrice: 420,
    address: '高雄市旗山區中山路',
    category: 'tickets',
    coordinates: { lat: 22.8885, lng: 120.4831 },
    imagePool: 'oldStreet',
    features: '巴洛克建築,香蕉名產,古早味美食,歷史老街,石拱迴廊',
    transport: '自高雄市區搭乘旗美國道快捷至旗山轉運站，步行約5分鐘',
    evaluate: 4.3,
    evaluateNum: 370,
  },
  {
    slug: 'neimen-zizhu-temple',
    title: '內門紫竹寺',
    description: '內門地區信仰中心，每年宋江陣文化祭熱鬧非凡。',
    content:
      '<p>內門紫竹寺主祀觀音佛祖，是高雄內門區最重要的廟宇。每年農曆二月的宋江陣文化祭吸引數十支陣頭競演，是全台最大的民俗藝陣盛會。門票含廟宇導覽與宋江陣文化展示，讓您深入了解台灣獨特的陣頭文化。</p>',
    price: 180,
    originPrice: 220,
    address: '高雄市內門區內門里內埔45號',
    category: 'tickets',
    coordinates: { lat: 22.9425, lng: 120.4622 },
    imagePool: 'temple',
    features: '宋江陣文化,民俗藝陣,廟宇建築,觀音信仰,文化祭典',
    transport: '自高雄市區搭乘高雄客運至內門站，車程約70分鐘',
    evaluate: 4.0,
    evaluateNum: 150,
  },
  {
    slug: 'xingjhongjhiang-shopping',
    title: '新堀江商圈',
    description: '高雄年輕人的潮流聖地，流行服飾與街頭美食的集散中心。',
    content:
      '<p>新堀江商圈位於中山路與文橫路一帶，是高雄年輕族群最愛的購物天堂。巷弄中密佈潮流服飾店、個性配件鋪與特色餐飲，每到假日人潮洶湧。本套票包含商圈美食護照，可兌換5間精選店家的人氣小吃，逛街吃美食一次滿足。</p>',
    price: 599,
    originPrice: 750,
    address: '高雄市新興區中山一路與文橫路口',
    category: 'package',
    coordinates: { lat: 22.6304, lng: 120.3026 },
    imagePool: 'city',
    features: '潮流購物,街頭美食,年輕文化,美食護照,個性小店,假日市集',
    transport: '搭乘捷運橘線至中央公園站2號出口，步行約3分鐘',
    evaluate: 4.1,
    evaluateNum: 460,
  },
  {
    slug: 'agongdian-reservoir',
    title: '崗山頭水庫',
    description: '阿公店水庫環湖自行車道，山水環繞的悠閒騎行體驗。',
    content:
      '<p>阿公店水庫（崗山頭水庫）是台灣歷史最悠久的水庫之一，環湖自行車道全長約10公里，沿途可欣賞壩頂風光、小崗山全景與湖面倒影。套票包含自行車租借、安全帽及沿途景點解說手冊，是親子休閒運動的絕佳選擇。</p>',
    price: 500,
    originPrice: 600,
    address: '高雄市燕巢區西燕村工程路',
    category: 'package',
    coordinates: { lat: 22.7812, lng: 120.3495 },
    imagePool: 'nature',
    features: '自行車道,環湖騎行,水庫風光,親子運動,山水景觀,單車租借',
    transport: '自高雄市區開車走國道1號岡山交流道下，約30分鐘；或搭客運至岡山站轉計程車',
    evaluate: 4.2,
    evaluateNum: 230,
  },
  {
    slug: 'kaohsiung-music-center',
    title: '高雄流行音樂中心',
    description: '亞洲最大流行音樂場館，海浪造型建築群矗立港灣水岸。',
    content:
      '<p>高雄流行音樂中心由西班牙建築團隊設計，六棟建築以海浪、鯨魚等海洋意象呈現，坐落於高雄港邊。場館內含萬人級戶外演唱會場地、Live House與音樂展覽空間。套票含建築導覽、音樂常設展參觀及海景咖啡廳折抵券。</p>',
    price: 700,
    originPrice: 880,
    address: '高雄市鹽埕區真愛路1號',
    category: 'package',
    coordinates: { lat: 22.6153, lng: 120.2853 },
    imagePool: 'city',
    features: '音樂場館,海洋建築,港灣水岸,展覽空間,建築導覽,海景咖啡',
    transport: '搭乘輕軌至真愛碼頭站，步行約3分鐘',
    evaluate: 4.6,
    evaluateNum: 490,
  },
  {
    slug: 'kw2-warehouse',
    title: '棧貳庫KW2',
    description: '百年港口倉庫活化再生，融合文創市集與港灣美食。',
    content:
      '<p>棧貳庫KW2前身為1914年建造的日治時期磚造倉庫，活化後成為結合文創品牌、特色餐飲與藝文展演的複合空間。倉庫內保留原始磚牆與鋼構，搭配現代設計風格。門票含園區導覽及一杯精品咖啡，漫步港邊感受新舊交融的高雄。</p>',
    price: 280,
    originPrice: 350,
    address: '高雄市鼓山區蓬萊路17號',
    category: 'tickets',
    coordinates: { lat: 22.6196, lng: 120.278 },
    imagePool: 'city',
    features: '文創倉庫,港灣美食,歷史建築,精品咖啡,藝文展演',
    transport: '搭乘輕軌至駁二蓬萊站，步行約3分鐘',
    evaluate: 4.4,
    evaluateNum: 510,
  },
]
