import type { ProductDefinition } from '../types'

export const keelungProducts: ProductDefinition[] = [
  {
    slug: 'miaokou-night-market',
    title: '基隆廟口夜市美食導覽',
    description: '跟著在地老饕深入基隆廟口，品嚐最道地的港都小吃與隱藏版美食。',
    content:
      '<p>基隆廟口夜市是全台最具歷史的夜市之一，從奠濟宮前延伸的攤販聚落匯集了數十年的老字號美食。本導覽將帶您穿梭巷弄，品嚐天婦羅、營養三明治、鼎邊趖等經典小吃，聽在地人說故事。</p>',
    price: 800,
    originPrice: 1000,
    address: '基隆市仁愛區愛四路20號',
    category: 'package',
    coordinates: { lat: 25.1283, lng: 121.7419 },
    imagePool: 'nightMarket',
    features: '在地導覽,經典小吃品嚐,隱藏版美食,文化故事,步行導覽,含試吃',
    transport: '搭乘基隆市公車至廟口站下車，或從基隆火車站步行約10分鐘即達。',
    evaluate: 4.7,
    evaluateNum: 620,
  },
  {
    slug: 'heping-island-park',
    title: '和平島公園門票',
    description: '探索北台灣獨特的海蝕地景與潮間帶生態，享受天然海水泳池。',
    content:
      '<p>和平島公園擁有千萬年海蝕風化形成的奇岩怪石，豆腐岩、蕈狀岩等地質景觀令人驚嘆。園區內設有天然海水游泳池、環山步道及觀海平台，是親子戶外踏青的絕佳去處。</p>',
    price: 120,
    originPrice: 150,
    address: '基隆市中正區平一路360號',
    category: 'tickets',
    coordinates: { lat: 25.159, lng: 121.7632 },
    imagePool: 'beach',
    features: '海蝕奇岩,天然泳池,潮間帶生態,環山步道,親子友善',
    transport: '搭乘基隆市公車101號至和平島公園站下車即達。',
    evaluate: 4.5,
    evaluateNum: 530,
  },
  {
    slug: 'zhengbin-colorful-houses',
    title: '正濱漁港彩色屋攝影半日遊',
    description: '漫步正濱漁港彩色屋，專業攝影師帶你拍出最美的基隆色彩。',
    content:
      '<p>正濱漁港的彩色屋是近年基隆最熱門的打卡景點，繽紛的房屋倒映在港灣水面上，被譽為台灣版威尼斯。本行程含專業攝影師隨行指導，帶您捕捉最美光影角度。</p>',
    price: 1200,
    originPrice: 1500,
    address: '基隆市中正區正濱路88號',
    category: 'package',
    coordinates: { lat: 25.1535, lng: 121.757 },
    imagePool: 'city',
    features: '彩色屋打卡,專業攝影指導,漁港風情,半日行程,含交通接送',
    transport: '搭乘基隆市公車101號至正濱漁港站下車，步行約3分鐘。',
    evaluate: 4.6,
    evaluateNum: 340,
  },
  {
    slug: 'keelung-islet',
    title: '基隆嶼登島生態之旅',
    description: '搭船登上基隆嶼，環島步道飽覽360度海景與豐富生態。',
    content:
      '<p>基隆嶼是基隆外海的火山島嶼，每年限定開放登島。搭乘遊艇約25分鐘即可登島，沿步道登頂可俯瞰基隆港全景，島上有豐富的海鳥與植物生態，是難得的離島體驗。</p>',
    price: 1500,
    originPrice: 1800,
    address: '基隆市中正區碧砂漁港（登船處）',
    category: 'package',
    coordinates: { lat: 25.1878, lng: 121.7808 },
    imagePool: 'island',
    features: '登島體驗,遊艇接駁,360度海景,生態導覽,季節限定,含保險',
    transport: '至碧砂漁港遊艇碼頭集合，基隆火車站搭乘103號公車至碧砂漁港站。',
    evaluate: 4.8,
    evaluateNum: 280,
  },
  {
    slug: 'marine-science-museum',
    title: '海洋科技博物館門票',
    description: '互動式海洋科學展覽，IMAX 3D海洋劇場帶你深入海底世界。',
    content:
      '<p>國立海洋科技博物館位於八斗子，館內設有海洋環境廳、深海展示廳、IMAX 3D海洋劇場等豐富展覽空間，透過互動裝置讓大小朋友認識海洋科學與生態保育。</p>',
    price: 200,
    originPrice: 250,
    address: '基隆市中正區北寧路367號',
    category: 'tickets',
    coordinates: { lat: 25.1372, lng: 121.7969 },
    imagePool: 'museum',
    features: '互動展覽,IMAX海洋劇場,親子共學,海洋生態,室內景點',
    transport: '搭乘台鐵至海科館站下車步行約10分鐘，或搭基隆市公車103號。',
    evaluate: 4.4,
    evaluateNum: 480,
  },
  {
    slug: 'zhongzheng-park',
    title: '中正公園觀音像巡禮',
    description: '登上基隆制高點，參觀巨型觀音像並俯瞰整座港都美景。',
    content:
      '<p>中正公園坐落於基隆市中心的山丘上，園內白色觀音大士像高達22.5公尺，是基隆最著名的地標。登上觀景台可360度俯瞰基隆港、市區與遠方山海，是免費的絕佳觀景點。</p>',
    price: 80,
    originPrice: 100,
    address: '基隆市仁愛區壽山路',
    category: 'tickets',
    coordinates: { lat: 25.1305, lng: 121.7402 },
    imagePool: 'temple',
    features: '觀音像,港都全景,免費景點,歷史建築,步道健行',
    transport: '基隆火車站步行約15分鐘上山，或搭乘501號公車至中正公園站。',
    evaluate: 4.2,
    evaluateNum: 350,
  },
  {
    slug: 'baimiweng-fort',
    title: '白米甕砲台歷史探索',
    description: '走訪清代海防砲台遺址，遠眺基隆港口與外海壯闊海景。',
    content:
      '<p>白米甕砲台建於清代光緒年間，是基隆港最重要的海防據點之一。保存完好的砲座與營舍遺址，搭配無敵海景與基隆嶼遠景，是歷史與自然兼具的秘境景點。</p>',
    price: 600,
    originPrice: 750,
    address: '基隆市中山區太白里光華路37巷',
    category: 'package',
    coordinates: { lat: 25.1563, lng: 121.7312 },
    imagePool: 'nature',
    features: '古蹟巡禮,海景步道,歷史導覽,砲台遺址,攝影景點',
    transport: '搭乘基隆市公車301號至太白社區站，步行約10分鐘。',
    evaluate: 4.3,
    evaluateNum: 180,
  },
  {
    slug: 'badouzi-wangyougu',
    title: '八斗子望幽谷濱海步道',
    description: '走在翠綠山谷與蔚藍大海之間，體驗基隆最美的海岸步道。',
    content:
      '<p>望幽谷又稱忘憂谷，位於八斗子半島上，V型翠綠山谷直面太平洋，步道沿海岸線延伸，沿途可見壯闊海蝕平台與潮間帶。日落時分金色光芒灑落海面，美不勝收。</p>',
    price: 500,
    originPrice: 650,
    address: '基隆市中正區北寧路旁（八斗子公園）',
    category: 'package',
    coordinates: { lat: 25.1378, lng: 121.802 },
    imagePool: 'nature',
    features: '海岸步道,V型山谷,海蝕平台,日落美景,生態觀察,輕鬆健行',
    transport: '搭乘台鐵至海科館站步行約15分鐘，或搭基隆市公車103號至八斗子站。',
    evaluate: 4.6,
    evaluateNum: 410,
  },
  {
    slug: 'lovers-lake-park',
    title: '情人湖公園環湖步道',
    description: '漫步基隆唯一的高地湖泊，吊橋、湖景與森林一次擁有。',
    content:
      '<p>情人湖公園位於大武崙山區，是基隆唯一的高地湖泊。園區設有環湖步道、情人吊橋、觀景亭及親水平台，四周被亞熱帶森林環繞，是都市裡的天然綠洲。</p>',
    price: 500,
    originPrice: 600,
    address: '基隆市安樂區基金一路208巷19號',
    category: 'package',
    coordinates: { lat: 25.1485, lng: 121.705 },
    imagePool: 'nature',
    features: '高地湖泊,情人吊橋,森林步道,觀景亭,親子友善',
    transport: '搭乘基隆市公車505號至情人湖站下車即達。',
    evaluate: 4.3,
    evaluateNum: 290,
  },
  {
    slug: 'chaojing-park',
    title: '潮境公園門票',
    description: '巨型飛天掃帚裝置藝術、海景草坪與潮間帶，基隆最夯打卡點。',
    content:
      '<p>潮境公園位於八斗子半島東側，以大型裝置藝術「飛天掃帚」聞名。廣闊的海景草坪適合野餐放風箏，園區旁的潮間帶可觀察豐富海洋生物，是基隆最受歡迎的戶外景點。</p>',
    price: 100,
    originPrice: 130,
    address: '基隆市中正區北寧路369巷',
    category: 'tickets',
    coordinates: { lat: 25.1365, lng: 121.804 },
    imagePool: 'park',
    features: '裝置藝術,海景草坪,潮間帶,打卡熱點,親子友善',
    transport: '搭乘台鐵至海科館站步行約20分鐘，或搭103號公車至潮境公園站。',
    evaluate: 4.5,
    evaluateNum: 550,
  },
  {
    slug: 'harbor-cruise',
    title: '基隆港遊港觀光船',
    description: '搭乘觀光遊艇環繞基隆港，從海上欣賞港都天際線與山海風光。',
    content:
      '<p>基隆港遊港之旅帶您從海上角度認識這座百年港都，航程約40分鐘，途經正濱漁港彩色屋、基隆燈塔、軍艦碼頭等知名地標，船上提供中英文導覽解說。</p>',
    price: 350,
    originPrice: 450,
    address: '基隆市仁愛區海洋廣場旁碼頭',
    category: 'tickets',
    coordinates: { lat: 25.132, lng: 121.743 },
    imagePool: 'city',
    features: '遊港體驗,海上觀景,中英導覽,彩色屋,港都風情',
    transport: '基隆火車站步行約5分鐘至海洋廣場旁碼頭。',
    evaluate: 4.4,
    evaluateNum: 380,
  },
  {
    slug: 'xiandong-temple',
    title: '仙洞巖洞穴探秘',
    description: '深入天然海蝕洞穴，參觀洞內佛像石刻與鐘乳石奇景。',
    content:
      '<p>仙洞巖是基隆最大的天然海蝕洞穴，洞內供奉觀音菩薩等佛像，石壁上有清代文人石刻。洞穴深處有狹窄的一線天通道，鐘乳石景觀令人讚嘆，充滿神秘氛圍。</p>',
    price: 80,
    originPrice: 100,
    address: '基隆市中山區仁安街1號',
    category: 'tickets',
    coordinates: { lat: 25.148, lng: 121.734 },
    imagePool: 'temple',
    features: '海蝕洞穴,佛像石刻,一線天,鐘乳石,歷史古蹟',
    transport: '搭乘基隆市公車301號至仙洞巖站下車，步行約3分鐘。',
    evaluate: 4.1,
    evaluateNum: 210,
  },
  {
    slug: 'shiqiuling-fort',
    title: '獅球嶺砲台古道健行',
    description: '走訪清法戰爭古戰場，穿越百年隧道與砲台遺址。',
    content:
      '<p>獅球嶺砲台建於清法戰爭期間，是基隆重要的軍事遺址。步道沿途經過劉銘傳隧道、砲台遺址與觀景台，可俯瞰基隆市區與港口，是結合歷史與健行的絕佳路線。</p>',
    price: 600,
    originPrice: 780,
    address: '基隆市仁愛區獅球路',
    category: 'package',
    coordinates: { lat: 25.121, lng: 121.738 },
    imagePool: 'mountain',
    features: '古戰場,劉銘傳隧道,砲台遺址,健行步道,歷史導覽',
    transport: '基隆火車站後站步行約20分鐘，或搭計程車約5分鐘。',
    evaluate: 4.2,
    evaluateNum: 150,
  },
  {
    slug: 'nuannuan-water-park',
    title: '暖暖親水公園半日遊',
    description: '夏日戲水天堂，溪畔步道與親水設施，全家大小的清涼選擇。',
    content:
      '<p>暖暖親水公園沿暖暖溪畔而建，設有兒童戲水池、噴泉廣場及溪畔步道。夏季開放戲水設施，清澈溪水與綠蔭環繞，是基隆在地人最愛的消暑秘境。</p>',
    price: 500,
    originPrice: 600,
    address: '基隆市暖暖區暖暖街',
    category: 'package',
    coordinates: { lat: 25.101, lng: 121.743 },
    imagePool: 'park',
    features: '親水設施,兒童戲水,溪畔步道,夏日消暑,親子友善',
    transport: '搭乘台鐵至暖暖站下車步行約10分鐘。',
    evaluate: 4.0,
    evaluateNum: 200,
  },
  {
    slug: 'waimushan-coast',
    title: '外木山海濱自行車之旅',
    description: '沿著基隆最美海岸線騎行，享受海風與無敵海景。',
    content:
      '<p>外木山濱海自行車道全長約4公里，是基隆最長的天然海岸線。沿途海景開闊，可見漁船點點與遠方基隆嶼，沿線設有多處觀海平台，適合騎車、慢跑或散步。</p>',
    price: 800,
    originPrice: 1000,
    address: '基隆市中山區協和街',
    category: 'package',
    coordinates: { lat: 25.153, lng: 121.718 },
    imagePool: 'beach',
    features: '海濱自行車,海景車道,含自行車租借,觀海平台,輕鬆騎行',
    transport: '搭乘基隆市公車302號至外木山站下車。',
    evaluate: 4.5,
    evaluateNum: 310,
  },
  {
    slug: 'cultural-center',
    title: '基隆文化中心展覽門票',
    description: '欣賞在地藝文展覽與表演，深入認識基隆的文化底蘊。',
    content:
      '<p>基隆文化中心定期舉辦各類藝文展覽、音樂會與戲劇演出，是基隆最重要的藝文展演空間。建築本身融合現代與在地風格，周邊亦有多處歷史建築可順遊。</p>',
    price: 150,
    originPrice: 200,
    address: '基隆市中正區信一路181號',
    category: 'tickets',
    coordinates: { lat: 25.129, lng: 121.7445 },
    imagePool: 'museum',
    features: '藝文展覽,音樂演出,在地文化,室內景點,雨天備案',
    transport: '基隆火車站步行約8分鐘即達。',
    evaluate: 3.9,
    evaluateNum: 120,
  },
  {
    slug: 'keelung-lighthouse',
    title: '基隆燈塔秘境導覽',
    description: '探訪基隆港口燈塔，從制高點遠眺大船入港的壯觀景象。',
    content:
      '<p>基隆燈塔位於萬人堆鼻岬角上，是指引船隻進出基隆港的重要航標。燈塔周邊視野開闊，可近距離觀看大型貨輪與郵輪進出港口，是攝影愛好者的秘密景點。</p>',
    price: 600,
    originPrice: 750,
    address: '基隆市中山區光華路51號',
    category: 'package',
    coordinates: { lat: 25.1555, lng: 121.748 },
    imagePool: 'city',
    features: '燈塔巡禮,港口遠眺,攝影秘境,專人導覽,歷史故事',
    transport: '搭乘基隆市公車301號至太白社區站，步行約15分鐘。',
    evaluate: 4.3,
    evaluateNum: 160,
  },
  {
    slug: 'dawulun-beach',
    title: '大武崙沙灘水上活動',
    description: '基隆唯一的金色沙灘，體驗SUP立槳、浮潛與沙灘排球。',
    content:
      '<p>大武崙沙灘是基隆最美的沙灘，細緻的金黃色沙子與清澈海水，媲美墾丁。夏季提供SUP立槳、浮潛等水上活動，沙灘旁有更衣淋浴設施，是北海岸戲水的好選擇。</p>',
    price: 1200,
    originPrice: 1500,
    address: '基隆市安樂區大武崙',
    category: 'package',
    coordinates: { lat: 25.156, lng: 121.698 },
    imagePool: 'beach',
    features: 'SUP立槳,浮潛體驗,金色沙灘,含裝備租借,教練指導,含保險',
    transport: '搭乘基隆市公車505號至大武崙沙灘站下車。',
    evaluate: 4.6,
    evaluateNum: 370,
  },
  {
    slug: 'yizheng-park',
    title: '役政公園軍事主題導覽',
    description: '參觀戶外軍事公園，近距離觀看退役戰車與軍事裝備。',
    content:
      '<p>役政公園展示多種退役軍事裝備，包括M48戰車、勝利女神飛彈等，是軍事迷的天堂。公園位於中正公園旁，綠地寬敞適合散步，也是親子寓教於樂的好去處。</p>',
    price: 80,
    originPrice: 100,
    address: '基隆市仁愛區壽山路',
    category: 'tickets',
    coordinates: { lat: 25.13, lng: 121.7395 },
    imagePool: 'park',
    features: '軍事裝備,退役戰車,戶外公園,免費入園,親子景點',
    transport: '基隆火車站步行約15分鐘，或搭乘501號公車至中正公園站。',
    evaluate: 3.8,
    evaluateNum: 95,
  },
  {
    slug: 'keelung-tower',
    title: '基隆塔觀景台門票',
    description: '搭乘全透明電梯直上基隆新地標，360度飽覽港都全景。',
    content:
      '<p>基隆塔是基隆最新的觀光地標，全透明豎梯連接市區與中正公園山頂，搭乘過程可欣賞港都風光。頂層觀景台提供360度環景視野，白天看港口運作，夜晚賞璀璨夜景。</p>',
    price: 200,
    originPrice: 250,
    address: '基隆市仁愛區壽山路',
    category: 'tickets',
    coordinates: { lat: 25.1308, lng: 121.74 },
    imagePool: 'city',
    features: '透明電梯,360度觀景,基隆新地標,港都夜景,拍照打卡',
    transport: '基隆火車站步行約10分鐘至基隆塔入口。',
    evaluate: 4.7,
    evaluateNum: 680,
  },
]
