import type { ProductDefinition } from '../types'

export const kinmenProducts: ProductDefinition[] = [
  {
    slug: 'juguang-tower',
    title: '莒光樓門票',
    description: '金門最具代表性的地標建築，曾登上郵票的經典城樓。',
    content:
      '<p>莒光樓建於1952年，是金門最知名的地標，曾多次登上中華民國郵票。三層樓的仿古宮殿式建築氣勢恢宏，登上頂樓可眺望金城市區與對岸廈門。館內展示金門的戰地歷史與建設成就，戶外廣場的莒光湖畔景色宜人，是認識金門歷史的第一站。</p>',
    price: 80,
    originPrice: 100,
    address: '金門縣金城鎮賢城路1號',
    category: 'tickets',
    coordinates: { lat: 24.4167, lng: 118.3167 },
    imagePool: 'city',
    features: '地標建築,歷史展覽,眺望廈門,郵票景點,莒光湖,攝影景點',
    transport: '金門機場搭乘公車至金城站，步行約10分鐘',
    evaluate: 4.2,
    evaluateNum: 480,
  },
  {
    slug: 'zhaishan-tunnel',
    title: '翟山坑道導覽',
    description: '鬼斧神工的花崗岩地下坑道，水面倒影形成奇幻的地底世界。',
    content:
      '<p>翟山坑道開鑿於1963年，是金門最壯觀的戰備水道。全長357公尺的花崗岩坑道深入地底，A字型的水道可容納42艘小艇同時停泊。平靜的水面完美倒映岩壁，形成對稱的地底奇景，燈光投射下宛如進入另一個世界。每年金門坑道音樂節在此舉辦，水面上的樂聲迴盪令人震撼。</p>',
    price: 100,
    originPrice: 130,
    address: '金門縣金城鎮古崗湖南方',
    category: 'tickets',
    coordinates: { lat: 24.3983, lng: 118.3117 },
    imagePool: 'museum',
    features: '花崗岩坑道,水面倒影,戰備水道,坑道音樂節,軍事遺跡,攝影秘境',
    transport: '金城車站搭乘公車7路至翟山坑道站，車程約15分鐘',
    evaluate: 4.6,
    evaluateNum: 620,
  },
  {
    slug: 'deyue-tower',
    title: '得月樓古厝導覽',
    description: '金門最精美的閩南建築群，水頭聚落中西合璧的建築瑰寶。',
    content:
      '<p>得月樓位於水頭聚落內，建於1931年，是金門最具代表性的洋樓建築。四層樓高的銃樓融合閩南與南洋建築風格，牆面精美的磚雕與彩繪保存完好。導覽將帶您穿梭水頭聚落，欣賞黃輝煌洋樓、黃天露宅等中西合璧的華僑建築群，感受金門的僑鄉風華。</p>',
    price: 300,
    originPrice: 380,
    address: '金門縣金城鎮前水頭45號',
    category: 'package',
    coordinates: { lat: 24.41, lng: 118.31 },
    imagePool: 'oldStreet',
    features: '閩南建築,得月樓,水頭聚落,華僑洋樓,磚雕彩繪,建築導覽',
    transport: '金城車站搭乘公車7路至水頭站，步行約5分鐘',
    evaluate: 4.5,
    evaluateNum: 450,
  },
  {
    slug: 'kinmen-national-park',
    title: '金門國家公園生態之旅',
    description: '全台唯一以戰地文化與自然生態為主題的國家公園。',
    content:
      '<p>金門國家公園成立於1995年，是台灣第六座國家公園，也是唯一以維護戰役史蹟與文化資產為主的國家公園。園區涵蓋太武山、古寧頭、馬山及烈嶼等區域，擁有豐富的閩南聚落、戰地遺跡及候鳥生態。生態之旅包含栗喉蜂虎賞鳥、濕地生態觀察及戰地巡禮。</p>',
    price: 1200,
    originPrice: 1500,
    address: '金門縣金寧鄉伯玉路二段460號',
    category: 'package',
    coordinates: { lat: 24.45, lng: 118.35 },
    imagePool: 'nature',
    features: '國家公園,戰地遺跡,候鳥生態,栗喉蜂虎,閩南聚落,深度導覽',
    transport: '金門機場搭乘公車至金門國家公園管理處，車程約15分鐘',
    evaluate: 4.4,
    evaluateNum: 370,
  },
  {
    slug: 'guningtou-war-museum',
    title: '古寧頭戰史館門票',
    description: '重現1949年古寧頭大捷的歷史場景，金門最重要的戰役紀念館。',
    content:
      '<p>古寧頭戰史館紀念1949年的古寧頭戰役，是國共內戰中影響台灣命運的關鍵一役。館內以12幅大型油畫呈現戰役過程，搭配武器實物、戰爭文物及多媒體影音，生動重現當年激烈的戰況。戶外展示區陳列戰車、大砲等重型武器，館旁的和平紀念碑銘記歷史教訓。</p>',
    price: 100,
    originPrice: 130,
    address: '金門縣金寧鄉北山村古寧頭',
    category: 'tickets',
    coordinates: { lat: 24.4694, lng: 118.3083 },
    imagePool: 'museum',
    features: '戰史紀念,油畫展覽,武器展示,多媒體影音,戰車陳列,歷史教育',
    transport: '金城車站搭乘公車10路至古寧頭站，車程約20分鐘',
    evaluate: 4.3,
    evaluateNum: 410,
  },
  {
    slug: 'shanhou-folk-village',
    title: '山后民俗文化村巡禮',
    description: '金門保存最完整的閩南聚落，十八棟大厝整齊排列氣勢恢宏。',
    content:
      '<p>山后民俗文化村由十八棟閩南傳統二落大厝組成，建於清光緒年間，是旅日華僑王國珍出資興建。整齊劃一的燕尾屋脊、精美的石雕與磚雕、寬敞的中庭，展現閩南建築的極致工藝。部分古厝闢為展示館，展出金門的民俗文物、婚嫁禮俗及常民生活。</p>',
    price: 150,
    originPrice: 200,
    address: '金門縣金沙鎮山后村中堡',
    category: 'tickets',
    coordinates: { lat: 24.4722, lng: 118.4222 },
    imagePool: 'oldStreet',
    features: '閩南聚落,十八棟大厝,燕尾屋脊,石雕磚雕,民俗展示,建築之美',
    transport: '金城車站搭乘公車25路至山后站，車程約30分鐘',
    evaluate: 4.4,
    evaluateNum: 380,
  },
  {
    slug: 'kinmen-kaoliang-distillery',
    title: '金門酒廠參觀體驗',
    description: '探訪金門高粱酒的釀造秘密，品酒體驗與限定酒款選購。',
    content:
      '<p>金門酒廠創立於1952年，出產的金門高粱酒是台灣最知名的白酒品牌。參觀行程帶您走訪釀酒廠區，了解從選料、蒸煮、發酵到蒸餾的完整製程。品酒區可品嚐不同年份的高粱酒，感受醇厚的口感差異。廠區商店提供多款限定酒品及伴手禮選購。</p>',
    price: 200,
    originPrice: 260,
    address: '金門縣金寧鄉桃園路1號',
    category: 'tickets',
    coordinates: { lat: 24.4528, lng: 118.3278 },
    imagePool: 'museum',
    features: '高粱酒,釀造導覽,品酒體驗,限定酒款,伴手禮,金門特產',
    transport: '金門機場搭乘計程車約10分鐘，或公車至酒廠站',
    evaluate: 4.3,
    evaluateNum: 520,
  },
  {
    slug: 'jiangong-islet',
    title: '建功嶼潮間帶探索',
    description: '退潮時才能通行的神秘小島，金門版摩西分海的奇幻體驗。',
    content:
      '<p>建功嶼位於金城鎮南方海面，退潮時一條石板路浮現海面，可步行前往，漲潮時則被海水淹沒，有「金門摩西分海」之稱。島上保留了軍事碉堡與營舍遺跡，更可眺望對岸廈門的摩天大樓群。潮間帶生態豐富，招潮蟹、彈塗魚隨處可見。需注意潮汐時間。</p>',
    price: 350,
    originPrice: 450,
    address: '金門縣金城鎮南門里',
    category: 'package',
    coordinates: { lat: 24.4083, lng: 118.3167 },
    imagePool: 'island',
    features: '摩西分海,潮間帶,軍事碉堡,眺望廈門,生態觀察,潮汐限定',
    transport: '金城車站步行約20分鐘至海岸，需查詢退潮時間',
    evaluate: 4.5,
    evaluateNum: 400,
  },
  {
    slug: 'shishan-artillery',
    title: '獅山砲陣地砲操表演',
    description: '全台唯一的坑道式砲陣地，震撼的榴彈砲操演令人熱血沸騰。',
    content:
      '<p>獅山砲陣地位於金門東北角，是全國唯一的坑道式榴彈砲陣地，被譽為「震東坑道」。花崗岩坑道內陳列八吋榴彈砲，每日定時的砲操表演由退役軍人演出，口令聲響徹坑道，砲彈裝填的動作整齊劃一，重現當年砲戰的震撼場面，是金門最受歡迎的體驗。</p>',
    price: 100,
    originPrice: 130,
    address: '金門縣金沙鎮山后村陽沙路',
    category: 'tickets',
    coordinates: { lat: 24.4833, lng: 118.4333 },
    imagePool: 'museum',
    features: '砲操表演,坑道砲陣地,八吋榴砲,軍事體驗,震東坑道,每日演出',
    transport: '金城車站搭乘公車25路至獅山站，車程約35分鐘',
    evaluate: 4.6,
    evaluateNum: 550,
  },
  {
    slug: 'shuitou-settlement',
    title: '水頭聚落深度導覽',
    description: '金門最美的傳統聚落，閩南古厝與洋樓建築的完美交融。',
    content:
      '<p>水頭聚落是金門保存最完整、風格最多元的傳統聚落，擁有閩南式古厝、洋樓、宗祠等不同時期的建築。聚落中的得月樓、黃輝煌洋樓、黃天露宅等建築各具特色。深度導覽由在地文史工作者帶領，講述每棟建築背後的家族故事與華僑奮鬥史。</p>',
    price: 500,
    originPrice: 650,
    address: '金門縣金城鎮前水頭',
    category: 'package',
    coordinates: { lat: 24.41, lng: 118.3083 },
    imagePool: 'oldStreet',
    features: '傳統聚落,閩南古厝,洋樓建築,文史導覽,華僑故事,建築多元',
    transport: '金城車站搭乘公車7路至水頭站，車程約10分鐘',
    evaluate: 4.5,
    evaluateNum: 360,
  },
  {
    slug: 'kinmen-ceramics-factory',
    title: '金門陶瓷廠彩繪體驗',
    description: '親手彩繪專屬風獅爺，將金門的守護神帶回家。',
    content:
      '<p>金門陶瓷廠是金門唯一的陶瓷工廠，以生產風獅爺、酒瓶及各式陶瓷工藝品聞名。彩繪體驗課程讓您在專業老師指導下，親手為素胚風獅爺上色，創作獨一無二的紀念品。廠區內還有展示館介紹金門陶瓷的發展歷史，以及各式精美的陶瓷藝術品。</p>',
    price: 350,
    originPrice: 450,
    address: '金門縣金湖鎮瓊徑路39號',
    category: 'package',
    coordinates: { lat: 24.4333, lng: 118.4083 },
    imagePool: 'museum',
    features: '風獅爺彩繪,陶瓷工藝,手作體驗,伴手禮,展示館,親子適合',
    transport: '金城車站搭乘公車至陶瓷廠站，車程約20分鐘',
    evaluate: 4.2,
    evaluateNum: 230,
  },
  {
    slug: 'jincheng-civil-defense-tunnel',
    title: '金城民防坑道探險',
    description: '穿梭金城鎮地底的秘密通道，體驗戰時居民的避難生活。',
    content:
      '<p>金城民防坑道是1960年代為因應戰爭而開鑿的地下防空通道，總長約2.5公里，連接金城鎮各主要據點。坑道內保留了當年的通訊設備、標語及避難設施。走在狹窄的地底通道中，頭上是熙來攘往的商街，腳下卻是冷戰時期的緊張氛圍，時空交錯感強烈。</p>',
    price: 150,
    originPrice: 200,
    address: '金門縣金城鎮光前路',
    category: 'tickets',
    coordinates: { lat: 24.4333, lng: 118.3167 },
    imagePool: 'museum',
    features: '防空坑道,地下探險,冷戰遺跡,戰時設施,時空穿越,歷史體驗',
    transport: '金城車站步行約5分鐘至坑道入口',
    evaluate: 4.1,
    evaluateNum: 280,
  },
  {
    slug: 'liaoluo-bay-beach',
    title: '料羅灣海灘半日遊',
    description: '金門最美的弧形沙灘，碧海白沙與戰地風情交織的海岸線。',
    content:
      '<p>料羅灣位於金門東南方，擁有金門最長最美的弧形沙灘。細緻的白色沙灘綿延數公里，海水清澈湛藍。這裡也是1958年八二三砲戰期間補給物資的重要港口，海灘旁仍可見當年的反登陸樁與碉堡遺跡。半日遊包含沙灘漫步、戰史導覽及在地風味點心。</p>',
    price: 500,
    originPrice: 650,
    address: '金門縣金湖鎮料羅村',
    category: 'package',
    coordinates: { lat: 24.4, lng: 118.4167 },
    imagePool: 'beach',
    features: '弧形沙灘,碧海白沙,八二三砲戰,反登陸樁,戰地風情,風味點心',
    transport: '金城車站搭乘公車至料羅站，車程約25分鐘',
    evaluate: 4.2,
    evaluateNum: 300,
  },
  {
    slug: 'taiwu-mountain-trail',
    title: '太武山步道健行',
    description: '金門最高峰，山頂的「毋忘在莒」勒石是金門精神的象徵。',
    content:
      '<p>太武山海拔253公尺，是金門的最高峰。步道全長約4.6公里，沿途經過海印寺、倒影塔及多處軍事據點。登頂後映入眼簾的是先總統蔣公題字的「毋忘在莒」巨大勒石，從山頂可360度俯瞰金門全島及對岸廈門。步道途中的海印寺是金門最古老的寺廟。</p>',
    price: 200,
    originPrice: 260,
    address: '金門縣金湖鎮太武山步道入口',
    category: 'tickets',
    coordinates: { lat: 24.4417, lng: 118.3917 },
    imagePool: 'mountain',
    features: '金門最高峰,毋忘在莒,海印寺,360度展望,軍事據點,歷史步道',
    transport: '金城車站搭乘公車至太武山入口站，車程約20分鐘',
    evaluate: 4.3,
    evaluateNum: 350,
  },
  {
    slug: 'chen-jinglan-mansion',
    title: '陳景蘭洋樓參觀',
    description: '金門規模最大的洋樓，華僑返鄉興建的巴洛克式宅邸。',
    content:
      '<p>陳景蘭洋樓建於1921年，是金門現存最大且最精美的洋樓建築。這棟白色巴洛克式建築為新加坡華僑陳景蘭所建，曾作為學校、軍醫院使用。樓內展示金門華僑的南洋奮鬥史，頂樓陽台可遠眺料羅灣的湛藍海岸。洋樓前的自強園林造景典雅。</p>',
    price: 80,
    originPrice: 100,
    address: '金門縣金湖鎮正義里成功村1號',
    category: 'tickets',
    coordinates: { lat: 24.4167, lng: 118.4167 },
    imagePool: 'oldStreet',
    features: '巴洛克洋樓,華僑歷史,南洋風格,料羅灣展望,自強園林,免費參觀',
    transport: '金城車站搭乘公車至成功站，步行約5分鐘',
    evaluate: 4.3,
    evaluateNum: 320,
  },
  {
    slug: 'wind-lion-god-tour',
    title: '風獅爺尋訪文化之旅',
    description: '騎車尋訪散布全島的風獅爺，認識金門獨特的鎮風辟邪文化。',
    content:
      '<p>風獅爺是金門最獨特的文化象徵，全島現存約70尊，分布在各村落中擔任鎮風辟邪的守護神。每尊風獅爺造型各異，有的威猛、有的可愛，高度從30公分到近4公尺不等。這趟文化之旅由在地導覽帶騎，走訪最具代表性的15尊風獅爺，聽它們守護村落的故事。</p>',
    price: 800,
    originPrice: 1000,
    address: '金門縣金城鎮（集合出發）',
    category: 'package',
    coordinates: { lat: 24.4333, lng: 118.3167 },
    imagePool: 'oldStreet',
    features: '風獅爺,文化巡禮,騎車尋訪,在地導覽,村落故事,攝影集章',
    transport: '金城車站集合出發，提供自行車或電動車',
    evaluate: 4.4,
    evaluateNum: 290,
  },
  {
    slug: 'kaoliang-tasting',
    title: '金門高粱品酒之旅',
    description: '品酒師帶路的高粱酒文化之旅，品嚐不同年份與風味的金門高粱。',
    content:
      '<p>金門高粱酒以金門特有的旱地高粱與花崗岩層地下水釀造，口感醇厚甘洌。這趟品酒之旅由專業品酒師帶領，參觀酒廠釀造過程，品嚐從38度到58度、從3年到12年陳釀的不同高粱酒款。還可學習品酒技巧，了解高粱酒與台菜的搭配之道。</p>',
    price: 1000,
    originPrice: 1300,
    address: '金門縣金寧鄉桃園路1號',
    category: 'package',
    coordinates: { lat: 24.4528, lng: 118.3278 },
    imagePool: 'museum',
    features: '品酒體驗,年份高粱,品酒師帶路,釀造參觀,餐酒搭配,限定酒款',
    transport: '金門機場搭乘計程車約10分鐘，或公車至酒廠站',
    evaluate: 4.5,
    evaluateNum: 270,
  },
  {
    slug: 'houpu-town-walk',
    title: '後浦小鎮散步導覽',
    description: '金城鎮舊稱後浦，漫步百年老街品味金門的庶民生活。',
    content:
      '<p>後浦是金城鎮的古稱，至今仍保留大量傳統建築與百年老店。散步導覽從模範街出發，穿梭清金門鎮總兵署、邱良功母節孝坊、金城老街等歷史景點。沿途品嚐廣東粥、蚵嗲、石蚵等在地小吃，聽導覽講述每棟建築與每道美食背後的故事。</p>',
    price: 500,
    originPrice: 650,
    address: '金門縣金城鎮模範街',
    category: 'package',
    coordinates: { lat: 24.4333, lng: 118.3194 },
    imagePool: 'oldStreet',
    features: '後浦老街,模範街,在地小吃,歷史建築,節孝坊,庶民生活',
    transport: '金城車站步行約3分鐘即達模範街',
    evaluate: 4.3,
    evaluateNum: 380,
  },
  {
    slug: 'lieyu-jiugong-tunnel',
    title: '烈嶼九宮坑道探索',
    description: '小金門最大的地下坑道，花崗岩中開鑿的軍事工程奇蹟。',
    content:
      '<p>九宮坑道位於烈嶼鄉（小金門），全長約790公尺，是小金門最大的戰備坑道。四通八達的坑道連接五個出入口，花崗岩壁上仍可見當年工兵開鑿的痕跡。坑道內設有展示區介紹小金門的戰史與居民生活。從坑道出口眺望對岸廈門，距離之近令人驚嘆。</p>',
    price: 350,
    originPrice: 450,
    address: '金門縣烈嶼鄉九宮碼頭旁',
    category: 'package',
    coordinates: { lat: 24.4167, lng: 118.2417 },
    imagePool: 'museum',
    features: '地下坑道,花崗岩,軍事工程,小金門,戰備遺跡,眺望廈門',
    transport: '金門水頭碼頭搭船至九宮碼頭，航程約15分鐘',
    evaluate: 4.2,
    evaluateNum: 260,
  },
  {
    slug: 'kinmen-battlefield-tour',
    title: '金門戰地文化一日遊',
    description: '完整走訪金門戰地遺跡，從古寧頭到太武山的軍事歷史之旅。',
    content:
      '<p>金門戰地文化一日遊是認識金門軍事歷史最全面的行程。從古寧頭戰史館出發，經北山斷崖的彈孔牆、獅山砲陣地觀看砲操、翟山坑道欣賞地底奇景，最後登太武山朝聖毋忘在莒。全程含專業戰史導覽、午餐及各景點門票，深度體驗金門獨特的戰地風貌。</p>',
    price: 2000,
    originPrice: 2500,
    address: '金門縣金城鎮（飯店接送）',
    category: 'package',
    coordinates: { lat: 24.4333, lng: 118.35 },
    imagePool: 'city',
    features: '戰地巡禮,一日遊,專業導覽,含午餐,多景點,軍事歷史',
    transport: '金門各飯店免費接送，或至金城車站集合',
    evaluate: 4.6,
    evaluateNum: 480,
  },
]
