import type { ProductDefinition } from '../types'

export const lienchiangProducts: ProductDefinition[] = [
  {
    slug: 'qinbi-settlement',
    title: '芹壁聚落石屋巡禮',
    description: '北竿最美的花崗岩石屋聚落，被譽為馬祖的地中海小鎮。',
    content:
      '<p>芹壁聚落位於北竿島北方，依山面海的花崗岩石屋層層疊起，搭配碧藍的海灣與龜島，景色宛如地中海沿岸的小漁村。聚落內的石屋經修復後進駐民宿、咖啡廳及藝文空間，白天可欣賞閩東建築之美，夜晚在石屋中聽海入眠，是馬祖最浪漫的體驗。</p>',
    price: 400,
    originPrice: 520,
    address: '連江縣北竿鄉芹壁村',
    category: 'package',
    coordinates: { lat: 26.1833, lng: 119.9667 },
    imagePool: 'oldStreet',
    features: '石屋聚落,地中海風情,閩東建築,海灣美景,龜島,攝影聖地',
    transport: '北竿機場或白沙碼頭搭車約10分鐘可達',
    evaluate: 4.7,
    evaluateNum: 480,
  },
  {
    slug: 'beihai-tunnel-blue-tears',
    title: '北海坑道藍眼淚體驗',
    description: '在戰備坑道中搖櫓觀賞神秘藍眼淚，馬祖最夢幻的夜間體驗。',
    content:
      '<p>北海坑道位於南竿鄉仁愛村，是一座深入花崗岩的海上戰備坑道，全長約640公尺。每年四月至九月，坑道水面上會出現被稱為「藍眼淚」的夜光藻，划動船槳時激起的藍色螢光宛如星河倒映。搭乘搖櫓小船穿行在幽暗坑道中，藍光閃爍，夢幻至極。</p>',
    price: 500,
    originPrice: 650,
    address: '連江縣南竿鄉仁愛村95號',
    category: 'tickets',
    coordinates: { lat: 26.1417, lng: 119.925 },
    imagePool: 'island',
    features: '藍眼淚,搖櫓體驗,戰備坑道,夜光藻,夜間限定,季節限定',
    transport: '南竿機場搭車約15分鐘至北海坑道入口',
    evaluate: 4.8,
    evaluateNum: 620,
  },
  {
    slug: 'daqiu-deer-island',
    title: '大坵梅花鹿島一日遊',
    description: '無人島上野放的梅花鹿群，與鹿共遊的奇妙島嶼體驗。',
    content:
      '<p>大坵島原為軍事據點，撤軍後島上梅花鹿自然繁衍，如今已有上百頭野放梅花鹿在島上自由生活。搭船登島後，沿著步道漫步即可近距離接觸不怕人的梅花鹿，牠們甚至會主動靠近討食。島上還有廢棄軍事碉堡與無敵海景，是馬祖最獨特的離島體驗。</p>',
    price: 800,
    originPrice: 1000,
    address: '連江縣北竿鄉大坵島',
    category: 'package',
    coordinates: { lat: 26.2, lng: 119.9833 },
    imagePool: 'island',
    features: '梅花鹿,無人島,近距離互動,軍事碉堡,海景步道,搭船登島',
    transport: '北竿橋仔碼頭搭乘交通船至大坵，航程約10分鐘',
    evaluate: 4.6,
    evaluateNum: 400,
  },
  {
    slug: 'baba-tunnel',
    title: '八八坑道參觀',
    description: '馬祖高粱酒的陳年酒窖，坑道內酒香撲鼻令人微醺。',
    content:
      '<p>八八坑道原為軍事戰備用途，因在蔣公八十八歲華誕時竣工而得名。如今作為馬祖酒廠的儲酒坑道，洞內恆溫恆濕的環境是陳年高粱酒與老酒的最佳窖藏地。走進坑道瞬間被濃郁的酒香包圍，兩側整齊排列的酒甕與橡木桶壯觀無比，令人彷彿微醺。</p>',
    price: 100,
    originPrice: 130,
    address: '連江縣南竿鄉復興村208號',
    category: 'tickets',
    coordinates: { lat: 26.1583, lng: 119.9417 },
    imagePool: 'museum',
    features: '儲酒坑道,高粱酒窖,酒香撲鼻,恆溫環境,酒甕排列,免費參觀',
    transport: '南竿機場搭車約10分鐘至八八坑道',
    evaluate: 4.4,
    evaluateNum: 520,
  },
  {
    slug: 'dongyin-lighthouse',
    title: '東引燈塔巡禮',
    description: '台灣國土最北端的燈塔，百年歷史的英式建築矗立海崖。',
    content:
      '<p>東引燈塔又名東湧燈塔，建於1904年清光緒年間，由英國工程師設計建造，是台灣最北端的燈塔。白色的維多利亞式燈塔矗立在陡峭海崖上，搭配湛藍海景極為壯觀。沿著步道可抵達燈塔腳下，沿途可見壯麗的海蝕地景與豐富的海鳥生態。</p>',
    price: 300,
    originPrice: 380,
    address: '連江縣東引鄉樂華村',
    category: 'package',
    coordinates: { lat: 26.375, lng: 120.5083 },
    imagePool: 'island',
    features: '國境之北,百年燈塔,英式建築,海崖步道,海蝕地景,攝影景點',
    transport: '南竿福澳碼頭搭乘台馬之星至東引，航程約2小時',
    evaluate: 4.6,
    evaluateNum: 280,
  },
  {
    slug: 'nangan-tiepu',
    title: '南竿鐵堡探索',
    description: '直接鑿入岩壁的海上碉堡，最驚險的戰地秘境體驗。',
    content:
      '<p>鐵堡位於南竿仁愛村海岸邊，是一座直接在花崗岩壁上開鑿的軍事據點。整座碉堡隱藏在岩石中，入口狹窄隱密，內部設有射口、彈藥庫及坑道。站在碉堡最外端的觀測台上，三面環海的視野令人震撼。退潮時可沿著海岸步道前往，潮汐增添了探訪的冒險感。</p>',
    price: 150,
    originPrice: 200,
    address: '連江縣南竿鄉仁愛村',
    category: 'tickets',
    coordinates: { lat: 26.1389, lng: 119.9222 },
    imagePool: 'island',
    features: '岩壁碉堡,軍事秘境,花崗岩,海岸步道,三面環海,冒險體驗',
    transport: '南竿機場搭車約15分鐘至鐵堡步道入口',
    evaluate: 4.3,
    evaluateNum: 310,
  },
  {
    slug: 'matsu-distillery',
    title: '馬祖酒廠品酒體驗',
    description: '品嚐馬祖特有的老酒與高粱，認識離島釀酒的獨特工藝。',
    content:
      '<p>馬祖酒廠以馬祖特有的紅麴老酒聞名，另也釀造高粱酒。品酒體驗帶您參觀製酒過程，了解紅麴老酒的釀造秘訣——使用在地糯米與紅麴，經長時間發酵熟成。品酒環節可品嚐不同年份的老酒與高粱，搭配馬祖特色小食。最後可選購限定酒款作為伴手禮。</p>',
    price: 500,
    originPrice: 650,
    address: '連江縣南竿鄉復興村208號',
    category: 'package',
    coordinates: { lat: 26.1583, lng: 119.9417 },
    imagePool: 'museum',
    features: '紅麴老酒,品酒體驗,釀造參觀,馬祖特產,限定酒款,伴手禮',
    transport: '南竿機場搭車約10分鐘至馬祖酒廠',
    evaluate: 4.3,
    evaluateNum: 280,
  },
  {
    slug: 'jinsha-settlement',
    title: '津沙聚落夕陽散策',
    description: '南竿西側的百年漁村聚落，夕陽西沉時石屋染上金色光芒。',
    content:
      '<p>津沙聚落位於南竿西南方，是馬祖保存最完整的漁村聚落之一。花崗岩石屋沿著山坡而建，層次分明。聚落面朝西方，每到黃昏時分，夕陽將整片石屋映照得金光閃閃，景色絕美。部分石屋改建為民宿與咖啡廳，在古樸石屋中品咖啡賞夕陽是最奢侈的享受。</p>',
    price: 300,
    originPrice: 380,
    address: '連江縣南竿鄉津沙村',
    category: 'package',
    coordinates: { lat: 26.1389, lng: 119.9111 },
    imagePool: 'oldStreet',
    features: '石屋聚落,夕陽美景,百年漁村,咖啡廳,攝影景點,閩東建築',
    transport: '南竿機場搭車約20分鐘至津沙聚落',
    evaluate: 4.4,
    evaluateNum: 260,
  },
  {
    slug: 'magang-tianhou-temple',
    title: '馬港天后宮參拜導覽',
    description: '全台唯一供奉媽祖靈穴的天后宮，馬祖地名的由來。',
    content:
      '<p>馬港天后宮是馬祖最重要的信仰中心，相傳媽祖林默娘的遺體漂流至此，居民感念而建廟供奉。廟宇的媽祖靈穴就在神像座下方，是全台唯一的媽祖葬身之地，也是「馬祖」地名的由來。導覽將詳述媽祖傳說、廟宇建築特色及馬祖特有的宗教民俗。</p>',
    price: 200,
    originPrice: 260,
    address: '連江縣南竿鄉馬祖村4號',
    category: 'tickets',
    coordinates: { lat: 26.1472, lng: 119.9222 },
    imagePool: 'temple',
    features: '媽祖靈穴,地名由來,信仰中心,廟宇建築,宗教民俗,歷史導覽',
    transport: '南竿機場搭車約15分鐘至馬港天后宮',
    evaluate: 4.2,
    evaluateNum: 340,
  },
  {
    slug: 'war-peace-memorial-park',
    title: '戰爭和平紀念公園門票',
    description: '馬祖最完整的戰地主題公園，從軍事歷史中反思和平的珍貴。',
    content:
      '<p>戰爭和平紀念公園位於北竿大沃山，園區包含戰爭和平紀念館、06及08兩座據點及多處軍事設施遺跡。紀念館以多媒體展示馬祖從戰地前線到觀光轉型的歷史過程，08據點的砲台與坑道保存完整。站在制高點可眺望大沃山至壁山的壯闘海岸線。</p>',
    price: 100,
    originPrice: 130,
    address: '連江縣北竿鄉坂里村',
    category: 'tickets',
    coordinates: { lat: 26.175, lng: 119.9583 },
    imagePool: 'museum',
    features: '戰地公園,紀念館,軍事據點,砲台坑道,歷史教育,海景展望',
    transport: '北竿機場搭車約10分鐘至紀念公園',
    evaluate: 4.2,
    evaluateNum: 230,
  },
  {
    slug: 'niujiao-settlement',
    title: '牛角聚落文創導覽',
    description: '南竿最大的傳統聚落，石屋裡蘊藏馬祖的文創能量。',
    content:
      '<p>牛角聚落是南竿面積最大的傳統聚落，花崗岩石屋沿山壁而建，巷弄蜿蜒如迷宮。近年文創工作者進駐，石屋變身為藝術工作室、獨立書店及手作工坊。導覽帶您穿梭巷弄間，認識閩東建築的營造智慧，體驗在地藝術家的創作，品嚐聚落內的手工點心。</p>',
    price: 450,
    originPrice: 580,
    address: '連江縣南竿鄉復興村（牛角）',
    category: 'package',
    coordinates: { lat: 26.1556, lng: 119.9472 },
    imagePool: 'oldStreet',
    features: '傳統聚落,文創空間,閩東建築,巷弄迷宮,手作體驗,藝術工坊',
    transport: '南竿機場搭車約8分鐘至牛角聚落',
    evaluate: 4.3,
    evaluateNum: 250,
  },
  {
    slug: 'bishan-observation-deck',
    title: '壁山觀景台眺望體驗',
    description: '馬祖最高點，360度無死角俯瞰北竿全島與周邊島嶼。',
    content:
      '<p>壁山海拔298公尺，是馬祖列島的最高點。觀景台設有雙層平台，天氣晴朗時可360度眺望北竿全島、南竿、大坵及周邊島嶼，甚至能隱約看見中國大陸海岸線。春夏季節常有雲霧繚繞，宛如置身仙境。這裡也是觀賞日出與星空的絕佳地點。</p>',
    price: 100,
    originPrice: 130,
    address: '連江縣北竿鄉坂里村壁山',
    category: 'tickets',
    coordinates: { lat: 26.175, lng: 119.9667 },
    imagePool: 'mountain',
    features: '馬祖最高點,360度展望,雲霧仙境,日出觀賞,觀星秘境,免費參觀',
    transport: '北竿機場搭車約15分鐘至壁山觀景台',
    evaluate: 4.4,
    evaluateNum: 310,
  },
  {
    slug: 'dongju-lighthouse',
    title: '東莒燈塔導覽',
    description: '百年歷史的英式燈塔，守護莒光海域的潔白浪漫地標。',
    content:
      '<p>東莒燈塔又名東犬燈塔，建於1872年清同治年間，由英國人設計監造，為二級古蹟。純白色的圓柱型燈塔搭配附屬建築群，在藍天綠地間格外醒目。燈塔下方是一片翠綠的大草原，面朝無垠大海，是馬祖最療癒的風景之一。導覽介紹燈塔歷史與航海知識。</p>',
    price: 250,
    originPrice: 320,
    address: '連江縣莒光鄉福正村',
    category: 'package',
    coordinates: { lat: 25.9583, lng: 119.9917 },
    imagePool: 'island',
    features: '百年燈塔,英式建築,二級古蹟,大草原,海景遼闊,歷史導覽',
    transport: '南竿福澳碼頭搭船至東莒猛澳港，航程約50分鐘',
    evaluate: 4.5,
    evaluateNum: 220,
  },
  {
    slug: 'fuzheng-settlement',
    title: '福正聚落漁村體驗',
    description: '東莒島上的百年漁村，石屋與沙灘交織的原始離島風情。',
    content:
      '<p>福正聚落位於東莒島東北方，是馬祖保存最原始的漁村聚落。花崗岩石屋依山而建，面朝一片金色沙灘。聚落雖已少有居民，但石屋的牆垣、廟宇與石階仍訴說著往日的漁村生活。退潮時可在沙灘上挖花蛤，體驗馬祖傳統的「討小海」生活方式。</p>',
    price: 600,
    originPrice: 780,
    address: '連江縣莒光鄉福正村',
    category: 'package',
    coordinates: { lat: 25.9611, lng: 119.9917 },
    imagePool: 'beach',
    features: '百年漁村,石屋聚落,討小海,花蛤體驗,金色沙灘,原始風情',
    transport: '東莒猛澳港搭車約10分鐘至福正聚落',
    evaluate: 4.3,
    evaluateNum: 180,
  },
  {
    slug: 'banli-beach',
    title: '坂里沙灘水上活動',
    description: '北竿最大的沙灘，清澈海水與細緻白沙的離島戲水天堂。',
    content:
      '<p>坂里沙灘位於北竿鄉，是馬祖地區面積最大的沙灘。綿延數百公尺的潔白沙灘配上清澈見底的海水，媲美國際級海灘。夏季提供SUP立槳、獨木舟、浮潛等水上活動，沙灘上還有貝殼與海玻璃可以撿拾。傍晚時分金色夕陽灑落沙灘，美不勝收。</p>',
    price: 800,
    originPrice: 1000,
    address: '連江縣北竿鄉坂里村',
    category: 'package',
    coordinates: { lat: 26.175, lng: 119.95 },
    imagePool: 'beach',
    features: '白色沙灘,SUP立槳,獨木舟,浮潛,夕陽美景,撿海玻璃',
    transport: '北竿機場搭車約5分鐘至坂里沙灘',
    evaluate: 4.4,
    evaluateNum: 270,
  },
  {
    slug: 'matsu-folk-museum',
    title: '馬祖民俗文物館門票',
    description: '全面認識馬祖的歷史文化與常民生活，館藏豐富的地方博物館。',
    content:
      '<p>馬祖民俗文物館位於南竿清水村，是認識馬祖最全面的室內景點。館內分為自然生態、歷史源流、民居建築、民俗信仰及漁業文化等展區，以實物與模型呈現馬祖從漁村到戰地再到觀光的發展歷程。閩東建築的木雕構件與傳統漁具展示尤為精采。</p>',
    price: 80,
    originPrice: 100,
    address: '連江縣南竿鄉清水村135號',
    category: 'tickets',
    coordinates: { lat: 26.1528, lng: 119.9333 },
    imagePool: 'museum',
    features: '地方博物館,常民文化,漁業歷史,閩東建築,自然生態,室內景點',
    transport: '南竿機場搭車約10分鐘至民俗文物館',
    evaluate: 3.9,
    evaluateNum: 160,
  },
  {
    slug: 'luoshan-nature-trail',
    title: '螺山自然步道健行',
    description: '馬祖最美的海岸步道，沿著海崖漫步欣賞壯闊海景。',
    content:
      '<p>螺山自然步道位於北竿島北端，全長約700公尺，沿著海岸山崖修築。步道一側是陡峭的花崗岩海崖，另一側是無邊際的大海，走在其中有種天涯海角的壯闊感。沿途可見豐富的海蝕地景、潮間帶生態，運氣好還能看到海鸚鵡與黑嘴端鳳頭燕鷗。</p>',
    price: 150,
    originPrice: 200,
    address: '連江縣北竿鄉螺山',
    category: 'tickets',
    coordinates: { lat: 26.1917, lng: 119.975 },
    imagePool: 'island',
    features: '海岸步道,花崗岩海崖,海蝕地景,賞鳥,天涯海角,自然生態',
    transport: '北竿機場搭車至步道入口約15分鐘',
    evaluate: 4.5,
    evaluateNum: 200,
  },
  {
    slug: 'dongyin-andong-tunnel',
    title: '東引安東坑道探險',
    description: '深入東引島花崗岩地底，規模宏大的軍事坑道系統。',
    content:
      '<p>安東坑道位於東引島南方，入口沿著陡峭的階梯向下深入花崗岩層，坑道全長約300公尺，設有彈藥庫、兵舍、豬舍及廚房等空間，可容納一個連的兵力。坑道盡頭開口面對懸崖與大海，景觀震撼。夏季坑道口是觀賞黑尾鷗築巢的最佳地點。</p>',
    price: 200,
    originPrice: 260,
    address: '連江縣東引鄉樂華村',
    category: 'tickets',
    coordinates: { lat: 26.3667, lng: 120.4917 },
    imagePool: 'museum',
    features: '軍事坑道,花崗岩層,懸崖出口,黑尾鷗,階梯探險,海景震撼',
    transport: '東引碼頭搭車約10分鐘至安東坑道入口',
    evaluate: 4.4,
    evaluateNum: 240,
  },
  {
    slug: 'blue-tears-ecology-tour',
    title: '馬祖藍眼淚生態體驗',
    description: '追尋神秘藍色螢光的生態之旅，專業導覽揭開藍眼淚的科學面紗。',
    content:
      '<p>藍眼淚是馬祖每年四月至九月出現的自然奇觀，由介形蟲（夜光蟲）受海浪刺激後發出藍色螢光。生態體驗由海洋生態專家帶領，前往最佳觀賞地點解說藍眼淚的成因、生態與觀賞技巧。在無光害的海岸邊，當浪花拍打礁岩激起滿天藍色星光，感動難以言喻。</p>',
    price: 800,
    originPrice: 1000,
    address: '連江縣南竿鄉（依當日海況選擇觀賞點）',
    category: 'package',
    coordinates: { lat: 26.15, lng: 119.9333 },
    imagePool: 'island',
    features: '藍眼淚,夜光蟲,生態導覽,海洋科學,季節限定,攝影教學',
    transport: '南竿各民宿接送至最佳觀賞地點',
    evaluate: 4.7,
    evaluateNum: 380,
  },
  {
    slug: 'beigan-battlefield-tour',
    title: '北竿戰地巡禮一日遊',
    description: '完整走訪北竿島的軍事據點與傳統聚落，感受戰地與人文的交織。',
    content:
      '<p>北竿戰地巡禮一日遊是認識北竿最深度的行程。從壁山觀景台出發，經戰爭和平紀念公園、08據點碉堡、螺山步道，再到芹壁聚落享用午餐。下午走訪橋仔聚落、大坵梅花鹿島（視航班而定）。全程由在地文史工作者導覽，含午餐及各景點門票。</p>',
    price: 2500,
    originPrice: 3200,
    address: '連江縣北竿鄉（白沙碼頭或機場集合）',
    category: 'package',
    coordinates: { lat: 26.1833, lng: 119.9667 },
    imagePool: 'island',
    features: '戰地巡禮,一日遊,文史導覽,含午餐,多景點,深度旅遊',
    transport: '北竿白沙碼頭或機場集合，提供全日交通',
    evaluate: 4.6,
    evaluateNum: 300,
  },
]
