import type { ProductDefinition } from "../types";

export const miaoliProducts: ProductDefinition[] = [
  {
    slug: "shengxing-station",
    title: "勝興車站懷舊之旅",
    description: "造訪台灣海拔最高的老火車站，漫步鐵道感受昔日山城風華。",
    content:
      "<p>勝興車站是西部縱貫鐵路最高點，海拔402.326公尺，日式木造站房保存完好。車站周邊有客家老街、手作體驗工坊，以及通往龍騰斷橋的步道，是三義最經典的旅遊起點。</p>",
    price: 800,
    originPrice: 1000,
    address: "苗栗縣三義鄉勝興村14鄰勝興89號",
    category: "package",
    coordinates: { lat: 24.348, lng: 120.778 },
    imagePool: "oldStreet",
    features: "日式車站,鐵道懷舊,客家文化,步道散策,手作體驗",
    transport: "自三義火車站搭乘免費接駁車約15分鐘，或自駕沿苗49線前往。",
    evaluate: 4.5,
    evaluateNum: 480,
  },
  {
    slug: "longteng-bridge",
    title: "龍騰斷橋歷史探索",
    description: "走訪1935年大地震遺留的紅磚拱橋遺跡，見證百年鐵道歷史。",
    content:
      "<p>龍騰斷橋又名魚藤坪斷橋，是1907年日治時期興建的磚造鐵道橋，因1935年關刀山大地震而斷裂。壯觀的紅磚拱橋殘跡矗立山谷間，已列為縣定古蹟，周邊設有步道與觀景台。</p>",
    price: 100,
    originPrice: 130,
    address: "苗栗縣三義鄉龍騰村",
    category: "tickets",
    coordinates: { lat: 24.342, lng: 120.781 },
    imagePool: "mountain",
    features: "百年古蹟,紅磚拱橋,地震遺跡,觀景步道,攝影景點",
    transport: "自勝興車站步行約20分鐘可達，或搭乘舊山線鐵道自行車。",
    evaluate: 4.4,
    evaluateNum: 390,
  },
  {
    slug: "nanzhuang-old-street",
    title: "南庄老街客家美食巡禮",
    description: "穿梭桂花巷品嚐客家小吃，體驗南庄山城的悠閒慢活。",
    content:
      "<p>南庄老街以桂花巷聞名，巷弄間飄散桂花香氣，沿途有客家麻糬、桂花釀、手工麵等在地美食。洗衫坑、乃木崎石階等歷史景點散布其中，充滿濃厚的客家風情。</p>",
    price: 900,
    originPrice: 1100,
    address: "苗栗縣南庄鄉中正路",
    category: "package",
    coordinates: { lat: 24.596, lng: 120.998 },
    imagePool: "oldStreet",
    features: "桂花巷,客家美食,手工麻糬,歷史建築,山城散策,含試吃",
    transport: "搭乘苗栗客運至南庄站下車即達，或由竹南火車站轉乘。",
    evaluate: 4.6,
    evaluateNum: 520,
  },
  {
    slug: "flying-cow-ranch",
    title: "飛牛牧場門票",
    description: "廣闊草原上與乳牛、羊群親密互動，享受苗栗通霄的田園風光。",
    content:
      "<p>飛牛牧場占地約50公頃，擁有大片翠綠草原、乳牛放牧區與多種小動物互動區。園區提供擠牛奶、奶酪DIY、彩繪等體驗活動，是親子出遊的首選牧場。</p>",
    price: 220,
    originPrice: 280,
    address: "苗栗縣通霄鎮南和里166號",
    category: "tickets",
    coordinates: { lat: 24.439, lng: 120.706 },
    imagePool: "nature",
    features: "牧場體驗,乳牛互動,DIY活動,大片草原,親子友善",
    transport: "自通霄火車站搭計程車約15分鐘，假日有接駁車（需預約）。",
    evaluate: 4.3,
    evaluateNum: 600,
  },
  {
    slug: "old-mountain-rail-bike",
    title: "舊山線鐵道自行車",
    description: "踩著鐵道自行車穿越隧道與高架橋，飽覽三義山城絕美風景。",
    content:
      "<p>舊山線鐵道自行車以勝興車站為起點，沿昔日鐵道路線行駛，穿越百年隧道、經過龍騰斷橋遺跡與高架鐵橋。全程約12公里，沿途山林翠綠、溪谷深幽，是全台最獨特的鐵道體驗。</p>",
    price: 250,
    originPrice: 300,
    address: "苗栗縣三義鄉勝興村14鄰勝興88號",
    category: "tickets",
    coordinates: { lat: 24.3478, lng: 120.7775 },
    imagePool: "mountain",
    features: "鐵道自行車,百年隧道,龍騰斷橋,山林美景,獨特體驗",
    transport: "自三義火車站搭乘接駁車至勝興車站，車程約15分鐘。",
    evaluate: 4.7,
    evaluateNum: 710,
  },
  {
    slug: "dahu-strawberry",
    title: "大湖採草莓體驗",
    description: "冬季限定！走入草莓園親手採摘鮮紅欲滴的大湖草莓。",
    content:
      "<p>苗栗大湖是台灣最大的草莓產地，每年12月至隔年4月為草莓季。走進溫室草莓園，親手採摘新鮮草莓，還可品嚐草莓大福、草莓香腸等創意美食，是冬季最甜蜜的旅行。</p>",
    price: 300,
    originPrice: 380,
    address: "苗栗縣大湖鄉富興村八寮灣2-4號",
    category: "tickets",
    coordinates: { lat: 24.422, lng: 120.863 },
    imagePool: "nature",
    features: "採草莓,季節限定,新鮮現採,草莓美食,親子體驗",
    transport: "搭乘苗栗客運至大湖站下車，步行約10分鐘至草莓園區。",
    evaluate: 4.5,
    evaluateNum: 550,
  },
  {
    slug: "sanyi-wood-sculpture-museum",
    title: "三義木雕博物館門票",
    description: "探索台灣木雕藝術之都，欣賞精湛的木雕創作與工藝演示。",
    content:
      "<p>三義木雕博物館是全台唯一以木雕為主題的公立博物館，館藏涵蓋傳統雕刻、現代藝術創作與東南亞木雕。定期舉辦木雕師現場示範，讓遊客近距離感受木藝之美。</p>",
    price: 80,
    originPrice: 100,
    address: "苗栗縣三義鄉廣盛村廣聲新城88號",
    category: "tickets",
    coordinates: { lat: 24.366, lng: 120.762 },
    imagePool: "museum",
    features: "木雕藝術,工藝展覽,現場示範,文化體驗,室內景點",
    transport: "自三義火車站步行約15分鐘即達。",
    evaluate: 4.2,
    evaluateNum: 280,
  },
  {
    slug: "mingde-reservoir",
    title: "明德水庫環湖自行車",
    description: "騎行於湖光山色間，經過日新島吊橋與水上教堂，盡享苗栗湖畔風情。",
    content:
      "<p>明德水庫位於頭屋鄉，湖面寬廣、四周青山環繞。環湖自行車道平緩易騎，沿途經過日新島、海棠島等水上景點，島上有咖啡廳與生態步道，是悠閒的半日遊路線。</p>",
    price: 700,
    originPrice: 900,
    address: "苗栗縣頭屋鄉明德路54號",
    category: "package",
    coordinates: { lat: 24.572, lng: 120.875 },
    imagePool: "nature",
    features: "環湖自行車,日新島,湖畔風光,含自行車租借,輕鬆騎行",
    transport: "自苗栗火車站搭乘苗栗客運至明德水庫站，車程約20分鐘。",
    evaluate: 4.3,
    evaluateNum: 230,
  },
  {
    slug: "tongxiao-shrine",
    title: "通霄神社日式古蹟導覽",
    description: "走訪保存完好的日治時期神社，感受和風建築之美。",
    content:
      "<p>通霄神社是苗栗少數保存完好的日治神社遺跡，鳥居、拜殿、參道石燈籠等構造皆保留原貌。神社坐落於虎頭山上，登頂後可遠眺通霄市區與台灣海峽，景色優美。</p>",
    price: 500,
    originPrice: 650,
    address: "苗栗縣通霄鎮虎頭山公園",
    category: "package",
    coordinates: { lat: 24.488, lng: 120.682 },
    imagePool: "temple",
    features: "日式神社,歷史古蹟,虎頭山,海景遠眺,專人導覽",
    transport: "自通霄火車站步行約15分鐘上山。",
    evaluate: 4.1,
    evaluateNum: 170,
  },
  {
    slug: "hakka-cultural-park",
    title: "苗栗客家文化園區門票",
    description: "沉浸式體驗客家文化，互動展覽與傳統建築一覽無遺。",
    content:
      "<p>苗栗客家文化園區是全台最大的客家文化展示中心，以現代建築融合傳統客家元素，設有常設展、特展、客家音樂戲曲館及兒童互動區。透過多媒體與實體展品，深入認識客家歷史與生活智慧。</p>",
    price: 150,
    originPrice: 200,
    address: "苗栗縣銅鑼鄉九湖村銅科南路6號",
    category: "tickets",
    coordinates: { lat: 24.446, lng: 120.783 },
    imagePool: "museum",
    features: "客家文化,互動展覽,傳統建築,兒童互動區,室內景點",
    transport: "搭乘苗栗客運至客家文化園區站下車，或自銅鑼火車站搭計程車約10分鐘。",
    evaluate: 4.4,
    evaluateNum: 420,
  },
  {
    slug: "huoyanshan",
    title: "火炎山登山健行",
    description: "挑戰苗栗著名的惡地地形，赤紅色礫岩山壁震撼視覺。",
    content:
      "<p>火炎山是苗栗三義與苑裡交界的自然保留區，以赤紅色礫岩惡地地形著稱。登山步道約3公里，沿途可見壯觀的尖峰、深溝與稜線，山頂視野遼闊可遠眺大安溪谷。</p>",
    price: 800,
    originPrice: 1000,
    address: "苗栗縣三義鄉火炎山自然保留區",
    category: "package",
    coordinates: { lat: 24.356, lng: 120.725 },
    imagePool: "mountain",
    features: "惡地地形,礫岩山壁,登山健行,自然保留區,專業嚮導,含保險",
    transport: "自三義火車站搭計程車約10分鐘至登山口。",
    evaluate: 4.5,
    evaluateNum: 320,
  },
  {
    slug: "tongluo-tea-garden",
    title: "銅鑼茶園品茗體驗",
    description: "漫步翠綠茶園，品嚐在地東方美人茶與客家茶點心。",
    content:
      "<p>銅鑼鄉是苗栗重要的茶產區，以東方美人茶聞名。茶園位於山坡地帶，梯田式茶園景觀優美。體驗內容包含茶園導覽、採茶體驗、揉茶製程解說與專業品茗，搭配客家茶點。</p>",
    price: 1000,
    originPrice: 1200,
    address: "苗栗縣銅鑼鄉新隆村",
    category: "package",
    coordinates: { lat: 24.454, lng: 120.801 },
    imagePool: "tea",
    features: "茶園體驗,東方美人茶,採茶揉茶,品茗教學,客家茶點",
    transport: "自銅鑼火車站搭計程車約10分鐘。",
    evaluate: 4.6,
    evaluateNum: 260,
  },
  {
    slug: "zhuolan-gorge",
    title: "卓蘭大安溪峽谷探險",
    description: "走入台灣版大峽谷，壯觀的溪谷地形令人驚嘆。",
    content:
      "<p>大安溪峽谷因921地震河床抬升而形成，深達數十公尺的峽谷地形被譽為台灣版大峽谷。赤褐色岩壁與蜿蜒溪流構成壯觀景象，是地質愛好者與攝影師的必訪之地。</p>",
    price: 1200,
    originPrice: 1500,
    address: "苗栗縣卓蘭鎮大安溪畔",
    category: "package",
    coordinates: { lat: 24.314, lng: 120.823 },
    imagePool: "mountain",
    features: "峽谷探險,地質景觀,溪谷健行,專業嚮導,含接駁,含保險",
    transport: "卓蘭鎮市區集合，由專車接駁至峽谷入口。",
    evaluate: 4.4,
    evaluateNum: 190,
  },
  {
    slug: "sheipa-visitor-center",
    title: "雪霸國家公園汶水遊客中心",
    description: "認識雪霸國家公園的自然生態，規劃登山行程的最佳起點。",
    content:
      "<p>汶水遊客中心是雪霸國家公園的主要服務據點，館內設有生態展示廳、視聽室與雪霸登山資訊站。周邊有八角亭步道與生態池，可輕鬆認識中海拔動植物生態。</p>",
    price: 100,
    originPrice: 120,
    address: "苗栗縣大湖鄉富興村水尾坪100號",
    category: "tickets",
    coordinates: { lat: 24.431, lng: 120.887 },
    imagePool: "mountain",
    features: "國家公園,生態展示,登山資訊,步道散策,自然教育",
    transport: "自大湖站搭乘苗栗客運至汶水站下車步行約5分鐘。",
    evaluate: 4.1,
    evaluateNum: 210,
  },
  {
    slug: "houlong-haowanjiao",
    title: "後龍好望角海景步道",
    description: "站在西海岸制高點，俯瞰風車群與壯闊的台灣海峽日落。",
    content:
      "<p>好望角位於後龍鎮半天寮，是苗栗西海岸的制高點。稜線步道兩側視野開闊，一面是整排白色風力發電機與蔚藍海岸，另一面是翠綠稻田與鐵道。日落時分景色尤為壯觀。</p>",
    price: 500,
    originPrice: 650,
    address: "苗栗縣後龍鎮半天寮",
    category: "package",
    coordinates: { lat: 24.61, lng: 120.712 },
    imagePool: "nature",
    features: "海景步道,風車群,日落美景,稜線步道,攝影景點",
    transport: "自後龍火車站搭計程車約15分鐘至步道入口。",
    evaluate: 4.6,
    evaluateNum: 380,
  },
  {
    slug: "taian-hot-spring",
    title: "泰安溫泉湯屋體驗",
    description: "隱身山林間的碳酸氫鈉美人湯，洗去旅途疲憊。",
    content:
      "<p>泰安溫泉位於苗栗泰安鄉山區，泉質為碳酸氫鈉泉（俗稱美人湯），水質清澈無味，對皮膚有滋潤效果。湯屋依山傍溪，在蟲鳴鳥叫中享受溫泉，是苗栗最療癒的體驗。</p>",
    price: 1500,
    originPrice: 1800,
    address: "苗栗縣泰安鄉錦水村",
    category: "package",
    coordinates: { lat: 24.458, lng: 120.92 },
    imagePool: "hotSpring",
    features: "碳酸氫鈉泉,美人湯,山林湯屋,溪畔風光,療癒體驗",
    transport: "自苗栗火車站搭乘苗栗客運至泰安溫泉站，車程約50分鐘。",
    evaluate: 4.7,
    evaluateNum: 450,
  },
  {
    slug: "zhunan-brewery",
    title: "竹南啤酒廠觀光導覽",
    description: "參觀全台最大啤酒廠，了解釀造過程並品嚐新鮮生啤。",
    content:
      "<p>竹南啤酒廠是台灣菸酒公司旗下最大的啤酒生產基地，提供免費工廠導覽，可參觀自動化產線、了解啤酒釀造工序，導覽結束還能品嚐剛出廠的新鮮生啤酒。</p>",
    price: 200,
    originPrice: 250,
    address: "苗栗縣竹南鎮和仁路2號",
    category: "tickets",
    coordinates: { lat: 24.683, lng: 120.878 },
    imagePool: "city",
    features: "啤酒廠導覽,釀造體驗,生啤品嚐,免費參觀,伴手禮",
    transport: "自竹南火車站搭計程車約5分鐘，或步行約20分鐘。",
    evaluate: 4.0,
    evaluateNum: 340,
  },
  {
    slug: "miaoli-railway-museum",
    title: "苗栗鐵道文物展示館門票",
    description: "鐵道迷必訪！近距離觀賞蒸汽火車頭與珍貴鐵道文物。",
    content:
      "<p>苗栗鐵道文物展示館位於苗栗火車站旁，館內展示多輛退役蒸汽機車與柴電機車，以及號誌燈、車票等珍貴鐵道文物。戶外展區可近距離接觸實體列車，是鐵道迷的朝聖地。</p>",
    price: 80,
    originPrice: 100,
    address: "苗栗縣苗栗市北苗里鐵路一村1號",
    category: "tickets",
    coordinates: { lat: 24.57, lng: 120.822 },
    imagePool: "museum",
    features: "蒸汽火車,鐵道文物,戶外展區,拍照打卡,免費景點",
    transport: "苗栗火車站步行約3分鐘即達。",
    evaluate: 4.0,
    evaluateNum: 190,
  },
  {
    slug: "xihu-resort",
    title: "西湖渡假村門票",
    description: "歐式花園、生態步道與遊樂設施，適合全家同遊的複合式渡假村。",
    content:
      "<p>西湖渡假村結合歐式花園、森林步道與多種遊樂設施，園區內四季花卉綻放，春季更有油桐花盛開。設有DIY教室、小火車、迷宮等親子設施，是苗栗老字號的渡假勝地。</p>",
    price: 399,
    originPrice: 500,
    address: "苗栗縣三義鄉西湖村西湖11號",
    category: "tickets",
    coordinates: { lat: 24.38, lng: 120.75 },
    imagePool: "park",
    features: "歐式花園,遊樂設施,油桐花季,生態步道,親子友善",
    transport: "自三義火車站搭計程車約10分鐘，假日有免費接駁車。",
    evaluate: 3.9,
    evaluateNum: 360,
  },
  {
    slug: "sanwan-落羽松",
    title: "三灣落羽松秘境漫遊",
    description: "季節限定的夢幻落羽松林，水面倒影如詩如畫。",
    content:
      "<p>三灣落羽松秘境位於北埔溪旁，數百株落羽松在秋冬季節轉紅，水面映照金黃橘紅的樹影，宛如北歐風景畫。春夏則呈現翠綠色澤，四季各有風情，是攝影愛好者的私房景點。</p>",
    price: 600,
    originPrice: 750,
    address: "苗栗縣三灣鄉內灣村",
    category: "package",
    coordinates: { lat: 24.634, lng: 120.956 },
    imagePool: "nature",
    features: "落羽松林,水面倒影,季節變色,攝影秘境,含導覽解說",
    transport: "自竹南火車站搭苗栗客運至三灣站，轉乘計程車約10分鐘。",
    evaluate: 4.3,
    evaluateNum: 240,
  },
];
