import type { ProductDefinition } from '../types'

export const nantouProducts: ProductDefinition[] = [
  {
    slug: 'sun-moon-lake-boat-ticket',
    title: '日月潭遊湖船票',
    description: '搭乘遊湖船暢遊日月潭三大碼頭，飽覽湖光山色與邵族文化風情。',
    content:
      '<p>日月潭是台灣最具代表性的高山湖泊，搭乘遊湖船從水社碼頭出發，途經玄光寺碼頭與伊達邵碼頭，沿途欣賞拉魯島、慈恩塔等經典地標。船上提供中英文導覽解說，讓您深入了解日月潭的自然生態與邵族傳說故事。</p>',
    price: 300,
    originPrice: 400,
    address: '南投縣魚池鄉中山路163號',
    category: 'tickets',
    coordinates: { lat: 23.8491, lng: 120.9155 },
    imagePool: 'nature',
    features: '遊湖船票,三大碼頭停靠,中英文導覽,自由上下船,湖景觀賞',
    transport: '搭乘台灣好行日月潭線至水社遊客中心下車，步行約3分鐘至水社碼頭',
    evaluate: 4.6,
    evaluateNum: 723,
  },
  {
    slug: 'cingjing-farm-ticket',
    title: '清境農場入園門票',
    description: '漫步在海拔1750公尺的高山牧場，觀賞綿羊秀與馬術表演。',
    content:
      '<p>清境農場位於南投仁愛鄉，擁有「霧上桃源」的美譽。園區內青青草原上綿羊成群，每日定時的綿羊秀與馬術表演是必看亮點。壯麗的合歡山群峰環繞，四季皆有不同風貌，春櫻夏綠秋楓冬雪，是台灣最受歡迎的高山農場。</p>',
    price: 200,
    originPrice: 250,
    address: '南投縣仁愛鄉仁和路170號',
    category: 'tickets',
    coordinates: { lat: 24.0594, lng: 121.1625 },
    imagePool: 'mountain',
    features: '青青草原,綿羊秀表演,馬術秀,觀山步道,高山花卉',
    transport: '搭乘南投客運至清境農場站下車即達',
    evaluate: 4.5,
    evaluateNum: 650,
  },
  {
    slug: 'xitou-nature-education-area',
    title: '溪頭自然教育園區門票',
    description: '走進千年神木與竹林環繞的森林步道，享受芬多精洗禮。',
    content:
      '<p>溪頭自然教育園區由台灣大學實驗林管處經營，園區內擁有超過2,800年的紅檜神木、大學池、銀杏林等著名景點。全長數公里的森林步道穿梭於杉木與竹林之間，空氣中瀰漫著豐沛的芬多精，是絕佳的森林浴場所。</p>',
    price: 200,
    originPrice: 250,
    address: '南投縣鹿谷鄉森林巷9號',
    category: 'tickets',
    coordinates: { lat: 23.6718, lng: 120.797 },
    imagePool: 'nature',
    features: '千年神木,大學池,銀杏林,森林步道,自然生態解說',
    transport: '搭乘員林客運或台中客運至溪頭站下車即達園區入口',
    evaluate: 4.4,
    evaluateNum: 512,
  },
  {
    slug: 'formosan-aboriginal-culture-village',
    title: '九族文化村門票套票',
    description: '結合原住民文化體驗與刺激遊樂設施的大型主題樂園。',
    content:
      '<p>九族文化村是台灣知名的主題樂園，園區完整呈現台灣十六族原住民的傳統建築、文化祭典與生活樣貌。同時擁有多項刺激的遊樂設施，包含自由落體、馬雅探險等。每年二月的九族櫻花祭更是不可錯過的年度盛事，夜間櫻花燈飾浪漫迷人。</p>',
    price: 780,
    originPrice: 900,
    address: '南投縣魚池鄉金天巷45號',
    category: 'tickets',
    coordinates: { lat: 23.8722, lng: 120.9308 },
    imagePool: 'park',
    features: '原住民文化展演,遊樂設施,櫻花祭,纜車搭乘,文化表演',
    transport: '搭乘台灣好行日月潭線至九族文化村站下車',
    evaluate: 4.3,
    evaluateNum: 489,
  },
  {
    slug: 'hehuanshan-sunrise-tour',
    title: '合歡山日出觀星二日遊',
    description: '登上台灣公路最高點，白天賞雲海夕陽，夜晚仰望銀河星空。',
    content:
      '<p>合歡山是台灣最容易親近的百岳之一，海拔3,417公尺的主峰有完善的步道設施。此行程包含專車接送、專業嚮導帶領觀賞日出雲海、高山杜鵑花海（春季限定），以及暗空公園的星空導覽。冬季更有機會欣賞銀白雪景，是四季皆宜的高山體驗。</p>',
    price: 3800,
    originPrice: 4500,
    address: '南投縣仁愛鄉合歡山主峰步道',
    category: 'package',
    coordinates: { lat: 24.1436, lng: 121.2719 },
    imagePool: 'mountain',
    features: '日出雲海,觀星導覽,專車接送,專業嚮導,高山生態解說,住宿一晚',
    transport: '台中高鐵站集合，專車沿台14甲線直達合歡山',
    evaluate: 4.8,
    evaluateNum: 356,
  },
  {
    slug: 'shanlinxi-forest-resort',
    title: '杉林溪森林生態渡假園區一日遊',
    description: '深入海拔1600公尺的原始森林，飽覽瀑布花海與四季變幻美景。',
    content:
      '<p>杉林溪森林生態渡假園區佔地廣達40公頃，園區內松瀧岩瀑布氣勢磅礴，石井磯天然壺穴地形獨特。四季花卉輪番綻放——春季牡丹、夏季繡球、秋季楓紅、冬季山茶。藥花園步道平緩好走，適合全家大小一同探索森林之美。</p>',
    price: 1200,
    originPrice: 1500,
    address: '南投縣竹山鎮大鞍里溪山路6號',
    category: 'package',
    coordinates: { lat: 23.6349, lng: 120.7432 },
    imagePool: 'nature',
    features: '松瀧岩瀑布,花卉園區,森林步道,專車接駁,午餐便當,導覽解說',
    transport: '台中干城站搭乘員林客運至杉林溪，車程約3.5小時',
    evaluate: 4.5,
    evaluateNum: 398,
  },
  {
    slug: 'jiji-station-cycling',
    title: '集集車站懷舊鐵道自行車之旅',
    description: '騎乘自行車穿越綠色隧道，探訪台灣最美的小鎮火車站。',
    content:
      '<p>集集車站建於1933年，是全台少數保留的木造車站之一，也是921地震後重建的歷史地標。此行程提供自行車租借，沿著集集綠色隧道騎行，兩旁樟樹夾道成蔭。途中可造訪軍史公園、明新書院、特有生物研究保育中心等景點，感受小鎮的悠閒氛圍。</p>',
    price: 650,
    originPrice: 800,
    address: '南投縣集集鎮民生路75號',
    category: 'package',
    coordinates: { lat: 23.8283, lng: 120.6839 },
    imagePool: 'oldStreet',
    features: '木造車站巡禮,綠色隧道騎行,自行車租借,小鎮導覽,在地小吃',
    transport: '搭乘集集支線火車至集集站下車即達',
    evaluate: 4.3,
    evaluateNum: 287,
  },
  {
    slug: 'puli-brewery-tour',
    title: '埔里酒廠品酒文化巡禮',
    description: '參觀台灣紹興酒發源地，品嚐紹興冰棒與酒香美食。',
    content:
      '<p>埔里酒廠創立於1917年，以埔里甘甜的愛蘭泉水釀造出聞名全台的紹興酒。廠區內設有酒文化館，展示百年釀酒歷史與製程。必嚐的紹興冰棒、紹興香腸與紹興滷味是到訪遊客的最愛。酒廠商品區還可選購各式酒類伴手禮。</p>',
    price: 150,
    originPrice: 200,
    address: '南投縣埔里鎮中山路三段219號',
    category: 'tickets',
    coordinates: { lat: 23.9646, lng: 120.9684 },
    imagePool: 'oldStreet',
    features: '酒文化館導覽,紹興冰棒品嚐,釀酒製程參觀,伴手禮選購',
    transport: '搭乘南投客運至埔里站，步行約10分鐘',
    evaluate: 4.1,
    evaluateNum: 356,
  },
  {
    slug: 'torii-restaurant-experience',
    title: '鳥居Torii喫茶食堂用餐體驗',
    description: '在日式鳥居庭園中品味精緻和風料理，感受濃厚的日本風情。',
    content:
      '<p>鳥居Torii喫茶食堂位於埔里市區，以大型紅色鳥居與日式庭園造景著稱，是南投超人氣的打卡餐廳。餐廳供應精緻的日式定食、烏龍麵、抹茶甜點等料理，搭配園區內的浴衣體驗與祈福繪馬，讓人彷彿置身日本京都。</p>',
    price: 580,
    originPrice: 700,
    address: '南投縣埔里鎮公誠路86號',
    category: 'package',
    coordinates: { lat: 23.9596, lng: 120.9622 },
    imagePool: 'temple',
    features: '日式庭園,和風料理套餐,浴衣體驗,鳥居打卡,抹茶甜點',
    transport: '搭乘南投客運至埔里站，步行約15分鐘或轉乘計程車',
    evaluate: 4.2,
    evaluateNum: 423,
  },
  {
    slug: 'sun-moon-lake-ropeway',
    title: '日月潭纜車來回票',
    description: '搭乘纜車從伊達邵飛越山巒直達九族文化村，鳥瞰日月潭全景。',
    content:
      '<p>日月潭纜車全長1,877公尺，連接日月潭伊達邵與九族文化村，單程約7分鐘。透明車廂高掛山谷之間，可360度鳥瞰日月潭碧綠湖面與周圍群山。晴天時視野遼闊，能將整個魚池盆地盡收眼底，是來日月潭不可錯過的空中體驗。</p>',
    price: 350,
    originPrice: 400,
    address: '南投縣魚池鄉中正路102號',
    category: 'tickets',
    coordinates: { lat: 23.8625, lng: 120.9345 },
    imagePool: 'nature',
    features: '空中纜車,日月潭全景,來回票,透明車廂可選,九族文化村聯票',
    transport: '搭乘台灣好行日月潭線至伊達邵站，步行約5分鐘至纜車站',
    evaluate: 4.5,
    evaluateNum: 567,
  },
  {
    slug: 'chung-tai-chan-monastery',
    title: '中台禪寺參觀導覽',
    description: '探訪台灣最宏偉的現代佛教建築，感受莊嚴的禪修氛圍。',
    content:
      '<p>中台禪寺由惟覺老和尚創建，是台灣最具規模的現代佛教建築之一。建築融合中西方設計元素，外觀氣勢恢宏，內部金碧輝煌。大雄寶殿的四大天王像以山西黑花崗岩雕刻而成，萬佛殿更供奉了上萬尊小型佛像，藝術價值極高。</p>',
    price: 100,
    originPrice: 120,
    address: '南投縣埔里鎮中台路2號',
    category: 'tickets',
    coordinates: { lat: 24.0028, lng: 120.9377 },
    imagePool: 'temple',
    features: '現代佛教建築,專人導覽,四大天王石雕,萬佛殿,禪修體驗',
    transport: '搭乘南投客運至中台禪寺站下車即達',
    evaluate: 4.4,
    evaluateNum: 312,
  },
  {
    slug: 'monster-village-tour',
    title: '妖怪村主題探索之旅',
    description: '走進日式妖怪主題商圈，品嚐咬人貓麵包與各式創意小吃。',
    content:
      '<p>妖怪村位於溪頭森林遊樂區入口處，以日式建築搭配各種妖怪裝置藝術打造出獨特的主題商圈。這裡最著名的咬人貓麵包每日限量出爐，總是大排長龍。商圈內還有妖怪郵局、妖怪柑仔店等趣味店鋪，夜晚點燈後更添神秘氛圍。</p>',
    price: 550,
    originPrice: 650,
    address: '南投縣鹿谷鄉內湖村興產路2-3號',
    category: 'package',
    coordinates: { lat: 23.6761, lng: 120.7952 },
    imagePool: 'oldStreet',
    features: '妖怪主題商圈,咬人貓麵包,日式建築巡禮,創意小吃,夜間點燈',
    transport: '搭乘員林客運至溪頭站，步行約2分鐘',
    evaluate: 4.0,
    evaluateNum: 445,
  },
  {
    slug: 'paper-dome-experience',
    title: '紙教堂園區體驗門票',
    description: '在埔里桃米生態村欣賞來自日本的紙管建築藝術與生態之美。',
    content:
      '<p>紙教堂原為日本阪神大地震後在神戶鷹取教會建造的臨時教堂，後來移建至南投埔里桃米社區，成為921震後社區重建的精神象徵。教堂以58根紙管支撐，內部光線通透柔和。周邊的桃米生態村以豐富的蛙類生態著稱，是生態旅遊的絕佳去處。</p>',
    price: 120,
    originPrice: 150,
    address: '南投縣埔里鎮桃米巷52-12號',
    category: 'tickets',
    coordinates: { lat: 23.9423, lng: 120.9277 },
    imagePool: 'park',
    features: '紙管建築藝術,生態園區,桃米社區,蛙類觀察,文創商品',
    transport: '搭乘南投客運至桃米坑站，步行約10分鐘',
    evaluate: 4.2,
    evaluateNum: 234,
  },
  {
    slug: 'wangyou-forest-hiking',
    title: '忘憂森林秘境健行之旅',
    description: '深入海拔2000公尺的夢幻枯木沼澤，拍攝如仙境般的絕美景致。',
    content:
      '<p>忘憂森林位於杉林溪附近，因921地震堰塞而形成的高山沼澤，枯立的杉木倒映在碧綠水面上，雲霧繚繞時宛如人間仙境。此行程包含專業嚮導帶領、接駁車服務、健行裝備建議與午餐便當，讓您安全又盡興地探訪這處台灣秘境。</p>',
    price: 1500,
    originPrice: 1800,
    address: '南投縣竹山鎮大鞍里溪山路3號',
    category: 'package',
    coordinates: { lat: 23.6449, lng: 120.725 },
    imagePool: 'nature',
    features: '秘境健行,枯木沼澤,攝影導覽,接駁車服務,午餐便當,專業嚮導',
    transport: '於杉林溪公路12K處集合，搭乘接駁車上山',
    evaluate: 4.7,
    evaluateNum: 198,
  },
  {
    slug: 'xiangshan-visitor-center',
    title: '向山遊客中心建築巡禮',
    description: '欣賞日本建築大師團紀彥設計的清水模地景建築，免費入場。',
    content:
      '<p>向山遊客中心由日本建築師團紀彥設計，以「環抱日月潭」為概念，兩棟彎曲的清水混凝土建築巧妙融入湖畔地景。頂樓觀景台可眺望日月潭全景，一樓展示南投在地文化與生態資訊。周邊的自行車道是環湖騎行的絕佳起點。</p>',
    price: 80,
    originPrice: 100,
    address: '南投縣魚池鄉中山路599號',
    category: 'tickets',
    coordinates: { lat: 23.8384, lng: 120.9005 },
    imagePool: 'nature',
    features: '清水模建築,觀景台,日月潭湖景,自行車租借,文化展覽',
    transport: '搭乘台灣好行日月潭線至向山遊客中心站下車',
    evaluate: 4.3,
    evaluateNum: 276,
  },
  {
    slug: 'shuili-snake-kiln',
    title: '水里蛇窯陶藝DIY體驗',
    description: '在台灣現存最古老的柴燒窯場親手製作陶藝作品。',
    content:
      '<p>水里蛇窯建於1927年，是台灣現存最古老且仍在運作的柴燒窯，因窯身順著山坡蜿蜒如蛇而得名。園區內可參觀傳統製陶流程、欣賞陶藝大師作品，更能親自體驗手拉坯或捏陶DIY，製作專屬於自己的陶藝紀念品。</p>',
    price: 650,
    originPrice: 800,
    address: '南投縣水里鄉回窯路16號',
    category: 'package',
    coordinates: { lat: 23.8175, lng: 120.847 },
    imagePool: 'oldStreet',
    features: '百年蛇窯參觀,手拉坯DIY,捏陶體驗,陶藝展覽,在地文化導覽',
    transport: '搭乘員林客運至水里站，轉乘計程車約10分鐘',
    evaluate: 4.4,
    evaluateNum: 189,
  },
  {
    slug: 'checheng-station-tour',
    title: '車埕車站木業文化深度之旅',
    description: '探訪集集支線終點站，漫步在充滿木業歷史的懷舊小鎮。',
    content:
      '<p>車埕車站是集集支線鐵路的最後一站，素有「最後的火車站」之稱。日治時期因伐木業興盛而繁華一時，如今保留了許多木業遺跡。車埕木業展示館、貯木池、老街等景點值得細細品味。此行程包含導覽解說、木工DIY體驗與在地特色午餐。</p>',
    price: 900,
    originPrice: 1100,
    address: '南投縣水里鄉車埕村民權巷127號',
    category: 'package',
    coordinates: { lat: 23.833, lng: 120.8655 },
    imagePool: 'oldStreet',
    features: '木造車站,木業展示館,貯木池,木工DIY,懷舊老街,特色午餐',
    transport: '搭乘集集支線火車至車埕站（終點站）',
    evaluate: 4.3,
    evaluateNum: 267,
  },
  {
    slug: 'caotun-craft-museum',
    title: '南投草屯工藝館參觀體驗',
    description: '認識台灣傳統工藝之美，參與竹編、漆藝等手作體驗。',
    content:
      '<p>國立臺灣工藝研究發展中心位於草屯，是全台最重要的工藝推廣基地。園區內展示竹編、陶藝、漆器、染織等各類傳統與現代工藝作品。定期舉辦手作體驗課程，遊客可親自嘗試竹編、藍染等工藝創作，是兼具教育與休閒的文化景點。</p>',
    price: 500,
    originPrice: 600,
    address: '南投縣草屯鎮中正路573號',
    category: 'package',
    coordinates: { lat: 23.9741, lng: 120.6839 },
    imagePool: 'museum',
    features: '工藝展覽,竹編體驗,漆藝創作,藍染DIY,文創商品,園區導覽',
    transport: '搭乘南投客運至草屯站，步行約5分鐘',
    evaluate: 4.1,
    evaluateNum: 156,
  },
  {
    slug: 'sanyu-christian-college',
    title: '三育基督書院校園漫步',
    description: '漫步在綠草如茵的歐式校園，感受寧靜優美的書院氛圍。',
    content:
      '<p>三育基督書院位於魚池鄉，校園佔地廣大且綠意盎然，筆直的林蔭大道兩旁種滿落羽松與樟樹，每到秋冬時節變色時分外美麗。歐式建築點綴在大片草坪之間，是南投知名的拍照打卡勝地，也是許多偶像劇的取景地點。</p>',
    price: 100,
    originPrice: 130,
    address: '南投縣魚池鄉瓊文巷39號',
    category: 'tickets',
    coordinates: { lat: 23.8867, lng: 120.928 },
    imagePool: 'park',
    features: '歐式校園,林蔭大道,落羽松,草坪散步,攝影取景',
    transport: '搭乘台灣好行日月潭線至三育基督書院站下車',
    evaluate: 4.2,
    evaluateNum: 198,
  },
  {
    slug: 'sun-moon-lake-cycling',
    title: '日月潭環湖自行車悠遊之旅',
    description: '騎乘全球十大最美自行車道，環繞日月潭飽覽湖光山色。',
    content:
      '<p>日月潭環湖自行車道曾獲CNN評選為全球十大最美自行車道之一，全長約30公里。本行程提供高品質自行車租借與專業導覽，沿途經過向山遊客中心、水社壩、月牙灣等絕美路段，中途安排在地小吃休憩站，讓您輕鬆愜意地完成環湖壯舉。</p>',
    price: 800,
    originPrice: 1000,
    address: '南投縣魚池鄉中山路163號',
    category: 'package',
    coordinates: { lat: 23.8491, lng: 120.9155 },
    imagePool: 'nature',
    features: '全球十大最美車道,自行車租借,環湖導覽,在地小吃,月牙灣,向山段',
    transport: '搭乘台灣好行日月潭線至水社遊客中心，步行至自行車租借站',
    evaluate: 4.7,
    evaluateNum: 445,
  },
  {
    slug: 'wujie-tribal-adventure',
    title: '武界部落秘境探索之旅',
    description: '深入布農族傳統部落，探訪雲的故鄉與壯麗峽谷瀑布。',
    content:
      '<p>武界部落位於南投仁愛鄉，是布農族的傳統領域，因雲海繚繞而有「雲的故鄉」之美名。行程包含部落文化導覽、武界壩水庫探訪、摩摩納爾瀑布健行，以及品嚐部落風味餐。清晨的武界雲海與曙光交織，美景令人屏息。</p>',
    price: 2500,
    originPrice: 3000,
    address: '南投縣仁愛鄉法治村界山巷',
    category: 'package',
    coordinates: { lat: 24.0413, lng: 121.1044 },
    imagePool: 'mountain',
    features: '布農族文化,雲海觀賞,瀑布健行,部落風味餐,專業嚮導,水庫探訪',
    transport: '埔里市區集合，專車接送進入部落（山路約40分鐘）',
    evaluate: 4.8,
    evaluateNum: 167,
  },
  {
    slug: 'aowanda-forest-recreation',
    title: '奧萬大國家森林遊樂區門票',
    description: '走訪台灣楓葉故鄉，秋季楓紅層層疊疊美不勝收。',
    content:
      '<p>奧萬大國家森林遊樂區海拔約1,100至2,600公尺，是台灣最負盛名的賞楓勝地。園區內的楓林步道、松林區、瀑布群各有特色，秋季時青楓、紅榨槭交織出層次豐富的紅黃橙色彩。春天的櫻花與夏季的螢火蟲也同樣令人驚艷。</p>',
    price: 200,
    originPrice: 250,
    address: '南投縣仁愛鄉親愛村大安路153號',
    category: 'tickets',
    coordinates: { lat: 24.0028, lng: 121.1723 },
    imagePool: 'nature',
    features: '楓林步道,瀑布群,吊橋,森林浴,賞鳥,生態導覽',
    transport: '搭乘南投客運至霧社站，轉乘接駁車或計程車約40分鐘',
    evaluate: 4.5,
    evaluateNum: 334,
  },
  {
    slug: 'cingjing-skywalk',
    title: '清境天空步道門票',
    description: '漫步在海拔1700公尺的高架步道，腳下是壯闘山谷與翠綠牧場。',
    content:
      '<p>清境高空觀景步道全長1.6公里，海拔約1,700公尺，是全台最高的景觀步道。步道採高架設計，沿途穿越樹冠層，可近距離觀賞奇萊山、合歡山等高山群峰。晴天時視野可達百公里，雲霧繚繞時則有漫步雲端的奇幻感受。</p>',
    price: 50,
    originPrice: 80,
    address: '南投縣仁愛鄉仁和路186-1號',
    category: 'tickets',
    coordinates: { lat: 24.056, lng: 121.159 },
    imagePool: 'mountain',
    features: '高空步道,山景觀賞,雲端漫步,合歡山群峰,清境農場連通',
    transport: '搭乘南投客運至清境農場站，步行約5分鐘至步道入口',
    evaluate: 4.3,
    evaluateNum: 478,
  },
  {
    slug: 'lugu-tea-experience',
    title: '鹿谷茶園品茗採茶體驗',
    description: '親手採摘凍頂烏龍茶，學習傳統製茶工藝與茶道文化。',
    content:
      '<p>鹿谷鄉是台灣凍頂烏龍茶的故鄉，茶園分佈在海拔600至1200公尺的山區。此體驗行程帶您走入翠綠茶園親手採茶，接著在製茶師傅指導下學習萎凋、揉捻、烘焙等工序。品茗時光中，茶藝師會教授正統泡茶技巧，讓您帶走自己親製的茶葉。</p>',
    price: 1200,
    originPrice: 1500,
    address: '南投縣鹿谷鄉中正路一段231號',
    category: 'package',
    coordinates: { lat: 23.7535, lng: 120.7521 },
    imagePool: 'tea',
    features: '採茶體驗,製茶工藝,品茗教學,茶園導覽,自製茶葉帶回,茶道文化',
    transport: '搭乘員林客運至鹿谷站，由茶園專車接送',
    evaluate: 4.6,
    evaluateNum: 223,
  },
  {
    slug: 'changhua-sky-bridge',
    title: '猴探井天空之橋門票',
    description: '走過全長204公尺的微笑天梯吊橋，俯瞰彰化平原與八卦山美景。',
    content:
      '<p>猴探井天空之橋位於南投與彰化交界的八卦山脈上，全長204公尺，橋面距谷底約70公尺。吊橋造型優美如微笑弧線，行走其上可俯瞰彰化平原的田園風光。橋的兩端設有觀景平台，天氣晴朗時可遠眺台灣海峽，是南投熱門的打卡景點。</p>',
    price: 80,
    originPrice: 100,
    address: '南投縣南投市猴探井街300號',
    category: 'tickets',
    coordinates: { lat: 23.9172, lng: 120.5833 },
    imagePool: 'mountain',
    features: '微笑天梯,俯瞰平原,觀景平台,八卦山步道,打卡拍照',
    transport: '搭乘彰化客運至猴探井站下車，步行約5分鐘',
    evaluate: 3.9,
    evaluateNum: 345,
  },
]
