import type { ProductDefinition } from '../types'

export const newTaipeiProducts: ProductDefinition[] = [
  {
    slug: 'jiufen-old-street',
    title: '九份老街',
    description: '山城石階與紅燈籠交織的懷舊風情，宮崎駿動畫靈感來源之一。',
    content:
      '<p>九份老街依山而建，蜿蜒的石階兩旁掛滿紅燈籠，入夜後的山城景致充滿魔幻氛圍。基山街上芋圓、草仔粿、魚丸等傳統美食琳瑯滿目，豎崎路的茶樓可眺望基隆山與太平洋。假日人潮擁擠，建議平日或傍晚前往最能感受山城之美。</p>',
    price: 799,
    originPrice: 999,
    address: '新北市瑞芳區基山街',
    category: 'package',
    coordinates: { lat: 25.1094, lng: 121.8444 },
    imagePool: 'oldStreet',
    features: '山城風情,紅燈籠,芋圓美食,茶樓眺望,懷舊氛圍,攝影勝地',
    transport: '搭乘台鐵至瑞芳站，轉乘788或1062公車至九份老街站',
    evaluate: 4.6,
    evaluateNum: 723,
  },
  {
    slug: 'yehliu-geopark',
    title: '野柳地質公園',
    description: '世界級海蝕奇岩地景，女王頭與燭台石是大自然的鬼斧神工。',
    content:
      '<p>野柳地質公園位於北海岸，擁有全球罕見的海蝕地形景觀。園區內女王頭、仙女鞋、燭台石等奇岩怪石歷經千萬年風化侵蝕而成，每一塊岩石都是大自然的藝術品。步道沿海岸線規劃完善，可近距離觀賞壯觀的地質奇觀。</p>',
    price: 120,
    originPrice: 150,
    address: '新北市萬里區野柳里港東路167-1號',
    category: 'tickets',
    coordinates: { lat: 25.2058, lng: 121.6907 },
    imagePool: 'beach',
    features: '女王頭,海蝕地形,地質奇觀,世界級景觀,海岸步道,自然教育',
    transport: '搭乘國光客運1815至野柳站，或從基隆搭乘790公車',
    evaluate: 4.7,
    evaluateNum: 654,
  },
  {
    slug: 'pingxi-sky-lantern',
    title: '平溪天燈',
    description: '將心願寫上天燈緩緩升空，全球最浪漫的祈福體驗之一。',
    content:
      '<p>平溪放天燈是台灣最具代表性的民俗活動，被CNN評選為全球最浪漫的節慶之一。在天燈上寫下心願，點燃後看著它緩緩升向夜空，感動難以言喻。平日也可體驗放天燈，搭配平溪老街的鐵道風情與山城美景，是深度體驗台灣文化的絕佳行程。</p>',
    price: 650,
    originPrice: 800,
    address: '新北市平溪區平溪街',
    category: 'package',
    coordinates: { lat: 25.0258, lng: 121.7383 },
    imagePool: 'oldStreet',
    features: '天燈祈福,鐵道風情,山城老街,浪漫體驗,民俗文化,CNN推薦',
    transport: '搭乘台鐵至瑞芳站，轉乘平溪支線至平溪站',
    evaluate: 4.7,
    evaluateNum: 567,
  },
  {
    slug: 'shifen-waterfall',
    title: '十分瀑布',
    description: '台灣版尼加拉瀑布，寬40公尺簾幕式瀑布氣勢磅礴。',
    content:
      '<p>十分瀑布是台灣最大的簾幕式瀑布，落差約20公尺、寬約40公尺，水量豐沛時水霧瀰漫、彩虹隱現。從十分遊客中心沿步道步行約15分鐘即可抵達觀瀑平台。園區內生態豐富，沿途可見翠綠溪谷與多種蝴蝶，是夏日消暑的絕佳去處。</p>',
    price: 100,
    originPrice: 120,
    address: '新北市平溪區乾坑路10號',
    category: 'tickets',
    coordinates: { lat: 25.0471, lng: 121.7756 },
    imagePool: 'waterfall',
    features: '簾幕式瀑布,台灣最大,彩虹美景,溪谷生態,消暑勝地',
    transport: '搭乘台鐵平溪支線至十分站，步行約20分鐘',
    evaluate: 4.5,
    evaluateNum: 489,
  },
  {
    slug: 'tamsui-fishermans-wharf',
    title: '淡水漁人碼頭',
    description: '情人橋上看夕陽，北台灣最浪漫的濱海休閒港區。',
    content:
      '<p>淡水漁人碼頭以純白色的情人橋為地標，橋上可遠眺觀音山與台灣海峽。碼頭內規劃完善的木棧道、商店街與遊艇碼頭，每到傍晚遊客紛紛聚集等待金黃色的夕陽沈入海平面。假日的街頭藝人演出與海鮮餐廳更增添浪漫氣氛。</p>',
    price: 500,
    originPrice: 600,
    address: '新北市淡水區觀海路199號',
    category: 'package',
    coordinates: { lat: 25.1821, lng: 121.415 },
    imagePool: 'beach',
    features: '情人橋,夕陽美景,遊艇碼頭,海鮮餐廳,浪漫散步,街頭藝人',
    transport: '捷運淡水信義線至淡水站，轉乘紅26公車至漁人碼頭站',
    evaluate: 4.4,
    evaluateNum: 398,
  },
  {
    slug: 'bitan-scenic-area',
    title: '碧潭風景區',
    description: '新店溪畔翡翠綠潭，踩天鵝船賞吊橋是假日最愜意的水岸時光。',
    content:
      '<p>碧潭因溪水碧綠如玉而得名，是大台北地區歷史悠久的風景區。碧潭吊橋橫跨新店溪，橋上可俯瞰湖面上五彩繽紛的天鵝船。東岸的水岸步道與西岸的和美山步道提供不同的散步體驗，夜間的水舞燈光秀更是一大亮點。</p>',
    price: 350,
    originPrice: 450,
    address: '新北市新店區碧潭路',
    category: 'package',
    coordinates: { lat: 24.9575, lng: 121.5344 },
    imagePool: 'nature',
    features: '碧潭吊橋,天鵝船,水岸步道,夜間水舞,翡翠綠潭',
    transport: '捷運松山新店線至新店站，出站步行約3分鐘',
    evaluate: 4.3,
    evaluateNum: 312,
  },
  {
    slug: 'wulai-hot-spring',
    title: '烏來溫泉',
    description: '泰雅族部落的碳酸氫鈉美人湯，搭配瀑布與台車的山林祕境。',
    content:
      '<p>烏來溫泉位於南勢溪畔，泉質屬碳酸氫鈉泉，無色無味，泡後肌膚滑嫩被稱為「美人湯」。烏來老街可品嚐泰雅族風味餐與山豬肉香腸，搭乘觀光台車前往烏來瀑布更是經典行程。冬季的溫泉搭配山林雲霧，是最療癒的自然體驗。</p>',
    price: 1200,
    originPrice: 1500,
    address: '新北市烏來區烏來街',
    category: 'package',
    coordinates: { lat: 24.8656, lng: 121.5506 },
    imagePool: 'hotSpring',
    features: '美人湯,泰雅文化,觀光台車,烏來瀑布,山林秘境,原住民料理',
    transport: '捷運松山新店線至新店站，轉乘849公車至烏來總站',
    evaluate: 4.6,
    evaluateNum: 423,
  },
  {
    slug: 'gold-museum',
    title: '黃金博物館',
    description: '見證金瓜石百年採金歲月，摸摸220公斤大金磚感受黃金魅力。',
    content:
      '<p>新北市立黃金博物館坐落於金瓜石礦區，完整保留日治時期的採礦建築與設施。館內展示金礦開採歷史，最受歡迎的是觸摸220公斤大金磚的體驗。本山五坑礦坑體驗可模擬礦工的工作環境，四連棟日式宿舍群則重現當年礦工生活樣貌。</p>',
    price: 200,
    originPrice: 250,
    address: '新北市瑞芳區金瓜石金光路8號',
    category: 'tickets',
    coordinates: { lat: 25.1088, lng: 121.8589 },
    imagePool: 'museum',
    features: '大金磚,礦坑體驗,日式建築,採金歷史,四連棟宿舍',
    transport: '搭乘台鐵至瑞芳站，轉乘788公車至金瓜石站',
    evaluate: 4.5,
    evaluateNum: 345,
  },
  {
    slug: 'yingge-ceramics',
    title: '鶯歌老街陶瓷',
    description: '台灣陶瓷之都，手拉坯DIY體驗與百家陶藝精品一次滿足。',
    content:
      '<p>鶯歌是台灣最重要的陶瓷產地，老街上百家陶瓷店鋪琳瑯滿目，從傳統茶具到現代藝術陶作應有盡有。多家工作室提供手拉坯、彩繪陶瓷等DIY體驗，適合親子同樂。鶯歌陶瓷博物館的常設展與戶外水廣場更是不可錯過的景點。</p>',
    price: 800,
    originPrice: 1000,
    address: '新北市鶯歌區文化路',
    category: 'package',
    coordinates: { lat: 24.9531, lng: 121.3531 },
    imagePool: 'oldStreet',
    features: '手拉坯DIY,陶瓷之都,陶博館,親子體驗,文創陶藝,百年傳承',
    transport: '搭乘台鐵至鶯歌站，步行約10分鐘至老街',
    evaluate: 4.4,
    evaluateNum: 287,
  },
  {
    slug: 'sanxia-old-street',
    title: '三峽老街',
    description: '全台保存最完整的紅磚拱廊老街，金牛角麵包飄香整條街。',
    content:
      '<p>三峽老街全長約200公尺，兩側紅磚拱廊建築保存完整，巴洛克式立面雕飾精美。老街上的金牛角麵包是必買伴手禮，三角湧老街的傳統豆花與碗粿也不容錯過。鄰近的三峽祖師廟被譽為「東方藝術殿堂」，精美的石雕與木雕令人讚嘆。</p>',
    price: 599,
    originPrice: 750,
    address: '新北市三峽區民權街',
    category: 'package',
    coordinates: { lat: 24.934, lng: 121.3697 },
    imagePool: 'oldStreet',
    features: '紅磚拱廊,金牛角,祖師廟,巴洛克建築,傳統美食,古蹟巡禮',
    transport: '搭乘台鐵至鶯歌站，轉乘桃園客運至三峽老街站',
    evaluate: 4.4,
    evaluateNum: 312,
  },
  {
    slug: 'shenkeng-tofu',
    title: '深坑老街豆腐',
    description: '百年豆腐故鄉，炭烤臭豆腐與豆腐冰淇淋挑戰你的味蕾。',
    content:
      '<p>深坑老街以手工豆腐聞名全台，老街上幾乎每家餐廳都以豆腐料理為主打。從經典的紅燒豆腐、麻辣臭豆腐到創意的豆腐冰淇淋，多元吃法讓人大開眼界。老街兩旁的閩南式建築與大樹下的悠閒氛圍，是體驗台灣小鎮風情的好去處。</p>',
    price: 550,
    originPrice: 680,
    address: '新北市深坑區深坑街',
    category: 'package',
    coordinates: { lat: 25.0022, lng: 121.6158 },
    imagePool: 'oldStreet',
    features: '手工豆腐,炭烤臭豆腐,閩南建築,小鎮風情,美食之旅,豆腐冰淇淋',
    transport: '捷運文湖線至木柵站，轉乘660或819公車至深坑站',
    evaluate: 4.3,
    evaluateNum: 234,
  },
  {
    slug: 'houtong-cat-village',
    title: '猴硐貓村',
    description: 'CNN評選世界六大賞貓景點，廢棄礦村因貓咪重獲新生。',
    content:
      '<p>猴硐貓村原是沒落的礦業聚落，因居民與流浪貓的共存故事而聲名大噪，被CNN評選為世界六大賞貓景點。村內隨處可見慵懶曬太陽的貓咪，貓橋連接車站與貓村，沿途設有可愛的貓咪裝置藝術。煤礦博物園區保留了完整的礦業遺址。</p>',
    price: 350,
    originPrice: 450,
    address: '新北市瑞芳區柴寮路70號',
    category: 'package',
    coordinates: { lat: 25.0867, lng: 121.8278 },
    imagePool: 'nature',
    features: 'CNN推薦,貓咪天堂,礦業遺址,貓橋,裝置藝術,攝影勝地',
    transport: '搭乘台鐵至猴硐站，出站即達',
    evaluate: 4.5,
    evaluateNum: 456,
  },
  {
    slug: 'fulong-beach',
    title: '福隆海水浴場',
    description: '東北角最美金沙灘，國際沙雕藝術季與獨木舟體驗的夏日天堂。',
    content:
      '<p>福隆海水浴場擁有綿延三公里的金黃色沙灘，是北台灣最受歡迎的戲水勝地。每年夏季舉辦的福隆國際沙雕藝術季吸引國內外頂尖沙雕藝術家參展。除了游泳戲水，還可體驗獨木舟、風帆等水上活動。福隆便當更是鐵道迷必嚐的經典美食。</p>',
    price: 500,
    originPrice: 600,
    address: '新北市貢寮區福隆街41號',
    category: 'package',
    coordinates: { lat: 25.0197, lng: 121.9444 },
    imagePool: 'beach',
    features: '金色沙灘,沙雕藝術季,獨木舟,水上活動,福隆便當,夏日戲水',
    transport: '搭乘台鐵至福隆站，步行約5分鐘',
    evaluate: 4.4,
    evaluateNum: 378,
  },
  {
    slug: 'jinguashi',
    title: '金瓜石',
    description: '黃金山城的歷史散策，十三層遺址與陰陽海構成絕美廢墟地景。',
    content:
      '<p>金瓜石曾是東亞最大金礦產地，如今留下壯觀的十三層選煉廠遺址，夜間點燈後有如天空之城。從報時山步道可同時眺望陰陽海、基隆山與太平洋，是北海岸最壯麗的觀景點。黃金瀑布的金黃色溪水與周圍荒涼地貌形成超現實的景觀。</p>',
    price: 650,
    originPrice: 800,
    address: '新北市瑞芳區金瓜石',
    category: 'package',
    coordinates: { lat: 25.1078, lng: 121.8614 },
    imagePool: 'mountain',
    features: '十三層遺址,陰陽海,報時山步道,黃金瀑布,礦業歷史,廢墟美學',
    transport: '搭乘台鐵至瑞芳站，轉乘788公車至金瓜石站',
    evaluate: 4.6,
    evaluateNum: 412,
  },
  {
    slug: 'bali-left-bank',
    title: '八里左岸',
    description: '騎單車遊淡水河左岸，十三行博物館與八里渡船頭的悠閒午後。',
    content:
      '<p>八里左岸自行車道沿淡水河畔延伸，全長約15公里，沿途經過關渡大橋、八里渡船頭與十三行博物館。租一台自行車迎著河風前行，沿途的紅樹林生態與河岸風光令人心曠神怡。渡船頭的孔雀蛤與雙胞胎甜甜圈是在地人推薦的必吃美食。</p>',
    price: 600,
    originPrice: 750,
    address: '新北市八里區觀海大道',
    category: 'package',
    coordinates: { lat: 25.1556, lng: 121.4297 },
    imagePool: 'nature',
    features: '自行車道,十三行博物館,渡船頭,河岸風光,紅樹林,親子騎行',
    transport: '捷運淡水信義線至淡水站，搭乘渡輪至八里左岸碼頭',
    evaluate: 4.3,
    evaluateNum: 267,
  },
  {
    slug: 'lin-family-mansion',
    title: '林家花園',
    description: '國定古蹟板橋林本源園邸，江南庭園之美在台灣完整重現。',
    content:
      '<p>林本源園邸是台灣保存最完整的中式園林建築，佔地約6000坪，由板橋林家歷時數十年打造。園內汲古書屋、來青閣、香玉簃等景點各具特色，迴廊曲橋與假山池塘展現江南園林的精緻美學。定期舉辦的導覽解說可深入了解林家與台灣近代史的關係。</p>',
    price: 160,
    originPrice: 200,
    address: '新北市板橋區西門街9號',
    category: 'tickets',
    coordinates: { lat: 25.01, lng: 121.4589 },
    imagePool: 'park',
    features: '國定古蹟,江南園林,導覽解說,歷史建築,迴廊曲橋,假山池塘',
    transport: '捷運板南線至府中站1號出口，步行約5分鐘',
    evaluate: 4.5,
    evaluateNum: 234,
  },
  {
    slug: 'sandiaojiao-lighthouse',
    title: '三貂角燈塔',
    description: '台灣本島最東端的白色燈塔，擁抱第一道曙光與太平洋無敵海景。',
    content:
      '<p>三貂角燈塔位於台灣本島的極東點，純白色的燈塔矗立在翠綠草坪上，背景是湛藍的太平洋。每年元旦這裡是迎接台灣本島第一道曙光的熱門地點。園區內設有極東觀景台，天氣晴朗時可遠眺龜山島。周邊的海蝕平台與潮間帶生態豐富。</p>',
    price: 100,
    originPrice: 120,
    address: '新北市貢寮區馬崗街38號',
    category: 'tickets',
    coordinates: { lat: 25.0097, lng: 121.9856 },
    imagePool: 'beach',
    features: '台灣極東,第一道曙光,白色燈塔,太平洋海景,龜山島,潮間帶',
    transport: '搭乘台鐵至福隆站，轉乘計程車約15分鐘',
    evaluate: 4.4,
    evaluateNum: 178,
  },
  {
    slug: 'xindian-bitan-bridge',
    title: '新店碧潭吊橋',
    description: '橫跨新店溪的白色吊橋，夜間光雕與水岸步道打造浪漫約會聖地。',
    content:
      '<p>碧潭吊橋全長200公尺，是新店地區最具代表性的地標。白天可從橋上俯瞰碧綠溪水與天鵝船，夜間的LED光雕讓吊橋化身發光的藝術品。橋兩端連接東西岸步道，西岸的和美山步道可登高眺望碧潭全景，是大台北最受歡迎的約會散步路線。</p>',
    price: 300,
    originPrice: 380,
    address: '新北市新店區碧潭路與新店路交叉口',
    category: 'package',
    coordinates: { lat: 24.9581, lng: 121.5339 },
    imagePool: 'city',
    features: '白色吊橋,夜間光雕,水岸步道,約會聖地,和美山,天鵝船',
    transport: '捷運松山新店線至新店站，出站步行約2分鐘',
    evaluate: 4.3,
    evaluateNum: 198,
  },
  {
    slug: 'manyueyuan-forest',
    title: '滿月圓國家森林遊樂區',
    description: '三峽山區的森林浴天堂，處女瀑布與滿月圓瀑布雙瀑奇觀。',
    content:
      '<p>滿月圓國家森林遊樂區位於三峽山區，因園區內有座山頭形似滿月而得名。園區擁有豐富的亞熱帶闊葉林生態，步道沿蚋仔溪溯溪而上，終點的滿月圓瀑布與處女瀑布水量豐沛。負離子含量極高的森林浴步道是都市人洗滌身心的天然氧吧。</p>',
    price: 150,
    originPrice: 180,
    address: '新北市三峽區有木里174-1號',
    category: 'tickets',
    coordinates: { lat: 24.8339, lng: 121.435 },
    imagePool: 'waterfall',
    features: '雙瀑奇觀,森林浴,負離子,亞熱帶林,溪谷步道,天然氧吧',
    transport: '搭乘台鐵至鶯歌站，轉乘桃園客運至滿月圓站',
    evaluate: 4.5,
    evaluateNum: 234,
  },
  {
    slug: 'yunxian-resort',
    title: '雲仙樂園',
    description: '全台唯一開車到不了的遊樂園，搭纜車跨越烏來瀑布進入森林秘境。',
    content:
      '<p>雲仙樂園位於烏來瀑布上方，是全台灣唯一需要搭乘纜車才能抵達的遊樂園。纜車橫跨烏來瀑布的壯觀畫面令人驚嘆。園區內保留豐富的原始森林生態，設有湖畔划船、森林步道、原住民文化展示等設施，是遠離塵囂的世外桃源。</p>',
    price: 500,
    originPrice: 620,
    address: '新北市烏來區瀑布路1-1號',
    category: 'tickets',
    coordinates: { lat: 24.8589, lng: 121.55 },
    imagePool: 'nature',
    features: '纜車體驗,烏來瀑布,原始森林,湖畔划船,世外桃源,原住民文化',
    transport: '捷運松山新店線至新店站，轉乘849公車至烏來總站，步行至纜車站',
    evaluate: 4.2,
    evaluateNum: 156,
  },
  {
    slug: 'shiding-thousand-island-lake',
    title: '石碇千島湖',
    description: '翡翠水庫上游的隱藏版絕景，翠綠茶園與湖光山色如詩如畫。',
    content:
      '<p>石碇千島湖位於翡翠水庫上游，因水位變化使得山丘露出水面形成大小島嶼，宛如縮小版的千島湖。從永安觀景步道可俯瞰湖面與周圍的翠綠茶園，層層疊疊的山巒與碧綠湖水交織出絕美畫面。搭配八卦茶園的品茗體驗，是台北近郊最療癒的秘境。</p>',
    price: 899,
    originPrice: 1100,
    address: '新北市石碇區永安村',
    category: 'package',
    coordinates: { lat: 24.9361, lng: 121.6589 },
    imagePool: 'tea',
    features: '千島湖景,八卦茶園,翡翠水庫,觀景步道,品茗體驗,秘境探索',
    transport: '捷運文湖線至木柵站，轉乘795公車至石碇站',
    evaluate: 4.6,
    evaluateNum: 289,
  },
  {
    slug: 'golden-waterfall',
    title: '瑞芳黃金瀑布',
    description: '金黃色礦泉水傾瀉而下，廢礦與自然交織的超現實奇景。',
    content:
      '<p>黃金瀑布位於金瓜石往水湳洞的公路旁，因雨水經過礦區溶解出金屬離子而呈現金黃色，流經岩壁形成多層瀑布的壯觀景象。搭配下方的陰陽海與遠處的十三層遺址，構成東北角最超現實的地景三連景。公路旁即可停車觀賞，是最便利的奇景體驗。</p>',
    price: 100,
    originPrice: 120,
    address: '新北市瑞芳區金水公路',
    category: 'tickets',
    coordinates: { lat: 25.1167, lng: 121.8622 },
    imagePool: 'waterfall',
    features: '金色瀑布,陰陽海,礦區地景,超現實,十三層遺址,免費參觀',
    transport: '搭乘台鐵至瑞芳站，轉乘788公車至黃金瀑布站',
    evaluate: 4.3,
    evaluateNum: 345,
  },
  {
    slug: 'keelung-river-bikeway',
    title: '基隆河自行車道',
    description: '沿基隆河畔騎行，串聯汐止、南港到內湖的城市綠色廊道。',
    content:
      '<p>基隆河自行車道全長約30公里，沿途經過汐止星光橋、南港公園與大佳河濱公園。平坦的河畔車道適合各年齡層騎乘，沿途風景從郊區田園到都會河岸不斷變換。星光橋的夜間燈光秀與彩虹橋的弧形造型是車道上最美的地標。</p>',
    price: 500,
    originPrice: 600,
    address: '新北市汐止區長江街',
    category: 'package',
    coordinates: { lat: 25.0675, lng: 121.6486 },
    imagePool: 'city',
    features: '自行車道,星光橋,河畔風光,親子騎行,城市綠廊,彩虹橋',
    transport: '搭乘台鐵至汐止站，步行約10分鐘至河畔自行車道入口',
    evaluate: 4.2,
    evaluateNum: 156,
  },
  {
    slug: 'xizhi-dajianshan-trail',
    title: '汐止大尖山步道',
    description: '汐止人的後山花園，杜鵑花季漫山遍野粉紅一片。',
    content:
      '<p>大尖山海拔460公尺，是汐止地區最受歡迎的登山步道。每年三至四月杜鵑花季期間，從山腳到山頂開滿粉紅色的杜鵑花，是北台灣最壯觀的賞花勝地之一。山頂的天秀宮觀景台可眺望台北盆地與基隆港，步道系統完善適合半日健行。</p>',
    price: 150,
    originPrice: 180,
    address: '新北市汐止區勤進路',
    category: 'tickets',
    coordinates: { lat: 25.0658, lng: 121.6614 },
    imagePool: 'mountain',
    features: '杜鵑花季,登山步道,觀景台,半日健行,粉紅花海,天秀宮',
    transport: '搭乘台鐵至汐止站，轉乘公車至天秀宮站',
    evaluate: 4.3,
    evaluateNum: 198,
  },
  {
    slug: 'xinbeitou-station',
    title: '新北投車站',
    description: '百年木造車站華麗重生，日式鐵道文化與溫泉小鎮的起點。',
    content:
      '<p>新北投車站建於1916年，是台北僅存的百年木造車站。歷經拆遷與重建，如今在七星公園內完整復原。車站內展示日治時期的鐵道文物與北投溫泉發展史，懷舊的檜木建築散發淡淡木香。作為北投溫泉之旅的起點，可從這裡開始探索整個溫泉區。</p>',
    price: 80,
    originPrice: 100,
    address: '新北市北投區七星街1號',
    category: 'tickets',
    coordinates: { lat: 25.1369, lng: 121.5032 },
    imagePool: 'city',
    features: '百年車站,木造建築,鐵道文化,溫泉起點,日式風情,檜木香',
    transport: '捷運新北投支線至新北投站，步行約2分鐘',
    evaluate: 4.2,
    evaluateNum: 134,
  },
  {
    slug: 'bitou-cape-trail',
    title: '鼻頭角步道',
    description: '東北角最壯觀的海岬步道，稜線上的小學與無邊際海景令人震撼。',
    content:
      '<p>鼻頭角步道沿著海岬稜線而建，全程約3.5公里，分為燈塔線、稜谷線與海濱線。稜線上的鼻頭國小被譽為全台最美的小學，操場旁即是壯闊的太平洋海景。步道沿途可見豆腐岩、海蝕平台等地質景觀，天氣晴朗時還能遠眺基隆嶼。</p>',
    price: 100,
    originPrice: 120,
    address: '新北市瑞芳區鼻頭路',
    category: 'tickets',
    coordinates: { lat: 25.1267, lng: 121.9222 },
    imagePool: 'beach',
    features: '海岬稜線,最美小學,豆腐岩,燈塔,太平洋海景,地質景觀',
    transport: '搭乘台鐵至瑞芳站，轉乘886公車至鼻頭角站',
    evaluate: 4.7,
    evaluateNum: 367,
  },
  {
    slug: 'longdong-rock-climbing',
    title: '龍洞攀岩',
    description: '台灣最大的天然攀岩場，四層樓高的海蝕崖壁挑戰你的極限。',
    content:
      '<p>龍洞攀岩場位於東北角海岸，擁有超過500條攀岩路線，從入門到專業級皆有適合的路線。砂岩壁面高達數十公尺，攀爬時可聽見腳下海浪拍岸的聲響。本行程包含專業教練指導、全套攀岩裝備與基礎教學，即使零經驗也能安全體驗攀岩樂趣。</p>',
    price: 2500,
    originPrice: 3000,
    address: '新北市貢寮區龍洞街',
    category: 'package',
    coordinates: { lat: 25.1086, lng: 121.9264 },
    imagePool: 'mountain',
    features: '天然岩場,專業教練,全套裝備,初學者友善,海岸攀岩,極限運動',
    transport: '搭乘台鐵至瑞芳站，轉乘886公車至龍洞站',
    evaluate: 4.8,
    evaluateNum: 198,
  },
  {
    slug: 'pinglin-tea-museum',
    title: '坪林茶博館',
    description: '包種茶的故鄉，茶文化體驗與翡翠水庫秘境的知性之旅。',
    content:
      '<p>坪林茶業博物館是台灣唯一以茶為主題的博物館，展示從採茶、製茶到品茶的完整過程。坪林是台灣包種茶的主要產地，周邊茶園遍布山丘。本行程包含茶園導覽、手作揉茶體驗與品茗教學，讓您深入了解台灣茶文化的精髓。</p>',
    price: 1200,
    originPrice: 1500,
    address: '新北市坪林區水聳淒坑19-1號',
    category: 'package',
    coordinates: { lat: 24.9375, lng: 121.7117 },
    imagePool: 'tea',
    features: '包種茶,揉茶體驗,品茗教學,茶園導覽,茶文化,知性之旅',
    transport: '搭乘新店客運923公車至坪林站',
    evaluate: 4.4,
    evaluateNum: 167,
  },
  {
    slug: 'banqiao-435-art-zone',
    title: '板橋435藝文特區',
    description: '舊軍營變身藝術聚落，免費展覽與親子遊戲場打造全齡藝文空間。',
    content:
      '<p>板橋435藝文特區由退役軍營改建而成，白色建築群圍繞著寬闘的綠地草坪。園區內進駐多家藝術工作室與展覽空間，定期舉辦免費展覽與藝文活動。濕地故事館與玩具博物館深受親子家庭喜愛，大片草地更是孩童奔跑嬉戲的天堂。</p>',
    price: 100,
    originPrice: 120,
    address: '新北市板橋區中正路435號',
    category: 'tickets',
    coordinates: { lat: 25.0194, lng: 121.4478 },
    imagePool: 'park',
    features: '免費展覽,藝術聚落,親子遊戲,玩具博物館,草地野餐,文創空間',
    transport: '捷運板南線至板橋站，轉乘307或810公車至板橋435藝文特區站',
    evaluate: 4.3,
    evaluateNum: 212,
  },
  {
    slug: 'zhonghe-hongludi',
    title: '中和烘爐地',
    description: '北台灣最靈驗的財神廟，百萬夜景搭配求財祈福雙重滿足。',
    content:
      '<p>烘爐地南山福德宮是北台灣最知名的土地公廟，以求財靈驗聞名全台。廟前的巨大土地公像高達兩層樓，金碧輝煌。登上廟旁的觀景台可俯瞰大台北百萬夜景，是台北近郊最佳的夜景觀賞點之一。農曆初一十五與過年期間香火尤為鼎盛。</p>',
    price: 500,
    originPrice: 620,
    address: '新北市中和區興南路二段399巷160-1號',
    category: 'package',
    coordinates: { lat: 24.9672, lng: 121.4953 },
    imagePool: 'temple',
    features: '財神廟,百萬夜景,土地公,求財祈福,巨型神像,夜間朝聖',
    transport: '捷運中和新蘆線至南勢角站，轉乘249公車至烘爐地站',
    evaluate: 4.5,
    evaluateNum: 456,
  },
]
