import type { ProductDefinition } from '../types'

export const penghuProducts: ProductDefinition[] = [
  {
    slug: 'cross-sea-bridge',
    title: '跨海大橋巡禮半日遊',
    description: '澎湖地標跨海大橋，連結白沙與西嶼的壯觀工程奇蹟。',
    content:
      '<p>澎湖跨海大橋全長2494公尺，橫跨吼門水道連接白沙鄉與西嶼鄉，是澎湖最具代表性的地標。半日遊將帶您走訪大橋兩端的觀景平台，了解大橋三次興建的歷史，並順遊通樑古榕與西嶼燈塔。站在橋上感受澎湖強勁的海風，眺望碧藍的海天一色。</p>',
    price: 800,
    originPrice: 1000,
    address: '澎湖縣白沙鄉通樑村',
    category: 'package',
    coordinates: { lat: 23.6667, lng: 119.55 },
    imagePool: 'beach',
    features: '地標建築,跨海大橋,海天一色,西嶼燈塔,通樑古榕,攝影景點',
    transport: '馬公市區搭乘澎湖公車藍線至通樑站，車程約40分鐘',
    evaluate: 4.4,
    evaluateNum: 580,
  },
  {
    slug: 'double-heart-stone-weir',
    title: '雙心石滬七美一日遊',
    description: '澎湖最浪漫的打卡景點，海上的雙心造型石滬美如明信片。',
    content:
      '<p>雙心石滬位於七美嶼東北方海岸，是澎湖最具代表性的人文景觀。兩個相連的心型石滬在潮間帶上形成完美的愛心造型，是先民智慧的結晶也是浪漫的象徵。一日遊包含七美島上主要景點巡禮：小台灣、望夫石、月鯉灣等，以及來回船票與島上機車。</p>',
    price: 1500,
    originPrice: 1900,
    address: '澎湖縣七美鄉東湖村',
    category: 'package',
    coordinates: { lat: 23.1978, lng: 119.4353 },
    imagePool: 'island',
    features: '雙心石滬,七美島,小台灣,望夫石,浪漫景點,來回船票',
    transport: '馬公南海遊客中心搭乘交通船至七美，航程約80分鐘',
    evaluate: 4.6,
    evaluateNum: 720,
  },
  {
    slug: 'tianhou-temple',
    title: '澎湖天后宮歷史導覽',
    description: '全台最古老的媽祖廟，四百年歷史的國定古蹟。',
    content:
      '<p>澎湖天后宮創建於明萬曆年間（1592年），是全台歷史最悠久的媽祖廟，被列為國定古蹟。廟內保存了珍貴的「沈有容諭退紅毛番韋麻郎等」石碑，為台灣最早的歷史文獻之一。導覽將深入介紹廟宇的建築藝術、歷史文物及澎湖的媽祖信仰文化。</p>',
    price: 200,
    originPrice: 260,
    address: '澎湖縣馬公市正義街1號',
    category: 'tickets',
    coordinates: { lat: 23.5631, lng: 119.5633 },
    imagePool: 'temple',
    features: '國定古蹟,四百年歷史,媽祖信仰,歷史文物,建築藝術,石碑',
    transport: '馬公機場搭乘計程車約15分鐘，或公車至馬公總站步行5分鐘',
    evaluate: 4.3,
    evaluateNum: 380,
  },
  {
    slug: 'fenggui-listening-waves',
    title: '風櫃聽濤體驗',
    description: '海蝕洞穴的天然音箱效應，聆聽大海的呼吸與怒吼。',
    content:
      '<p>風櫃洞位於馬公市風櫃半島南端，是一處海蝕溝與海蝕洞交會形成的特殊地景。當海浪湧入洞穴時，壓縮的空氣從岩縫噴出，發出如風箱般的轟隆巨響，噴發的水柱更可高達數公尺。站在玄武岩海岸上聆聽大海的低吟與怒號，感受自然的原始力量。</p>',
    price: 150,
    originPrice: 200,
    address: '澎湖縣馬公市風櫃里',
    category: 'tickets',
    coordinates: { lat: 23.5333, lng: 119.5583 },
    imagePool: 'beach',
    features: '海蝕洞穴,自然奇景,玄武岩,聽濤體驗,攝影景點,地質教育',
    transport: '馬公市區搭乘澎湖公車風櫃線至風櫃站，車程約20分鐘',
    evaluate: 4.2,
    evaluateNum: 310,
  },
  {
    slug: 'penghu-aquarium',
    title: '澎湖水族館門票',
    description: '認識澎湖海洋生態的最佳場所，超大海底隧道令人驚嘆。',
    content:
      '<p>澎湖水族館是台灣離島唯一的水族館，館內以澎湖周邊海域的海洋生物為主題。最大亮點是14公尺長的海底隧道，魟魚、鯊魚從頭頂游過的畫面令人震撼。每日定時的大洋池餵食秀與觸摸池體驗深受小朋友喜愛，是雨天或炎夏的最佳室內景點。</p>',
    price: 300,
    originPrice: 380,
    address: '澎湖縣白沙鄉岐頭村58號',
    category: 'tickets',
    coordinates: { lat: 23.6028, lng: 119.6028 },
    imagePool: 'beach',
    features: '海底隧道,餵食秀,觸摸池,海洋生態,親子景點,室內場館',
    transport: '馬公市區搭乘澎湖公車藍線至岐頭站，車程約30分鐘',
    evaluate: 4.1,
    evaluateNum: 420,
  },
  {
    slug: 'jibei-water-activities',
    title: '吉貝嶼水上活動一日遊',
    description: '澎湖最美的沙灘島嶼，八合一水上活動暢玩到飽。',
    content:
      '<p>吉貝嶼擁有澎湖最長的金色沙灘，綿延800公尺的貝殼沙灘細軟潔白。一日遊包含來回快艇船票及八合一水上活動：香蕉船、水上摩托車、拖曳圈、浮潛、獨木舟、SUP立槳、飛魚船及鴛鴦飛船，讓您在碧藍海水中盡情暢玩一整天。</p>',
    price: 1200,
    originPrice: 1500,
    address: '澎湖縣白沙鄉吉貝村',
    category: 'package',
    coordinates: { lat: 23.7272, lng: 119.6106 },
    imagePool: 'island',
    features: '金色沙灘,八合一水上,快艇來回,浮潛體驗,SUP立槳,暢玩整天',
    transport: '白沙鄉赤崁碼頭搭乘快艇至吉貝，航程約20分鐘',
    evaluate: 4.5,
    evaluateNum: 650,
  },
  {
    slug: 'qimei-little-taiwan',
    title: '七美小台灣地景導覽',
    description: '大自然鬼斧神工雕刻出的台灣形狀海蝕平台，澎湖必訪奇景。',
    content:
      '<p>七美小台灣是一處天然形成的海蝕平台，從高處俯瞰其輪廓與台灣本島形狀極為相似，連花東縱谷與中央山脈的紋理都栩栩如生。導覽將帶您從最佳觀景點欣賞這處自然奇觀，並解說七美島的玄武岩地質成因及周邊海蝕地景的形成過程。</p>',
    price: 200,
    originPrice: 260,
    address: '澎湖縣七美鄉平和村',
    category: 'tickets',
    coordinates: { lat: 23.2033, lng: 119.4283 },
    imagePool: 'island',
    features: '海蝕地景,台灣輪廓,地質奇觀,玄武岩,攝影景點,導覽解說',
    transport: '七美碼頭租機車約10分鐘可達',
    evaluate: 4.3,
    evaluateNum: 450,
  },
  {
    slug: 'wangan-green-turtle',
    title: '望安綠蠵龜故事館門票',
    description: '認識瀕危的綠蠵龜生態，望安島上的海龜保育教育基地。',
    content:
      '<p>望安島是台灣綠蠵龜最重要的產卵棲地之一，綠蠵龜故事館以互動展示介紹綠蠵龜的生命週期、產卵行為及保育現況。館內有綠蠵龜標本、卵窩模型及即時生態影像。每年五月至十月的產卵季，還有機會在專業人員帶領下夜訪沙灘觀察母龜上岸產卵。</p>',
    price: 100,
    originPrice: 130,
    address: '澎湖縣望安鄉東安村1號',
    category: 'tickets',
    coordinates: { lat: 23.3583, lng: 119.5 },
    imagePool: 'island',
    features: '綠蠵龜,保育教育,產卵觀察,互動展示,望安島,生態體驗',
    transport: '馬公南海遊客中心搭乘交通船至望安，航程約50分鐘',
    evaluate: 4.0,
    evaluateNum: 190,
  },
  {
    slug: 'erkan-settlement',
    title: '二崁古厝聚落巡禮',
    description: '保存完整的閩南傳統聚落，咾咕石與紅磚建築的百年風華。',
    content:
      '<p>二崁聚落位於西嶼鄉，是澎湖保存最完整的閩南傳統聚落，被列為國家歷史聚落。以咾咕石（珊瑚礁石灰�ite）砌築的古厝群保留了百年前的建築風貌，巷弄間設有杏仁茶館、褒歌展示及二崁傳香等文化體驗點。漫步其中感受離島聚落的寧靜與歲月之美。</p>',
    price: 350,
    originPrice: 450,
    address: '澎湖縣西嶼鄉二崁村',
    category: 'package',
    coordinates: { lat: 23.6333, lng: 119.5167 },
    imagePool: 'oldStreet',
    features: '古厝聚落,咾咕石建築,杏仁茶,傳統文化,歷史聚落,攝影景點',
    transport: '馬公市區搭乘澎湖公車藍線至二崁站，車程約50分鐘',
    evaluate: 4.4,
    evaluateNum: 360,
  },
  {
    slug: 'guanyin-rainbow-bridge',
    title: '觀音亭彩虹橋夕陽體驗',
    description: '澎湖最美的夕陽觀賞點，彩虹橋在落日餘暉中美到窒息。',
    content:
      '<p>觀音亭位於馬公市西濱海岸，廟前的彩虹橋是澎湖最知名的夕陽觀賞地點。每當夕陽西沉，金色光芒穿透彩虹橋的拱型結構，映照在平靜的海面上，形成如夢似幻的金色畫面。夏季花火節期間，煙火在彩虹橋後方綻放，更是年度盛事。</p>',
    price: 200,
    originPrice: 260,
    address: '澎湖縣馬公市介壽路7號',
    category: 'tickets',
    coordinates: { lat: 23.5667, lng: 119.5583 },
    imagePool: 'beach',
    features: '夕陽美景,彩虹橋,花火節,海岸風光,攝影天堂,浪漫體驗',
    transport: '馬公市區步行約15分鐘即達觀音亭',
    evaluate: 4.5,
    evaluateNum: 530,
  },
  {
    slug: 'penghu-living-museum',
    title: '澎湖生活博物館門票',
    description: '全方位認識澎湖的歷史、文化與常民生活的知識殿堂。',
    content:
      '<p>澎湖生活博物館以「澎湖人的故事」為核心，展示從史前時代到現代的澎湖發展史。館內分為自然地質、歷史移民、產業漁業及民俗信仰四大展區，以實物、模型與多媒體呈現澎湖的自然環境與常民生活。是認識澎湖最全面的室內景點。</p>',
    price: 80,
    originPrice: 100,
    address: '澎湖縣馬公市新生路327號',
    category: 'tickets',
    coordinates: { lat: 23.57, lng: 119.5717 },
    imagePool: 'museum',
    features: '歷史展覽,常民文化,自然地質,漁業產業,多媒體展示,室內景點',
    transport: '馬公機場搭乘計程車約10分鐘，或公車至馬公總站步行8分鐘',
    evaluate: 3.9,
    evaluateNum: 170,
  },
  {
    slug: 'blue-cave',
    title: '藍洞秘境探索之旅',
    description: '澎湖最神秘的海蝕洞穴，陽光折射出夢幻的寶石藍光芒。',
    content:
      '<p>澎湖藍洞位於西吉嶼的海蝕洞穴中，當陽光從洞頂裂隙射入，海水折射出璀璨的寶石藍光芒，如同歐洲卡布里島的藍洞般夢幻。這趟探索之旅搭乘快艇前往，沿途可欣賞南方四島的壯觀玄武岩海崖。需注意海況，僅在天候穩定時出航。</p>',
    price: 2000,
    originPrice: 2500,
    address: '澎湖縣望安鄉西吉嶼',
    category: 'package',
    coordinates: { lat: 23.2917, lng: 119.4917 },
    imagePool: 'island',
    features: '藍洞秘境,海蝕洞穴,快艇巡航,玄武岩,限量出航,攝影秘境',
    transport: '馬公南海遊客中心搭乘專屬快艇前往，航程約60分鐘',
    evaluate: 4.7,
    evaluateNum: 280,
  },
  {
    slug: 'south-penghu-marine-park',
    title: '南方四島國家公園浮潛一日遊',
    description: '台灣最年輕的國家公園，珊瑚覆蓋率超過50%的浮潛天堂。',
    content:
      '<p>澎湖南方四島國家公園由東吉嶼、西吉嶼、東嶼坪嶼、西嶼坪嶼及周邊島礁組成，海域珊瑚覆蓋率高達50%以上。一日遊搭乘快艇巡遊四島，在清澈海域浮潛可見繽紛珊瑚、熱帶魚群及海龜。登島探訪東吉燈塔與傳統聚落，感受無人島的原始之美。</p>',
    price: 2500,
    originPrice: 3200,
    address: '澎湖縣望安鄉東吉村',
    category: 'package',
    coordinates: { lat: 23.2583, lng: 119.6667 },
    imagePool: 'island',
    features: '國家公園,珊瑚浮潛,快艇巡航,海龜,無人島,東吉燈塔',
    transport: '馬公南海遊客中心搭乘專屬快艇前往，航程約90分鐘',
    evaluate: 4.8,
    evaluateNum: 350,
  },
  {
    slug: 'daguoye-basalt',
    title: '大菓葉柱狀玄武岩導覽',
    description: '壯觀的六角柱狀玄武岩壁，大自然千萬年雕刻的地質奇觀。',
    content:
      '<p>大菓葉柱狀玄武岩位於西嶼鄉，是澎湖最壯觀的地質景觀之一。高約數十公尺的玄武岩壁呈現規則的六角柱狀節理，是千萬年前岩漿冷卻收縮形成的自然奇觀。雨後岩壁前的窪地積水倒映岩柱，形成對稱的鏡面效果，是攝影師追捧的經典畫面。</p>',
    price: 150,
    originPrice: 200,
    address: '澎湖縣西嶼鄉池東村',
    category: 'tickets',
    coordinates: { lat: 23.6167, lng: 119.5083 },
    imagePool: 'beach',
    features: '柱狀玄武岩,地質奇觀,鏡面倒影,攝影景點,自然教室,免費參觀',
    transport: '馬公市區搭乘澎湖公車藍線至大菓葉站，車程約45分鐘',
    evaluate: 4.5,
    evaluateNum: 470,
  },
  {
    slug: 'north-ring-island-tour',
    title: '北環島公路一日遊',
    description: '澎湖本島北環經典路線，一次蒐集跨海大橋、古榕與漁村風光。',
    content:
      '<p>北環島公路是澎湖最經典的觀光路線，從馬公出發經白沙至西嶼，沿途景點豐富。行程包含中屯風車、通樑古榕、跨海大橋、二崁聚落、大菓葉玄武岩、西嶼燈塔及漁翁島等。一日遊含專車導覽、午餐及各景點門票，輕鬆暢遊澎湖北半部精華。</p>',
    price: 1800,
    originPrice: 2300,
    address: '澎湖縣馬公市（出發集合點）',
    category: 'package',
    coordinates: { lat: 23.5667, lng: 119.5667 },
    imagePool: 'beach',
    features: '環島行程,專車導覽,經典路線,含午餐,多景點串聯,輕鬆旅遊',
    transport: '馬公市區飯店接送，或至馬公總站集合出發',
    evaluate: 4.4,
    evaluateNum: 500,
  },
  {
    slug: 'fireworks-festival',
    title: '花火節觀賞VIP席位',
    description: '澎湖年度盛事國際海上花火節，VIP席位享最佳觀賞視角。',
    content:
      '<p>澎湖國際海上花火節每年四月至六月舉行，是澎湖最盛大的年度活動。璀璨煙火在觀音亭海域上空綻放，搭配音樂與燈光秀，場面壯觀動人。VIP席位設於彩虹橋正前方最佳觀賞區，附贈限定紀念品及在地小點心，讓您在最舒適的位置欣賞海上煙火。</p>',
    price: 800,
    originPrice: 1000,
    address: '澎湖縣馬公市觀音亭海濱公園',
    category: 'tickets',
    coordinates: { lat: 23.5667, lng: 119.5583 },
    imagePool: 'beach',
    features: '花火節,VIP席位,海上煙火,音樂燈光,紀念品,年度盛事',
    transport: '馬公市區步行約15分鐘即達觀音亭',
    evaluate: 4.7,
    evaluateNum: 620,
  },
  {
    slug: 'ocean-ranch',
    title: '海洋牧場蚵仔吃到飽體驗',
    description: '海上平台現烤鮮蚵吃到飽，搭配海鮮粥與釣魚樂趣。',
    content:
      '<p>海洋牧場是澎湖獨有的海上休閒體驗，搭乘接駁船前往外海的海上平台，在海風吹拂下享用現烤鮮蚵吃到飽。平台上還可體驗海釣、餵食海鱺魚，鮮美的海鮮粥無限供應。望著碧藍大海大啖肥美鮮蚵，是澎湖旅遊最難忘的美食體驗。</p>',
    price: 500,
    originPrice: 650,
    address: '澎湖縣馬公市鎖港里',
    category: 'package',
    coordinates: { lat: 23.5417, lng: 119.5833 },
    imagePool: 'beach',
    features: '鮮蚵吃到飽,海上平台,海釣體驗,海鮮粥,海鱺餵食,獨特體驗',
    transport: '馬公市區各碼頭搭乘接駁船前往，航程約10分鐘',
    evaluate: 4.3,
    evaluateNum: 550,
  },
  {
    slug: 'duxing-shicun',
    title: '篤行十村眷村文創園區',
    description: '全台最古老眷村改建的文創園區，張雨生故事館令人感動。',
    content:
      '<p>篤行十村是全台歷史最悠久的眷村，日治時期即為軍官宿舍群。園區經活化後進駐文創商店、咖啡廳及展覽空間。最知名的是張雨生故事館與潘安邦紀念館，展示兩位澎湖出身歌手的生平與音樂歷程。漫步日式建築群間，感受眷村的溫馨歲月。</p>',
    price: 100,
    originPrice: 130,
    address: '澎湖縣馬公市新復路2巷22號',
    category: 'tickets',
    coordinates: { lat: 23.5639, lng: 119.56 },
    imagePool: 'oldStreet',
    features: '眷村文化,張雨生,潘安邦,文創園區,日式建築,音樂故事',
    transport: '馬公市區步行約10分鐘即達',
    evaluate: 4.2,
    evaluateNum: 390,
  },
  {
    slug: 'tongliang-banyan',
    title: '通樑古榕生態導覽',
    description: '三百年老榕樹氣根盤繞如綠色隧道，澎湖最壯觀的自然奇景。',
    content:
      '<p>通樑古榕位於白沙鄉保安宮前，樹齡超過三百年，一棵榕樹以氣根不斷延伸，如今覆蓋面積廣達660平方公尺，氣根多達97支，形成一座天然的綠色華蓋。生態導覽將介紹古榕的生長奧秘、與廟宇的共生關係，以及澎湖獨特的風土環境如何影響植物生長。</p>',
    price: 150,
    originPrice: 200,
    address: '澎湖縣白沙鄉通樑村76號',
    category: 'tickets',
    coordinates: { lat: 23.6639, lng: 119.5556 },
    imagePool: 'nature',
    features: '三百年古榕,氣根奇觀,保安宮,生態導覽,自然奇景,仙人掌冰',
    transport: '馬公市區搭乘澎湖公車藍線至通樑站，車程約35分鐘',
    evaluate: 4.1,
    evaluateNum: 330,
  },
  {
    slug: 'xiyu-lighthouse',
    title: '西嶼燈塔古蹟巡禮',
    description: '台灣最古老的燈塔之一，矗立在西嶼最西端守護海峽。',
    content:
      '<p>西嶼燈塔又稱漁翁島燈塔，建於1778年（清乾隆年間），是台灣最早的西式燈塔之一，被列為國定古蹟。純白色的燈塔矗立在西嶼最西端的斷崖上，搭配藍天碧海的背景壯麗如畫。古蹟巡禮包含燈塔歷史導覽、西嶼西台古堡參觀及落日觀賞。</p>',
    price: 500,
    originPrice: 650,
    address: '澎湖縣西嶼鄉外垵村195號',
    category: 'package',
    coordinates: { lat: 23.5917, lng: 119.4667 },
    imagePool: 'island',
    features: '古蹟燈塔,清代建築,海崖景觀,落日觀賞,西台古堡,歷史導覽',
    transport: '馬公市區搭乘澎湖公車藍線至外垵站，車程約60分鐘',
    evaluate: 4.3,
    evaluateNum: 270,
  },
]
