import type { ProductDefinition } from '../types'

export const pingtungProducts: ProductDefinition[] = [
  {
    slug: 'kenting-national-park-pass',
    title: '墾丁國家公園生態通行證',
    description: '暢遊台灣最南端的國家公園，探索珊瑚礁海岸與熱帶森林。',
    content:
      '<p>墾丁國家公園是台灣唯一涵蓋陸域與海域的國家公園，擁有珊瑚礁海岸、熱帶季風林、候鳥棲息地等豐富生態。此通行證可進入鵝鑾鼻公園、社頂自然公園、龍磐草原等多處景點，一票暢遊南台灣最壯麗的自然風光。</p>',
    price: 250,
    originPrice: 300,
    address: '屏東縣恆春鎮墾丁路596號',
    category: 'tickets',
    coordinates: { lat: 21.9464, lng: 120.7972 },
    imagePool: 'beach',
    features: '珊瑚礁海岸,熱帶森林,多景點通行,候鳥觀賞,地質景觀',
    transport: '搭乘墾丁快線至墾丁站下車',
    evaluate: 4.5,
    evaluateNum: 678,
  },
  {
    slug: 'ocean-biology-museum',
    title: '國立海洋生物博物館門票',
    description: '走進亞洲最大的海洋博物館，與白鯨、企鵝和珊瑚礁魚群近距離互動。',
    content:
      '<p>海生館佔地約96公頃，設有台灣水域館、珊瑚王國館、世界水域館三大展館。84公尺長的海底隧道讓您彷彿置身海中，與鯊魚、魟魚擦身而過。白鯨池與企鵝館是最受歡迎的區域，夜宿海生館更是獨一無二的體驗。</p>',
    price: 450,
    originPrice: 550,
    address: '屏東縣車城鄉後灣路2號',
    category: 'tickets',
    coordinates: { lat: 22.0466, lng: 120.6968 },
    imagePool: 'museum',
    features: '三大展館,海底隧道,白鯨觀賞,企鵝館,觸摸池體驗',
    transport: '搭乘墾丁快線至海生館轉乘站，轉搭接駁車約10分鐘',
    evaluate: 4.6,
    evaluateNum: 756,
  },
  {
    slug: 'eluanbi-lighthouse',
    title: '鵝鑾鼻燈塔公園門票',
    description: '造訪台灣最南端的白色燈塔，眺望巴士海峽與太平洋交會處。',
    content:
      '<p>鵝鑾鼻燈塔建於1883年，是台灣最南端的燈塔，也是全世界少數擁有武裝設施的燈塔。園區內的珊瑚礁石灰岩地形獨特，步道穿梭於熱帶植物之間，觀海亭可同時眺望巴士海峽與太平洋。日落時分金光灑落海面，景色絕美。</p>',
    price: 80,
    originPrice: 100,
    address: '屏東縣恆春鎮鵝鑾里鵝鑾路301號',
    category: 'tickets',
    coordinates: { lat: 21.901, lng: 120.8558 },
    imagePool: 'beach',
    features: '百年燈塔,珊瑚礁地形,觀海亭,熱帶植物步道,日落觀賞',
    transport: '搭乘墾丁街車藍線至鵝鑾鼻站下車',
    evaluate: 4.4,
    evaluateNum: 534,
  },
  {
    slug: 'longpan-park-stargazing',
    title: '龍磐公園觀星夜遊體驗',
    description: '在無光害的太平洋海岸崖上，由專業導覽帶領仰望璀璨星空。',
    content:
      '<p>龍磐公園位於恆春半島東南方，是台灣本島最佳的觀星地點之一。崖頂草原面向太平洋，完全沒有光害遮蔽，銀河清晰可見。此行程由專業天文導覽師帶領，提供星空望遠鏡，解說星座故事與天文知識，並安排星空攝影教學。</p>',
    price: 800,
    originPrice: 1000,
    address: '屏東縣恆春鎮台26線旁',
    category: 'package',
    coordinates: { lat: 21.9228, lng: 120.8623 },
    imagePool: 'nature',
    features: '觀星導覽,星空望遠鏡,銀河拍攝教學,草原夜遊,天文解說,零光害',
    transport: '恆春鎮市區集合，專車接送至龍磐公園',
    evaluate: 4.7,
    evaluateNum: 312,
  },
  {
    slug: 'houbihu-snorkeling',
    title: '墾丁後壁湖浮潛體驗',
    description: '在台灣最大的珊瑚礁潟湖浮潛，與熱帶魚群和海龜共游。',
    content:
      '<p>後壁湖是墾丁海域最具代表性的浮潛地點，擁有豐富的珊瑚礁生態與清澈見底的海水。此行程包含專業教練指導、全套浮潛裝備租借，帶您近距離觀賞小丑魚、蝶魚、海膽等海洋生物。運氣好時還能遇到悠游的綠蠵龜。</p>',
    price: 600,
    originPrice: 750,
    address: '屏東縣恆春鎮大光路',
    category: 'package',
    coordinates: { lat: 21.9442, lng: 120.7444 },
    imagePool: 'beach',
    features: '浮潛教學,全套裝備,珊瑚礁觀賞,熱帶魚群,教練帶領,水下攝影',
    transport: '搭乘墾丁街車橘線至後壁湖站下車',
    evaluate: 4.5,
    evaluateNum: 489,
  },
  {
    slug: 'xiaoliuqiu-island-tour',
    title: '小琉球環島一日遊',
    description: '搭船前往珊瑚礁島嶼，環島探訪花瓶岩、美人洞與浮潛秘境。',
    content:
      '<p>小琉球是台灣唯一的珊瑚礁島嶼，距離東港僅25分鐘船程。此一日遊包含來回船票、機車租借、浮潛體驗與景點導覽。環島可造訪花瓶岩、美人洞、烏鬼洞、山豬溝等經典景點，海域中綠蠵龜數量豐富，浮潛時幾乎必能相遇。</p>',
    price: 1800,
    originPrice: 2200,
    address: '屏東縣東港鎮朝隆路1號（東港碼頭）',
    category: 'package',
    coordinates: { lat: 22.3381, lng: 120.4371 },
    imagePool: 'island',
    features: '來回船票,機車租借,浮潛體驗,環島導覽,花瓶岩,綠蠵龜共游',
    transport: '搭乘高鐵至左營站，轉乘墾丁快線至東港碼頭',
    evaluate: 4.7,
    evaluateNum: 623,
  },
  {
    slug: 'dapeng-bay-scenic-area',
    title: '大鵬灣國家風景區遊湖體驗',
    description: '搭乘遊湖船探索台灣最大的潟湖，欣賞開橋秀與紅樹林生態。',
    content:
      '<p>大鵬灣是台灣最大的單口囊狀潟湖，擁有豐富的紅樹林與濕地生態。園區內最著名的鵬灣跨海大橋是全台唯一的開啟式景觀橋，每日定時開橋讓船隻通過。遊湖船巡航潟湖一周，沿途可觀賞紅樹林、蚵棚與水上教堂等特色景觀。</p>',
    price: 500,
    originPrice: 600,
    address: '屏東縣東港鎮鵬灣大道二段1號',
    category: 'package',
    coordinates: { lat: 22.4286, lng: 120.4941 },
    imagePool: 'nature',
    features: '潟湖遊船,開橋秀,紅樹林生態,水上教堂,蚵棚景觀',
    transport: '搭乘屏東客運至大鵬灣站下車',
    evaluate: 4.1,
    evaluateNum: 234,
  },
  {
    slug: 'liangshan-waterfall',
    title: '涼山瀑布健行之旅',
    description: '走進屏東三地門的清涼秘境，穿越原始林徑抵達三層壯觀瀑布。',
    content:
      '<p>涼山瀑布位於屏東瑪家鄉，分為三層，每層各有特色。第一層瀑布平緩易達，適合親子同行；第二、三層需沿溪谷攀行，途經原始林與巨石，第三層瀑布高約50公尺，水量豐沛氣勢磅礴。此行程含專業嚮導與輕食補給。</p>',
    price: 900,
    originPrice: 1100,
    address: '屏東縣瑪家鄉涼山村',
    category: 'package',
    coordinates: { lat: 22.6414, lng: 120.6423 },
    imagePool: 'waterfall',
    features: '三層瀑布,原始林健行,溪谷探險,專業嚮導,輕食補給,清涼戲水',
    transport: '屏東火車站集合，專車接送約40分鐘',
    evaluate: 4.4,
    evaluateNum: 198,
  },
  {
    slug: 'wanluan-pork-knuckle-tour',
    title: '萬巒豬腳美食之旅',
    description: '品嚐正宗萬巒豬腳名店，走訪客家聚落與五溝水濕地。',
    content:
      '<p>萬巒是台灣豬腳的故鄉，鎮上豬腳名店林立。此美食之旅安排品嚐最道地的滷豬腳套餐，外皮Q彈、肉質軟嫩、醬汁入味。餐後導覽萬巒老街的客家伯公廟、五溝水濕地聚落，體驗屏東客家文化的深厚底蘊。</p>',
    price: 750,
    originPrice: 900,
    address: '屏東縣萬巒鄉民和路16號',
    category: 'package',
    coordinates: { lat: 22.5725, lng: 120.5703 },
    imagePool: 'oldStreet',
    features: '豬腳名店品嚐,客家聚落導覽,五溝水濕地,伯公廟參觀,在地文化',
    transport: '搭乘屏東客運至萬巒站下車，步行約5分鐘',
    evaluate: 4.2,
    evaluateNum: 267,
  },
  {
    slug: 'hengchun-old-town',
    title: '恆春古城半日文化巡禮',
    description: '漫步全台保存最完整的古城門，探訪海角七號場景與在地故事。',
    content:
      '<p>恆春古城建於清光緒年間，四座城門保存完整，是全台僅存的完整古城。此行程由在地導覽員帶領，走訪東西南北四座城門、出火特別景觀區，以及電影《海角七號》的拍攝場景阿嘉的家。沿途品嚐恆春在地小吃綠豆蒜與洋蔥冰淇淋。</p>',
    price: 600,
    originPrice: 750,
    address: '屏東縣恆春鎮中山路',
    category: 'package',
    coordinates: { lat: 22.0025, lng: 120.7454 },
    imagePool: 'oldStreet',
    features: '四座古城門,海角七號場景,在地導覽,特色小吃,出火景觀,文化體驗',
    transport: '搭乘墾丁快線至恆春轉運站下車',
    evaluate: 4.3,
    evaluateNum: 345,
  },
  {
    slug: 'sichongxi-hot-spring',
    title: '四重溪溫泉泡湯體驗',
    description: '浸泡日治時期即聞名的碳酸氫鈉泉，享受暖湯與山林靜謐。',
    content:
      '<p>四重溪溫泉是台灣四大名泉之一，泉質屬弱鹼性碳酸氫鈉泉，水溫約攝氏50至60度，對皮膚有極佳的滋潤效果。此體驗包含溫泉會館的露天風呂或獨立湯屋使用，搭配下午茶點心，讓您在山林環繞中徹底放鬆身心。</p>',
    price: 800,
    originPrice: 1000,
    address: '屏東縣車城鄉溫泉路玉泉巷',
    category: 'package',
    coordinates: { lat: 22.067, lng: 120.7307 },
    imagePool: 'hotSpring',
    features: '碳酸氫鈉泉,露天風呂,獨立湯屋,下午茶,四大名泉,山林環境',
    transport: '搭乘屏東客運至四重溪站下車，步行約5分鐘',
    evaluate: 4.4,
    evaluateNum: 289,
  },
  {
    slug: 'fengchuisha-scenic-area',
    title: '風吹沙地質景觀導覽',
    description: '探訪恆春半島獨特的風蝕沙河地形，見證大自然的鬼斧神工。',
    content:
      '<p>風吹沙位於恆春半島東岸，是台灣唯一的沙河與沙瀑地形。冬季強烈的落山風將海岸沙粒吹上崖頂，夏季雨水再將沙粒沖回海岸，形成獨特的沙河景觀。此導覽行程由地質專家帶領，深入解說風蝕地形的形成過程與環境變遷。</p>',
    price: 350,
    originPrice: 450,
    address: '屏東縣恆春鎮台26線（佳鵝公路旁）',
    category: 'package',
    coordinates: { lat: 21.9319, lng: 120.856 },
    imagePool: 'nature',
    features: '風蝕地形,沙河沙瀑,地質導覽,海岸景觀,攝影取景',
    transport: '恆春鎮市區集合，專車接送約15分鐘',
    evaluate: 4.1,
    evaluateNum: 156,
  },
  {
    slug: 'baisha-bay-beach',
    title: '白沙灣海灘水上活動套票',
    description: '在墾丁最美的白色沙灘上暢玩水上摩托車、香蕉船與沙灘排球。',
    content:
      '<p>白沙灣擁有長約500公尺的潔白貝殼沙灘，是墾丁地區公認最美的海灘之一，也是電影《少年乜的奇幻漂流》的拍攝地。此套票包含水上摩托車、香蕉船、浮潛三項水上活動，另附沙灘躺椅與陽傘租借，讓您盡享南國海灘假期。</p>',
    price: 1200,
    originPrice: 1500,
    address: '屏東縣恆春鎮白砂路',
    category: 'package',
    coordinates: { lat: 21.9318, lng: 120.7187 },
    imagePool: 'beach',
    features: '水上摩托車,香蕉船,浮潛體驗,沙灘躺椅,陽傘租借,白色沙灘',
    transport: '搭乘墾丁街車橘線至白沙灣站下車',
    evaluate: 4.3,
    evaluateNum: 412,
  },
  {
    slug: 'nanwan-beach-experience',
    title: '南灣海灘戲水踏浪體驗',
    description: '在墾丁大街旁的金黃沙灘盡情戲水，享受南台灣陽光海岸。',
    content:
      '<p>南灣是墾丁最熱鬧的海灘，以金黃色的細沙與湛藍海水著稱。海灘緊鄰墾丁大街，交通便利且設施完善。此體驗包含陽傘躺椅租借、衝浪板體驗課程與海灘BBQ套餐，從白天戲水到傍晚烤肉，一站式享受墾丁海灘的熱情魅力。</p>',
    price: 950,
    originPrice: 1200,
    address: '屏東縣恆春鎮南灣路223號',
    category: 'package',
    coordinates: { lat: 21.9583, lng: 120.7722 },
    imagePool: 'beach',
    features: '衝浪體驗,海灘BBQ,陽傘躺椅,金黃沙灘,近墾丁大街',
    transport: '搭乘墾丁快線至南灣站下車，步行約2分鐘',
    evaluate: 4.2,
    evaluateNum: 534,
  },
  {
    slug: 'alangyi-ancient-trail',
    title: '阿朗壹古道全日健行',
    description: '走過台灣最後的原始海岸線，體驗原住民古道的壯麗與荒野之美。',
    content:
      '<p>阿朗壹古道是台灣環島公路唯一未貫通的海岸路段，保留了最原始的南田石礫灘與海岸林。全程約8公里，需事先申請入山許可。此行程包含申請代辦、專業嚮導帶領、接駁車安排與行動糧食，沿途解說排灣族歷史與海岸生態。</p>',
    price: 2200,
    originPrice: 2800,
    address: '屏東縣牡丹鄉旭海村',
    category: 'package',
    coordinates: { lat: 22.164, lng: 120.8964 },
    imagePool: 'nature',
    features: '原始海岸線,入山許可代辦,專業嚮導,南田石礫灘,排灣族文化,接駁車',
    transport: '恆春鎮集合，專車接送至旭海登山口',
    evaluate: 4.8,
    evaluateNum: 178,
  },
  {
    slug: 'sheding-nature-park',
    title: '社頂自然公園生態導覽',
    description: '夜間走入墾丁高位珊瑚礁森林，探尋螢火蟲、棋盤腳與夜行動物。',
    content:
      '<p>社頂自然公園位於墾丁國家公園內，擁有豐富的高位珊瑚礁森林生態。夜間導覽是最受歡迎的活動，在專業解說員帶領下，可觀察到津田氏大頭竹節蟲、棋盤腳花、螢火蟲、灰面鷲等珍貴物種。日間的凌霄亭步道視野遼闊。</p>',
    price: 300,
    originPrice: 380,
    address: '屏東縣恆春鎮公園路',
    category: 'tickets',
    coordinates: { lat: 21.9529, lng: 120.8115 },
    imagePool: 'nature',
    features: '夜間生態導覽,珊瑚礁森林,螢火蟲觀察,棋盤腳花,專業解說',
    transport: '搭乘墾丁街車綠線至社頂站下車',
    evaluate: 4.5,
    evaluateNum: 234,
  },
  {
    slug: 'liuqiu-vase-rock',
    title: '琉球嶼花瓶岩浮潛體驗',
    description: '在小琉球最著名的地標旁浮潛，與綠蠵龜近距離共游。',
    content:
      '<p>花瓶岩是小琉球最具代表性的珊瑚礁石灰岩地標，頂部長滿綠色植物如花瓶般矗立海岸。花瓶岩周邊海域是綠蠵龜頻繁出沒的區域，浮潛時幾乎百分之百能與海龜相遇。此體驗包含全套裝備、專業教練指導與水下拍攝服務。</p>',
    price: 700,
    originPrice: 900,
    address: '屏東縣琉球鄉花瓶岩海域',
    category: 'package',
    coordinates: { lat: 22.3489, lng: 120.3782 },
    imagePool: 'island',
    features: '花瓶岩浮潛,綠蠵龜共游,全套裝備,水下攝影,專業教練',
    transport: '東港碼頭搭船至小琉球白沙碼頭，步行約10分鐘',
    evaluate: 4.6,
    evaluateNum: 445,
  },
  {
    slug: 'chuhuo-special-scenic-area',
    title: '出火特別景觀區夜間導覽',
    description: '觀賞地底天然氣自地表竄出燃燒的奇景，體驗大自然的神奇力量。',
    content:
      '<p>出火位於恆春鎮東方，是泥岩層中天然氣從裂縫竄出地表後燃燒的自然景觀。夜晚時火焰在漆黑中搖曳格外壯觀，是墾丁地區獨特的地質奇景。導覽員會解說地質成因，遊客還可在火焰旁烤爆米花、烤棉花糖，是有趣的夜間活動。</p>',
    price: 200,
    originPrice: 250,
    address: '屏東縣恆春鎮恆公路',
    category: 'tickets',
    coordinates: { lat: 22.0125, lng: 120.7581 },
    imagePool: 'nature',
    features: '天然氣火焰,地質導覽,夜間活動,爆米花體驗,奇特景觀',
    transport: '恆春轉運站搭乘計程車約5分鐘',
    evaluate: 4.0,
    evaluateNum: 312,
  },
  {
    slug: 'kenting-forest-recreation',
    title: '墾丁森林遊樂區門票',
    description: '探索全台唯一的熱帶植物園，穿越鐘乳石洞與珊瑚礁林道。',
    content:
      '<p>墾丁森林遊樂區佔地約466公頃，擁有超過1,200種熱帶植物。園區內的仙洞與銀龍洞是天然的鐘乳石洞穴，觀海樓可遠眺巴士海峽。花榭、望海台、銀葉板根等景點沿步道串聯，是認識熱帶生態的最佳戶外教室。</p>',
    price: 150,
    originPrice: 200,
    address: '屏東縣恆春鎮公園路201號',
    category: 'tickets',
    coordinates: { lat: 21.9496, lng: 120.804 },
    imagePool: 'nature',
    features: '熱帶植物園,鐘乳石洞,觀海樓,銀葉板根,珊瑚礁步道',
    transport: '搭乘墾丁街車綠線至墾丁森林遊樂區站下車',
    evaluate: 4.2,
    evaluateNum: 267,
  },
  {
    slug: 'victory-star-village',
    title: '屏東勝利星村文創園區漫遊',
    description: '漫步日式眷村老屋群，品味文創小店與在地美食。',
    content:
      '<p>勝利星村是全台最大的日式軍官眷舍群，保留了近70棟日治時期的軍官宿舍。經過活化再利用，現已進駐餐廳、咖啡廳、藝廊、手作工坊等文創店家。老樹與日式建築交織的巷弄氛圍悠閒，是屏東市區最具文青氣息的散步景點。</p>',
    price: 350,
    originPrice: 450,
    address: '屏東縣屏東市青島街106號',
    category: 'package',
    coordinates: { lat: 22.6691, lng: 120.4863 },
    imagePool: 'oldStreet',
    features: '日式眷村,文創小店,在地美食,老屋巡禮,藝文展覽',
    transport: '搭乘火車至屏東站，步行約15分鐘',
    evaluate: 4.3,
    evaluateNum: 289,
  },
  {
    slug: 'checheng-fuan-temple',
    title: '車城福安宮參拜祈福',
    description: '參訪全台最大的土地公廟，體驗金紙爐自動生火的神奇傳說。',
    content:
      '<p>車城福安宮是全台灣規模最大的土地公廟，廟宇金碧輝煌，香火鼎盛。最特別的是廟中的金爐據說會自動起火焚燒金紙，被信眾視為神蹟。廟前廣場的洋蔥冰淇淋是車城名物，甜中帶有獨特的洋蔥香氣，是到訪必嚐的在地美食。</p>',
    price: 100,
    originPrice: 130,
    address: '屏東縣車城鄉福安路51號',
    category: 'tickets',
    coordinates: { lat: 22.0742, lng: 120.7122 },
    imagePool: 'temple',
    features: '全台最大土地公廟,金爐奇觀,祈福參拜,洋蔥冰淇淋,在地信仰',
    transport: '搭乘墾丁快線至車城站下車，步行約3分鐘',
    evaluate: 4.1,
    evaluateNum: 345,
  },
  {
    slug: 'jialeshuei-scenic-area',
    title: '佳樂水風景區門票',
    description: '沿著海岸奇岩怪石搭乘遊園車，欣賞大自然的雕刻藝術。',
    content:
      '<p>佳樂水風景區以海蝕奇岩聞名，海岸線上的砂岩經年累月被海浪雕刻出各種形狀，如蜂巢岩、青蛙石、山豬頭等維妙維肖的自然雕塑。搭乘遊園車沿海岸巡遊，導覽員會風趣地介紹各塊奇岩的命名由來，全程約40分鐘。</p>',
    price: 120,
    originPrice: 150,
    address: '屏東縣滿州鄉佳樂水',
    category: 'tickets',
    coordinates: { lat: 21.9867, lng: 120.8664 },
    imagePool: 'beach',
    features: '海蝕奇岩,遊園車導覽,自然雕塑,海岸景觀,趣味解說',
    transport: '恆春轉運站搭乘墾丁街車至佳樂水站',
    evaluate: 4.0,
    evaluateNum: 198,
  },
  {
    slug: 'kenting-sailing-experience',
    title: '墾丁帆船出海體驗',
    description: '乘坐帆船出海航向巴士海峽，享受乘風破浪與海天一色的快感。',
    content:
      '<p>從後壁湖漁港出發，搭乘專業帆船駛入巴士海峽，在船長指導下可親自操帆、掌舵，體驗馭風航行的樂趣。航程中可欣賞墾丁海岸線的壯麗全景，運氣好時還能看到飛魚躍出海面。落日航班更能在海上欣賞絕美的恆春半島夕陽。</p>',
    price: 2500,
    originPrice: 3200,
    address: '屏東縣恆春鎮大光路（後壁湖漁港）',
    category: 'package',
    coordinates: { lat: 21.945, lng: 120.7423 },
    imagePool: 'beach',
    features: '帆船體驗,操帆教學,海上觀景,落日航班,巴士海峽,船長導覽',
    transport: '搭乘墾丁街車橘線至後壁湖站下車',
    evaluate: 4.6,
    evaluateNum: 178,
  },
  {
    slug: 'sandimen-aboriginal-culture',
    title: '三地門原住民文化園區一日遊',
    description: '深入排灣族與魯凱族的傳統領域，體驗原住民歌舞與琉璃珠藝術。',
    content:
      '<p>台灣原住民族文化園區位於屏東三地門，完整呈現台灣十六族原住民的傳統生活。園區內每日演出的原住民樂舞表演精彩動人，排灣族的琉璃珠手作體驗與傳統服飾試穿更是熱門活動。此一日遊包含門票、導覽與風味餐。</p>',
    price: 1200,
    originPrice: 1500,
    address: '屏東縣瑪家鄉北葉村風景104號',
    category: 'package',
    coordinates: { lat: 22.6764, lng: 120.6344 },
    imagePool: 'park',
    features: '原住民樂舞,琉璃珠手作,傳統服飾體驗,風味餐,文化導覽,十六族展示',
    transport: '搭乘屏東客運至原住民文化園區站下車',
    evaluate: 4.4,
    evaluateNum: 312,
  },
  {
    slug: 'donggang-seafood-market',
    title: '東港華僑市場海鮮饗宴',
    description: '在東港最大的海鮮市場現挑現煮，大啖黑鮪魚與櫻花蝦。',
    content:
      '<p>東港華僑市場是屏東最著名的海鮮集散地，以黑鮪魚、櫻花蝦、油魚子三寶聞名全台。市場內攤商提供現點現做的代客料理服務，新鮮漁獲直接端上桌。此行程包含市場導覽、海鮮食材介紹與雙人海鮮套餐，讓您深度品味東港漁港文化。</p>',
    price: 1500,
    originPrice: 1800,
    address: '屏東縣東港鎮朝安里光復路二段104號',
    category: 'package',
    coordinates: { lat: 22.4617, lng: 120.4457 },
    imagePool: 'city',
    features: '現撈海鮮,黑鮪魚,櫻花蝦,代客料理,市場導覽,雙人套餐',
    transport: '搭乘屏東客運至東港站下車，步行約10分鐘',
    evaluate: 4.5,
    evaluateNum: 456,
  },
]
