import type { ProductDefinition } from '../types'

export const taichungProducts: ProductDefinition[] = [
  {
    slug: 'rainbow-village',
    title: '彩虹眷村',
    description: '色彩繽紛的眷村彩繪藝術，是臺中最具代表性的打卡景點之一。',
    content:
      '<p>彩虹眷村由退伍老兵黃永阜手繪而成，整個村落充滿了繽紛的色彩與童趣的圖案。漫步其中彷彿走入童話世界，每一面牆都是獨一無二的藝術創作，是認識臺灣眷村文化的絕佳去處。</p>',
    price: 100,
    originPrice: 120,
    address: '臺中市南屯區春安路56巷25號',
    category: 'tickets',
    coordinates: { lat: 24.1338, lng: 120.6082 },
    imagePool: 'city',
    features: '彩繪藝術,眷村文化,拍照打卡,免費導覽,文創商品',
    transport: '搭乘臺中客運56路至彩虹眷村站下車，步行約3分鐘。',
    evaluate: 4.3,
    evaluateNum: 680,
  },
  {
    slug: 'gaomei-wetland',
    title: '高美濕地',
    description: '絕美夕陽與生態濕地交織的自然景觀，被譽為臺灣最美濕地。',
    content:
      '<p>高美濕地擁有豐富的潮間帶生態，是候鳥過境的重要棲息地。黃昏時分的夕陽映照在廣闊的濕地上，形成令人屏息的美景。木棧道延伸入濕地，讓遊客可以近距離觀察螃蟹、彈塗魚等生物。</p>',
    price: 800,
    originPrice: 1000,
    address: '臺中市清水區美堤街',
    category: 'package',
    coordinates: { lat: 24.3128, lng: 120.5496 },
    imagePool: 'beach',
    features: '夕陽美景,生態導覽,潮間帶,候鳥觀察,攝影天堂',
    transport: '搭乘臺中客運178、179路至高美濕地站下車。',
    evaluate: 4.7,
    evaluateNum: 750,
  },
  {
    slug: 'science-museum',
    title: '國立自然科學博物館',
    description: '臺灣規模最大的科學博物館，涵蓋天文、地質、生命科學等主題展覽。',
    content:
      '<p>國立自然科學博物館是臺灣首座科學博物館，館內設有太空劇場、科學中心、生命科學廳、地球環境廳等多個展區。豐富的互動式展品與定期更新的特展，讓大人小孩都能在遊戲中學習科學知識。</p>',
    price: 200,
    originPrice: 250,
    address: '臺中市北區館前路1號',
    category: 'tickets',
    coordinates: { lat: 24.1577, lng: 120.6655 },
    imagePool: 'museum',
    features: '科學教育,互動展覽,太空劇場,親子景點,恐龍化石',
    transport: '搭乘臺中市公車至科博館站下車，或搭BRT至科博館站。',
    evaluate: 4.5,
    evaluateNum: 620,
  },
  {
    slug: 'fengjia-night-market',
    title: '逢甲夜市美食巡禮',
    description: '全臺最大夜市的在地美食導覽，品嚐經典與創新小吃。',
    content:
      '<p>逢甲夜市是全臺灣面積最大、最具創新精神的夜市。跟隨在地達人的腳步，品嚐大腸包小腸、章魚小丸子、雞排、地瓜球等經典美食，還有各種只有逢甲才吃得到的創意小吃，讓你的味蕾一次滿足。</p>',
    price: 899,
    originPrice: 1100,
    address: '臺中市西屯區文華路',
    category: 'package',
    coordinates: { lat: 24.1787, lng: 120.6464 },
    imagePool: 'nightMarket',
    features: '夜市美食,在地導覽,創意小吃,伴手禮推薦,文化體驗',
    transport: '搭乘臺中客運33、35路至逢甲大學站下車，步行約5分鐘。',
    evaluate: 4.6,
    evaluateNum: 520,
  },
  {
    slug: 'miyahara',
    title: '宮原眼科',
    description: '日治時期眼科醫院改建的文創甜點店，華麗復古的建築令人驚豔。',
    content:
      '<p>宮原眼科保留了日治時期的建築外觀，內部改建為充滿奢華感的甜點空間。挑高的書架式裝潢、精緻的伴手禮包裝，加上招牌的土鳳梨酥與冰淇淋，讓每一位到訪的遊客都能感受到臺中的文創魅力。</p>',
    price: 350,
    originPrice: 420,
    address: '臺中市中區中山路20號',
    category: 'tickets',
    coordinates: { lat: 24.1382, lng: 120.6837 },
    imagePool: 'oldStreet',
    features: '文創甜點,日治建築,冰淇淋,伴手禮,復古風格',
    transport: '搭乘臺中市公車至臺中火車站，步行約3分鐘。',
    evaluate: 4.4,
    evaluateNum: 590,
  },
  {
    slug: 'national-theater',
    title: '台中國家歌劇院',
    description: '世界級建築大師伊東豊雄設計，被譽為全球最難蓋的建築之一。',
    content:
      '<p>台中國家歌劇院以「美聲涵洞」概念設計，獨特的曲牆結構打破了傳統建築的直線思維。館內除了精彩的表演藝術節目，還設有空中花園、文創商店與餐廳，是臺中最具代表性的藝文地標。</p>',
    price: 250,
    originPrice: 300,
    address: '臺中市西屯區惠來路二段101號',
    category: 'tickets',
    coordinates: { lat: 24.1627, lng: 120.6401 },
    imagePool: 'city',
    features: '建築藝術,表演藝術,空中花園,文創商店,拍照打卡',
    transport: '搭乘臺中市公車至新光/遠百站下車，步行約5分鐘。',
    evaluate: 4.6,
    evaluateNum: 480,
  },
  {
    slug: 'lihpao-land',
    title: '麗寶樂園',
    description: '結合遊樂設施、購物中心與摩天輪的大型複合式度假園區。',
    content:
      '<p>麗寶樂園是中臺灣最大的主題樂園，園區分為探索世界與馬拉灣水上樂園兩大主題。120公尺高的天空之夢摩天輪是全臺最大，搭配Outlet Mall購物中心，提供一整天的歡樂體驗。</p>',
    price: 799,
    originPrice: 999,
    address: '臺中市后里區福容路8號',
    category: 'tickets',
    coordinates: { lat: 24.3079, lng: 120.7193 },
    imagePool: 'park',
    features: '主題樂園,摩天輪,水上樂園,購物中心,親子遊樂',
    transport: '搭乘豐原客運215路至麗寶樂園站下車。',
    evaluate: 4.2,
    evaluateNum: 710,
  },
  {
    slug: 'houfeng-bikeway',
    title: '后豐鐵馬道',
    description: '利用舊山線鐵道改建的自行車道，穿越隧道與鐵橋的獨特體驗。',
    content:
      '<p>后豐鐵馬道全長約4.5公里，沿途經過花梁鋼橋與九號隧道等歷史遺跡。騎著單車穿越百年隧道，在鐵橋上欣賞大甲溪風光，是臺中最受歡迎的自行車道之一，適合全家大小一同騎乘。</p>',
    price: 600,
    originPrice: 750,
    address: '臺中市豐原區國豐路三段',
    category: 'package',
    coordinates: { lat: 24.2711, lng: 120.7289 },
    imagePool: 'nature',
    features: '自行車道,舊鐵道,花梁鋼橋,隧道探險,親子騎乘',
    transport: '搭乘臺鐵至豐原站，轉搭豐原客運至后里馬場站。',
    evaluate: 4.5,
    evaluateNum: 430,
  },
  {
    slug: 'shenji-new-village',
    title: '審計新村',
    description: '老舊宿舍群活化再利用的文創聚落，假日市集活力十足。',
    content:
      '<p>審計新村是臺灣省政府審計處員工宿舍改建而成的文創園區。老舊的日式宿舍與現代文創店鋪交融，假日的勤美市集更吸引大批手作愛好者前來，是臺中最文青的散步好去處。</p>',
    price: 500,
    originPrice: 600,
    address: '臺中市西區民生路368巷',
    category: 'package',
    coordinates: { lat: 24.1493, lng: 120.6635 },
    imagePool: 'oldStreet',
    features: '文創聚落,假日市集,手作體驗,老屋改建,文青打卡',
    transport: '搭乘臺中市公車至審計新村站下車，步行約2分鐘。',
    evaluate: 4.3,
    evaluateNum: 370,
  },
  {
    slug: 'calligraphy-greenway',
    title: '草悟道',
    description: '連結科博館與美術館的城市綠廊，臺中最具人文氣息的散步大道。',
    content:
      '<p>草悟道全長約3.6公里，沿途串聯國立自然科學博物館、勤美誠品綠園道與國立臺灣美術館。寬敞的人行步道兩側林蔭蔽日，街頭藝人表演、特色咖啡廳與文創商店林立，是體驗臺中悠閒生活的最佳路線。</p>',
    price: 650,
    originPrice: 800,
    address: '臺中市西區英才路與向上路之間',
    category: 'package',
    coordinates: { lat: 24.151, lng: 120.6633 },
    imagePool: 'park',
    features: '城市綠廊,藝文散步,咖啡廳,街頭藝人,文創商店',
    transport: '搭乘臺中市公車至科博館站或草悟道站下車。',
    evaluate: 4.4,
    evaluateNum: 310,
  },
  {
    slug: 'luce-chapel',
    title: '東海大學路思義教堂',
    description: '貝聿銘設計的雙曲面教堂，臺灣現代主義建築經典之作。',
    content:
      '<p>路思義教堂由知名建築師貝聿銘與陳其寬共同設計，獨特的雙曲面薄殼結構如同祈禱的雙手合十，是臺灣最具代表性的現代建築。東海大學校園綠蔭盎然，漫步其中感受學術與藝術交織的氛圍。</p>',
    price: 150,
    originPrice: 180,
    address: '臺中市西屯區臺灣大道四段1727號',
    category: 'tickets',
    coordinates: { lat: 24.1792, lng: 120.6003 },
    imagePool: 'city',
    features: '建築藝術,大學校園,教堂巡禮,綠蔭步道,攝影景點',
    transport: '搭乘臺中市公車至東海大學站下車，步行約10分鐘。',
    evaluate: 4.5,
    evaluateNum: 420,
  },
  {
    slug: 'qiuhonggu',
    title: '秋紅谷廣場',
    description: '城市中的下凹式生態公園，白天綠意盎然、夜晚燈光迷人。',
    content:
      '<p>秋紅谷廣場是臺中市中心難得的大型綠地，下凹式的設計形成獨特的湖泊景觀。白天可在湖畔散步欣賞綠意，夜晚周圍高樓大廈的燈光倒映湖面，營造出浪漫迷人的夜景氛圍。</p>',
    price: 80,
    originPrice: 100,
    address: '臺中市西屯區朝富路30號',
    category: 'tickets',
    coordinates: { lat: 24.1646, lng: 120.6389 },
    imagePool: 'park',
    features: '生態公園,夜景,湖畔散步,城市綠地,約會景點',
    transport: '搭乘臺中市公車至秋紅谷站下車。',
    evaluate: 4.2,
    evaluateNum: 280,
  },
  {
    slug: 'parklane',
    title: '勤美誠品綠園道',
    description: '結合藝文展覽與商場的綠色空間，臺中年輕人的聚集地。',
    content:
      '<p>勤美誠品綠園道是臺中最具代表性的藝文商場，外牆整面的植栽綠牆是一大特色。周圍的草地廣場經常舉辦市集與藝文活動，結合誠品書店與特色餐廳，是臺中最具活力的休閒去處。</p>',
    price: 450,
    originPrice: 550,
    address: '臺中市西區公益路68號',
    category: 'package',
    coordinates: { lat: 24.151, lng: 120.6612 },
    imagePool: 'city',
    features: '藝文商場,綠建築,假日市集,書店咖啡,文創活動',
    transport: '搭乘臺中市公車至勤美誠品站下車。',
    evaluate: 4.3,
    evaluateNum: 350,
  },
  {
    slug: 'dakeng-trail',
    title: '大坑步道',
    description: '臺中人的後花園，十二條登山步道各有特色，適合各種體能程度。',
    content:
      '<p>大坑風景區擁有十二條編號步道，其中九、十號步道平緩易行適合親子，五、六號步道以相思圓木棧道聞名，挑戰性十足。登頂後可俯瞰臺中市區全景，是臺中市民最愛的假日健行去處。</p>',
    price: 700,
    originPrice: 880,
    address: '臺中市北屯區東山路二段',
    category: 'package',
    coordinates: { lat: 24.1835, lng: 120.7341 },
    imagePool: 'mountain',
    features: '登山健行,圓木棧道,市區全景,親子步道,自然生態',
    transport: '搭乘臺中客運66路至大坑站下車。',
    evaluate: 4.4,
    evaluateNum: 510,
  },
  {
    slug: 'yizhong-street',
    title: '一中商圈',
    description: '臺中最熱鬧的學生商圈，平價美食與流行服飾的天堂。',
    content:
      '<p>一中商圈位於臺中一中與中國醫藥大學之間，是臺中最具青春活力的商圈。這裡聚集了各種平價美食、潮流服飾與娛樂場所，滷味、雞排、珍珠奶茶等銅板美食更是不容錯過的好滋味。</p>',
    price: 750,
    originPrice: 900,
    address: '臺中市北區一中街',
    category: 'package',
    coordinates: { lat: 24.1497, lng: 120.6843 },
    imagePool: 'nightMarket',
    features: '學生商圈,平價美食,流行服飾,青春活力,銅板小吃',
    transport: '搭乘臺中市公車至臺中一中站下車。',
    evaluate: 4.1,
    evaluateNum: 440,
  },
  {
    slug: 'flora-expo-park',
    title: '台中花博公園',
    description: '花博遺址改建的都市公園，四季花卉綻放的繽紛園區。',
    content:
      '<p>台中花博公園保留了2018年世界花卉博覽會的精華，園區內四季花卉輪番綻放。大型裝置藝術與綠意盎然的步道交錯，加上不定期的主題花展與園藝教學，是臺中市民親近自然的最佳選擇。</p>',
    price: 150,
    originPrice: 180,
    address: '臺中市后里區堤防路',
    category: 'tickets',
    coordinates: { lat: 24.3133, lng: 120.7105 },
    imagePool: 'park',
    features: '花卉展覽,裝置藝術,園藝教學,親子景點,戶外休閒',
    transport: '搭乘臺鐵至后里站，步行約15分鐘。',
    evaluate: 4.2,
    evaluateNum: 290,
  },
  {
    slug: 'wufeng-lin-house',
    title: '霧峰林家宅園',
    description: '臺灣五大家族之一的百年宅邸，國定古蹟巡禮體驗。',
    content:
      '<p>霧峰林家是臺灣最具代表性的傳統建築群之一，包含頂厝、下厝與萊園三大區域。宅園融合閩南、日式與西洋建築風格，見證了臺灣近代史的興衰更迭，導覽解說讓你深入了解林家的傳奇故事。</p>',
    price: 250,
    originPrice: 300,
    address: '臺中市霧峰區民生路26號',
    category: 'tickets',
    coordinates: { lat: 24.061, lng: 120.6996 },
    imagePool: 'temple',
    features: '國定古蹟,傳統建築,歷史導覽,閩南文化,園林景觀',
    transport: '搭乘臺中客運100、107路至霧峰站，步行約5分鐘。',
    evaluate: 4.3,
    evaluateNum: 210,
  },
  {
    slug: 'xinshe-castle',
    title: '新社古堡',
    description: '歐式城堡風格的莊園，花園、瀑布與城堡交織的夢幻場景。',
    content:
      '<p>新社古堡莊園以歐洲中世紀古堡為設計概念，園區內有石砌城堡、木橋、瀑布與花園，彷彿置身於歐洲小鎮。每年秋季的新社花海更是臺中最盛大的花卉盛事，吸引數十萬遊客前來賞花。</p>',
    price: 350,
    originPrice: 420,
    address: '臺中市新社區協成里協中街65號',
    category: 'tickets',
    coordinates: { lat: 24.2231, lng: 120.7924 },
    imagePool: 'park',
    features: '歐式城堡,花園景觀,瀑布,拍照打卡,新社花海',
    transport: '搭乘豐原客運270、271路至新社站，轉搭計程車約10分鐘。',
    evaluate: 4.1,
    evaluateNum: 360,
  },
  {
    slug: 'wuling-farm',
    title: '武陵農場',
    description: '海拔1750公尺的高山農場，櫻花季與楓紅時節美不勝收。',
    content:
      '<p>武陵農場位於雪霸國家公園境內，四季皆有不同風情。春天的粉紅佳人櫻花大道聞名全臺，夏季桃李結實纍纍，秋季楓紅遍野，冬季偶有雪景。園區內的步道更是觀賞臺灣鉤吻鮭的重要據點。</p>',
    price: 2800,
    originPrice: 3500,
    address: '臺中市和平區武陵路3-1號',
    category: 'package',
    coordinates: { lat: 24.3587, lng: 121.3103 },
    imagePool: 'mountain',
    features: '高山農場,櫻花季,楓紅,臺灣鉤吻鮭,四季景觀',
    transport: '搭乘國光客運1751路至武陵農場站（需預約）。',
    evaluate: 4.8,
    evaluateNum: 650,
  },
  {
    slug: 'fushoushan-farm',
    title: '福壽山農場',
    description: '海拔2100公尺的世外桃源，蘋果、水蜜桃與雲海的夢幻農場。',
    content:
      '<p>福壽山農場是臺灣最高的農場之一，以種植溫帶水果聞名。春天的桃花、夏天的高山蔬果、秋天的松廬楓紅與冬天的雪景各有風情。清晨的雲海與星空更是攝影愛好者的朝聖之地。</p>',
    price: 2500,
    originPrice: 3000,
    address: '臺中市和平區梨山里福壽路29號',
    category: 'package',
    coordinates: { lat: 24.2527, lng: 121.238 },
    imagePool: 'mountain',
    features: '高山農場,雲海,楓紅,溫帶水果,星空攝影',
    transport: '搭乘豐原客運865路至梨山站，轉搭場區接駁車。',
    evaluate: 4.7,
    evaluateNum: 480,
  },
  {
    slug: 'dajia-mazu-temple',
    title: '大甲鎮瀾宮',
    description: '臺灣最重要的媽祖廟之一，大甲媽祖遶境享譽國際。',
    content:
      '<p>大甲鎮瀾宮創建於清雍正年間，是臺灣媽祖信仰的重要中心。每年農曆三月的大甲媽祖遶境進香活動被譽為世界三大宗教盛事之一，廟宇建築精美、雕梁畫棟，展現了傳統宮廟藝術的極致。</p>',
    price: 500,
    originPrice: 600,
    address: '臺中市大甲區順天路158號',
    category: 'package',
    coordinates: { lat: 24.3488, lng: 120.6222 },
    imagePool: 'temple',
    features: '媽祖信仰,宮廟藝術,遶境文化,歷史古蹟,民俗體驗',
    transport: '搭乘臺鐵至大甲站，步行約5分鐘。',
    evaluate: 4.5,
    evaluateNum: 380,
  },
  {
    slug: 'guguan-hot-spring',
    title: '谷關溫泉',
    description: '中部橫貫公路上的溫泉勝地，弱鹼性碳酸泉質潤膚養生。',
    content:
      '<p>谷關溫泉位於大甲溪畔，泉質屬弱鹼性碳酸泉，水質清澈無硫磺味，素有「美人湯」之稱。周圍群山環繞、溪谷幽靜，泡湯之餘還可走訪捎來步道與谷關吊橋，享受山林間的悠閒時光。</p>',
    price: 1200,
    originPrice: 1500,
    address: '臺中市和平區東關路一段',
    category: 'package',
    coordinates: { lat: 24.2001, lng: 120.9958 },
    imagePool: 'hotSpring',
    features: '溫泉泡湯,美人湯,山林景觀,步道健行,溪谷風光',
    transport: '搭乘豐原客運850路至谷關站下車。',
    evaluate: 4.6,
    evaluateNum: 420,
  },
  {
    slug: 'central-park',
    title: '台中中央公園',
    description: '佔地67公頃的都市森林公園，智慧互動裝置打造未來公園體驗。',
    content:
      '<p>台中中央公園是水湳經貿園區內的大型都市公園，以「智慧」、「低碳」、「創新」為設計核心。園區內設有12感官互動裝置，結合生態滯洪與綠能設施，是臺中最具前瞻性的都市綠地空間。</p>',
    price: 80,
    originPrice: 100,
    address: '臺中市西屯區中科路2966號',
    category: 'tickets',
    coordinates: { lat: 24.1856, lng: 120.6364 },
    imagePool: 'park',
    features: '都市公園,智慧互動,生態綠地,散步慢跑,親子遊憩',
    transport: '搭乘臺中市公車至中央公園站下車。',
    evaluate: 4.1,
    evaluateNum: 260,
  },
  {
    slug: 'literature-museum',
    title: '台中文學館',
    description: '日治時期警察宿舍改建的文學園區，老樹環繞的靜謐空間。',
    content:
      '<p>台中文學館由六棟日式木造建築組成，前身為日治時期的警察宿舍群。園區保留了百年老榕樹與日式庭園，常設展覽介紹臺中文學發展脈絡，不定期舉辦文學講座與工作坊，是喧囂都市中的一方淨土。</p>',
    price: 120,
    originPrice: 150,
    address: '臺中市西區樂群街38號',
    category: 'tickets',
    coordinates: { lat: 24.1404, lng: 120.6716 },
    imagePool: 'oldStreet',
    features: '日式建築,文學展覽,百年老樹,庭園散步,文化講座',
    transport: '搭乘臺中市公車至第五市場站下車，步行約3分鐘。',
    evaluate: 4.2,
    evaluateNum: 180,
  },
  {
    slug: 'wanggaoliao',
    title: '望高寮夜景公園',
    description: '臺中最佳夜景觀賞點，可一覽臺中盆地與彰化平原的萬家燈火。',
    content:
      '<p>望高寮位於大肚山上，海拔約270公尺，是臺中市區最佳的夜景觀賞點。從觀景台可以俯瞰整個臺中盆地，夕陽西下時金黃色的光芒灑落，入夜後萬家燈火璀璨，浪漫氛圍令人陶醉。</p>',
    price: 550,
    originPrice: 680,
    address: '臺中市南屯區中台路601號',
    category: 'package',
    coordinates: { lat: 24.1268, lng: 120.5913 },
    imagePool: 'city',
    features: '夜景觀賞,夕陽美景,觀景台,約會聖地,攝影推薦',
    transport: '搭乘臺中客運26路至望高寮站下車，步行約10分鐘。',
    evaluate: 4.5,
    evaluateNum: 320,
  },
  {
    slug: 'guangfu-new-village',
    title: '光復新村',
    description: '臺灣第一個新市鎮計畫的眷村聚落，文創工作室進駐的藝術小鎮。',
    content:
      '<p>光復新村建於1950年代，是臺灣第一個以花園城市概念規劃的市鎮。經過活化再利用，老眷村房舍進駐了各種文創工作室、手作店鋪與咖啡廳。漫步在綠蔭蔽日的巷弄間，感受時光靜好的老社區魅力。</p>',
    price: 450,
    originPrice: 550,
    address: '臺中市霧峰區和平路2號',
    category: 'package',
    coordinates: { lat: 24.0552, lng: 120.6873 },
    imagePool: 'oldStreet',
    features: '眷村文化,文創工作室,手作體驗,咖啡廳,老屋巡禮',
    transport: '搭乘臺中客運100、107路至光復新村站下車。',
    evaluate: 4.2,
    evaluateNum: 190,
  },
  {
    slug: 'taichung-prefectural-hall',
    title: '台中州廳',
    description: '日治時期的巴洛克式官署建築，見證臺中百年行政中心的歷史。',
    content:
      '<p>台中州廳建於1913年，是臺灣現存最完整的日治時期官署建築之一。巴洛克式的立面、圓頂與迴廊展現了殖民時期的建築美學，歷經修復後開放參觀，是了解臺中城市發展史的重要窗口。</p>',
    price: 100,
    originPrice: 120,
    address: '臺中市西區民權路99號',
    category: 'tickets',
    coordinates: { lat: 24.1418, lng: 120.678 },
    imagePool: 'museum',
    features: '巴洛克建築,歷史古蹟,建築導覽,殖民歷史,攝影景點',
    transport: '搭乘臺中市公車至臺中市政府站下車，步行約3分鐘。',
    evaluate: 4.1,
    evaluateNum: 150,
  },
  {
    slug: 'daya-wheat-field',
    title: '大雅小麥田',
    description: '臺灣罕見的小麥產區，金黃麥浪隨風搖曳的田園美景。',
    content:
      '<p>大雅是臺灣少數種植小麥的地區，每年三月小麥成熟時，金黃色的麥田在微風中搖曳，形成如畫般的田園風光。大雅小麥文化節更結合在地農特產體驗，讓遊客親近土地、認識臺灣農業。</p>',
    price: 500,
    originPrice: 620,
    address: '臺中市大雅區神林路一段',
    category: 'package',
    coordinates: { lat: 24.2218, lng: 120.6487 },
    imagePool: 'nature',
    features: '小麥田園,農業體驗,田園風光,季節限定,在地文化',
    transport: '搭乘臺中市公車至大雅站下車，轉搭計程車約10分鐘。',
    evaluate: 4.0,
    evaluateNum: 120,
  },
  {
    slug: 'fazih-creek-corridor',
    title: '筏子溪迎賓廊道',
    description: '巨大的「TAICHUNG」地標字樣，臺中高鐵站旁的打卡新景點。',
    content:
      '<p>筏子溪迎賓廊道以大型的「TAICHUNG」英文字樣地標聞名，搭配河畔的景觀步道與自行車道，是臺中近年最熱門的打卡景點。傍晚時分夕陽映照溪面，與地標合影留念成為到訪臺中的必備行程。</p>',
    price: 80,
    originPrice: 100,
    address: '臺中市南屯區筏子東街一段',
    category: 'tickets',
    coordinates: { lat: 24.1175, lng: 120.6375 },
    imagePool: 'city',
    features: '地標打卡,河畔步道,自行車道,夕陽美景,免費景點',
    transport: '搭乘高鐵至臺中站，步行約10分鐘。',
    evaluate: 4.0,
    evaluateNum: 250,
  },
  {
    slug: 'wuqi-fishing-port',
    title: '梧棲觀光漁港',
    description: '中部最大的觀光漁港，新鮮海產與海風相伴的港灣體驗。',
    content:
      '<p>梧棲觀光漁港位於臺中港旁，是中臺灣最重要的漁獲集散地。漁港內的魚市場販售各種新鮮海產，現場代客料理讓你品嚐最新鮮的海味。港邊步道可以欣賞漁船進出與海上落日，是海鮮愛好者的天堂。</p>',
    price: 900,
    originPrice: 1100,
    address: '臺中市清水區海濱里北堤路30號',
    category: 'package',
    coordinates: { lat: 24.2946, lng: 120.5278 },
    imagePool: 'beach',
    features: '觀光漁港,新鮮海產,代客料理,港灣風光,海鮮美食',
    transport: '搭乘臺中客運306、307路至梧棲觀光漁港站下車。',
    evaluate: 4.3,
    evaluateNum: 380,
  },
]
