import type { ProductDefinition } from '../types'

export const tainanProducts: ProductDefinition[] = [
  {
    slug: 'chihkan-tower',
    title: '赤崁樓',
    description: '荷蘭時期普羅民遮城遺址，臺南最具代表性的歷史古蹟。',
    content:
      '<p>赤崁樓建於1653年荷蘭統治時期，原名普羅民遮城，是臺灣最重要的古蹟之一。經過清代多次改建，現存的海神廟與文昌閣展現了中西合璧的建築特色，九座贔屭碑更是不可錯過的歷史瑰寶。</p>',
    price: 150,
    originPrice: 180,
    address: '臺南市中西區民族路二段212號',
    category: 'tickets',
    coordinates: { lat: 22.9975, lng: 120.2024 },
    imagePool: 'temple',
    features: '歷史古蹟,荷蘭遺址,建築巡禮,贔屭碑,文化導覽',
    transport: '搭乘臺南市公車3、5路至赤崁樓站下車。',
    evaluate: 4.4,
    evaluateNum: 620,
  },
  {
    slug: 'anping-fort',
    title: '安平古堡',
    description: '臺灣第一座城堡，見證荷治、明鄭到清代的四百年滄桑歲月。',
    content:
      '<p>安平古堡原為荷蘭人所建的「熱蘭遮城」，是臺灣最古老的城堡遺跡。園區內保留了荷蘭時期的城牆遺跡與瞭望台，登上瞭望台可以遠眺安平港與臺灣海峽，是認識臺灣開拓史的必訪之地。</p>',
    price: 200,
    originPrice: 250,
    address: '臺南市安平區國勝路82號',
    category: 'tickets',
    coordinates: { lat: 23.0015, lng: 120.1604 },
    imagePool: 'temple',
    features: '四百年古蹟,荷蘭城堡,瞭望台,歷史遺跡,安平老街',
    transport: '搭乘臺南市公車2路至安平古堡站下車。',
    evaluate: 4.3,
    evaluateNum: 580,
  },
  {
    slug: 'chimei-museum',
    title: '奇美博物館',
    description: '歐式宮殿風格的私人博物館，典藏西洋藝術與自然史的殿堂。',
    content:
      '<p>奇美博物館由奇美實業創辦人許文龍先生創立，以西洋古典宮殿風格建築聞名。館內收藏了大量西洋繪畫、雕塑、樂器與自然史標本，戶外的阿波羅噴泉廣場更是臺南最具話題性的拍照景點。</p>',
    price: 400,
    originPrice: 500,
    address: '臺南市仁德區文華路二段66號',
    category: 'tickets',
    coordinates: { lat: 22.9349, lng: 120.2266 },
    imagePool: 'museum',
    features: '西洋藝術,宮殿建築,自然史,樂器收藏,噴泉廣場',
    transport: '搭乘臺南市公車紅3、紅4路至奇美博物館站下車。',
    evaluate: 4.8,
    evaluateNum: 780,
  },
  {
    slug: 'garden-night-market',
    title: '花園夜市美食導覽',
    description: '臺南最大夜市的在地美食巡禮，跟著達人吃遍經典小吃。',
    content:
      '<p>花園夜市是臺南規模最大的流動夜市，每週四、六、日開市。跟隨在地美食達人的腳步，品嚐棺材板、鱔魚意麵、沙茶牛肉、蚵仔煎等臺南經典小吃，體驗最道地的臺南夜市文化。</p>',
    price: 899,
    originPrice: 1100,
    address: '臺南市北區海安路三段533號',
    category: 'package',
    coordinates: { lat: 23.018, lng: 120.1958 },
    imagePool: 'nightMarket',
    features: '夜市美食,在地導覽,棺材板,鱔魚意麵,臺南小吃',
    transport: '搭乘臺南市公車0右至花園夜市站下車。',
    evaluate: 4.6,
    evaluateNum: 550,
  },
  {
    slug: 'confucius-temple',
    title: '台南孔廟',
    description: '全臺首學，臺灣最早的孔廟，三百多年的儒學文化聖地。',
    content:
      '<p>台南孔廟建於1665年明鄭時期，是全臺灣第一座孔廟，素有「全臺首學」之稱。紅牆綠瓦的傳統建築莊嚴典雅，大成殿前的半月池與古榕樹相映成趣。周圍的府中街更是文青散步的好去處。</p>',
    price: 120,
    originPrice: 150,
    address: '臺南市中西區南門路2號',
    category: 'tickets',
    coordinates: { lat: 22.9901, lng: 120.2039 },
    imagePool: 'temple',
    features: '全臺首學,儒學文化,傳統建築,紅牆綠瓦,府中街',
    transport: '搭乘臺南市公車1、2路至孔廟站下車。',
    evaluate: 4.4,
    evaluateNum: 450,
  },
  {
    slug: 'shennong-street',
    title: '神農街',
    description: '清代商行老街復興為文青藝術街區，夜晚燈籠映照更添風情。',
    content:
      '<p>神農街是臺南五條港文化園區最具代表性的街道，保留了清代的街屋格局。白天可以探訪各式文創小店、手作工坊與藝廊，夜晚紅燈籠亮起，整條街道瀰漫著懷舊浪漫的氛圍，是臺南最具韻味的老街。</p>',
    price: 600,
    originPrice: 750,
    address: '臺南市中西區神農街',
    category: 'package',
    coordinates: { lat: 22.9983, lng: 120.1955 },
    imagePool: 'oldStreet',
    features: '老街巡禮,文創小店,紅燈籠,夜間散步,清代街屋',
    transport: '搭乘臺南市公車至水仙宮站下車，步行約3分鐘。',
    evaluate: 4.5,
    evaluateNum: 470,
  },
  {
    slug: 'hayashi-department',
    title: '林百貨',
    description: '臺南第一間百貨公司，日治時期摩登建築的復古風華。',
    content:
      '<p>林百貨建於1932年，是當時臺南最高的建築，也是全臺第二間百貨公司。歷經修復後重新開幕，保留了日治時期的電梯、神社鳥居與彈痕牆面，現在販售臺南在地文創商品，是古蹟活化的典範。</p>',
    price: 200,
    originPrice: 240,
    address: '臺南市中西區忠義路二段63號',
    category: 'tickets',
    coordinates: { lat: 22.9919, lng: 120.201 },
    imagePool: 'city',
    features: '日治建築,復古百貨,文創商品,古蹟活化,頂樓神社',
    transport: '搭乘臺南市公車至林百貨站下車。',
    evaluate: 4.3,
    evaluateNum: 510,
  },
  {
    slug: 'anping-old-street',
    title: '安平老街',
    description: '臺灣第一條老街，傳統美食與古厝交織的歷史街區。',
    content:
      '<p>安平老街是臺灣歷史最悠久的街道，延平街上保留了許多清代與日治時期的傳統建築。蝦餅、蜜餞、豆花等傳統小吃飄香四溢，老街巷弄間的劍獅裝飾更是安平獨特的文化符號，值得細細品味。</p>',
    price: 750,
    originPrice: 900,
    address: '臺南市安平區延平街',
    category: 'package',
    coordinates: { lat: 23.0012, lng: 120.1623 },
    imagePool: 'oldStreet',
    features: '歷史老街,傳統小吃,劍獅文化,古厝巡禮,蝦餅蜜餞',
    transport: '搭乘臺南市公車2路至安平老街站下車。',
    evaluate: 4.4,
    evaluateNum: 530,
  },
  {
    slug: 'sicao-green-tunnel',
    title: '四草綠色隧道',
    description: '紅樹林形成的天然水上綠色隧道，被譽為臺灣版亞馬遜河。',
    content:
      '<p>四草綠色隧道由紅樹林交織而成的天然拱形樹冠，搭乘竹筏穿梭其間，彷彿進入了一座水上森林。陽光穿透枝葉灑落水面，光影交錯美不勝收，是臺南最獨特的生態旅遊體驗。</p>',
    price: 350,
    originPrice: 420,
    address: '臺南市安南區大眾路360號',
    category: 'tickets',
    coordinates: { lat: 23.0327, lng: 120.144 },
    imagePool: 'nature',
    features: '紅樹林,竹筏遊船,生態導覽,水上隧道,臺灣亞馬遜',
    transport: '搭乘臺南市公車10路至四草站下車，步行約5分鐘。',
    evaluate: 4.7,
    evaluateNum: 650,
  },
  {
    slug: 'eternal-golden-castle',
    title: '億載金城',
    description: '清代劉銘傳所建的西式砲台，見證臺灣海防歷史的重要古蹟。',
    content:
      '<p>億載金城建於1876年，是臺灣第一座西式砲台，為防禦日軍侵犯而建。城池採用方形稜堡設計，護城河環繞四周。園區內保留了阿姆斯壯大砲複製品，綠蔭蔽日的環境也是市民散步的好去處。</p>',
    price: 100,
    originPrice: 120,
    address: '臺南市安平區光州路3號',
    category: 'tickets',
    coordinates: { lat: 22.9884, lng: 120.1571 },
    imagePool: 'park',
    features: '西式砲台,海防歷史,護城河,古蹟巡禮,綠蔭散步',
    transport: '搭乘臺南市公車14路至億載金城站下車。',
    evaluate: 4.1,
    evaluateNum: 280,
  },
  {
    slug: 'tainan-art-museum',
    title: '台南美術館',
    description: '日本建築大師坂茂設計的當代美術館，臺南最新藝文地標。',
    content:
      '<p>台南美術館分為一館與二館，一館由警察署改建保留日治建築之美，二館由普利茲克獎得主坂茂設計，獨特的碎形遮陽屋頂成為臺南新地標。館內展出臺灣近現代藝術作品，是藝術愛好者的朝聖之地。</p>',
    price: 300,
    originPrice: 360,
    address: '臺南市中西區忠義路二段1號',
    category: 'tickets',
    coordinates: { lat: 22.9906, lng: 120.2042 },
    imagePool: 'museum',
    features: '當代藝術,坂茂建築,碎形屋頂,臺灣藝術,建築美學',
    transport: '搭乘臺南市公車至孔廟站下車，步行約3分鐘。',
    evaluate: 4.6,
    evaluateNum: 490,
  },
  {
    slug: 'blueprint-cultural-park',
    title: '藍晒圖文創園區',
    description: '舊司法宿舍群改建的文創園區，藍色建築外牆成為打卡熱點。',
    content:
      '<p>藍晒圖文創園區前身為日治時期的司法宿舍，以3D藍晒圖藝術牆聞名。園區進駐了各式文創品牌、獨立書店、手作工坊與特色餐飲，定期舉辦市集與藝文活動，是臺南年輕人最愛的文創聚落。</p>',
    price: 500,
    originPrice: 600,
    address: '臺南市南區西門路一段689巷',
    category: 'package',
    coordinates: { lat: 22.9837, lng: 120.1988 },
    imagePool: 'city',
    features: '文創園區,藍晒圖,手作工坊,文青聚落,藝文市集',
    transport: '搭乘臺南市公車至藍晒圖文創園區站下車。',
    evaluate: 4.2,
    evaluateNum: 340,
  },
  {
    slug: 'taijiang-national-park',
    title: '台江國家公園',
    description: '臺灣第八座國家公園，濕地生態與黑面琵鷺的棲息天堂。',
    content:
      '<p>台江國家公園涵蓋了臺南沿海的濕地、潟湖與紅樹林生態系統。每年冬季大量黑面琵鷺到此過冬，是全球最重要的黑面琵鷺棲息地。搭船遊潟湖、觀賞候鳥、體驗蚵架風光，感受臺灣西南海岸的自然之美。</p>',
    price: 1200,
    originPrice: 1500,
    address: '臺南市安南區四草大道118號',
    category: 'package',
    coordinates: { lat: 23.0393, lng: 120.1296 },
    imagePool: 'nature',
    features: '國家公園,黑面琵鷺,濕地生態,潟湖遊船,候鳥觀察',
    transport: '搭乘臺南市公車10路至四草大橋站下車。',
    evaluate: 4.5,
    evaluateNum: 380,
  },
  {
    slug: 'guanziling-hot-spring',
    title: '關子嶺溫泉',
    description: '全臺唯一的泥漿溫泉，百年溫泉鄉的養生泡湯體驗。',
    content:
      '<p>關子嶺溫泉是臺灣四大溫泉之一，以獨特的灰黑色泥漿泉質聞名，被稱為「黑色溫泉」或「泥巴溫泉」。泥漿富含礦物質，泡湯後肌膚滑嫩。周圍的水火同源、大仙寺與碧雲寺也是值得走訪的景點。</p>',
    price: 1500,
    originPrice: 1800,
    address: '臺南市白河區關子嶺',
    category: 'package',
    coordinates: { lat: 23.3438, lng: 120.5133 },
    imagePool: 'hotSpring',
    features: '泥漿溫泉,黑色溫泉,養生泡湯,水火同源,百年溫泉鄉',
    transport: '搭乘大臺南公車黃12至關子嶺站下車。',
    evaluate: 4.6,
    evaluateNum: 420,
  },
  {
    slug: 'jingzaijiao-salt-fields',
    title: '井仔腳瓦盤鹽田',
    description: '臺灣現存最古老的瓦盤鹽田，夕陽映照鹽田的絕美風景。',
    content:
      '<p>井仔腳瓦盤鹽田有超過二百年歷史，是臺灣現存最古老且仍在運作的鹽田。遊客可以親身體驗曬鹽、收鹽的傳統製鹽過程。黃昏時分，夕陽將鹽田染成一片金黃與火紅，是臺南最夢幻的攝影景點。</p>',
    price: 500,
    originPrice: 600,
    address: '臺南市北門區永華里井仔腳',
    category: 'package',
    coordinates: { lat: 23.2839, lng: 120.127 },
    imagePool: 'beach',
    features: '古老鹽田,曬鹽體驗,夕陽美景,攝影景點,文化體驗',
    transport: '搭乘大臺南公車藍1至井仔腳站下車。',
    evaluate: 4.5,
    evaluateNum: 360,
  },
  {
    slug: 'hutoupi',
    title: '虎頭埤風景區',
    description: '臺灣第一座水庫，湖光山色環繞的百年風景區。',
    content:
      '<p>虎頭埤建於1846年，是臺灣最早興建的水庫。湖面碧波蕩漾，四周青山環繞，園區內設有環湖步道、烤肉區與露營場地。春季阿勃勒黃花盛開，被譽為「小日月潭」，是臺南近郊最佳的休閒去處。</p>',
    price: 200,
    originPrice: 250,
    address: '臺南市新化區中興路42巷36號',
    category: 'tickets',
    coordinates: { lat: 23.0582, lng: 120.3348 },
    imagePool: 'nature',
    features: '百年水庫,環湖步道,阿勃勒,露營烤肉,小日月潭',
    transport: '搭乘大臺南公車綠幹線至虎頭埤站下車。',
    evaluate: 4.2,
    evaluateNum: 220,
  },
  {
    slug: 'shanshang-waterworks',
    title: '山上花園水道博物館',
    description: '日治時期水道設施改建的博物館，工業遺產與花園的完美結合。',
    content:
      '<p>山上花園水道博物館保存了日治時期完整的淨水設施，包含快濾池室、送出唧筒室等壯觀的紅磚建築。園區結合了花園景觀與水道歷史，館內的巨型機械設備讓人驚嘆百年前的工程技術。</p>',
    price: 250,
    originPrice: 300,
    address: '臺南市山上區山上里山上16號',
    category: 'tickets',
    coordinates: { lat: 23.101, lng: 120.3675 },
    imagePool: 'museum',
    features: '水道博物館,工業遺產,紅磚建築,花園景觀,淨水設施',
    transport: '搭乘大臺南公車綠幹線至山上站下車，步行約15分鐘。',
    evaluate: 4.4,
    evaluateNum: 310,
  },
  {
    slug: 'snail-alley',
    title: '蝸牛巷',
    description: '隱藏在巷弄間的袖珍藝術街區，尋找牆上蝸牛的探索樂趣。',
    content:
      '<p>蝸牛巷是臺南市中心一條充滿巧思的小巷，以臺南文學家葉石濤的作品為靈感，在巷弄牆面與角落放置了各種蝸牛裝置藝術。漫步其中像是一場尋寶遊戲，每個轉角都可能發現令人會心一笑的小驚喜。</p>',
    price: 350,
    originPrice: 420,
    address: '臺南市中西區永福路二段97巷',
    category: 'package',
    coordinates: { lat: 22.9949, lng: 120.201 },
    imagePool: 'oldStreet',
    features: '巷弄探索,裝置藝術,文學散步,蝸牛尋寶,拍照打卡',
    transport: '搭乘臺南市公車至西門路站下車，步行約5分鐘。',
    evaluate: 4.1,
    evaluateNum: 200,
  },
  {
    slug: 'yuguang-island',
    title: '漁光島',
    description: '臺南最美秘境沙灘，月牙形海灣與防風林的靜謐天堂。',
    content:
      '<p>漁光島是安平港旁的一座小島，以月牙形的沙灘與茂密的防風林聞名。黃昏時分的夕陽從海平面落下，金黃色的光芒灑在沙灘上，浪漫至極。每年的漁光島藝術節更以大型裝置藝術為小島增添藝文氣息。</p>',
    price: 700,
    originPrice: 850,
    address: '臺南市安平區漁光路114號',
    category: 'package',
    coordinates: { lat: 22.9862, lng: 120.1473 },
    imagePool: 'beach',
    features: '秘境沙灘,夕陽美景,防風林,藝術節,月牙海灣',
    transport: '搭乘臺南市公車2路至漁光島站下車。',
    evaluate: 4.5,
    evaluateNum: 390,
  },
  {
    slug: 'zuojin-fossil-park',
    title: '左鎮化石園區',
    description: '臺灣唯一的化石主題博物館，探索數百萬年前的遠古世界。',
    content:
      '<p>左鎮化石園區展示了臺南左鎮地區出土的豐富化石，包含早坂犀牛、梅花鹿、古象等珍貴標本。互動式的展覽設計讓大人小孩都能認識臺灣的古生物歷史，彷彿穿越時空回到數百萬年前的臺灣。</p>',
    price: 300,
    originPrice: 360,
    address: '臺南市左鎮區榮和里61-1號',
    category: 'tickets',
    coordinates: { lat: 23.057, lng: 120.3962 },
    imagePool: 'museum',
    features: '化石博物館,古生物,互動展覽,親子教育,早坂犀牛',
    transport: '搭乘大臺南公車綠幹線至左鎮站下車，步行約10分鐘。',
    evaluate: 4.3,
    evaluateNum: 270,
  },
  {
    slug: 'danei-totoro',
    title: '大內龍貓公車站',
    description: '隱藏在鄉間的彩繪村，宮崎駿動畫主題的童趣壁畫。',
    content:
      '<p>大內龍貓公車站是臺南大內區石林里的一處彩繪村，以宮崎駿動畫「龍貓」為主題的壁畫聞名。等比例的龍貓公車站牌與各種動畫角色栩栩如生，是動漫迷與親子家庭的打卡聖地，充滿童趣與歡樂。</p>',
    price: 450,
    originPrice: 550,
    address: '臺南市大內區石城里石林10-18號',
    category: 'package',
    coordinates: { lat: 23.1319, lng: 120.3483 },
    imagePool: 'city',
    features: '彩繪村,龍貓主題,童趣壁畫,親子打卡,動漫文化',
    transport: '搭乘大臺南公車橘幹線至大內站下車，步行約15分鐘。',
    evaluate: 3.9,
    evaluateNum: 160,
  },
  {
    slug: 'nanke-archaeology',
    title: '南科考古館',
    description: '臺灣史前文化的寶庫，五千年前的人類生活遺跡在此重現。',
    content:
      '<p>南科考古館坐落於臺南科學園區內，展示了園區開發過程中發掘的大量史前文化遺跡。從大坌坑文化到西拉雅族，跨越五千年的人類足跡在此一一呈現。黃色建築外觀與互動式展覽設計，讓考古知識生動有趣。</p>',
    price: 200,
    originPrice: 250,
    address: '臺南市新市區南科三路10號',
    category: 'tickets',
    coordinates: { lat: 23.1055, lng: 120.2725 },
    imagePool: 'museum',
    features: '考古博物館,史前文化,互動展覽,五千年歷史,親子教育',
    transport: '搭乘大臺南公車至南科考古館站下車。',
    evaluate: 4.4,
    evaluateNum: 290,
  },
  {
    slug: 'cigu-salt-mountain',
    title: '七股鹽山',
    description: '白色鹽山矗立於藍天下，臺灣曬鹽產業的歷史見證。',
    content:
      '<p>七股鹽山是臺灣西南沿海鹽業文化的象徵，高達六層樓的白色鹽山在豔陽下閃閃發光。園區內可以體驗踩鹽山、品嚐鹽味冰棒，還有鹽雕展覽與臺鹽歷史介紹，是認識臺灣鹽業文化的最佳去處。</p>',
    price: 250,
    originPrice: 300,
    address: '臺南市七股區鹽埕里66號',
    category: 'tickets',
    coordinates: { lat: 23.1597, lng: 120.1064 },
    imagePool: 'nature',
    features: '鹽山體驗,鹽業文化,鹽味冰棒,鹽雕展覽,產業歷史',
    transport: '搭乘大臺南公車藍1至七股鹽山站下車。',
    evaluate: 4.0,
    evaluateNum: 350,
  },
  {
    slug: 'xuanzang-temple',
    title: '玄奘寺',
    description: '供奉玄奘法師頂骨舍利的莊嚴佛寺，清幽的山林古剎。',
    content:
      '<p>臺南玄奘寺位於玄奘大學附近，是供奉玄奘法師的重要佛教寺院。寺院建築融合唐式風格與現代設計，清幽的環境讓人心靈沉靜。每年佛誕節與玄奘法師紀念日會舉辦盛大法會，吸引眾多信徒前來朝拜。</p>',
    price: 80,
    originPrice: 100,
    address: '臺南市玉井區沙田里56號',
    category: 'tickets',
    coordinates: { lat: 23.1208, lng: 120.46 },
    imagePool: 'temple',
    features: '佛教寺院,唐式建築,清幽古剎,宗教文化,心靈沉靜',
    transport: '搭乘大臺南公車綠幹線至玉井站下車，轉搭計程車約10分鐘。',
    evaluate: 4.0,
    evaluateNum: 100,
  },
  {
    slug: 'xinhua-old-street',
    title: '新化老街',
    description: '巴洛克式街屋保存完好的小鎮老街，品味臺南鄉鎮的慢活風情。',
    content:
      '<p>新化老街擁有全臺保存最完整的巴洛克式街屋群，華麗的立面裝飾展現了日治時期的商業繁榮。老街上的特色小吃、傳統糕餅與在地手工藝品令人流連忘返，漫步其中感受小鎮特有的悠閒節奏。</p>',
    price: 650,
    originPrice: 800,
    address: '臺南市新化區中正路',
    category: 'package',
    coordinates: { lat: 23.038, lng: 120.3106 },
    imagePool: 'oldStreet',
    features: '巴洛克街屋,小鎮漫步,傳統糕餅,日治建築,慢活風情',
    transport: '搭乘大臺南公車綠幹線至新化站下車。',
    evaluate: 4.2,
    evaluateNum: 180,
  },
  {
    slug: 'shanhua-sugar-factory',
    title: '善化糖廠',
    description: '百年糖廠的懷舊散步，必吃的古早味紅豆冰棒。',
    content:
      '<p>善化糖廠創立於1905年，是臺南現存的百年糖業遺跡。園區保留了日式宿舍群、糖廠煙囪與製糖設備，漫步其中充滿懷舊氛圍。最受歡迎的是糖廠冰品部販售的紅豆冰棒與芋頭冰，是臺南人記憶中的古早好味道。</p>',
    price: 400,
    originPrice: 480,
    address: '臺南市善化區溪美里228號',
    category: 'package',
    coordinates: { lat: 23.1282, lng: 120.2996 },
    imagePool: 'oldStreet',
    features: '百年糖廠,古早冰棒,日式宿舍,糖業歷史,懷舊散步',
    transport: '搭乘臺鐵至善化站，步行約10分鐘。',
    evaluate: 4.1,
    evaluateNum: 230,
  },
  {
    slug: 'madou-daitian',
    title: '麻豆代天府',
    description: '全臺最大的王爺廟，天堂地獄場景重現的奇幻宗教體驗。',
    content:
      '<p>麻豆代天府是臺灣最著名的五府千歲信仰中心，廟宇規模宏偉。最特別的是園區內以實景重現的十八層地獄與天堂場景，栩栩如生的塑像與聲光效果令人印象深刻。巨龍造型的觀景台更是打卡熱點。</p>',
    price: 150,
    originPrice: 180,
    address: '臺南市麻豆區關帝廟60號',
    category: 'tickets',
    coordinates: { lat: 23.1817, lng: 120.2503 },
    imagePool: 'temple',
    features: '王爺信仰,天堂地獄,巨龍觀景台,宗教文化,奇幻體驗',
    transport: '搭乘大臺南公車橘幹線至麻豆站下車，步行約10分鐘。',
    evaluate: 4.3,
    evaluateNum: 340,
  },
  {
    slug: 'baihe-lotus',
    title: '白河蓮花季體驗',
    description: '臺灣蓮花之鄉的夏日風情，賞蓮、採蓮、品蓮子大餐。',
    content:
      '<p>白河是臺灣最大的蓮花產地，每年六至八月蓮花盛開，粉紅與白色的蓮花鋪滿水田，美不勝收。蓮花季期間可體驗採蓮蓬、剝蓮子的農家樂趣，品嚐蓮子湯、蓮藕茶等在地美食，感受臺灣農村的夏日風情。</p>',
    price: 800,
    originPrice: 980,
    address: '臺南市白河區玉豐里',
    category: 'package',
    coordinates: { lat: 23.3502, lng: 120.4168 },
    imagePool: 'nature',
    features: '蓮花季,採蓮體驗,蓮子美食,農村風情,季節限定',
    transport: '搭乘大臺南公車黃幹線至白河站下車，轉搭計程車約10分鐘。',
    evaluate: 4.4,
    evaluateNum: 280,
  },
  {
    slug: 'history-museum',
    title: '國立台灣歷史博物館',
    description: '以臺灣歷史為主題的國家級博物館，認識這座島嶼的前世今生。',
    content:
      '<p>國立臺灣歷史博物館以「大家的博物館」為理念，透過豐富的文物、模型與多媒體展示，從史前時期到當代，完整呈現臺灣的歷史發展脈絡。館內的情境再現展區以等比例場景重現歷史片段，讓觀眾身歷其境。</p>',
    price: 250,
    originPrice: 300,
    address: '臺南市安南區長和路一段250號',
    category: 'tickets',
    coordinates: { lat: 23.0363, lng: 120.1847 },
    imagePool: 'museum',
    features: '臺灣歷史,國家博物館,情境再現,多媒體展覽,親子教育',
    transport: '搭乘臺南市公車18路至臺灣歷史博物館站下車。',
    evaluate: 4.5,
    evaluateNum: 410,
  },
  {
    slug: 'zhengxing-street',
    title: '正興街散步',
    description: '臺南最有個性的特色街區，蜷尾家冰淇淋與文青小店的朝聖地。',
    content:
      '<p>正興街是臺南最具個性的創意街區，短短一條街匯聚了蜷尾家冰淇淋、布萊恩紅茶等排隊名店。街上的獨立商店、二手衣物店與藝術空間展現了臺南年輕世代的創業活力，每月的正興街封街活動更是熱鬧非凡。</p>',
    price: 550,
    originPrice: 680,
    address: '臺南市中西區正興街',
    category: 'package',
    coordinates: { lat: 22.9924, lng: 120.1975 },
    imagePool: 'city',
    features: '特色街區,蜷尾家冰淇淋,文青小店,創意商圈,封街活動',
    transport: '搭乘臺南市公車至西門路站下車，步行約3分鐘。',
    evaluate: 4.3,
    evaluateNum: 350,
  },
]
