import type { ProductDefinition } from '../types'

export const taipeiProducts: ProductDefinition[] = [
  {
    slug: 'taipei-101-observatory',
    title: '台北101觀景台',
    description: '登上台灣最高建築，從89樓俯瞰台北盆地360度壯麗全景。',
    content:
      '<p>台北101觀景台位於信義區，曾為世界最高建築。搭乘超高速電梯僅需37秒即可抵達89樓觀景台，天氣晴朗時可遠眺整個台北盆地與周圍山脈。觀景台設有多媒體導覽與風阻尼球展示，是認識台北城市風貌的絕佳起點。</p>',
    price: 600,
    originPrice: 750,
    address: '台北市信義區信義路五段7號89樓',
    category: 'tickets',
    coordinates: { lat: 25.034, lng: 121.5645 },
    imagePool: 'city',
    features: '高空景觀,超高速電梯,風阻尼球,多媒體導覽,紀念品商店',
    transport: '捷運淡水信義線至台北101/世貿站4號出口，步行約1分鐘',
    evaluate: 4.7,
    evaluateNum: 782,
  },
  {
    slug: 'national-palace-museum',
    title: '故宮博物院',
    description: '典藏近70萬件華夏文物精品，翠玉白菜與肉形石為鎮館之寶。',
    content:
      '<p>國立故宮博物院是世界四大博物館之一，收藏跨越數千年的中華文化珍品。常設展覽涵蓋書畫、陶瓷、玉器、銅器等類別，定期更換展品讓每次造訪都有新發現。館內亦設有兒童學藝中心及多媒體互動區，適合各年齡層參觀。</p>',
    price: 350,
    originPrice: 450,
    address: '台北市士林區至善路二段221號',
    category: 'tickets',
    coordinates: { lat: 25.1024, lng: 121.5485 },
    imagePool: 'museum',
    features: '世界級館藏,翠玉白菜,多媒體互動,語音導覽,文創商品',
    transport: '捷運淡水信義線至士林站，轉乘紅30或255公車至故宮正門',
    evaluate: 4.8,
    evaluateNum: 695,
  },
  {
    slug: 'longshan-temple',
    title: '龍山寺',
    description: '建於1738年的國定古蹟，融合儒釋道三教信仰的台北精神地標。',
    content:
      '<p>艋舺龍山寺歷經多次天災戰火仍屹立不搖，是台北最具代表性的廟宇之一。寺內精美的石雕、木雕與剪黏藝術展現傳統匠師的巔峰工藝。每逢農曆初一十五香火鼎盛，花燈節期間更是璀璨壯觀，周邊的萬華商圈也值得探索。</p>',
    price: 100,
    originPrice: 120,
    address: '台北市萬華區廣州街211號',
    category: 'tickets',
    coordinates: { lat: 25.0372, lng: 121.4999 },
    imagePool: 'temple',
    features: '國定古蹟,傳統建築,石雕藝術,花燈節,宗教文化',
    transport: '捷運板南線至龍山寺站1號出口，步行約3分鐘',
    evaluate: 4.6,
    evaluateNum: 623,
  },
  {
    slug: 'chiang-kai-shek-memorial',
    title: '中正紀念堂',
    description: '白色大理石莊嚴建築搭配自由廣場，每日衛兵交接儀式不容錯過。',
    content:
      '<p>中正紀念堂是台北最具代表性的紀念性建築，佔地25公頃的園區包含國家戲劇院與音樂廳。主堂內每整點的三軍儀隊交接儀式莊嚴肅穆，吸引大量遊客駐足觀看。園區內花木扶疏，櫻花季與荷花季更是攝影愛好者的天堂。</p>',
    price: 80,
    originPrice: 100,
    address: '台北市中正區中山南路21號',
    category: 'tickets',
    coordinates: { lat: 25.035, lng: 121.5218 },
    imagePool: 'city',
    features: '衛兵交接,自由廣場,國家劇院,櫻花季,歷史建築',
    transport: '捷運淡水信義線或松山新店線至中正紀念堂站5號出口',
    evaluate: 4.5,
    evaluateNum: 540,
  },
  {
    slug: 'elephant-mountain-trail',
    title: '象山步道',
    description: '台北市區最熱門的登山步道，是拍攝台北101夕陽與夜景的首選地點。',
    content:
      '<p>象山步道全長約1.5公里，沿途設有多處觀景平台，其中六巨石觀景台是拍攝台北101最經典的角度。步道沿途生態豐富，可觀察到台灣獼猴、五色鳥等野生動物。傍晚時分登頂可同時欣賞夕陽與城市華燈初上的迷人景色。</p>',
    price: 150,
    originPrice: 180,
    address: '台北市信義區信義路五段150巷',
    category: 'tickets',
    coordinates: { lat: 25.0272, lng: 121.5716 },
    imagePool: 'mountain',
    features: '101夜景,六巨石,生態豐富,夕陽美景,親子步道',
    transport: '捷運淡水信義線至象山站2號出口，步行約10分鐘抵達登山口',
    evaluate: 4.6,
    evaluateNum: 487,
  },
  {
    slug: 'beitou-hot-spring',
    title: '北投溫泉',
    description: '台北近郊日式溫泉勝地，百年溫泉文化搭配硫磺谷自然地景。',
    content:
      '<p>北投溫泉區擁有白磺、青磺、鐵磺三種泉質，是台灣最具歷史的溫泉鄉之一。區內保留日治時期溫泉建築，北投溫泉博物館與地熱谷是必訪景點。從市區搭捷運僅需30分鐘即可抵達，是忙碌都市人放鬆身心的最佳選擇。</p>',
    price: 800,
    originPrice: 1000,
    address: '台北市北投區中山路2號',
    category: 'package',
    coordinates: { lat: 25.1367, lng: 121.5069 },
    imagePool: 'hotSpring',
    features: '日式溫泉,三種泉質,溫泉博物館,地熱谷,放鬆療癒',
    transport: '捷運淡水信義線至北投站轉乘新北投支線至新北投站',
    evaluate: 4.7,
    evaluateNum: 534,
  },
  {
    slug: 'shilin-night-market-tour',
    title: '士林夜市美食導覽',
    description: '跟著在地達人深入士林夜市，品嚐經典小吃與隱藏版美食。',
    content:
      '<p>士林夜市是台北規模最大、最具知名度的觀光夜市。本導覽行程由在地美食家帶路，深入地下美食街與巷弄攤位，品嚐大餅包小餅、生煎包、蚵仔煎等招牌小吃。每團限額12人，確保每位旅客都能充分體驗道地夜市文化。</p>',
    price: 899,
    originPrice: 1100,
    address: '台北市士林區基河路101號',
    category: 'package',
    coordinates: { lat: 25.0882, lng: 121.5243 },
    imagePool: 'nightMarket',
    features: '美食導覽,在地達人,小團體,經典小吃,夜市文化',
    transport: '捷運淡水信義線至劍潭站1號出口，步行約3分鐘',
    evaluate: 4.5,
    evaluateNum: 312,
  },
  {
    slug: 'taipei-zoo',
    title: '台北動物園',
    description: '亞洲最大動物園之一，園區佔地165公頃，擁有超過400種動物。',
    content:
      '<p>台北市立動物園（木柵動物園）是台灣歷史最悠久的動物園，擁有大貓熊館、企鵝館、熱帶雨林區等主題展區。園內大貓熊團團與圓圓一家深受遊客喜愛。搭配貓空纜車可規劃一日遊行程，從空中俯瞰動物園全景。</p>',
    price: 60,
    originPrice: 80,
    address: '台北市文山區新光路二段30號',
    category: 'tickets',
    coordinates: { lat: 24.9986, lng: 121.5811 },
    imagePool: 'nature',
    features: '大貓熊,企鵝館,熱帶雨林,親子同遊,教育展覽',
    transport: '捷運文湖線至動物園站，出站即達',
    evaluate: 4.4,
    evaluateNum: 456,
  },
  {
    slug: 'maokong-gondola',
    title: '貓空纜車',
    description: '全長4公里的高空纜車，水晶車廂可透視腳下翠綠茶園與台北市景。',
    content:
      '<p>貓空纜車連接動物園站至貓空站，沿途經過四座車站，全程約30分鐘。特殊的水晶車廂底部透明，可俯瞰山谷景致。抵達貓空後可品嚐在地鐵觀音茶、走訪茶園步道，夜間搭乘更能欣賞台北璀璨夜景。</p>',
    price: 250,
    originPrice: 300,
    address: '台北市文山區新光路二段8號',
    category: 'tickets',
    coordinates: { lat: 24.9983, lng: 121.5764 },
    imagePool: 'tea',
    features: '水晶車廂,高空覽勝,茶園風光,夜間搭乘,親子行程',
    transport: '捷運文湖線至動物園站，步行至纜車動物園站',
    evaluate: 4.5,
    evaluateNum: 389,
  },
  {
    slug: 'tamsui-old-street',
    title: '淡水老街',
    description: '河畔夕陽老街，阿給、鐵蛋、魚酥等經典淡水美食一次滿足。',
    content:
      '<p>淡水老街沿著淡水河畔延伸，結合歷史古蹟與美食小吃。漫步老街可品嚐阿給、鐵蛋、魚丸等在地美食，還能參觀紅毛城、小白宮等古蹟。傍晚時分的河畔夕陽被譽為台灣八景之一，是最浪漫的散步路線。</p>',
    price: 599,
    originPrice: 750,
    address: '台北市淡水區中正路',
    category: 'package',
    coordinates: { lat: 25.1699, lng: 121.4404 },
    imagePool: 'oldStreet',
    features: '河畔夕陽,在地美食,紅毛城,歷史古蹟,浪漫散步',
    transport: '捷運淡水信義線至淡水站，出站步行約5分鐘',
    evaluate: 4.4,
    evaluateNum: 421,
  },
  {
    slug: 'sun-yat-sen-memorial',
    title: '國父紀念館',
    description: '莊嚴的紀念殿堂與寬闊廣場，衛兵交接儀式與藝文展覽雙重體驗。',
    content:
      '<p>國父紀念館是為紀念孫中山先生而建的殿堂式建築，大廳內的銅像前每整點舉行衛兵交接。館內定期舉辦書畫展與文藝活動，周圍的翠湖與庭園是市民休閒運動的熱門場所。從廣場可直接眺望台北101，是拍照的絕佳角度。</p>',
    price: 80,
    originPrice: 100,
    address: '台北市信義區仁愛路四段505號',
    category: 'tickets',
    coordinates: { lat: 25.04, lng: 121.5601 },
    imagePool: 'city',
    features: '衛兵交接,藝文展覽,翠湖庭園,101取景,免費參觀',
    transport: '捷運板南線至國父紀念館站4號出口，步行約3分鐘',
    evaluate: 4.3,
    evaluateNum: 287,
  },
  {
    slug: 'taipei-fine-arts-museum',
    title: '台北市立美術館',
    description: '台灣第一座現代美術館，白色幾何建築本身即是藝術品。',
    content:
      '<p>台北市立美術館（北美館）於1983年開館，是台灣首座以現代藝術為導向的美術館。館內常設展與特展兼具本土與國際視野，地下樓層的兒童藝術教育中心深受親子家庭喜愛。純白幾何造型的建築外觀本身就是花博公園的亮眼地標。</p>',
    price: 150,
    originPrice: 180,
    address: '台北市中山區中山北路三段181號',
    category: 'tickets',
    coordinates: { lat: 25.0725, lng: 121.5248 },
    imagePool: 'museum',
    features: '現代藝術,建築之美,特展豐富,兒童藝教,花博園區',
    transport: '捷運淡水信義線至圓山站1號出口，步行約10分鐘',
    evaluate: 4.5,
    evaluateNum: 234,
  },
  {
    slug: 'daan-forest-park',
    title: '大安森林公園',
    description: '都會中心的綠色綠洲，26公頃城市之肺是台北人最愛的休憩空間。',
    content:
      '<p>大安森林公園被譽為「台北之肺」，佔地25.9公頃的綠地位於市中心精華地段。園內生態池吸引白鷺鷥、夜鷺等鳥類棲息，環園步道是晨跑族的最愛。露天音樂台定期舉辦免費音樂會，週末的花卉市集也是一大看點。</p>',
    price: 80,
    originPrice: 100,
    address: '台北市大安區新生南路二段1號',
    category: 'tickets',
    coordinates: { lat: 25.03, lng: 121.5355 },
    imagePool: 'park',
    features: '城市綠洲,生態豐富,音樂台,晨跑步道,花卉市集',
    transport: '捷運淡水信義線至大安森林公園站，出站即達',
    evaluate: 4.4,
    evaluateNum: 356,
  },
  {
    slug: 'yangmingshan-national-park',
    title: '陽明山國家公園',
    description: '台北後花園，春賞櫻花杜鵑、秋觀芒草、冬泡溫泉四季皆宜。',
    content:
      '<p>陽明山國家公園以火山地形與溫泉資源聞名，擁有七星山、擎天崗、小油坑等著名景點。春季花季期間竹子湖海芋與各色櫻花爭相綻放，秋季擎天崗大片芒草隨風搖曳。園區步道系統完善，從輕鬆散步到登頂七星山皆有選擇。</p>',
    price: 1200,
    originPrice: 1500,
    address: '台北市北投區竹子湖路1-20號',
    category: 'package',
    coordinates: { lat: 25.1685, lng: 121.5601 },
    imagePool: 'mountain',
    features: '火山地形,花季賞花,芒草季,溫泉區,七星山登頂',
    transport: '捷運淡水信義線至劍潭站轉乘紅5公車，或至北投站轉乘230公車',
    evaluate: 4.7,
    evaluateNum: 567,
  },
  {
    slug: 'songshan-cultural-park',
    title: '松山文創園區',
    description: '日治時期菸廠華麗轉身，匯集設計展覽、文創市集與誠品生活。',
    content:
      '<p>松山文創園區前身為松山菸廠，保留完整的巴洛克花園與日式工業建築。園區內定期舉辦設計展、藝術節等活動，誠品生活松菸店更是文青必訪之地。寬闘的生態池與綠蔭步道讓這裡成為信義區鬧中取靜的文藝角落。</p>',
    price: 500,
    originPrice: 600,
    address: '台北市信義區光復南路133號',
    category: 'package',
    coordinates: { lat: 25.044, lng: 121.5609 },
    imagePool: 'city',
    features: '文創展覽,歷史建築,誠品生活,生態池,設計市集',
    transport: '捷運板南線至市政府站1號出口，步行約10分鐘',
    evaluate: 4.4,
    evaluateNum: 298,
  },
  {
    slug: 'huashan-1914',
    title: '華山1914文創園區',
    description: '百年酒廠遺址化身文創基地，展覽演出與手作體驗日日精彩。',
    content:
      '<p>華山1914文創園區由日治時期酒廠改建而成，紅磚老建築與現代藝術完美融合。園區內全年無休舉辦各類展覽、音樂演出與市集活動，周邊的文青咖啡廳與獨立書店也值得探索。大草原上的週末市集是最受歡迎的假日去處。</p>',
    price: 450,
    originPrice: 550,
    address: '台北市中正區八德路一段1號',
    category: 'package',
    coordinates: { lat: 25.0441, lng: 121.5296 },
    imagePool: 'city',
    features: '文創基地,展覽演出,紅磚建築,手作體驗,假日市集',
    transport: '捷運板南線至忠孝新生站1號出口，步行約3分鐘',
    evaluate: 4.5,
    evaluateNum: 345,
  },
  {
    slug: 'raohe-night-market',
    title: '饒河街夜市',
    description: '台北最具歷史的觀光夜市，胡椒餅與藥燉排骨是必吃經典。',
    content:
      '<p>饒河街觀光夜市全長約600公尺，入口處的牌樓氣勢磅礴。夜市內攤位規劃整齊，從知名的福州世祖胡椒餅、陳董藥燉排骨到各式創意小吃應有盡有。相較於士林夜市，饒河街的動線更為集中，適合想有效率逛完的旅客。</p>',
    price: 699,
    originPrice: 850,
    address: '台北市松山區饒河街',
    category: 'package',
    coordinates: { lat: 25.0511, lng: 121.5773 },
    imagePool: 'nightMarket',
    features: '胡椒餅,藥燉排骨,觀光夜市,美食集中,歷史悠久',
    transport: '捷運松山新店線至松山站1號出口，步行約3分鐘',
    evaluate: 4.4,
    evaluateNum: 376,
  },
  {
    slug: 'ximending-culture-tour',
    title: '西門町文化探索',
    description: '台北潮流發源地，結合街頭藝術、電影街與在地次文化深度導覽。',
    content:
      '<p>西門町是台北最具活力的商圈，從日治時期的電影街發展至今成為年輕人的流行聖地。本行程帶您探索紅樓劇場、刺青街、美國街等特色區域，了解西門町從戲院文化到潮流中心的百年演變，還能品嚐老字號冰品與創意美食。</p>',
    price: 799,
    originPrice: 999,
    address: '台北市萬華區漢中街',
    category: 'package',
    coordinates: { lat: 25.0421, lng: 121.5081 },
    imagePool: 'city',
    features: '潮流文化,紅樓劇場,街頭藝術,電影街,美食體驗',
    transport: '捷運板南線或松山新店線至西門站6號出口',
    evaluate: 4.3,
    evaluateNum: 256,
  },
  {
    slug: 'xinyi-shopping-experience',
    title: '信義區購物體驗',
    description: '台北最繁華的購物商圈，百貨群集結合城市美學與時尚品味。',
    content:
      '<p>信義區是台北首屈一指的購物天堂，從新光三越、微風南山到ATT 4 FUN等百貨林立。本體驗行程包含專屬購物顧問服務、精選品牌折扣與特色餐廳推薦。夜晚的信義區霓虹燈光點亮天際，搭配台北101的壯觀背景，是最時尚的台北體驗。</p>',
    price: 1500,
    originPrice: 1800,
    address: '台北市信義區松壽路9號',
    category: 'package',
    coordinates: { lat: 25.036, lng: 121.5672 },
    imagePool: 'city',
    features: '精品購物,百貨商圈,購物顧問,美食推薦,城市夜景',
    transport: '捷運淡水信義線至台北101/世貿站，或板南線至市政府站',
    evaluate: 4.2,
    evaluateNum: 198,
  },
  {
    slug: 'beitou-library',
    title: '北投圖書館',
    description: '全台第一座綠建築圖書館，木造建築融入溫泉公園的森林綠意。',
    content:
      '<p>北投圖書館是台灣首座鑽石級綠建築圖書館，全棟以木構造打造，外觀宛如一艘停泊在綠樹間的方舟。陽台與大片落地窗讓自然光灑入閱讀空間，屋頂設有太陽能板與草皮綠化。位於北投溫泉公園內，與溫泉博物館比鄰而居。</p>',
    price: 100,
    originPrice: 120,
    address: '台北市北投區光明路251號',
    category: 'tickets',
    coordinates: { lat: 25.1363, lng: 121.5065 },
    imagePool: 'nature',
    features: '綠建築,木造設計,溫泉公園,閱讀空間,建築巡禮',
    transport: '捷運新北投支線至新北投站，步行約5分鐘',
    evaluate: 4.6,
    evaluateNum: 178,
  },
  {
    slug: 'taipei-discovery-center',
    title: '台北探索館',
    description: '免費認識台北城市發展史，互動展覽讓你秒懂台北前世今生。',
    content:
      '<p>台北探索館位於市政大樓內，以多媒體互動方式展示台北城市的過去、現在與未來。從清代城牆到現代都會規劃，四個樓層的常設展深入淺出。360度環形劇場播放的台北城市影片尤為震撼，是快速認識台北歷史文化的最佳起點。</p>',
    price: 80,
    originPrice: 100,
    address: '台北市信義區市府路1號',
    category: 'tickets',
    coordinates: { lat: 25.0378, lng: 121.5653 },
    imagePool: 'museum',
    features: '免費參觀,互動展覽,城市歷史,環形劇場,多媒體',
    transport: '捷運板南線至市政府站，由市政大樓連通道直達',
    evaluate: 4.2,
    evaluateNum: 134,
  },
  {
    slug: 'ningxia-night-market',
    title: '寧夏夜市',
    description: '台北最道地的傳統夜市，蚵仔煎與滷肉飯飄香數十年。',
    content:
      '<p>寧夏夜市以傳統台灣小吃聞名，規模不大但每攤都是數十年老店。劉芋仔蛋黃芋餅、賴記蚵仔煎、豬肝榮仔等攤位常常大排長龍。千歲宴活動更能一次品嚐夜市精選美食。相較於觀光夜市，這裡更能體驗在地台北人的夜市日常。</p>',
    price: 650,
    originPrice: 800,
    address: '台北市大同區寧夏路',
    category: 'package',
    coordinates: { lat: 25.0556, lng: 121.5155 },
    imagePool: 'nightMarket',
    features: '傳統小吃,老店雲集,千歲宴,在地美食,蚵仔煎',
    transport: '捷運淡水信義線至雙連站1號出口，步行約10分鐘',
    evaluate: 4.5,
    evaluateNum: 289,
  },
  {
    slug: 'dadaocheng-wharf',
    title: '大稻埕碼頭',
    description: '淡水河畔浪漫碼頭，夕陽遊船與河岸市集打造最美黃昏時光。',
    content:
      '<p>大稻埕碼頭是台北市區最佳的夕陽觀賞點之一，每到傍晚河畔聚集眾多攝影愛好者。夏季的河岸音樂節與貨櫃市集為碼頭增添熱鬧氛圍。搭乘藍色公路遊船可沿淡水河巡遊至關渡或淡水，從水上角度欣賞台北城市天際線。</p>',
    price: 750,
    originPrice: 950,
    address: '台北市大同區環河北路一段',
    category: 'package',
    coordinates: { lat: 25.0573, lng: 121.5089 },
    imagePool: 'city',
    features: '夕陽美景,遊船體驗,河岸市集,音樂節,攝影勝地',
    transport: '捷運松山新店線至北門站3號出口，步行約10分鐘',
    evaluate: 4.4,
    evaluateNum: 267,
  },
  {
    slug: 'dihua-street',
    title: '迪化街老街',
    description: '百年商街轉型文創聚落，巴洛克老建築裡藏著新舊交融的台北味。',
    content:
      '<p>迪化街是台北最具歷史的商業街道，清代即為南北貨集散地。如今街上保留大量巴洛克與閩南式建築，進駐了文創商店、咖啡廳與藝廊。每逢農曆年前的年貨大街更是人潮洶湧。走一趟迪化街，等於閱讀了台北百年商業發展史。</p>',
    price: 599,
    originPrice: 750,
    address: '台北市大同區迪化街一段',
    category: 'package',
    coordinates: { lat: 25.0558, lng: 121.51 },
    imagePool: 'oldStreet',
    features: '百年老街,巴洛克建築,文創商店,年貨大街,南北貨',
    transport: '捷運松山新店線至北門站3號出口，步行約8分鐘',
    evaluate: 4.5,
    evaluateNum: 334,
  },
  {
    slug: 'taipei-botanical-garden',
    title: '台北植物園',
    description: '鬧市中的植物方舟，百年歷史園區收藏超過1500種植物。',
    content:
      '<p>台北植物園創建於1896年，是台灣歷史最悠久的植物園。園內劃分為荷花池、蕨類區、多肉植物區等主題區域，夏季荷花盛開時尤為壯觀。歷史博物館與欽差行台等古蹟散布其中，是結合自然生態與人文歷史的市區綠色寶地。</p>',
    price: 80,
    originPrice: 100,
    address: '台北市中正區南海路53號',
    category: 'tickets',
    coordinates: { lat: 25.032, lng: 121.512 },
    imagePool: 'park',
    features: '百年植物園,荷花池,蕨類專區,歷史古蹟,生態教育',
    transport: '捷運松山新店線至小南門站3號出口，步行約5分鐘',
    evaluate: 4.3,
    evaluateNum: 198,
  },
  {
    slug: 'national-taiwan-museum',
    title: '國立臺灣博物館',
    description: '台灣最古老的博物館，希臘神殿式建築典藏台灣自然與人文瑰寶。',
    content:
      '<p>國立臺灣博物館創立於1908年，是台灣歷史最悠久的博物館。本館位於二二八和平紀念公園內，希臘復興式建築氣勢恢宏。常設展涵蓋台灣原住民文化、自然史與地質學，對面的土銀展示館更有壯觀的恐龍化石與金庫體驗。</p>',
    price: 150,
    originPrice: 180,
    address: '台北市中正區襄陽路2號',
    category: 'tickets',
    coordinates: { lat: 25.0431, lng: 121.5151 },
    imagePool: 'museum',
    features: '百年博物館,恐龍化石,原住民文化,希臘建築,土銀展館',
    transport: '捷運淡水信義線至台大醫院站4號出口，步行約3分鐘',
    evaluate: 4.4,
    evaluateNum: 212,
  },
  {
    slug: 'miniatures-museum',
    title: '袖珍博物館',
    description: '亞洲首座專門收藏袖珍藝術品的博物館，微縮世界精巧令人驚嘆。',
    content:
      '<p>袖珍博物館收藏超過200件來自世界各國的袖珍藝術作品，每件都以1:12的比例精心打造。從維多利亞式豪宅到歐洲中世紀城堡，每個微縮場景都令人嘆為觀止。館內設有互動區讓遊客體驗微縮製作的樂趣，是雨天備案的絕佳選擇。</p>',
    price: 250,
    originPrice: 300,
    address: '台北市中山區建國北路一段96號B1',
    category: 'tickets',
    coordinates: { lat: 25.0486, lng: 121.536 },
    imagePool: 'museum',
    features: '袖珍藝術,微縮世界,互動體驗,雨天備案,親子推薦',
    transport: '捷運松山新店線至松江南京站7號出口，步行約5分鐘',
    evaluate: 4.3,
    evaluateNum: 167,
  },
  {
    slug: 'taipei-astronomical-museum',
    title: '臺北天文科學教育館',
    description: '探索宇宙奧秘的科學殿堂，IMAX宇宙劇場帶你遨遊星際。',
    content:
      '<p>臺北天文科學教育館（天文館）是台灣最大的天文教育設施，擁有全台唯一的IMAX宇宙劇場。常設展從太陽系到星系演化，以互動裝置讓天文知識生動有趣。宇宙探險車模擬太空旅行的體驗深受大小朋友喜愛，是寓教於樂的最佳去處。</p>',
    price: 200,
    originPrice: 250,
    address: '台北市士林區基河路363號',
    category: 'tickets',
    coordinates: { lat: 25.0959, lng: 121.5179 },
    imagePool: 'museum',
    features: 'IMAX劇場,宇宙探險,互動展覽,天文教育,太空體驗',
    transport: '捷運淡水信義線至劍潭站3號出口，步行約15分鐘',
    evaluate: 4.4,
    evaluateNum: 245,
  },
  {
    slug: 'zhishan-rock-trail',
    title: '芝山岩步道',
    description: '台北市區最豐富的地質教室，千年遺址與百年老樹共存的生態秘境。',
    content:
      '<p>芝山岩是台北盆地中難得的獨立小山丘，海拔僅52公尺卻蘊藏豐富的地質與考古資源。步道沿途可見七千年前的貝塚遺址、百年老樟樹與多樣的蕨類植物。芝山文化生態綠園提供專業導覽解說，是認識台北自然史的最佳戶外教室。</p>',
    price: 150,
    originPrice: 180,
    address: '台北市士林區雨聲街120號',
    category: 'tickets',
    coordinates: { lat: 25.0998, lng: 121.5285 },
    imagePool: 'nature',
    features: '地質教室,考古遺址,百年老樹,生態綠園,輕鬆步道',
    transport: '捷運淡水信義線至芝山站1號出口，步行約10分鐘',
    evaluate: 4.2,
    evaluateNum: 89,
  },
  {
    slug: 'jiantan-mountain-trail',
    title: '劍潭山步道',
    description: '捷運站旁即可起登，輕鬆攻頂眺望松山機場飛機起降與大直美景。',
    content:
      '<p>劍潭山步道是台北最親民的都會步道之一，從劍潭捷運站出發即可起登。步道全程鋪設完善，沿途設有多處涼亭與觀景台。最知名的老地方觀景台可近距離觀看松山機場飛機起降，同時將基隆河與大直橋盡收眼底，是航空迷的朝聖地。</p>',
    price: 100,
    originPrice: 120,
    address: '台北市中山區北安路底',
    category: 'tickets',
    coordinates: { lat: 25.0833, lng: 121.5262 },
    imagePool: 'mountain',
    features: '都會步道,飛機觀景,老地方平台,輕鬆攻頂,基隆河景',
    transport: '捷運淡水信義線至劍潭站2號出口，步行約5分鐘抵達登山口',
    evaluate: 4.5,
    evaluateNum: 312,
  },
]
