import type { ProductDefinition } from '../types'

export const taitungProducts: ProductDefinition[] = [
  {
    slug: 'sanxiantai-bridge-ticket',
    title: '三仙台跨海拱橋門票',
    description: '走過八拱跨海步橋登上火山岩島嶼，探索海蝕洞與奇岩地質景觀。',
    content:
      '<p>三仙台位於台東成功鎮北方，是一座由火山集塊岩構成的離岸小島。八拱跨海步橋如巨龍橫臥海面，是東海岸最經典的地標。島上有海蝕洞、壺穴、海蝕柱等豐富地質景觀，登上燈塔可眺望太平洋壯闊海景，日出時分更是美不勝收。</p>',
    price: 100,
    originPrice: 130,
    address: '台東縣成功鎮三仙里基翬路74號',
    category: 'tickets',
    coordinates: { lat: 23.1225, lng: 121.4098 },
    imagePool: 'beach',
    features: '八拱跨海橋,火山岩地質,海蝕洞穴,太平洋日出,燈塔觀景',
    transport: '搭乘花蓮客運海線至三仙台站下車，步行約10分鐘',
    evaluate: 4.6,
    evaluateNum: 567,
  },
  {
    slug: 'brown-avenue-cycling',
    title: '伯朗大道自行車田園之旅',
    description: '騎行在金黃稻浪間的天堂之路，拍下最經典的台東風景照。',
    content:
      '<p>伯朗大道位於池上鄉，因金城武拍攝航空廣告而聲名大噪，又被稱為「天堂之路」。筆直的道路兩旁盡是無際的稻田，完全沒有電線桿遮擋視線。此行程提供自行車租借與在地導覽，帶您穿梭於稻田小路，感受台東最純粹的田園風光。</p>',
    price: 500,
    originPrice: 650,
    address: '台東縣池上鄉錦新三號道路',
    category: 'package',
    coordinates: { lat: 23.1132, lng: 121.2182 },
    imagePool: 'nature',
    features: '天堂之路,自行車租借,稻田風光,金城武樹,田園導覽',
    transport: '搭乘火車至池上站，步行至自行車租借站約5分鐘',
    evaluate: 4.7,
    evaluateNum: 623,
  },
  {
    slug: 'luye-balloon-festival',
    title: '鹿野高台熱氣球繫留體驗',
    description: '搭乘繽紛熱氣球升空，俯瞰花東縱谷的壯麗田園與山巒。',
    content:
      '<p>鹿野高台是台灣國際熱氣球嘉年華的舉辦地，每年六至八月色彩繽紛的熱氣球升空，景象壯觀。繫留體驗讓您搭乘熱氣球升至約30公尺高空，360度俯瞰花東縱谷、卑南溪與中央山脈。非嘉年華期間，高台也是飛行傘的絕佳起飛點。</p>',
    price: 600,
    originPrice: 750,
    address: '台東縣鹿野鄉永安村高台路46號',
    category: 'tickets',
    coordinates: { lat: 22.9132, lng: 121.1212 },
    imagePool: 'mountain',
    features: '熱氣球繫留,花東縱谷俯瞰,高台草原,飛行傘觀賞,季節限定',
    transport: '搭乘台灣好行縱谷鹿野線至鹿野高台站下車',
    evaluate: 4.5,
    evaluateNum: 478,
  },
  {
    slug: 'zhiben-hot-spring',
    title: '知本溫泉頂級湯屋體驗',
    description: '浸泡在東台灣最知名的碳酸氫鈉美人湯中，享受山林間的療癒時光。',
    content:
      '<p>知本溫泉位於台東卑南鄉，是東台灣最著名的溫泉區，泉質為弱鹼性碳酸氫鈉泉，有「美人湯」之稱。此體驗安排頂級溫泉會館的獨立湯屋或露天風呂，搭配精緻和風下午茶。溫泉區周邊的知本森林遊樂區也值得順遊。</p>',
    price: 1200,
    originPrice: 1500,
    address: '台東縣卑南鄉溫泉路',
    category: 'package',
    coordinates: { lat: 22.6963, lng: 120.9904 },
    imagePool: 'hotSpring',
    features: '碳酸氫鈉泉,獨立湯屋,露天風呂,和風下午茶,美人湯,山林環境',
    transport: '搭乘火車至知本站，轉乘計程車約15分鐘',
    evaluate: 4.4,
    evaluateNum: 389,
  },
  {
    slug: 'lanyu-island-tour',
    title: '蘭嶼環島三日深度之旅',
    description: '飛往太平洋上的達悟族之島，探索拼板舟文化與絕美海岸秘境。',
    content:
      '<p>蘭嶼是台灣最具異國風情的離島，達悟族（雅美族）在此保存了獨特的飛魚文化與拼板舟傳統。三日行程包含台東至蘭嶼來回機票、環島機車租借、浮潛體驗、部落文化導覽與民宿住宿。東清灣看日出、野銀冷泉戲水、青青草原看夕陽，每一刻都令人難忘。</p>',
    price: 4800,
    originPrice: 5800,
    address: '台東縣蘭嶼鄉開元港',
    category: 'package',
    coordinates: { lat: 22.0441, lng: 121.5483 },
    imagePool: 'island',
    features: '來回機票,機車租借,浮潛體驗,達悟族文化導覽,民宿二晚,環島行程',
    transport: '台東豐年機場搭乘德安航空至蘭嶼機場，航程約25分鐘',
    evaluate: 4.9,
    evaluateNum: 234,
  },
  {
    slug: 'green-island-diving',
    title: '綠島潛水與朝日溫泉二日遊',
    description: '潛入世界級珊瑚礁海域，夜泡全球三大海底溫泉之一。',
    content:
      '<p>綠島擁有世界級的潛水環境，海底珊瑚礁生態豐富多樣。此二日遊包含台東至綠島來回船票、體驗潛水或浮潛、朝日溫泉門票與民宿住宿。朝日溫泉是全球僅有三處的海底溫泉之一，在太平洋畔泡著溫泉看日出，體驗獨一無二。</p>',
    price: 3500,
    originPrice: 4200,
    address: '台東縣綠島鄉南寮漁港',
    category: 'package',
    coordinates: { lat: 22.6614, lng: 121.476 },
    imagePool: 'island',
    features: '體驗潛水,朝日溫泉,來回船票,民宿一晚,珊瑚礁,機車租借',
    transport: '台東富岡漁港搭乘客輪至綠島，船程約50分鐘',
    evaluate: 4.8,
    evaluateNum: 345,
  },
  {
    slug: 'taitung-forest-park',
    title: '台東森林公園門票',
    description: '在都市邊緣的黑森林中騎單車，繞行琵琶湖與活水湖的翠綠水域。',
    content:
      '<p>台東森林公園（又稱黑森林）佔地約280公頃，以大面積的木麻黃防風林得名。園區內有琵琶湖、活水湖、鷺鷥湖三座湖泊，湖面倒映藍天綠樹，景色如畫。自行車道貫穿全園，騎行其中彷彿置身歐洲鄉間，是台東市民的後花園。</p>',
    price: 80,
    originPrice: 100,
    address: '台東縣台東市華泰路300號',
    category: 'tickets',
    coordinates: { lat: 22.747, lng: 121.149 },
    imagePool: 'park',
    features: '琵琶湖,活水湖,黑森林自行車道,木麻黃林,湖泊倒影',
    transport: '台東火車站搭乘市區公車至森林公園站，步行約5分鐘',
    evaluate: 4.3,
    evaluateNum: 412,
  },
  {
    slug: 'jialulan-coast',
    title: '加路蘭海岸藝術散步',
    description: '漫步在太平洋畔的戶外裝置藝術園區，享受東海岸的遼闊與自由。',
    content:
      '<p>加路蘭海岸位於台東市北方，是東海岸著名的休憩區與裝置藝術展場。大型漂流木藝術品散落在翠綠草地上，背景是湛藍太平洋與蜿蜒海岸線。這裡是觀賞月光海與都蘭山的絕佳地點，也是每年東海岸大地藝術節的重要展場之一。</p>',
    price: 80,
    originPrice: 100,
    address: '台東縣台東市台11線157公里處',
    category: 'tickets',
    coordinates: { lat: 22.8091, lng: 121.2001 },
    imagePool: 'beach',
    features: '裝置藝術,太平洋海景,漂流木創作,都蘭山景,海岸草原',
    transport: '搭乘台灣好行東海岸線至加路蘭站下車',
    evaluate: 4.4,
    evaluateNum: 334,
  },
  {
    slug: 'xiaoyeliu-geological-area',
    title: '小野柳地質公園導覽',
    description: '探索台東版野柳的奇岩怪石，認識豆腐岩、蕈狀岩等海蝕地形。',
    content:
      '<p>小野柳位於台東市東北方海岸，因地質景觀類似北海岸野柳而得名。園區內佈滿各種風化與海蝕形成的奇岩，包含蕈狀岩、豆腐岩、蜂窩岩等多樣地形。此導覽由地質解說員帶領，深入介紹每種岩石的成因，並沿海岸步道觀賞潮間帶生態。</p>',
    price: 300,
    originPrice: 380,
    address: '台東縣台東市松江路一段500號',
    category: 'package',
    coordinates: { lat: 22.7847, lng: 121.1802 },
    imagePool: 'beach',
    features: '海蝕奇岩,地質導覽,豆腐岩,蕈狀岩,潮間帶生態',
    transport: '搭乘台灣好行東海岸線至小野柳站下車',
    evaluate: 4.2,
    evaluateNum: 234,
  },
  {
    slug: 'prehistory-museum',
    title: '國立臺灣史前文化博物館門票',
    description: '認識台灣數千年的史前文化與南島語族的遷徙故事。',
    content:
      '<p>國立臺灣史前文化博物館是台灣唯一以史前文化為主題的國家級博物館，展示卑南遺址出土的大量石棺、玉器與陶器。常設展廳完整呈現台灣從舊石器時代到鐵器時代的文化演進，以及南島語族的起源與擴散。互動式展示深受親子家庭喜愛。</p>',
    price: 80,
    originPrice: 100,
    address: '台東縣台東市豐田里博物館路1號',
    category: 'tickets',
    coordinates: { lat: 22.7554, lng: 121.1066 },
    imagePool: 'museum',
    features: '史前文化,卑南遺址,南島語族,互動展示,考古體驗',
    transport: '搭乘火車至台東站，轉乘市區公車至史前博物館站',
    evaluate: 4.3,
    evaluateNum: 278,
  },
  {
    slug: 'taimali-daylily-mountain',
    title: '太麻里金針山賞花一日遊',
    description: '登上海拔1450公尺的金針花海，俯瞰太平洋與層巒疊翠的山景。',
    content:
      '<p>太麻里金針山每年八至九月盛開滿山金針花，橙黃色花海漫山遍野，與遠方湛藍太平洋形成絕美對比。此一日遊包含專車接送、在地導覽、金針花田步道健行，以及品嚐金針花風味餐。曙光亭是觀賞太麻里日出的最佳位置。</p>',
    price: 1500,
    originPrice: 1800,
    address: '台東縣太麻里鄉大王村',
    category: 'package',
    coordinates: { lat: 22.6176, lng: 120.9746 },
    imagePool: 'mountain',
    features: '金針花海,專車接送,花田步道,風味餐,太平洋海景,日出觀賞',
    transport: '台東火車站集合，專車接送上山約40分鐘',
    evaluate: 4.6,
    evaluateNum: 289,
  },
  {
    slug: 'duoliang-station',
    title: '多良車站觀景台門票',
    description: '造訪全台最美車站，在高架月台上眺望無邊際的太平洋碧海藍天。',
    content:
      '<p>多良車站被譽為「全台最美車站」，車站建在山坡上，月台直接面向太平洋。站在觀景台上，鐵軌、椰子樹與無際的海平面構成一幅絕美的畫面。雖然已停止營運，但改建為觀光景點後人氣不減。每當列車經過時，火車與海景同框的畫面是攝影愛好者的最愛。</p>',
    price: 100,
    originPrice: 120,
    address: '台東縣太麻里鄉多良村瀧溪8-1號',
    category: 'tickets',
    coordinates: { lat: 22.5285, lng: 120.9516 },
    imagePool: 'beach',
    features: '最美車站,海景月台,火車觀賞,太平洋全景,攝影聖地',
    transport: '搭乘火車至瀧溪站，步行約20分鐘或搭計程車',
    evaluate: 4.4,
    evaluateNum: 456,
  },
  {
    slug: 'chenggong-fishing-port',
    title: '成功鎮漁港旗魚體驗之旅',
    description: '在台灣旗魚之都觀賞漁獲拍賣，品嚐最新鮮的旗魚料理。',
    content:
      '<p>成功漁港是東海岸最大的漁港，以旗魚捕獲量居全台之冠聞名。此行程安排清晨觀賞漁港拍賣會的熱鬧實況，接著參觀旗魚神殿了解旗魚文化，最後在港邊餐廳享用旗魚生魚片、旗魚肚等鮮美料理，深度體驗漁村風情。</p>',
    price: 1000,
    originPrice: 1200,
    address: '台東縣成功鎮港邊路19號',
    category: 'package',
    coordinates: { lat: 23.1004, lng: 121.3804 },
    imagePool: 'city',
    features: '漁港拍賣,旗魚料理,漁村導覽,旗魚文化,海鮮午餐',
    transport: '搭乘花蓮客運海線至成功站下車，步行約5分鐘',
    evaluate: 4.3,
    evaluateNum: 212,
  },
  {
    slug: 'duli-beach',
    title: '都歷海灘衝浪體驗課程',
    description: '在東海岸浪點學習衝浪，感受太平洋湧浪帶來的極限快感。',
    content:
      '<p>都歷海灘是台東知名的衝浪聖地，沙灘平緩、浪型穩定，適合初學者入門。此課程由專業衝浪教練指導，包含岸上教學、水中實練與全套裝備租借。課後可在海灘上休息，欣賞衝浪好手在浪頭上帥氣的英姿。</p>',
    price: 1200,
    originPrice: 1500,
    address: '台東縣成功鎮都歷路',
    category: 'package',
    coordinates: { lat: 23.0398, lng: 121.3315 },
    imagePool: 'beach',
    features: '衝浪教學,全套裝備,專業教練,初學者友善,太平洋浪點',
    transport: '搭乘台灣好行東海岸線至都歷站下車',
    evaluate: 4.5,
    evaluateNum: 267,
  },
  {
    slug: 'baxiandong-caves',
    title: '八仙洞史前遺址導覽',
    description: '探訪台灣最古老的人類居住遺址，走進萬年前的海蝕洞穴群。',
    content:
      '<p>八仙洞位於台東長濱鄉，是台灣已知最早的人類居住遺址，距今約三萬年。十餘個海蝕洞穴分佈在陡峭的岩壁上，其中靈岩洞、潮音洞等已闢為參觀步道。此導覽由考古專家帶領，解說舊石器時代長濱文化的發現經過與文化意義。</p>',
    price: 250,
    originPrice: 300,
    address: '台東縣長濱鄉三間村水母丁1-4號',
    category: 'tickets',
    coordinates: { lat: 23.3001, lng: 121.452 },
    imagePool: 'nature',
    features: '史前遺址,海蝕洞穴,考古導覽,長濱文化,萬年歷史',
    transport: '搭乘花蓮客運海線至八仙洞站下車',
    evaluate: 4.1,
    evaluateNum: 156,
  },
  {
    slug: 'tiehua-music-village',
    title: '鐵花村音樂聚落夜間體驗',
    description: '在台東市中心的文創聚落聆聽現場音樂演出，逛彩繪熱氣球市集。',
    content:
      '<p>鐵花村是由舊台鐵宿舍活化而成的音樂聚落，每週三至日晚間有現場音樂演出，以獨立音樂與原住民音樂為主。園區內的假日慢市集匯集在地農產與手作商品，彩繪熱氣球燈飾在夜空中搖曳，充滿台東獨有的悠閒與浪漫氛圍。</p>',
    price: 350,
    originPrice: 450,
    address: '台東縣台東市新生路135巷26號',
    category: 'tickets',
    coordinates: { lat: 22.7536, lng: 121.1445 },
    imagePool: 'city',
    features: '現場音樂,慢市集,彩繪熱氣球,文創商品,原住民音樂',
    transport: '搭乘火車至台東站，步行約10分鐘',
    evaluate: 4.4,
    evaluateNum: 389,
  },
  {
    slug: 'chishang-lunchbox-museum',
    title: '池上飯包文化故事館體驗',
    description: '走進懷舊火車車廂品嚐正宗池上便當，認識台灣鐵道便當文化。',
    content:
      '<p>池上飯包文化故事館重現了早期月台賣便當的場景，館內展示池上米的種植歷史與便當文化演變。最特別的是可以坐在復古火車車廂座位上，享用以池上米製作的經典便當。故事館也提供飯包DIY體驗，自己動手做一份專屬的池上便當。</p>',
    price: 250,
    originPrice: 300,
    address: '台東縣池上鄉忠孝路259號',
    category: 'package',
    coordinates: { lat: 23.1248, lng: 121.2199 },
    imagePool: 'oldStreet',
    features: '池上便當,懷舊車廂,飯包DIY,米食文化,鐵道記憶',
    transport: '搭乘火車至池上站，步行約5分鐘',
    evaluate: 4.2,
    evaluateNum: 345,
  },
  {
    slug: 'chulu-ranch',
    title: '初鹿牧場門票與乳製品體驗',
    description: '在東台灣最大的坡地牧場餵食乳牛，品嚐新鮮現擠的鮮奶冰淇淋。',
    content:
      '<p>初鹿牧場位於卑南鄉，佔地約72公頃，是台東最具代表性的觀光牧場。大片翠綠草原上黑白花乳牛悠閒漫步，背景是中央山脈連綿山峰。園區提供餵食乳牛、滑草、小馬騎乘等親子活動，鮮奶冰淇淋與鮮乳饅頭是必嚐美食。</p>',
    price: 200,
    originPrice: 250,
    address: '台東縣卑南鄉明峰村牧場1號',
    category: 'tickets',
    coordinates: { lat: 22.8288, lng: 121.0506 },
    imagePool: 'park',
    features: '餵食乳牛,鮮奶冰淇淋,滑草體驗,小馬騎乘,草原風光',
    transport: '搭乘鼎東客運山線至初鹿站下車，步行約10分鐘',
    evaluate: 4.2,
    evaluateNum: 378,
  },
  {
    slug: 'taitung-seaside-park',
    title: '台東海濱公園國際地標打卡',
    description: '在台東最具代表性的海濱地標前拍照，欣賞太平洋日出與裝置藝術。',
    content:
      '<p>台東海濱公園的國際地標以竹編與藤編工藝打造，造型如巨大的藤編裝置矗立海岸邊，是台東的城市標誌。公園沿太平洋海岸延伸，設有完善的步道與自行車道。清晨來此觀賞日出，金光灑落在地標與海面上，是台東最經典的打卡畫面。</p>',
    price: 80,
    originPrice: 100,
    address: '台東縣台東市大同路',
    category: 'tickets',
    coordinates: { lat: 22.7531, lng: 121.158 },
    imagePool: 'city',
    features: '國際地標,太平洋日出,裝置藝術,海濱步道,自行車道',
    transport: '搭乘火車至台東站，步行約15分鐘',
    evaluate: 4.1,
    evaluateNum: 423,
  },
  {
    slug: 'fugang-fishing-port-whale',
    title: '富岡漁港賞鯨豚體驗',
    description: '搭乘賞鯨船出海，在太平洋上追尋海豚與鯨魚的蹤跡。',
    content:
      '<p>富岡漁港是台東前往綠島與蘭嶼的門戶，也是賞鯨豚的出發港。東海岸海域是多種鯨豚的棲息地，春夏期間可觀察到飛旋海豚、瓶鼻海豚，偶爾還有抹香鯨出沒。此體驗包含三小時海上航程、專業鯨豚解說與航海體驗。</p>',
    price: 900,
    originPrice: 1100,
    address: '台東縣台東市富岡街297號',
    category: 'package',
    coordinates: { lat: 22.787, lng: 121.1822 },
    imagePool: 'beach',
    features: '賞鯨船,海豚觀賞,專業解說,三小時航程,太平洋巡航',
    transport: '搭乘市區公車至富岡漁港站下車',
    evaluate: 4.3,
    evaluateNum: 198,
  },
  {
    slug: 'luanshan-forest-museum',
    title: '鸞山森林博物館部落體驗',
    description: '走進布農族的會走路的樹林，體驗部落文化與原始森林冒險。',
    content:
      '<p>鸞山森林博物館是由布農族人阿力曼守護的原始森林，以白榕樹盤根錯節的壯觀景象聞名，被稱為「會走路的樹」。此體驗需事先預約，由部落族人帶領穿越森林、攀爬榕樹氣根，並安排搗麻糬、烤山豬肉等傳統布農族體驗活動。</p>',
    price: 800,
    originPrice: 1000,
    address: '台東縣延平鄉鸞山路21號',
    category: 'package',
    coordinates: { lat: 22.8986, lng: 121.0754 },
    imagePool: 'nature',
    features: '白榕森林,布農族文化,搗麻糬體驗,森林冒險,部落導覽,預約制',
    transport: '台東火車站集合，專車接送至鸞山部落約30分鐘',
    evaluate: 4.7,
    evaluateNum: 234,
  },
  {
    slug: 'lijia-forest-trail',
    title: '利嘉林道生態健行之旅',
    description: '走入台東近郊的原始闊葉林步道，沉浸在蟲鳴鳥叫的綠色世界。',
    content:
      '<p>利嘉林道位於台東卑南鄉，是一條穿越低海拔原始闊葉林的林道，生態豐富而遊客稀少。步道沿溪而行，沿途可觀賞台灣獼猴、五色鳥、樹蛙等豐富的野生動物。此健行行程由生態導覽師帶領，深入解說沿途動植物生態。</p>',
    price: 700,
    originPrice: 900,
    address: '台東縣卑南鄉利嘉林道',
    category: 'package',
    coordinates: { lat: 22.7756, lng: 121.0231 },
    imagePool: 'nature',
    features: '原始闊葉林,生態導覽,野生動物觀察,溪谷步道,台灣獼猴',
    transport: '台東火車站集合，專車接送至林道入口約25分鐘',
    evaluate: 4.3,
    evaluateNum: 134,
  },
  {
    slug: 'lisong-hot-spring',
    title: '栗松溫泉秘境溯溪探險',
    description: '溯溪攀繩深入南橫山谷，抵達台灣最美的翡翠色野溪溫泉。',
    content:
      '<p>栗松溫泉被譽為「全台最美野溪溫泉」，碳酸鈣結晶在岩壁上形成翡翠綠與乳白色交錯的鐘乳石瀑布，溫泉水沿岩壁流入溪谷中的天然池。前往栗松溫泉需經過陡峭的溯溪路段，此行程由專業溯溪教練帶領，提供全套溯溪裝備與安全保障。</p>',
    price: 2800,
    originPrice: 3500,
    address: '台東縣海端鄉南橫公路',
    category: 'package',
    coordinates: { lat: 23.1848, lng: 121.0122 },
    imagePool: 'hotSpring',
    features: '野溪溫泉,溯溪體驗,全套裝備,專業教練,翡翠岩壁,安全保障',
    transport: '台東市區集合，專車沿南橫公路接送至登山口',
    evaluate: 4.8,
    evaluateNum: 156,
  },
  {
    slug: 'donghe-steamed-bun',
    title: '東河包子美食與部落文化體驗',
    description: '品嚐東海岸最知名的手工包子，走訪阿美族部落與東河橋。',
    content:
      '<p>東河包子是台東東海岸最具人氣的在地美食，以手工現桿現蒸聞名，肉餡飽滿多汁。此體驗結合美食與文化，品嚐包子後前往東河橋欣賞新舊橋交錯的獨特景觀，並走訪附近的阿美族都蘭部落，了解海岸阿美族的生活智慧與傳統文化。</p>',
    price: 600,
    originPrice: 750,
    address: '台東縣東河鄉東河村大馬路15-2號',
    category: 'package',
    coordinates: { lat: 22.9694, lng: 121.3012 },
    imagePool: 'oldStreet',
    features: '東河包子,阿美族部落,東河橋,在地導覽,部落文化,手工美食',
    transport: '搭乘花蓮客運海線至東河站下車，步行約3分鐘',
    evaluate: 4.2,
    evaluateNum: 298,
  },
  {
    slug: 'guanshan-cycling-trail',
    title: '關山自行車道環鎮之旅',
    description: '騎乘全台第一條自行車專用道，環繞關山小鎮飽覽田園與山景。',
    content:
      '<p>關山環鎮自行車道是全台第一條自行車專用道，全長12公里，沿途穿越稻田、果園與親水公園。車道平緩好騎，適合全家大小。此行程包含自行車租借與在地導覽，帶您認識關山米的故事，途中安排品嚐關山便當與在地特色小吃。</p>',
    price: 500,
    originPrice: 600,
    address: '台東縣關山鎮隆盛路1號',
    category: 'package',
    coordinates: { lat: 23.0476, lng: 121.164 },
    imagePool: 'nature',
    features: '全台第一自行車道,環鎮12公里,稻田風光,關山便當,親水公園',
    transport: '搭乘火車至關山站，步行至自行車租借站約5分鐘',
    evaluate: 4.4,
    evaluateNum: 312,
  },
]
