import type { ProductDefinition } from '../types'

export const taoyuanProducts: ProductDefinition[] = [
  {
    slug: 'daxi-old-street',
    title: '大溪老街導覽體驗',
    description: '漫步百年巴洛克牌樓街屋，品嚐豆干與木器文化之美。',
    content:
      '<p>大溪老街是桃園最具歷史風情的街區，保留了日治時期巴洛克風格的牌樓立面。沿街有百年豆干老店、傳統木器行與特色小吃，搭配專業導覽深入了解在地文化脈絡，是認識桃園人文的最佳起點。</p>',
    price: 350,
    originPrice: 450,
    address: '桃園市大溪區和平路',
    category: 'package',
    coordinates: { lat: 24.8836, lng: 121.2868 },
    imagePool: 'oldStreet',
    features: '專業導覽,豆干試吃,木藝DIY,老建築巡禮,伴手禮折扣',
    transport: '搭乘台灣好行慈湖線於大溪老街站下車',
    evaluate: 4.5,
    evaluateNum: 520,
  },
  {
    slug: 'window-on-china',
    title: '小人國主題樂園門票',
    description: '亞洲首座迷你景觀主題樂園，世界知名建築一次看遍。',
    content:
      '<p>小人國主題樂園以精緻的1:25迷你建築模型聞名，園區內可欣賞台灣、中國及世界各國地標建築。另設有室內外遊樂設施與水樂園，適合親子同遊，是桃園最經典的主題樂園之一。</p>',
    price: 650,
    originPrice: 799,
    address: '桃園市龍潭區高原路891號',
    category: 'tickets',
    coordinates: { lat: 24.8283, lng: 121.2147 },
    imagePool: 'park',
    features: '迷你建築,遊樂設施,水樂園,親子友善,拍照景點',
    transport: '搭乘新竹客運5653路於小人國站下車',
    evaluate: 4.3,
    evaluateNum: 680,
  },
  {
    slug: 'lalashan-nature-reserve',
    title: '拉拉山自然保護區生態之旅',
    description: '走進千年巨木群，感受北台灣最壯觀的原始森林。',
    content:
      '<p>拉拉山自然保護區擁有全台面積最大的紅檜巨木群，園區內設有完善的木棧步道串聯24棵編號巨木，樹齡最高超過2800年。沿途可觀察豐富的中海拔生態，春季水蜜桃盛產時更添風味。</p>',
    price: 1800,
    originPrice: 2200,
    address: '桃園市復興區華陵里',
    category: 'package',
    coordinates: { lat: 24.7083, lng: 121.4297 },
    imagePool: 'mountain',
    features: '千年巨木,木棧步道,生態導覽,部落文化,高山茶品嚐',
    transport: '搭乘桃園客運5090路至上巴陵後轉乘接駁車',
    evaluate: 4.7,
    evaluateNum: 310,
  },
  {
    slug: 'shimen-reservoir',
    title: '石門水庫環湖遊船體驗',
    description: '搭遊艇飽覽石門水庫碧綠湖光山色，享受悠閒午後。',
    content:
      '<p>石門水庫是北台灣最大的水庫，四季景色各有千秋——春天賞楓、夏日碧波、秋季楓紅、冬令梅開。搭乘遊艇環湖一圈約40分鐘，可遠眺溪洲山與薑母島，搭配活魚料理更是一大享受。</p>',
    price: 500,
    originPrice: 600,
    address: '桃園市大溪區環湖路一段68號',
    category: 'tickets',
    coordinates: { lat: 24.8134, lng: 121.2378 },
    imagePool: 'nature',
    features: '遊船體驗,湖光山色,楓葉季,活魚料理,攝影勝地',
    transport: '搭乘桃園客運5055路於石門水庫站下車',
    evaluate: 4.4,
    evaluateNum: 450,
  },
  {
    slug: 'taoyuan-shrine',
    title: '桃園神社古蹟巡禮',
    description: '全台保存最完整的日式神社，感受和風歷史之美。',
    content:
      '<p>桃園神社建於1938年，是目前台灣保存最完整的日治時期神社建築。園區內有鳥居、石燈籠、拜殿及本殿等完整建築群，經修復後成為桃園忠烈祠暨神社文化園區，是體驗日式建築美學的絕佳去處。</p>',
    price: 150,
    originPrice: 200,
    address: '桃園市桃園區成功路三段200號',
    category: 'tickets',
    coordinates: { lat: 24.9942, lng: 121.3186 },
    imagePool: 'temple',
    features: '日式建築,歷史古蹟,和服體驗,攝影景點,文化導覽',
    transport: '搭乘桃園市區公車於桃園神社站下車，步行約5分鐘',
    evaluate: 4.6,
    evaluateNum: 380,
  },
  {
    slug: 'xpark-aquarium',
    title: 'Xpark水族館門票',
    description: '日本橫濱八景島海島樂園海外首館，沉浸式海洋體驗。',
    content:
      '<p>Xpark是由日本橫濱八景島海島樂園打造的都會型水族館，共有13個展區，以科技投影與聲光效果營造沉浸式海洋體驗。從福爾摩沙大水槽到企鵝奇遇區，每個角落都令人驚嘆，是桃園最熱門的室內景點。</p>',
    price: 550,
    originPrice: 650,
    address: '桃園市中壢區春德路105號',
    category: 'tickets',
    coordinates: { lat: 25.0132, lng: 121.2157 },
    imagePool: 'nature',
    features: '沉浸式體驗,企鵝互動,水母展區,親子景點,室內場館',
    transport: '搭乘機場捷運至A18高鐵桃園站步行約8分鐘',
    evaluate: 4.5,
    evaluateNum: 750,
  },
  {
    slug: 'jiaobanshan',
    title: '角板山行館園區半日遊',
    description: '前總統蔣公行館與梅園，俯瞰大漢溪谷壯麗風光。',
    content:
      '<p>角板山行館位於復興區台地上，為蔣中正總統生前最喜愛的行館之一。園區內有梅園、樟腦收納所及戰備隧道等歷史遺跡，每年一月梅花盛開時吸引大量遊客前來賞花，登高可俯瞰大漢溪河谷美景。</p>',
    price: 800,
    originPrice: 1000,
    address: '桃園市復興區澤仁里中正路133-1號',
    category: 'package',
    coordinates: { lat: 24.8303, lng: 121.3508 },
    imagePool: 'mountain',
    features: '歷史行館,梅花季,戰備隧道,溪谷風光,原民文化',
    transport: '搭乘桃園客運5104路至角板山站下車',
    evaluate: 4.3,
    evaluateNum: 290,
  },
  {
    slug: 'daxi-old-tea-factory',
    title: '大溪老茶廠品茗體驗',
    description: '日治時期百年茶廠重生，在復古空間品一壺好茶。',
    content:
      '<p>大溪老茶廠建於1926年，曾是台灣最大的製茶廠之一。經修復後保留了原始檜木與紅磚結構，挑高的萎凋區搭配自然光線極為迷人。在此可了解製茶工序、品嚐在地茶品，是文青與茶人必訪之處。</p>',
    price: 600,
    originPrice: 750,
    address: '桃園市大溪區復興路一段732巷80號',
    category: 'package',
    coordinates: { lat: 24.8628, lng: 121.3049 },
    imagePool: 'tea',
    features: '百年茶廠,品茗體驗,製茶導覽,文青空間,伴手禮',
    transport: '搭乘台灣好行慈湖線於大溪老茶廠站下車',
    evaluate: 4.6,
    evaluateNum: 340,
  },
  {
    slug: 'taoyuan-baseball-stadium',
    title: '桃園國際棒球場觀賽體驗',
    description: '中華職棒Lamigo主場，感受全台最熱情的棒球氛圍。',
    content:
      '<p>桃園國際棒球場是樂天桃猿隊主場，球場設施完善並導入多項創新觀賽體驗，包括全猿主場、啤酒暢飲區與主題包廂。比賽日現場氣氛火熱，桃猿啦啦隊表演更是一大亮點，適合棒球迷與初次觀賽者。</p>',
    price: 500,
    originPrice: 650,
    address: '桃園市中壢區領航北路一段1號',
    category: 'tickets',
    coordinates: { lat: 25.0122, lng: 121.1936 },
    imagePool: 'city',
    features: '職棒觀賽,主題包廂,美食攤位,啦啦隊表演,紀念品',
    transport: '搭乘機場捷運至A19桃園體育園區站步行約10分鐘',
    evaluate: 4.4,
    evaluateNum: 410,
  },
  {
    slug: 'yongan-fishing-port',
    title: '永安漁港海鮮美食之旅',
    description: '桃園最大觀光漁港，現撈海鮮與絕美落日一次滿足。',
    content:
      '<p>永安漁港位於新屋區海岸線，是桃園最具規模的觀光漁港。漁港內有觀光魚市可採購新鮮漁獲，周邊餐廳提供平價海鮮料理。傍晚時分在綠色隧道自行車道騎車觀賞夕陽，是在地人推薦的私房行程。</p>',
    price: 800,
    originPrice: 1000,
    address: '桃園市新屋區永安里中山西路三段1165號',
    category: 'package',
    coordinates: { lat: 25.0036, lng: 121.0481 },
    imagePool: 'beach',
    features: '海鮮美食,觀光魚市,自行車道,落日美景,親子適合',
    transport: '搭乘桃園客運5031路至永安漁港站下車',
    evaluate: 4.2,
    evaluateNum: 360,
  },
  {
    slug: 'taoyuan-confucius-temple',
    title: '桃園孔廟文化參訪',
    description: '閩南式傳統建築孔廟，認識儒學文化與古典之美。',
    content:
      '<p>桃園孔廟位於虎頭山下，建築採閩南傳統宮殿式風格，紅牆黃瓦氣勢莊嚴。每年九月舉辦祭孔大典，重現古禮佾舞，平日則是市民散步休憩的清幽場所，園區內花木扶疏，適合靜心漫步。</p>',
    price: 80,
    originPrice: 100,
    address: '桃園市桃園區公園路42號',
    category: 'tickets',
    coordinates: { lat: 24.9968, lng: 121.3094 },
    imagePool: 'temple',
    features: '孔廟建築,祭孔大典,文化體驗,古典庭園,免費導覽',
    transport: '搭乘桃園市區公車於孔廟站下車，步行約3分鐘',
    evaluate: 4.1,
    evaluateNum: 180,
  },
  {
    slug: 'hutoushan-park',
    title: '虎頭山公園生態步道健行',
    description: '桃園市區後花園，全齡化步道與奧爾森林學堂。',
    content:
      '<p>虎頭山公園是桃園市區最大的都會公園，園區內有全齡化步道、奧爾森林學堂樹屋群及觀景平台。步道沿途生態豐富，可觀察松鼠、五色鳥等野生動物，登上山頂可遠眺桃園平原與台灣海峽，是市民休閒健行的首選。</p>',
    price: 500,
    originPrice: 650,
    address: '桃園市桃園區公園路',
    category: 'package',
    coordinates: { lat: 25.0003, lng: 121.3052 },
    imagePool: 'park',
    features: '生態步道,奧爾森林學堂,觀景平台,親子友善,自然生態',
    transport: '搭乘桃園市區公車於虎頭山公園站下車',
    evaluate: 4.4,
    evaluateNum: 420,
  },
  {
    slug: 'zhuwei-fishing-port',
    title: '竹圍漁港觀光半日遊',
    description: '北台灣知名觀光漁港，嚐鮮買魚看彩虹橋。',
    content:
      '<p>竹圍漁港是桃園北部最具知名度的觀光漁港，港區內設有魚貨直銷中心，各式新鮮海產任君挑選。跨越港口的彩虹橋是地標建築，傍晚在橋上欣賞夕陽餘暉映照漁港，是攝影愛好者的熱門取景點。</p>',
    price: 650,
    originPrice: 800,
    address: '桃園市大園區沙崙里1鄰漁港路451巷25號',
    category: 'package',
    coordinates: { lat: 25.1108, lng: 121.2344 },
    imagePool: 'beach',
    features: '海鮮直銷,彩虹橋,落日美景,觀光漁港,代客料理',
    transport: '搭乘桃園客運5065路至竹圍漁港站下車',
    evaluate: 4.2,
    evaluateNum: 380,
  },
  {
    slug: 'bade-ecological-park',
    title: '八德埤塘生態公園散策',
    description: '桃園獨特的埤塘地景，都市中的生態綠洲。',
    content:
      '<p>八德埤塘生態公園保留了桃園特有的埤塘文化地景，園區內水塘碧綠、林蔭步道環繞，設有生態觀察平台與木棧道。常見白鷺鷥、翠鳥等水鳥棲息，是都市中難得的生態教育場域，適合全家悠閒散步。</p>',
    price: 350,
    originPrice: 450,
    address: '桃園市八德區興豐路1315號',
    category: 'package',
    coordinates: { lat: 24.9456, lng: 121.2928 },
    imagePool: 'nature',
    features: '埤塘生態,木棧步道,水鳥觀察,生態教育,休閒散步',
    transport: '搭乘桃園市區公車於八德埤塘公園站下車',
    evaluate: 4.3,
    evaluateNum: 210,
  },
  {
    slug: 'zhongli-night-market',
    title: '中壢夜市美食巡禮',
    description: '北台灣最大觀光夜市之一，經典小吃一網打盡。',
    content:
      '<p>中壢觀光夜市擁有超過五百個攤位，從蚵仔煎、臭豆腐到新住民異國料理應有盡有。夜市以新明路為主軸延伸，是在地人與觀光客共同喜愛的夜間美食天堂。本套餐包含精選店家美食兌換券與導覽手冊。</p>',
    price: 500,
    originPrice: 650,
    address: '桃園市中壢區新明路',
    category: 'package',
    coordinates: { lat: 24.9575, lng: 121.2268 },
    imagePool: 'nightMarket',
    features: '夜市美食,小吃攤位,異國料理,伴手禮,在地文化',
    transport: '搭乘中壢市區公車至中壢夜市站下車',
    evaluate: 4.3,
    evaluateNum: 550,
  },
  {
    slug: 'tomita-farm',
    title: '富田花園農場入園門票',
    description: '四季花卉盛開的浪漫農場，拍照打卡超好拍。',
    content:
      '<p>富田花園農場以大面積花海聞名，四季輪替種植薰衣草、向日葵、波斯菊等花卉，園區內還有水晶教堂、歐式花園等造景。是婚紗攝影與網美打卡的熱門景點，也設有小動物互動區，適合親子遊覽。</p>',
    price: 200,
    originPrice: 250,
    address: '桃園市大溪區福安里頭寮一路29巷59號',
    category: 'tickets',
    coordinates: { lat: 24.8689, lng: 121.2753 },
    imagePool: 'nature',
    features: '四季花海,水晶教堂,小動物互動,婚紗攝影,親子適合',
    transport: '搭乘台灣好行慈湖線於富田農場站下車',
    evaluate: 4.1,
    evaluateNum: 320,
  },
  {
    slug: 'longtan-pond',
    title: '龍潭大池水上體驗',
    description: '桃園龍潭地標湖泊，踩船遊湖賞吊橋夜景。',
    content:
      '<p>龍潭大池是龍潭區最具代表性的地標，湖面設有觀光吊橋與環湖步道，可租借天鵝船或腳踏船悠遊湖面。每年端午節龍舟競賽更是年度盛事，夜間吊橋光雕亮起別有風情，是在地休閒的好去處。</p>',
    price: 300,
    originPrice: 400,
    address: '桃園市龍潭區中豐路上林段115巷11號',
    category: 'tickets',
    coordinates: { lat: 24.8639, lng: 121.2163 },
    imagePool: 'nature',
    features: '天鵝船,環湖步道,觀光吊橋,夜間光雕,龍舟賽',
    transport: '搭乘新竹客運5653路於龍潭大池站下車',
    evaluate: 4.2,
    evaluateNum: 280,
  },
  {
    slug: 'matsu-new-village',
    title: '馬祖新村眷村文創園區導覽',
    description: '桃園保存最完整的眷村聚落，走入時光隧道。',
    content:
      '<p>馬祖新村是桃園市保存最完整的眷村之一，原為陸軍眷屬宿舍，經活化後成為文創園區。巷弄間保留了紅磚矮房、老樹與舊時生活痕跡，不定期舉辦市集與展覽，是體驗台灣眷村文化的最佳場域。</p>',
    price: 400,
    originPrice: 500,
    address: '桃園市中壢區龍吉二街155號',
    category: 'package',
    coordinates: { lat: 24.9634, lng: 121.2456 },
    imagePool: 'oldStreet',
    features: '眷村文化,文創園區,歷史導覽,藝術展覽,假日市集',
    transport: '搭乘中壢市區公車至馬祖新村站下車步行約5分鐘',
    evaluate: 4.4,
    evaluateNum: 260,
  },
  {
    slug: 'caota-sand-dunes',
    title: '草漯沙丘地質探索',
    description: '台灣版撒哈拉沙漠，桃園海岸線最壯觀的自然奇景。',
    content:
      '<p>草漯沙丘是桃園觀音區海岸線上獨特的沙丘地形，綿延約8公里，最高處達15公尺。風吹沙動形成的紋理宛如微型沙漠，是攝影師與地質愛好者的天堂。目前設有觀景步道，可安全欣賞這片難得的海岸地景。</p>',
    price: 600,
    originPrice: 750,
    address: '桃園市觀音區忠孝路',
    category: 'package',
    coordinates: { lat: 25.0756, lng: 121.1028 },
    imagePool: 'beach',
    features: '沙丘地景,海岸風光,地質探索,攝影勝地,生態導覽',
    transport: '搭乘桃園客運5039路至草漯站下車步行約15分鐘',
    evaluate: 4.5,
    evaluateNum: 230,
  },
  {
    slug: 'qingtang-garden',
    title: '青塘園水岸散步',
    description: '桃園高鐵特區旁的都會綠地，地景藝術與水塘輝映。',
    content:
      '<p>青塘園位於桃園高鐵特區內，是經過生態整治的埤塘公園。園區內有送子鳥地景藝術裝置、環湖木棧道與大片草坪，夜間燈光倒映水面極為浪漫。交通便利，適合搭高鐵來桃園後第一站造訪。</p>',
    price: 350,
    originPrice: 450,
    address: '桃園市中壢區文德路339號',
    category: 'package',
    coordinates: { lat: 25.0126, lng: 121.2242 },
    imagePool: 'park',
    features: '地景藝術,水岸步道,夜間燈光,親子友善,交通便利',
    transport: '搭乘機場捷運至A18高鐵桃園站步行約12分鐘',
    evaluate: 4.2,
    evaluateNum: 190,
  },
  {
    slug: 'daxi-bridge',
    title: '大溪橋夜景漫步',
    description: '仿巴洛克風格的景觀橋樑，夜間光雕浪漫迷人。',
    content:
      '<p>大溪橋橫跨大漢溪，橋身採仿巴洛克風格設計，白天可遠眺河谷與石門水庫方向的山巒。入夜後LED光雕點亮整座橋身，是大溪地區最浪漫的夜景景點，也是連接大溪老街與河濱步道的重要通道。</p>',
    price: 100,
    originPrice: 130,
    address: '桃園市大溪區瑞安路一段',
    category: 'tickets',
    coordinates: { lat: 24.8802, lng: 121.2832 },
    imagePool: 'city',
    features: '夜間光雕,巴洛克建築,河谷風光,步行散策,攝影景點',
    transport: '搭乘台灣好行慈湖線於大溪橋頭站下車',
    evaluate: 4.3,
    evaluateNum: 350,
  },
  {
    slug: 'guanyin-algal-reef',
    title: '觀音藻礁生態導覽',
    description: '世界級珍貴藻礁地景，認識七千年的海洋奇蹟。',
    content:
      '<p>觀音藻礁是由殼狀珊瑚藻經過七千多年累積而成的珍貴地質景觀，為全球少數大面積藻礁之一。在專業導覽帶領下，可近距離觀察潮間帶豐富的生態，認識藻礁成因與保育議題，是深度生態旅遊的絕佳選擇。</p>',
    price: 700,
    originPrice: 900,
    address: '桃園市觀音區保生里',
    category: 'package',
    coordinates: { lat: 25.0667, lng: 121.0833 },
    imagePool: 'beach',
    features: '藻礁生態,潮間帶觀察,環境教育,生態導覽,攝影記錄',
    transport: '搭乘桃園客運5039路至觀音站後轉乘接駁',
    evaluate: 4.6,
    evaluateNum: 170,
  },
  {
    slug: 'beihen-highway-baling',
    title: '北橫公路巴陵段探險之旅',
    description: '穿越北台灣最美山路，飽覽溪谷與原民部落風情。',
    content:
      '<p>北橫公路巴陵段是台灣最壯觀的山區公路之一，沿途經過羅浮橋、巴陵橋與達觀山等景點，可俯瞰大漢溪上游深邃峽谷。行程包含泰雅族部落導覽與風味餐，帶您深入體驗北橫沿線的自然與人文魅力。</p>',
    price: 2500,
    originPrice: 3000,
    address: '桃園市復興區巴陵',
    category: 'package',
    coordinates: { lat: 24.7175, lng: 121.3847 },
    imagePool: 'mountain',
    features: '山岳公路,溪谷風光,泰雅部落,風味餐,專車接送',
    transport: '集合地點：桃園火車站前廣場，含專車接送',
    evaluate: 4.7,
    evaluateNum: 150,
  },
  {
    slug: 'taoyuan-art-museum',
    title: '桃園市立美術館門票',
    description: '桃園最新文化地標，當代藝術與建築的完美交會。',
    content:
      '<p>桃園市立美術館是桃園指標性的文化建設，建築外觀以山丘意象設計，融入在地埤塘地景。館內展出國內外當代藝術作品，不定期舉辦特展與藝術教育活動，是藝文愛好者不可錯過的新興景點。</p>',
    price: 200,
    originPrice: 250,
    address: '桃園市中壢區高鐵南路二段418號',
    category: 'tickets',
    coordinates: { lat: 25.0058, lng: 121.2148 },
    imagePool: 'museum',
    features: '當代藝術,建築設計,特展活動,藝術教育,文創商店',
    transport: '搭乘機場捷運至A19桃園體育園區站步行約15分鐘',
    evaluate: 4.5,
    evaluateNum: 200,
  },
  {
    slug: 'wei-chuan-farm',
    title: '味全埔心農場一日遊',
    description: '北台灣老字號休閒農場，與可愛動物近距離互動。',
    content:
      '<p>味全埔心農場佔地約50公頃，是北台灣歷史最悠久的休閒農場之一。園區內有牧場區可餵食乳牛與山羊、大片歐式花園與露營區。假日還有擠牛奶、DIY奶酪等體驗活動，是親子同遊的熱門選擇。</p>',
    price: 350,
    originPrice: 400,
    address: '桃園市楊梅區幼獅路一段439號',
    category: 'tickets',
    coordinates: { lat: 24.9194, lng: 121.1528 },
    imagePool: 'nature',
    features: '動物互動,牧場體驗,DIY活動,歐式花園,露營區',
    transport: '搭乘新竹客運5654路於埔心農場站下車',
    evaluate: 4.2,
    evaluateNum: 480,
  },
]
