import type { ProductDefinition } from '../types'

export const yilanProducts: ProductDefinition[] = [
  {
    slug: 'jiaoxi-hot-spring',
    title: '礁溪溫泉湯屋體驗',
    description: '宜蘭最知名的平地溫泉鄉，碳酸氫鈉美人湯暖心暖身。',
    content:
      '<p>礁溪溫泉是台灣少數位於平地的溫泉區，泉質為碳酸氫鈉泉，無色無味，有「美人湯」的美譽。本體驗提供精選湯屋雙人泡湯，附贈下午茶點心，讓您在雪山山脈腳下享受最放鬆的溫泉時光。</p>',
    price: 1200,
    originPrice: 1500,
    address: '宜蘭縣礁溪鄉溫泉路',
    category: 'package',
    coordinates: { lat: 24.8275, lng: 121.7719 },
    imagePool: 'hotSpring',
    features: '美人湯,雙人湯屋,下午茶,碳酸氫鈉泉,放鬆療癒',
    transport: '搭乘火車至礁溪站步行約10分鐘',
    evaluate: 4.7,
    evaluateNum: 680,
  },
  {
    slug: 'jimmy-plaza',
    title: '幾米廣場拍照散策',
    description: '繪本走入現實，宜蘭火車站旁的奇幻藝術裝置。',
    content:
      '<p>幾米廣場位於宜蘭火車站南側，以繪本作家幾米的《向左走·向右走》與《星空》為主題，將繪本場景立體化呈現。巨大行李箱、公車候車亭與飛天列車等裝置藝術，是打卡拍照的熱門景點，全天候免費開放。</p>',
    price: 300,
    originPrice: 380,
    address: '宜蘭縣宜蘭市光復路1號',
    category: 'package',
    coordinates: { lat: 24.7553, lng: 121.7583 },
    imagePool: 'city',
    features: '幾米繪本,裝置藝術,拍照景點,免費參觀,文創商品',
    transport: '搭乘火車至宜蘭站即達',
    evaluate: 4.3,
    evaluateNum: 520,
  },
  {
    slug: 'luodong-night-market',
    title: '羅東夜市美食巡禮',
    description: '宜蘭最熱鬧的夜市，包心粉圓與三星蔥餅飄香四溢。',
    content:
      '<p>羅東夜市是宜蘭人氣最旺的夜間美食聚落，以民權路與民生路為主要範圍。必吃美食包括包心粉圓、三星蔥肉串、龍鳳腿、當歸羊肉湯與花生捲冰淇淋。本套票含精選六攤美食兌換券與夜市導覽地圖。</p>',
    price: 550,
    originPrice: 700,
    address: '宜蘭縣羅東鎮民權路',
    category: 'package',
    coordinates: { lat: 24.6797, lng: 121.77 },
    imagePool: 'nightMarket',
    features: '夜市小吃,包心粉圓,三星蔥餅,當歸羊肉,花生捲冰淇淋,美食券',
    transport: '搭乘火車至羅東站步行約10分鐘',
    evaluate: 4.5,
    evaluateNum: 750,
  },
  {
    slug: 'traditional-arts-center',
    title: '國立傳統藝術中心門票',
    description: '體驗台灣民俗工藝之美，穿越時空的傳藝老街。',
    content:
      '<p>國立傳統藝術中心位於冬山河畔，園區以傳統閩南式建築群重現台灣早期街景。內有多間工藝工坊提供捏麵人、手拉坯、藍染等DIY體驗，假日還有布袋戲與歌仔戲演出，是認識台灣傳統文化的最佳場域。</p>',
    price: 250,
    originPrice: 300,
    address: '宜蘭縣五結鄉五濱路二段201號',
    category: 'tickets',
    coordinates: { lat: 24.6892, lng: 121.8239 },
    imagePool: 'oldStreet',
    features: '傳統工藝,DIY體驗,古早街景,戲曲表演,文化園區',
    transport: '搭乘國光客運1766路於傳藝中心站下車',
    evaluate: 4.6,
    evaluateNum: 600,
  },
  {
    slug: 'taipingshan',
    title: '太平山國家森林遊樂區一日遊',
    description: '宜蘭最壯觀的高山森林，搭蹦蹦車穿梭雲霧間。',
    content:
      '<p>太平山位於海拔約2000公尺，是北台灣面積最大的國家森林遊樂區。園區內有翠峰湖環山步道、見晴懷古步道（全球最美28條小路之一）與蹦蹦車鐵道體驗。四季風景各異——春花、夏綠、秋楓、冬雪，是宜蘭必訪的山林秘境。</p>',
    price: 2500,
    originPrice: 3200,
    address: '宜蘭縣大同鄉太平巷58之1號',
    category: 'package',
    coordinates: { lat: 24.5061, lng: 121.5139 },
    imagePool: 'mountain',
    features: '蹦蹦車,翠峰湖,見晴步道,高山森林,雲海日出',
    transport: '集合地點：宜蘭火車站，含專車接送',
    evaluate: 4.8,
    evaluateNum: 520,
  },
  {
    slug: 'suao-cold-spring',
    title: '蘇澳冷泉泡湯體驗',
    description: '全世界僅有的低溫碳酸冷泉，夏日消暑聖地。',
    content:
      '<p>蘇澳冷泉是世界少見的低溫碳酸泉，水溫終年維持在22°C左右，富含二氧化碳氣泡。初入泉中略感冰涼，數分鐘後全身溫暖舒暢，有如天然氣泡水SPA。本體驗含個人湯屋與冷泉汽水一瓶，是夏日最獨特的消暑方式。</p>',
    price: 350,
    originPrice: 450,
    address: '宜蘭縣蘇澳鎮冷泉路6-4號',
    category: 'tickets',
    coordinates: { lat: 24.5964, lng: 121.8456 },
    imagePool: 'hotSpring',
    features: '碳酸冷泉,個人湯屋,冷泉汽水,夏日消暑,獨特體驗',
    transport: '搭乘火車至蘇澳新站步行約15分鐘',
    evaluate: 4.4,
    evaluateNum: 410,
  },
  {
    slug: 'guishan-island',
    title: '龜山島登島半日遊',
    description: '台灣最具代表性的火山島，登島賞鯨一次滿足。',
    content:
      '<p>龜山島位於宜蘭外海約10公里處，是台灣唯一的活火山島。登島行程包含環湖步道、軍事坑道與401高地攻頂，沿途可見硫氣噴發口與牛奶海奇景。搭配賞鯨行程，有機會目睹飛旋海豚躍出海面的震撼畫面。</p>',
    price: 1800,
    originPrice: 2200,
    address: '宜蘭縣頭城鎮烏石港',
    category: 'package',
    coordinates: { lat: 24.8428, lng: 121.9508 },
    imagePool: 'island',
    features: '登島探險,賞鯨豚,牛奶海,火山地質,軍事坑道',
    transport: '烏石港搭乘賞鯨船前往，航程約30分鐘',
    evaluate: 4.8,
    evaluateNum: 460,
  },
  {
    slug: 'waiao-beach',
    title: '外澳沙灘衝浪體驗',
    description: '宜蘭最熱門的衝浪海灘，面對龜山島乘風破浪。',
    content:
      '<p>外澳沙灘位於頭城鎮，金色沙灘面對太平洋與龜山島，是北台灣最佳的衝浪聖地之一。本體驗包含專業教練指導、衝浪板租借與防寒衣，適合初學者至進階衝浪客。岸邊的黃色外澳服務區是打卡地標。</p>',
    price: 1500,
    originPrice: 1800,
    address: '宜蘭縣頭城鎮濱海路二段6號',
    category: 'package',
    coordinates: { lat: 24.87, lng: 121.8422 },
    imagePool: 'beach',
    features: '衝浪教學,器材租借,龜山島海景,沙灘活動,專業教練',
    transport: '搭乘火車至外澳站步行約5分鐘',
    evaluate: 4.5,
    evaluateNum: 370,
  },
  {
    slug: 'happy-station',
    title: '宜蘭幸福轉運站門票',
    description: '廢棄客運站變身童趣樂園，幾米彩繪巴士好療癒。',
    content:
      '<p>宜蘭幸福轉運站由舊國光客運站改建，以幾米繪本《忘記親一下》為主題打造。園區內有大型粉紅大象溜滑梯、長頸鹿瞭望台與彩繪巴士等遊樂設施，結合文創市集與輕食咖啡，是親子遊客的快樂天堂。</p>',
    price: 150,
    originPrice: 200,
    address: '宜蘭縣宜蘭市宜興路一段117號',
    category: 'tickets',
    coordinates: { lat: 24.7517, lng: 121.755 },
    imagePool: 'city',
    features: '幾米主題,親子遊樂,溜滑梯,文創市集,拍照景點',
    transport: '搭乘火車至宜蘭站步行約3分鐘',
    evaluate: 4.2,
    evaluateNum: 340,
  },
  {
    slug: 'kavalan-whisky',
    title: '噶瑪蘭威士忌酒廠導覽',
    description: '台灣之光的威士忌酒廠，從製程到品酒全體驗。',
    content:
      '<p>噶瑪蘭威士忌酒廠是台灣第一座威士忌蒸餾廠，其產品多次在國際烈酒競賽中獲獎。導覽行程帶您參觀糖化、發酵、蒸餾與熟成等製程，最後在品酒室品嚐經典與限定酒款，是威士忌愛好者的朝聖之地。</p>',
    price: 500,
    originPrice: 600,
    address: '宜蘭縣員山鄉員山路二段326號',
    category: 'tickets',
    coordinates: { lat: 24.7278, lng: 121.7186 },
    imagePool: 'nature',
    features: '威士忌品酒,製程導覽,國際得獎,限定酒款,伴手禮',
    transport: '搭乘國光客運1786路於噶瑪蘭酒廠站下車',
    evaluate: 4.6,
    evaluateNum: 490,
  },
  {
    slug: 'mingchi-forest',
    title: '明池國家森林遊樂區門票',
    description: '北橫明珠，海拔1200公尺的高山湖泊仙境。',
    content:
      '<p>明池位於北橫公路最高點附近，海拔約1150公尺，園區以高山人工湖為核心，四周環繞原始檜木林。湖面常年薄霧繚繞，倒映周圍翠綠山林，有「北橫明珠」之美譽。園區內設有森林步道、靜石園與蕨園等景觀。</p>',
    price: 350,
    originPrice: 450,
    address: '宜蘭縣大同鄉英士村明池山莊1號',
    category: 'tickets',
    coordinates: { lat: 24.6531, lng: 121.4697 },
    imagePool: 'mountain',
    features: '高山湖泊,檜木森林,雲霧仙境,森林步道,靜石園',
    transport: '集合地點：宜蘭火車站，搭乘接駁車約2.5小時',
    evaluate: 4.7,
    evaluateNum: 320,
  },
  {
    slug: 'dongshan-river',
    title: '冬山河親水公園門票',
    description: '宜蘭國際童玩節主場地，水上活動與河岸風光。',
    content:
      '<p>冬山河親水公園以「親近水，擁有綠」為設計理念，河道平緩適合划船與水上活動。每年暑假舉辦的宜蘭國際童玩節在此盛大展開，園區內設有噴泉廣場、戲水區與大片草坪，平日則是市民野餐休憩的好去處。</p>',
    price: 200,
    originPrice: 250,
    address: '宜蘭縣五結鄉親河路二段2號',
    category: 'tickets',
    coordinates: { lat: 24.6819, lng: 121.8083 },
    imagePool: 'nature',
    features: '親水公園,童玩節,水上活動,河岸風光,野餐草坪',
    transport: '搭乘國光客運1766路於親水公園站下車',
    evaluate: 4.3,
    evaluateNum: 450,
  },
  {
    slug: 'meihua-lake',
    title: '梅花湖自行車環湖',
    description: '形如梅花瓣的靜謐湖泊，騎單車悠遊湖畔風光。',
    content:
      '<p>梅花湖因湖面形狀酷似五瓣梅花而得名，環湖車道全長約4公里，沿途林蔭夾道、視野開闊。湖中有座小島可搭乘小船前往，湖畔的小熊書房咖啡廳是知名休憩點。騎乘電動自行車環湖一圈約30分鐘，輕鬆愜意。</p>',
    price: 400,
    originPrice: 500,
    address: '宜蘭縣冬山鄉環湖路',
    category: 'package',
    coordinates: { lat: 24.6403, lng: 121.7431 },
    imagePool: 'nature',
    features: '自行車環湖,湖中小島,咖啡廳,電動自行車,親子適合',
    transport: '搭乘首都客運1570路至梅花湖站下車',
    evaluate: 4.4,
    evaluateNum: 380,
  },
  {
    slug: 'nanfangao-port',
    title: '南方澳漁港海鮮之旅',
    description: '東台灣最大近海漁港，現撈海鮮鮮甜到不行。',
    content:
      '<p>南方澳漁港是台灣東部最大的漁港，以鯖魚與飛虎魚聞名。港邊的海鮮餐廳提供現撈現煮的平價海產，搭配豆腐岬風景區的海蝕地形與內埤海灘的弧形沙灘，是蘇澳地區最受歡迎的美食觀光路線。</p>',
    price: 800,
    originPrice: 1000,
    address: '宜蘭縣蘇澳鎮南方澳漁港路',
    category: 'package',
    coordinates: { lat: 24.5847, lng: 121.8681 },
    imagePool: 'beach',
    features: '海鮮美食,觀光漁港,豆腐岬,內埤海灘,現撈料理',
    transport: '搭乘國光客運1766路至南方澳站下車',
    evaluate: 4.5,
    evaluateNum: 430,
  },
  {
    slug: 'toucheng-old-street',
    title: '頭城老街文化散步',
    description: '宜蘭開發最早的街區，清代商港風華歲月留痕。',
    content:
      '<p>頭城老街是蘭陽平原最古老的街道，曾是清代烏石港旁的繁華商埠。街道兩側保留了多棟清代與日治時期建築，包括盧宅、新長興樹記等歷史宅邸。近年注入文創活力，藝術家工作室與小店穿插其間，散步別有韻味。</p>',
    price: 350,
    originPrice: 450,
    address: '宜蘭縣頭城鎮和平街',
    category: 'package',
    coordinates: { lat: 24.8594, lng: 121.8231 },
    imagePool: 'oldStreet',
    features: '歷史老街,清代建築,文創小店,藝術家工作室,古蹟導覽',
    transport: '搭乘火車至頭城站步行約10分鐘',
    evaluate: 4.3,
    evaluateNum: 260,
  },
  {
    slug: 'renshan-botanical',
    title: '仁山植物園生態探索',
    description: '冬山鄉的後花園，多元生態與登山步道一次擁有。',
    content:
      '<p>仁山植物園位於冬山鄉新寮山上，佔地約100公頃，分為東方庭園、西方庭園與大航海植物區等主題區。步道系統完善，沿途可觀察亞熱帶植物生態，山頂可遠眺蘭陽平原與太平洋，免費入園是一大優點。</p>',
    price: 500,
    originPrice: 650,
    address: '宜蘭縣冬山鄉新寮路500號',
    category: 'package',
    coordinates: { lat: 24.6478, lng: 121.7606 },
    imagePool: 'nature',
    features: '植物園區,登山步道,蘭陽平原眺望,免費入園,生態教育',
    transport: '搭乘首都客運1570路至仁山植物園站下車',
    evaluate: 4.3,
    evaluateNum: 200,
  },
  {
    slug: 'yilan-setting-museum',
    title: '宜蘭設治紀念館門票',
    description: '日式木造官邸的雅致空間，訴說宜蘭百年設治歷史。',
    content:
      '<p>宜蘭設治紀念館前身為宜蘭廳長官邸，建於1906年，是典型的日式和洋折衷建築。館內展示宜蘭從清代噶瑪蘭廳到現代的行政沿革，庭園內百年老樟樹蒼翠挺拔。與鄰近的文學館及九芎埕藝術廣場連成文化散步路線。</p>',
    price: 80,
    originPrice: 100,
    address: '宜蘭縣宜蘭市舊城南路力行3巷3號',
    category: 'tickets',
    coordinates: { lat: 24.7519, lng: 121.7547 },
    imagePool: 'museum',
    features: '日式官邸,歷史展覽,百年老樹,和洋建築,文化散步',
    transport: '搭乘火車至宜蘭站步行約10分鐘',
    evaluate: 4.4,
    evaluateNum: 190,
  },
  {
    slug: 'qingshui-geothermal',
    title: '清水地熱公園煮蛋體驗',
    description: '在天然地熱噴氣口煮溫泉蛋與玉米，大地廚房超有趣。',
    content:
      '<p>清水地熱公園位於大同鄉，是台灣少數可體驗地熱煮食的景點。園區內提供竹籃與食材租借，將蛋、玉米、筊白筍放入攝氏近百度的地熱水中烹煮，約15分鐘即可享用。周圍白煙裊裊的地熱景觀壯觀而獨特。</p>',
    price: 300,
    originPrice: 380,
    address: '宜蘭縣大同鄉三星路八段501巷139號',
    category: 'tickets',
    coordinates: { lat: 24.6225, lng: 121.6167 },
    imagePool: 'hotSpring',
    features: '地熱煮食,溫泉蛋,自然奇觀,親子體驗,食材租借',
    transport: '搭乘國光客運1745路至清水地熱站下車',
    evaluate: 4.5,
    evaluateNum: 550,
  },
  {
    slug: 'wufengqi-waterfall',
    title: '五峰旗瀑布步道健行',
    description: '三層壯觀瀑布群，礁溪最美的山林秘境。',
    content:
      '<p>五峰旗瀑布位於礁溪鄉，由三層瀑布組成，全長約1公里的步道串聯各層瀑布。第三層瀑布高約50公尺最為壯觀，水氣氤氳清涼宜人。步道沿途溪水淙淙、綠意盎然，也是前往聖母山莊朝聖之路的起點。</p>',
    price: 400,
    originPrice: 500,
    address: '宜蘭縣礁溪鄉五峰路',
    category: 'package',
    coordinates: { lat: 24.82, lng: 121.7453 },
    imagePool: 'waterfall',
    features: '三層瀑布,森林步道,負離子,溪水戲水,聖母山莊',
    transport: '搭乘台灣好行礁溪線至五峰旗瀑布站下車',
    evaluate: 4.6,
    evaluateNum: 400,
  },
  {
    slug: 'zhuangwei-dunes',
    title: '壯圍沙丘旅遊服務園區門票',
    description: '蔡明亮導演策展的藝術沙丘，影像與自然的對話。',
    content:
      '<p>壯圍沙丘旅遊服務園區由建築師黃聲遠設計，導演蔡明亮策劃常設展《行者》系列。建築以沙丘意象融入海岸地景，內部展廳播放慢電影影像，走出戶外即是宜蘭綿延的黃金沙灘，是一處結合藝術與自然的獨特空間。</p>',
    price: 150,
    originPrice: 200,
    address: '宜蘭縣壯圍鄉壯濱路二段196巷18號',
    category: 'tickets',
    coordinates: { lat: 24.7539, lng: 121.8228 },
    imagePool: 'beach',
    features: '藝術展覽,沙丘地景,慢電影,建築設計,黃金沙灘',
    transport: '搭乘國光客運1788路至壯圍沙丘站下車',
    evaluate: 4.3,
    evaluateNum: 220,
  },
  {
    slug: 'linmei-shipan-trail',
    title: '林美石磐步道健行',
    description: '礁溪最美的低海拔亞熱帶溪谷步道，綠意環抱。',
    content:
      '<p>林美石磐步道位於礁溪鄉林美村，全長約1.7公里，以環形路線穿越亞熱帶溪谷森林。步道沿途有巨石、瀑布與清澈溪流，林蔭覆蓋率極高，即使炎夏也涼爽宜人。因控管入園人數，建議提早前往確保入場。</p>',
    price: 500,
    originPrice: 650,
    address: '宜蘭縣礁溪鄉林尾路',
    category: 'package',
    coordinates: { lat: 24.8389, lng: 121.7389 },
    imagePool: 'waterfall',
    features: '環形步道,溪谷森林,瀑布景觀,涼爽宜人,人數控管',
    transport: '搭乘台灣好行礁溪線至林美石磐步道站下車',
    evaluate: 4.7,
    evaluateNum: 350,
  },
  {
    slug: 'lanyang-museum',
    title: '蘭陽博物館門票',
    description: '以單面山造型聞名的宜蘭地標，認識蘭陽平原的前世今生。',
    content:
      '<p>蘭陽博物館以北關海岸的單面山地形為設計靈感，建築外觀獨特震撼。館內常設展以「山之層」、「平原層」、「海之層」呈現宜蘭的自然與人文風貌，互動式展覽適合各年齡層，是認識宜蘭的最佳起點。</p>',
    price: 100,
    originPrice: 130,
    address: '宜蘭縣頭城鎮青雲路三段750號',
    category: 'tickets',
    coordinates: { lat: 24.8672, lng: 121.8311 },
    imagePool: 'museum',
    features: '地標建築,常設展覽,互動體驗,山海文化,建築攝影',
    transport: '搭乘火車至頭城站轉乘台灣好行至蘭陽博物館站',
    evaluate: 4.5,
    evaluateNum: 530,
  },
  {
    slug: 'sanxing-scallion-farm',
    title: '三星蔥農場體驗',
    description: '親手拔蔥、洗蔥、做蔥油餅，宜蘭最有趣的農事體驗。',
    content:
      '<p>三星蔥是宜蘭最具代表性的農產品，蔥白長且口感細嫩。在三星蔥農場可體驗從蔥田拔蔥、清洗到親手製作蔥油餅的完整流程，現煎現吃的蔥油餅香氣撲鼻。農場主人會講解三星蔥的種植知識，寓教於樂。</p>',
    price: 250,
    originPrice: 300,
    address: '宜蘭縣三星鄉天福村東興路13號',
    category: 'tickets',
    coordinates: { lat: 24.6644, lng: 121.6653 },
    imagePool: 'nature',
    features: '拔蔥體驗,蔥油餅DIY,農事教育,親子活動,在地農產',
    transport: '搭乘國光客運1794路至三星站轉乘接駁',
    evaluate: 4.6,
    evaluateNum: 470,
  },
  {
    slug: 'cilan-forest',
    title: '棲蘭森林遊樂區一日遊',
    description: '棲蘭神木園的千年扁柏群，走入台灣最原始的霧林帶。',
    content:
      '<p>棲蘭森林遊樂區位於大同鄉，園區內最珍貴的是棲蘭神木園，擁有51棵以歷代古人命名的千年紅檜與扁柏巨木。步道穿梭於霧林帶中，空氣中瀰漫芬多精，是喜愛森林浴與巨木的旅人不可錯過的秘境。</p>',
    price: 2800,
    originPrice: 3500,
    address: '宜蘭縣大同鄉泰雅路四段',
    category: 'package',
    coordinates: { lat: 24.5833, lng: 121.5 },
    imagePool: 'mountain',
    features: '千年神木,霧林帶,森林浴,芬多精,專車接送',
    transport: '集合地點：宜蘭火車站，含專車接送',
    evaluate: 4.7,
    evaluateNum: 240,
  },
  {
    slug: 'jiuzhize-hot-spring',
    title: '鳩之澤溫泉煮蛋泡湯',
    description: '太平山腳下的野溪溫泉，在山林間享受原始泡湯樂趣。',
    content:
      '<p>鳩之澤溫泉位於太平山國家森林遊樂區內，泉質為弱鹼性碳酸氫鈉泉，水溫約攝氏50度。設有露天SPA池、裸湯區與煮蛋槽，可在群山環繞的原始森林中泡湯，再用溫泉水煮顆藍色溫泉蛋當點心，愜意無比。</p>',
    price: 800,
    originPrice: 1000,
    address: '宜蘭縣大同鄉太平巷58之1號',
    category: 'package',
    coordinates: { lat: 24.5194, lng: 121.525 },
    imagePool: 'hotSpring',
    features: '野溪溫泉,露天SPA,溫泉煮蛋,森林泡湯,碳酸氫鈉泉',
    transport: '由太平山莊搭乘接駁車約20分鐘可達',
    evaluate: 4.6,
    evaluateNum: 360,
  },
]
