import type { ProductDefinition } from '../types'

export const yunlinProducts: ProductDefinition[] = [
  {
    slug: 'janfusun-fancyworld',
    title: '劍湖山世界主題樂園門票',
    description: '中南部最大主題樂園，刺激遊樂設施與水上樂園一票玩到底。',
    content:
      '<p>劍湖山世界是雲林最具代表性的主題樂園，園區內有摩天輪、自由落體、雲霄飛車等數十項遊樂設施，夏季水上樂園更是消暑首選。夜間園區燈光秀與煙火表演增添浪漫氣氛。</p>',
    price: 799,
    originPrice: 999,
    address: '雲林縣古坑鄉永光村大湖口67之8號',
    category: 'tickets',
    coordinates: { lat: 23.615, lng: 120.588 },
    imagePool: 'park',
    features: '主題樂園,雲霄飛車,水上樂園,摩天輪,親子友善',
    transport: '自斗六火車站搭乘台西客運至劍湖山站，車程約30分鐘。',
    evaluate: 4.3,
    evaluateNum: 780,
  },
  {
    slug: 'huwei-sugar-factory',
    title: '虎尾糖廠冰品與文創巡禮',
    description: '走訪百年糖廠遺址，品嚐招牌冰棒並逛文創聚落。',
    content:
      '<p>虎尾糖廠創立於日治時期，是台灣少數仍保留製糖設備的老糖廠。廠區內的冰品部販售古早味紅豆冰棒與甘蔗冰，周邊同心公園與文創聚落有藝術家工作室與小店，充滿懷舊風情。</p>',
    price: 500,
    originPrice: 650,
    address: '雲林縣虎尾鎮中山路2號',
    category: 'package',
    coordinates: { lat: 23.708, lng: 120.432 },
    imagePool: 'oldStreet',
    features: '百年糖廠,古早味冰品,文創聚落,日式建築,懷舊氛圍',
    transport: '自虎尾轉運站步行約10分鐘。',
    evaluate: 4.2,
    evaluateNum: 340,
  },
  {
    slug: 'beigang-chaotian-temple',
    title: '北港朝天宮媽祖文化之旅',
    description: '參拜全台最重要的媽祖廟，深入認識三百年的媽祖信仰文化。',
    content:
      '<p>北港朝天宮創建於清康熙年間，是台灣媽祖信仰的重鎮。廟宇建築雕工精美，每年農曆三月媽祖遶境是全台最盛大的宗教活動。導覽將解說廟宇建築特色、媽祖文化與北港老街歷史。</p>',
    price: 800,
    originPrice: 1000,
    address: '雲林縣北港鎮中山路178號',
    category: 'package',
    coordinates: { lat: 23.569, lng: 120.303 },
    imagePool: 'temple',
    features: '國定古蹟,媽祖信仰,廟宇建築,文化導覽,北港老街,含試吃',
    transport: '自嘉義火車站搭嘉義客運至北港站，車程約40分鐘。',
    evaluate: 4.7,
    evaluateNum: 620,
  },
  {
    slug: 'xiluo-bridge',
    title: '西螺大橋歷史巡禮',
    description: '漫步曾經的遠東第一大橋，見證台灣戰後建設的輝煌年代。',
    content:
      '<p>西螺大橋橫跨濁水溪，1953年完工時是遠東最長的鋼鐵大橋。紅色鋼構桁架在夕陽下特別壯觀，橋頭公園設有歷史解說牌，搭配西螺老街巡禮是認識雲林歷史的經典路線。</p>',
    price: 600,
    originPrice: 750,
    address: '雲林縣西螺鎮大橋路',
    category: 'package',
    coordinates: { lat: 23.782, lng: 120.466 },
    imagePool: 'city',
    features: '歷史大橋,紅色鋼構,夕陽美景,歷史導覽,搭配老街',
    transport: '自斗六火車站搭台西客運至西螺站，車程約20分鐘。',
    evaluate: 4.1,
    evaluateNum: 250,
  },
  {
    slug: 'puppet-museum',
    title: '雲林布袋戲博物館門票',
    description: '走進布袋戲的故鄉，欣賞精緻戲偶與現場表演。',
    content:
      '<p>雲林布袋戲博物館位於虎尾，展示台灣布袋戲從傳統到金光戲的發展歷程。館內收藏數百尊精緻戲偶，定時有現場表演與操偶體驗，是認識台灣傳統藝術的重要場所。</p>',
    price: 150,
    originPrice: 200,
    address: '雲林縣虎尾鎮林森路一段498號',
    category: 'tickets',
    coordinates: { lat: 23.71, lng: 120.435 },
    imagePool: 'museum',
    features: '布袋戲,傳統藝術,戲偶收藏,現場表演,操偶體驗',
    transport: '自虎尾轉運站步行約8分鐘。',
    evaluate: 4.4,
    evaluateNum: 310,
  },
  {
    slug: 'gukeng-coffee',
    title: '古坑咖啡莊園體驗',
    description: '探訪台灣咖啡原鄉，從採豆到烘焙，品嚐道地古坑咖啡。',
    content:
      '<p>古坑是台灣最早種植咖啡的產地之一，日治時期即有咖啡栽種紀錄。莊園體驗包含咖啡園導覽、認識咖啡品種、親手採摘咖啡果實、體驗手烘咖啡，最後品嚐自己烘的古坑咖啡。</p>',
    price: 1200,
    originPrice: 1500,
    address: '雲林縣古坑鄉荷苞村',
    category: 'package',
    coordinates: { lat: 23.642, lng: 120.562 },
    imagePool: 'tea',
    features: '咖啡莊園,採豆體驗,手烘咖啡,品嚐教學,台灣咖啡原鄉',
    transport: '自斗六火車站搭台西客運至古坑站，車程約25分鐘。',
    evaluate: 4.6,
    evaluateNum: 380,
  },
  {
    slug: 'caoling-canyon',
    title: '草嶺萬年峽谷探險',
    description: '溯溪而上深入萬年地層，壯觀的峽谷溪流令人屏息。',
    content:
      '<p>草嶺萬年峽谷位於古坑鄉草嶺山區，清水溪歷經數萬年切割侵蝕形成壯觀的V型峽谷。溪水清澈見底，岩壁紋理層次分明，沿溪步道可近距離欣賞大自然的鬼斧神工。</p>',
    price: 1500,
    originPrice: 1800,
    address: '雲林縣古坑鄉草嶺村',
    category: 'package',
    coordinates: { lat: 23.584, lng: 120.672 },
    imagePool: 'waterfall',
    features: '萬年峽谷,溪谷探險,地質景觀,溯溪體驗,專業嚮導,含保險',
    transport: '古坑市區集合，專車接駁至草嶺峽谷入口，車程約40分鐘。',
    evaluate: 4.5,
    evaluateNum: 220,
  },
  {
    slug: 'douliu-squirrel-park',
    title: '斗六膨鼠森林公園門票',
    description: '巨型松鼠裝置藝術與森林步道，斗六市區的綠色休憩空間。',
    content:
      '<p>膨鼠森林公園以可愛的松鼠為主題，園區內有大型松鼠裝置藝術、兒童遊樂設施與林蔭步道。都市中的綠色空間，適合親子散步、野餐與拍照，是斗六市民日常的休憩去處。</p>',
    price: 80,
    originPrice: 100,
    address: '雲林縣斗六市中堅西路',
    category: 'tickets',
    coordinates: { lat: 23.711, lng: 120.527 },
    imagePool: 'park',
    features: '松鼠主題,裝置藝術,兒童遊樂,林蔭步道,免費入園',
    transport: '自斗六火車站步行約15分鐘。',
    evaluate: 3.8,
    evaluateNum: 160,
  },
  {
    slug: 'huwei-station',
    title: '虎尾驛歷史文化導覽',
    description: '走訪日治時期五分車站遺址，感受糖鐵年代的鐵道風華。',
    content:
      '<p>虎尾驛是日治時期虎尾糖廠的五分車站，木造站房保存良好，現已活化為文化展覽空間。站前廣場保留鐵軌與車頭裝置，定期舉辦市集與藝文活動，是虎尾文化復興的起點。</p>',
    price: 500,
    originPrice: 600,
    address: '雲林縣虎尾鎮中山路10號',
    category: 'package',
    coordinates: { lat: 23.709, lng: 120.431 },
    imagePool: 'oldStreet',
    features: '五分車站,日式車站,文化展覽,鐵道遺跡,市集活動',
    transport: '自虎尾轉運站步行約5分鐘。',
    evaluate: 4.1,
    evaluateNum: 190,
  },
  {
    slug: 'erlun-story-house',
    title: '二崙故事屋親子體驗',
    description: '在日式老屋中聽故事、演布袋戲，孩子的歡樂文化基地。',
    content:
      '<p>二崙故事屋由日治時期派出所改建而成，保留原有木造建築風貌。館內定期舉辦繪本說故事、布袋戲DIY、客語歌謠教唱等活動，是雲林最溫馨的親子文化空間。</p>',
    price: 100,
    originPrice: 130,
    address: '雲林縣二崙鄉中山路102號',
    category: 'tickets',
    coordinates: { lat: 23.756, lng: 120.413 },
    imagePool: 'oldStreet',
    features: '故事屋,親子活動,布袋戲DIY,日式建築,客家文化',
    transport: '自西螺轉運站搭計程車約10分鐘。',
    evaluate: 4.2,
    evaluateNum: 140,
  },
  {
    slug: 'kouhu-wetland',
    title: '口湖成龍濕地生態遊',
    description: '探訪國際級濕地藝術村，欣賞裝置藝術與候鳥生態。',
    content:
      '<p>成龍濕地原為農田因地層下陷而成的濕地，每年邀請國際藝術家駐村創作大型裝置藝術。濕地吸引大量候鳥棲息，黃昏時鳥群飛舞的景象壯觀，是結合藝術與生態的獨特景點。</p>',
    price: 800,
    originPrice: 1000,
    address: '雲林縣口湖鄉成龍村',
    category: 'package',
    coordinates: { lat: 23.531, lng: 120.183 },
    imagePool: 'nature',
    features: '濕地生態,裝置藝術,候鳥觀賞,國際藝術村,生態導覽',
    transport: '自北港轉運站搭計程車約20分鐘。',
    evaluate: 4.3,
    evaluateNum: 170,
  },
  {
    slug: 'taixi-sea-story-house',
    title: '台西海口故事屋文化體驗',
    description: '聆聽雲林海口的漁村故事，體驗蚵殼手作與在地生活。',
    content:
      '<p>台西海口故事屋以漁村文化為核心，透過故事、影像與手作體驗，讓遊客認識雲林沿海的養殖漁業與海口生活。蚵殼風鈴DIY與漁村散策是最受歡迎的活動項目。</p>',
    price: 600,
    originPrice: 750,
    address: '雲林縣台西鄉海口村',
    category: 'package',
    coordinates: { lat: 23.568, lng: 120.196 },
    imagePool: 'beach',
    features: '漁村文化,蚵殼手作,故事體驗,海口散策,在地導覽',
    transport: '自北港轉運站搭台西客運至台西站，車程約30分鐘。',
    evaluate: 4.0,
    evaluateNum: 120,
  },
  {
    slug: 'dounan-taliwu',
    title: '斗南他里霧文化園區',
    description: '廢棄穀倉改建的文創基地，繪本館與生活美學空間。',
    content:
      '<p>他里霧文化園區由斗南舊穀倉群改建而成，設有繪本館、生活美學館、環境教育館等多元空間。保留穀倉原始結構的挑高空間展示當代藝術與在地創作，是雲林最文青的景點。</p>',
    price: 80,
    originPrice: 100,
    address: '雲林縣斗南鎮南昌路17號',
    category: 'tickets',
    coordinates: { lat: 23.679, lng: 120.478 },
    imagePool: 'museum',
    features: '穀倉改建,繪本館,文創空間,藝術展覽,免費參觀',
    transport: '自斗南火車站步行約3分鐘即達。',
    evaluate: 4.0,
    evaluateNum: 150,
  },
  {
    slug: 'beigang-craft-workshop',
    title: '北港工藝坊傳統技藝體驗',
    description: '親手學做北港傳統麻花捲與花生糖，帶回最道地的伴手禮。',
    content:
      '<p>北港工藝坊位於朝天宮旁，提供傳統糕餅與工藝的手作體驗。在師傅指導下製作北港麻花捲、花生糖或香包，體驗過程寓教於樂，完成品可帶回當伴手禮。</p>',
    price: 500,
    originPrice: 650,
    address: '雲林縣北港鎮共和街2號',
    category: 'package',
    coordinates: { lat: 23.57, lng: 120.305 },
    imagePool: 'oldStreet',
    features: '傳統技藝,手作體驗,麻花捲,花生糖,含材料費',
    transport: '自北港朝天宮步行約3分鐘。',
    evaluate: 4.3,
    evaluateNum: 200,
  },
  {
    slug: 'tuku-shuntian-temple',
    title: '土庫順天宮古蹟導覽',
    description: '走訪兩百年古廟，欣賞精緻的剪黏與石雕工藝。',
    content:
      '<p>土庫順天宮建於清嘉慶年間，主祀天上聖母。廟宇屋脊的剪黏工藝色彩鮮豔、栩栩如生，石雕龍柱與木雕門神皆出自名匠之手。導覽將解說廟宇建築與土庫在地歷史。</p>',
    price: 500,
    originPrice: 600,
    address: '雲林縣土庫鎮中正路109號',
    category: 'package',
    coordinates: { lat: 23.677, lng: 120.387 },
    imagePool: 'temple',
    features: '古廟建築,剪黏工藝,石雕龍柱,歷史導覽,在地文化',
    transport: '自虎尾轉運站搭計程車約10分鐘。',
    evaluate: 4.1,
    evaluateNum: 130,
  },
  {
    slug: 'linnei-tea-garden',
    title: '林內坪頂茶園品茗',
    description: '隱身山間的小茶園，品嚐雲林自產的手摘烏龍茶。',
    content:
      '<p>林內坪頂茶園位於濁水溪畔的山坡地，海拔約300公尺，日夜溫差大有利茶葉生長。茶園體驗包含茶園導覽、手摘茶體驗與專業品茗，搭配在地茶點，享受山間的悠閒時光。</p>',
    price: 800,
    originPrice: 1000,
    address: '雲林縣林內鄉坪頂村',
    category: 'package',
    coordinates: { lat: 23.758, lng: 120.612 },
    imagePool: 'tea',
    features: '茶園體驗,手摘茶,品茗教學,山間美景,含茶點',
    transport: '自林內火車站搭計程車約15分鐘至茶園。',
    evaluate: 4.4,
    evaluateNum: 160,
  },
  {
    slug: 'huashan-coffee-village',
    title: '華山咖啡園區漫遊',
    description: '漫步山間咖啡步道，在百家咖啡館中找到你的最愛。',
    content:
      '<p>華山咖啡園區位於古坑華山地區，數十家咖啡館沿山坡散布，每家都有獨特的風景與咖啡風味。園區內設有多條健行步道，沿途可眺望嘉南平原，是邊健行邊品咖啡的悠閒路線。</p>',
    price: 700,
    originPrice: 900,
    address: '雲林縣古坑鄉華山村',
    category: 'package',
    coordinates: { lat: 23.604, lng: 120.593 },
    imagePool: 'mountain',
    features: '咖啡步道,山間咖啡館,健行路線,嘉南平原眺望,含咖啡券',
    transport: '自斗六火車站搭台西客運至華山站，車程約35分鐘。',
    evaluate: 4.5,
    evaluateNum: 350,
  },
  {
    slug: 'xiluo-old-street',
    title: '西螺老街文化巡禮',
    description: '漫步巴洛克風格老街屋，品嚐西螺醬油與在地小吃。',
    content:
      '<p>西螺延平老街保存大量日治時期巴洛克風格街屋，華麗的立面裝飾訴說著昔日繁榮。老街上有百年醬油老舖、傳統米食點心與手作工坊，是認識雲林農村文化的重要街區。</p>',
    price: 800,
    originPrice: 1000,
    address: '雲林縣西螺鎮延平路',
    category: 'package',
    coordinates: { lat: 23.78, lng: 120.464 },
    imagePool: 'oldStreet',
    features: '巴洛克街屋,醬油文化,老街巡禮,美食品嚐,文化導覽,含試吃',
    transport: '自斗六火車站搭台西客運至西螺站，車程約20分鐘。',
    evaluate: 4.4,
    evaluateNum: 280,
  },
  {
    slug: 'huwei-towel-factory',
    title: '虎尾毛巾觀光工廠門票',
    description: '走入毛巾的繽紛世界，蛋糕毛巾與動物毛巾超療癒。',
    content:
      '<p>虎尾毛巾觀光工廠展示台灣毛巾產業的發展歷程，工廠內可參觀毛巾織造過程。最受歡迎的是造型毛巾展示區，蛋糕、冰棒、動物造型毛巾栩栩如生，還有毛巾蛋糕DIY體驗。</p>',
    price: 100,
    originPrice: 130,
    address: '雲林縣虎尾鎮埒內里84號',
    category: 'tickets',
    coordinates: { lat: 23.723, lng: 120.418 },
    imagePool: 'city',
    features: '觀光工廠,毛巾DIY,造型毛巾,產業參觀,親子友善',
    transport: '自虎尾轉運站搭計程車約8分鐘。',
    evaluate: 4.2,
    evaluateNum: 390,
  },
  {
    slug: 'gukeng-green-tunnel',
    title: '古坑綠色隧道自行車',
    description: '騎行於兩公里芒果樹隧道下，享受鄉間的綠蔭微風。',
    content:
      '<p>古坑綠色隧道是長約兩公里的芒果樹林蔭大道，兩側老樹枝葉交織形成天然綠色隧道。沿途設有假日市集、蜜蜂故事館與咖啡攤位，騎自行車悠遊其間，是雲林最愜意的田園體驗。</p>',
    price: 300,
    originPrice: 380,
    address: '雲林縣古坑鄉湳仔村湳仔路',
    category: 'tickets',
    coordinates: { lat: 23.653, lng: 120.551 },
    imagePool: 'nature',
    features: '綠色隧道,自行車道,假日市集,芒果樹蔭,田園風光',
    transport: '自斗六火車站搭台西客運至永光站，車程約20分鐘。',
    evaluate: 4.5,
    evaluateNum: 420,
  },
]
